import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { Navbar } from '@/components/layout/navbar'
import { Footer } from '@/components/layout/footer'
import { SentimentReportPage } from '@/components/tools/sentiment-report-page'
import { SentimentRelated } from '@/components/tools/sentiment-related'
import { getToolBySlug, getAlternativeTools, getToolsByIds } from '@/lib/data/tools'
import { getEditorialComparisonsForTool } from '@/lib/data/comparisons'
import { getAdminClient } from '@/lib/cron/supabase-admin'

export const dynamic = 'force-dynamic'

type PageProps = { params: Promise<{ slug: string }> }

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params
  const tool = await getToolBySlug(slug)
  if (!tool) return { title: 'Tool Not Found' }
  return {
    title: `${tool.name} — Live Market Sentiment | RightAIChoice`,
    description: `What people really think about ${tool.name}: a real-time sweep of social media, forums, reviews, and community discussions, synthesized into an honest verdict.`,
    robots: { index: false }, // gated, dynamic per-user — not for indexing
  }
}

export default async function ToolSentimentPage({ params }: PageProps) {
  const { slug } = await params
  const tool = await getToolBySlug(slug)
  if (!tool) notFound()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const categories = (tool as any).tool_categories?.map((tc: { categories: { id: string; name: string; slug: string } }) => tc.categories).filter(Boolean) ?? []
  const categoryIds = categories.map((c: { id: string }) => c.id)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tagSlugs: string[] = ((tool as any).tool_tags ?? [])
    .map((tt: { tags: { slug: string } | { slug: string }[] | null }) => (Array.isArray(tt.tags) ? tt.tags[0]?.slug : tt.tags?.slug))
    .filter(Boolean)

  // Phase 12 Bug-3 — alternatives were broad same-category siblings (wrong). Now
  // lead with the tool's REAL competitors (the other tool in each editorial
  // comparison pair — the ones people actually weigh it against), then fill with
  // the relevance-ranked siblings (feeding getAlternativeTools the tag/tagline/
  // name signal it needs instead of raw view_count), de-duplicated.
  const compares = await getEditorialComparisonsForTool(tool.id).catch(
    () => [] as Awaited<ReturnType<typeof getEditorialComparisonsForTool>>,
  )
  const competitorIds = [...new Set(compares.flatMap((c) => c.tool_ids).filter((id) => id !== tool.id))]
  const [competitorTools, fill] = await Promise.all([
    getToolsByIds(competitorIds).catch(() => [] as Awaited<ReturnType<typeof getToolsByIds>>),
    categoryIds.length
      ? getAlternativeTools(tool.id, categoryIds, 10, {
          sourceSlug: tool.slug,
          sourceTagSlugs: tagSlugs,
          sourceTagline: tool.tagline ?? '',
          sourceName: tool.name,
        }).catch(() => [] as Awaited<ReturnType<typeof getAlternativeTools>>)
      : Promise.resolve([] as Awaited<ReturnType<typeof getAlternativeTools>>),
  ])
  const seenAlt = new Set<string>([tool.slug])
  const alternatives = [...competitorTools, ...fill]
    .filter((a) => {
      if (seenAlt.has(a.slug)) return false
      seenAlt.add(a.slug)
      return true
    })
    .slice(0, 8)

  // Phase 12 Bug-3 — dynamic, tool-specific FAQs (generated by the last scan,
  // cached) so the server-rendered FAQ block is real + SEO-crawlable rather than
  // a generic template. Empty until the tool has been scanned at least once.
  let cachedFaqs: { q: string; a: string }[] = []
  try {
    const { data: cacheRow } = await getAdminClient()
      .from('tool_sentiment_cache')
      .select('faqs')
      .eq('tool_id', tool.id)
      .maybeSingle()
    const f = (cacheRow as { faqs?: unknown } | null)?.faqs
    if (Array.isArray(f)) {
      cachedFaqs = (f as Array<{ q?: unknown; a?: unknown }>)
        .filter((x) => x && typeof x.q === 'string' && typeof x.a === 'string')
        .map((x) => ({ q: x.q as string, a: x.a as string }))
        .slice(0, 8)
    }
  } catch { /* no cached scan yet — fall back to the generic FAQ */ }

  return (
    <>
      <Navbar />
      <main className="flex-1">
        <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
          <SentimentReportPage toolSlug={slug} toolName={tool.name} />
          <SentimentRelated
            toolName={tool.name}
            toolSlug={slug}
            alternatives={alternatives.map((a) => ({ slug: a.slug, name: a.name, tagline: a.tagline, logo_url: a.logo_url }))}
            compares={compares.map((c) => ({ slug: c.slug }))}
            category={categories[0] ? { name: categories[0].name, slug: categories[0].slug } : null}
            faqs={cachedFaqs}
          />
        </div>
      </main>
      <Footer />
    </>
  )
}
