import { NextResponse, type NextRequest } from 'next/server'
import { updateSession } from '@/lib/supabase/middleware'
import { DELETED_TOOL_SLUGS, DELETED_COMPARE_SLUGS } from '@/lib/seo/deleted-tools'
import { MERGED_TOOL_REDIRECTS } from '@/lib/seo/merged-redirects'

// Phase 4 dedup follow-up (2026-05-07): the page-handler-level
// permanentRedirect emits a meta-refresh in streaming contexts instead of
// HTTP 308. The proxy runs BEFORE the page handler / streaming begins, so
// returning NextResponse.redirect(url, 308) here gives a true 308 with no
// body — the right signal for SEO crawlers.
//
// Match: /tools/<slug> (single segment, no sub-paths). Sub-paths like
// /tools/<slug>/alternatives or /tools/<slug>/report aren't merged URLs.
const TOOL_SLUG_REGEX = /^\/tools\/([a-z0-9][a-z0-9-]{0,80})(?:\/.*)?$/
const COMPARE_SLUG_REGEX = /^\/compare\/([a-z0-9][a-z0-9-]{0,200})\/?$/

// Phase 9 Day-4 (2026-05-29) — 410 Gone for hard-deleted slugs. The set is
// baked into the build via lib/seo/deleted-tools.ts and regenerated by the
// non-AI delete script. 410 (vs 404) tells Google "this is permanently gone"
// which accelerates deindexation in Search Console.
function maybeGoneResponse(request: NextRequest): NextResponse | null {
  const path = request.nextUrl.pathname
  const tool = path.match(TOOL_SLUG_REGEX)
  if (tool && DELETED_TOOL_SLUGS.has(tool[1])) {
    return new NextResponse(GONE_HTML(`/tools/${tool[1]}`), {
      status: 410,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'X-Robots-Tag': 'noindex',
        'Cache-Control': 'public, max-age=86400',
      },
    })
  }
  const cmp = path.match(COMPARE_SLUG_REGEX)
  if (cmp && DELETED_COMPARE_SLUGS.has(cmp[1])) {
    return new NextResponse(GONE_HTML(`/compare/${cmp[1]}`), {
      status: 410,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'X-Robots-Tag': 'noindex',
        'Cache-Control': 'public, max-age=86400',
      },
    })
  }
  return null
}

function GONE_HTML(path: string): string {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>410 Gone — RightAIChoice</title>
<meta name="robots" content="noindex,nofollow">
<meta http-equiv="refresh" content="0; url=/tools">
</head><body style="font-family:system-ui,sans-serif;background:#09090b;color:#e4e4e7;padding:48px 24px;max-width:640px;margin:0 auto;">
<h1 style="font-size:1.5rem;margin:0 0 16px;">Gone — page permanently removed</h1>
<p>We removed <code style="color:#a1a1aa;">${path}</code> from our catalog. RightAIChoice now lists only AI-native and AI-enabled tools.</p>
<p><a href="/tools" style="color:#34d399;">Browse our AI tool catalog →</a></p>
</body></html>`
}

// Phase 9 perf (2026-05-29) — O(1) lookup against the baked-in slug→canonical
// map (generated by `npm run merged:build`). Replaces the per-request Supabase
// query that was costing ~100–200ms on every /tools/<slug> hit.
function maybeMergedToolRedirect(request: NextRequest): NextResponse | null {
  const bare = request.nextUrl.pathname.match(/^\/tools\/([a-z0-9][a-z0-9-]{0,80})\/?$/)
  if (!bare) return null
  const merged = MERGED_TOOL_REDIRECTS.get(bare[1])
  if (!merged) return null
  const url = request.nextUrl.clone()
  url.pathname = `/tools/${merged}`
  // Preserve query string + hash so backlinks like /tools/old-slug?utm_x=y
  // hit the canonical page with the same query state.
  return NextResponse.redirect(url, 308)
}

export async function proxy(request: NextRequest) {
  const gone = maybeGoneResponse(request)
  if (gone) return gone
  const merged = maybeMergedToolRedirect(request)
  if (merged) return merged
  return await updateSession(request)
}

export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
}
