import {
  PenLine,
  ImagePlus,
  Video,
  Mic,
  Music,
  Code,
  Palette,
  Camera,
  TrendingUp,
  Share2,
  Mail,
  Zap,
  Bot,
  Headphones,
  Target,
  BarChart3,
  GraduationCap,
  Briefcase,
  Users,
  Heart,
  Scale,
  Shield,
  Languages,
  Presentation,
  MessageSquare,
  ClipboardList,
  ShoppingCart,
  Home,
  Table,
  Box,
  FileText,
  Search,
  Blocks,
  Wallet,
  Building,
  LayoutGrid,
  type LucideIcon,
} from 'lucide-react'

const CATEGORY_ICON: Record<string, LucideIcon> = {
  'writing-content': PenLine,
  'image-generation': ImagePlus,
  'video-animation': Video,
  'voice-audio': Mic,
  'music-creation': Music,
  'code-development': Code,
  'design-ui': Palette,
  'photo-editing': Camera,
  'seo-marketing': TrendingUp,
  'social-media': Share2,
  'email-marketing': Mail,
  productivity: Zap,
  'automation-agents': Bot,
  'customer-support': Headphones,
  'sales-crm': Target,
  'data-analytics': BarChart3,
  'research-education': GraduationCap,
  'business-finance': Briefcase,
  'hr-recruiting': Users,
  healthcare: Heart,
  legal: Scale,
  cybersecurity: Shield,
  translation: Languages,
  presentations: Presentation,
  'chatbots-assistants': MessageSquare,
  'project-management': ClipboardList,
  ecommerce: ShoppingCart,
  'real-estate': Home,
  'spreadsheets-data': Table,
  '3d-game-dev': Box,
  transcription: FileText,
  'search-knowledge': Search,
  'no-code': Blocks,
  'personal-finance': Wallet,
  'architecture-interior': Building,
}

export function categoryIconFor(slug: string | null | undefined): LucideIcon {
  if (!slug) return LayoutGrid
  return CATEGORY_ICON[slug] ?? LayoutGrid
}
