/**
 * Phase 9 perf — Static map of duplicate-tool merge redirects.
 *
 * Loaded by `proxy.ts` so every /tools/<slug> request can resolve a merge
 * redirect in O(1) without hitting Supabase. Saves ~100–200ms of edge → DB
 * round-trip per tool page request.
 *
 * Source of truth: `tools.merged_into` in Supabase. Regenerated by
 * `scripts/build-merged-redirects.ts` whenever a tool gets merged.
 *
 * DO NOT hand-edit. Run `npm run merged:build` instead.
 */

export const MERGED_TOOL_REDIRECTS: Map<string, string> = new Map<string, string>([
])

export const MERGED_LAST_GENERATED_AT = '1970-01-01T00:00:00.000Z'
