// Phase 13 Social — per-platform weekly strategy ("this week's plan").
//
// Each week, per platform, we craft a short strategy from LAST week's posts +
// their engagement, aligned to the two brand goals. It's shown in the admin AND
// fed into the drafting brain so each week's posts pursue that week's plan.
// Generated by the social-strategy cron (Mon), regenerable on-demand. ~$0.001 each.

import { getAdminClient } from '../cron/supabase-admin'
import { callDeepSeek, stripJsonFences } from '../plan/deepseek'
import { engagementScore } from './insights'
import type { Platform } from './types'

/** The north star every strategy is aligned to. */
export const SOCIAL_GOALS = ['Strong online brand awareness', 'Bring in more engagement & users'] as const
const PLATFORMS: Platform[] = ['linkedin', 'x', 'instagram', 'reddit']

export type WeeklyStrategy = {
  focus: string
  themes: string[]
  postTypes: string[]
  cadence: string
  rationale: string
  goalAlignment: string
}
export type LastWeekSummary = { postCount: number; avgEngagement: number; topAngle: string | null; formatsUsed: string[] }
export type StoredStrategy = WeeklyStrategy & { platform: Platform; weekStart: string; basedOn: LastWeekSummary; generatedAt?: string }

/** Monday 00:00 UTC (date string) of `now`'s week. Pure. */
export function weekStartUTC(now: Date = new Date()): string {
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()))
  const dow = d.getUTCDay() // 0=Sun..6=Sat
  d.setUTCDate(d.getUTCDate() + (dow === 0 ? -6 : 1 - dow))
  return d.toISOString().slice(0, 10)
}

/** Validate/coerce a model reply into a WeeklyStrategy (or null). Pure. */
export function parseStrategy(raw: string): WeeklyStrategy | null {
  try {
    const o = JSON.parse(stripJsonFences(raw)) as Partial<WeeklyStrategy>
    if (!o || typeof o.focus !== 'string' || !o.focus.trim()) return null
    const arr = (v: unknown) => (Array.isArray(v) ? v.filter((x) => typeof x === 'string' && x.trim()).slice(0, 6) : [])
    return {
      focus: o.focus.trim(),
      themes: arr(o.themes),
      postTypes: arr(o.postTypes),
      cadence: typeof o.cadence === 'string' ? o.cadence : '',
      rationale: typeof o.rationale === 'string' ? o.rationale : '',
      goalAlignment: typeof o.goalAlignment === 'string' ? o.goalAlignment : '',
    }
  } catch {
    return null
  }
}

/** A sensible goal-aligned starter when there's no engagement history (or the model fails). */
function starterStrategy(platform: Platform): WeeklyStrategy {
  return {
    focus: `Establish a credible, data-led ${platform} presence`,
    themes: ['What we track and why it can be trusted', 'A standout tool finding', 'An honest pricing or viability insight'],
    postTypes: platform === 'instagram' ? ['stat_card', 'tool_spotlight'] : ['stat_card', 'tool_spotlight', 'news_roundup'],
    cadence: 'Start with 2–3 posts this week; reply to anyone who engages',
    rationale: 'No engagement history yet — establish a consistent, credible baseline that we sharpen as data arrives.',
    goalAlignment: 'Brand awareness via useful original data; engagement via concrete, debate-worthy findings.',
  }
}

/** Read last week's posted content + latest metrics for a platform. */
export async function summarizeLastWeek(platform: Platform): Promise<LastWeekSummary> {
  const db = getAdminClient()
  const since = new Date(Date.now() - 7 * 86_400_000).toISOString()
  const postsRes = await db
    .from('social_posts')
    .select('id, kind, brain_meta')
    .eq('platform', platform)
    .eq('status', 'posted')
    .gte('posted_at', since)
  const posts = (postsRes.data ?? []) as Array<{ id: string; kind: string; brain_meta: { angle?: string } | null }>
  if (!posts.length) return { postCount: 0, avgEngagement: 0, topAngle: null, formatsUsed: [] }

  const metricsRes = await db
    .from('social_metrics')
    .select('post_id, captured_at, impressions, likes, comments, shares, clicks')
    .in('post_id', posts.map((p) => p.id))
  type MRow = { post_id: string; captured_at: string; impressions?: number | null; likes?: number | null; comments?: number | null; shares?: number | null; clicks?: number | null }
  const latest = new Map<string, MRow>()
  for (const m of (metricsRes.data ?? []) as MRow[]) {
    const cur = latest.get(m.post_id)
    if (!cur || m.captured_at > cur.captured_at) latest.set(m.post_id, m)
  }
  let best = { angle: null as string | null, score: -1 }
  let total = 0
  for (const p of posts) {
    const s = engagementScore(latest.get(p.id) ?? {})
    total += s
    if (s > best.score) best = { angle: p.brain_meta?.angle ?? null, score: s }
  }
  return {
    postCount: posts.length,
    avgEngagement: +(total / posts.length).toFixed(1),
    topAngle: best.angle,
    formatsUsed: [...new Set(posts.map((p) => p.kind))],
  }
}

function systemPrompt(): string {
  return [
    `You are the social-media strategist for RightAIChoice (rightaichoice.com), an independent decision engine for AI tools.`,
    `Craft THIS WEEK'S strategy for one platform, aligned to two goals: (1) ${SOCIAL_GOALS[0]}; (2) ${SOCIAL_GOALS[1]}.`,
    `Ground it in last week's results when provided. Be specific and platform-appropriate; no hype.`,
    `Return STRICT JSON only: { "focus": "<one line>", "themes": ["..."], "postTypes": ["stat_card|tool_spotlight|news_roundup|comparison|quote|text|thread"], "cadence": "<how often + engagement note>", "rationale": "<why, tied to last week>", "goalAlignment": "<how it serves the two goals>" }. No prose, no fences.`,
  ].join('\n')
}

function userPrompt(platform: Platform, s: LastWeekSummary): string {
  const lastWeek = s.postCount
    ? `LAST WEEK on ${platform}: ${s.postCount} posts, avg engagement score ${s.avgEngagement}, best angle: ${s.topAngle ?? 'n/a'}, formats used: ${s.formatsUsed.join(', ') || 'n/a'}.`
    : `LAST WEEK on ${platform}: no posts/engagement data yet — design a starter plan to establish presence.`
  return [`PLATFORM: ${platform}`, lastWeek, `Design this week's strategy now, aligned to the two goals.`].join('\n')
}

/** Build (and store) this week's strategy for one platform. */
export async function buildWeeklyStrategy(platform: Platform, opts: { dryRun?: boolean } = {}): Promise<StoredStrategy> {
  const basedOn = await summarizeLastWeek(platform)
  let strategy: WeeklyStrategy | null = null
  try {
    const raw = await callDeepSeek({ system: systemPrompt(), user: userPrompt(platform, basedOn), max_tokens: 600 })
    strategy = parseStrategy(raw)
  } catch {
    /* fall back below */
  }
  strategy = strategy ?? starterStrategy(platform)
  const weekStart = weekStartUTC()
  const result: StoredStrategy = { ...strategy, platform, weekStart, basedOn }

  if (!opts.dryRun) {
    const db = getAdminClient()
    await db.from('social_strategies').upsert(
      {
        platform,
        week_start: weekStart,
        focus: strategy.focus,
        themes: strategy.themes,
        post_types: strategy.postTypes,
        cadence: strategy.cadence,
        rationale: strategy.rationale,
        goal_alignment: strategy.goalAlignment,
        based_on: basedOn,
        generated_at: new Date().toISOString(),
      } as never,
      { onConflict: 'platform,week_start' },
    )
  }
  return result
}

/** This week's stored strategy for a platform (or null). Used by the brain + admin. */
export async function getCurrentStrategy(platform: Platform): Promise<StoredStrategy | null> {
  const db = getAdminClient()
  const res = await db
    .from('social_strategies')
    .select('*')
    .eq('platform', platform)
    .eq('week_start', weekStartUTC())
    .maybeSingle()
  const r = res.data as Record<string, unknown> | null
  if (!r) return null
  return {
    platform,
    weekStart: r.week_start as string,
    focus: (r.focus as string) ?? '',
    themes: (r.themes as string[]) ?? [],
    postTypes: (r.post_types as string[]) ?? [],
    cadence: (r.cadence as string) ?? '',
    rationale: (r.rationale as string) ?? '',
    goalAlignment: (r.goal_alignment as string) ?? '',
    basedOn: (r.based_on as LastWeekSummary) ?? { postCount: 0, avgEngagement: 0, topAngle: null, formatsUsed: [] },
    generatedAt: r.generated_at as string,
  }
}

/** One-line strategy hint for the drafting prompt (focus + themes). */
export function strategyHint(s: StoredStrategy | null): string | undefined {
  if (!s) return undefined
  const themes = s.themes.length ? ` Themes: ${s.themes.join('; ')}.` : ''
  return `${s.focus}.${themes} (Goals: ${SOCIAL_GOALS.join(' + ')}.)`
}

export async function buildAllStrategies(opts: { dryRun?: boolean } = {}): Promise<StoredStrategy[]> {
  const out: StoredStrategy[] = []
  for (const p of PLATFORMS) out.push(await buildWeeklyStrategy(p, opts))
  return out
}
