/**
 * Phase 9 perf — Regenerate lib/seo/merged-redirects.ts from the
 * `tools.merged_into` column.
 *
 * The edge proxy uses this static map to redirect duplicate / merged tool
 * slugs without doing a Supabase round-trip on every /tools/<slug> request.
 *
 * USAGE:
 *   npm run merged:build         # writes lib/seo/merged-redirects.ts
 *   npm run merged:build -- --dry  # prints the count without writing
 */
export {}

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createClient } from '@supabase/supabase-js'

const OUT_PATH = resolve(process.cwd(), 'lib/seo/merged-redirects.ts')

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) throw new Error('missing Supabase env')
  const supa = createClient(url, key)

  // Pull every merged tool. merged_into stores the canonical slug to redirect
  // to. Paginate in case >1000.
  type Row = { slug: string; merged_into: string | null }
  const rows: Row[] = []
  for (let from = 0; ; from += 1000) {
    const { data, error } = await supa
      .from('tools')
      .select('slug, merged_into')
      .not('merged_into', 'is', null)
      .range(from, from + 999)
    if (error) throw new Error(`tools fetch: ${error.message}`)
    if (!data || data.length === 0) break
    rows.push(...(data as Row[]))
    if (data.length < 1000) break
  }

  const pairs = rows
    .filter((r) => r.merged_into && r.merged_into !== r.slug)
    .map((r) => [r.slug, r.merged_into as string] as const)
    .sort((a, b) => a[0].localeCompare(b[0]))

  console.log(`[merged] found ${pairs.length} merged → canonical mappings`)

  if (process.argv.includes('--dry')) {
    pairs.slice(0, 20).forEach(([from, to]) => console.log(`  ${from} → ${to}`))
    if (pairs.length > 20) console.log(`  ... +${pairs.length - 20} more`)
    return
  }

  const now = new Date().toISOString()
  const body = `/**
 * Phase 9 perf — Static map of duplicate-tool merge redirects.
 *
 * Loaded by \`proxy.ts\` so every /tools/<slug> request can resolve a merge
 * redirect in O(1) without hitting Supabase. Saves ~100–200ms of edge → DB
 * round-trip per tool page request.
 *
 * Source of truth: \`tools.merged_into\` in Supabase. Regenerated by
 * \`scripts/build-merged-redirects.ts\` whenever a tool gets merged.
 *
 * DO NOT hand-edit. Run \`npm run merged:build\` instead.
 */

export const MERGED_TOOL_REDIRECTS: Map<string, string> = new Map<string, string>(${JSON.stringify(pairs, null, 2)})

export const MERGED_LAST_GENERATED_AT = '${now}'
`
  writeFileSync(OUT_PATH, body)
  console.log(`[merged] wrote ${OUT_PATH} (${pairs.length} entries)`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
