/**
 * Phase 9 perf — Regenerate lib/seo/merged-redirects.ts from the
 * `tools.merged_into` column.
 *
 * The edge proxy uses this static map to redirect duplicate / merged tool
 * slugs without doing a Supabase round-trip on every /tools/<slug> request.
 *
 * USAGE:
 *   npm run merged:build         # writes lib/seo/merged-redirects.ts
 *   npm run merged:build -- --dry  # prints the count without writing
 */
export {}

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createClient } from '@supabase/supabase-js'
import { DELETED_TOOL_SLUGS } from '@/lib/seo/deleted-tools'

const OUT_PATH = resolve(process.cwd(), 'lib/seo/merged-redirects.ts')
const MAX_CHAIN_DEPTH = 10

/**
 * BUG-07: flatten redirect chains to their terminal canonical. The edge proxy
 * does ONE hop, so a stored chain A→B, B→C makes /tools/A a 308→308 chain —
 * Google bleeds link equity across hops and may stop following. We rewrite to
 * A→C, B→C. Along the way we break cycles, drop self-loops, and drop any
 * redirect whose terminal is itself a DELETED slug (that must 410, not redirect
 * into a dead page). Returns the flattened pairs + human-readable warnings.
 */
function flattenChains(
  pairs: ReadonlyArray<readonly [string, string]>,
): { flat: Array<readonly [string, string]>; warnings: string[] } {
  const oneHop = new Map(pairs)
  const warnings: string[] = []
  const flat: Array<readonly [string, string]> = []
  for (const [slug] of pairs) {
    const seen = new Set<string>([slug])
    let cur = slug
    let depth = 0
    for (; depth < MAX_CHAIN_DEPTH; depth++) {
      const next = oneHop.get(cur)
      if (!next || next === cur) break // terminal canonical, or a self-loop on cur
      if (seen.has(next)) {
        warnings.push(`cycle broken: ${slug} … → ${next} (already visited)`)
        break
      }
      seen.add(next)
      cur = next
    }
    if (depth >= MAX_CHAIN_DEPTH) warnings.push(`depth>${MAX_CHAIN_DEPTH} from ${slug}; truncated at ${cur}`)
    const terminal = cur
    if (terminal === slug) {
      warnings.push(`self-loop dropped: ${slug} → ${slug}`)
      continue
    }
    if (DELETED_TOOL_SLUGS.has(terminal)) {
      warnings.push(`target deleted, redirect dropped (should 410): ${slug} → ${terminal}`)
      continue
    }
    flat.push([slug, terminal] as const)
  }
  flat.sort((a, b) => a[0].localeCompare(b[0]))
  return { flat, warnings }
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) throw new Error('missing Supabase env')
  const supa = createClient(url, key)

  // Pull every merged tool. merged_into stores the canonical slug to redirect
  // to. Paginate in case >1000.
  type Row = { slug: string; merged_into: string | null }
  const rows: Row[] = []
  for (let from = 0; ; from += 1000) {
    const { data, error } = await supa
      .from('tools')
      .select('slug, merged_into')
      .not('merged_into', 'is', null)
      .range(from, from + 999)
    if (error) throw new Error(`tools fetch: ${error.message}`)
    if (!data || data.length === 0) break
    rows.push(...(data as Row[]))
    if (data.length < 1000) break
  }

  const rawPairs = rows
    .filter((r) => r.merged_into && r.merged_into !== r.slug)
    .map((r) => [r.slug, r.merged_into as string] as const)

  // BUG-07: flatten chains, break cycles, drop self-loops + deleted targets.
  const { flat: pairs, warnings } = flattenChains(rawPairs)
  console.log(`[merged] ${rawPairs.length} raw mappings → ${pairs.length} flattened (terminal-canonical)`)
  if (warnings.length) {
    console.warn(`[merged] ${warnings.length} warning(s):`)
    warnings.forEach((w) => console.warn(`  ⚠ ${w}`))
  }

  // CI invariant: after flattening, NO target may itself be a redirect source
  // (that would mean a chain survived). Fail hard so a bad map never ships.
  const sources = new Set(pairs.map(([s]) => s))
  const surviving = pairs.filter(([, t]) => sources.has(t))
  if (surviving.length > 0) {
    console.error(`[merged] INVARIANT VIOLATION — ${surviving.length} target(s) are still redirect sources (chain survived):`)
    surviving.slice(0, 10).forEach(([s, t]) => console.error(`  ${s} → ${t}, but ${t} also redirects`))
    process.exit(1)
  }

  if (process.argv.includes('--dry')) {
    pairs.slice(0, 20).forEach(([from, to]) => console.log(`  ${from} → ${to}`))
    if (pairs.length > 20) console.log(`  ... +${pairs.length - 20} more`)
    return
  }

  const now = new Date().toISOString()
  const body = `/**
 * Phase 9 perf — Static map of duplicate-tool merge redirects.
 *
 * Loaded by \`proxy.ts\` so every /tools/<slug> request can resolve a merge
 * redirect in O(1) without hitting Supabase. Saves ~100–200ms of edge → DB
 * round-trip per tool page request.
 *
 * Source of truth: \`tools.merged_into\` in Supabase. Regenerated by
 * \`scripts/build-merged-redirects.ts\` whenever a tool gets merged.
 *
 * DO NOT hand-edit. Run \`npm run merged:build\` instead.
 */

export const MERGED_TOOL_REDIRECTS: Map<string, string> = new Map<string, string>(${JSON.stringify(pairs, null, 2)})

export const MERGED_LAST_GENERATED_AT = '${now}'
`
  writeFileSync(OUT_PATH, body)
  console.log(`[merged] wrote ${OUT_PATH} (${pairs.length} entries)`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
