/**
 * Step 41 Slice 2 — bulk catalog scale-up runner.
 *
 * Pulls candidates via the existing cron discover/dedup/enrich pipeline,
 * runs them through the Step 41 Slice 1 curation gate, predicts category
 * slugs via Haiku, and writes survivors to a new seed migration file.
 *
 * Does NOT write to the DB. Operator reviews the generated SQL, then runs
 * `supabase db push` (or applies via dashboard) to ship the batch.
 *
 * Usage:
 *   tsx scripts/scale-catalog.ts                       # default: target=50, batch=19
 *   tsx scripts/scale-catalog.ts --target=200          # 200 survivors max
 *   tsx scripts/scale-catalog.ts --batch=20            # writes 039_seed_tools_batch20.sql
 *   tsx scripts/scale-catalog.ts --dry-run             # don't write the .sql file
 *   tsx scripts/scale-catalog.ts --concurrency=5       # 5 parallel enrich (default 3)
 *
 * Required env: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, ANTHROPIC_API_KEY
 */
export {}

import { writeFile } from 'node:fs/promises'
import { z } from 'zod'
import { getAdminClient } from '../lib/cron/supabase-admin'
import { getAnthropicClient } from '../lib/ai/anthropic'
import { discoverTools } from '../lib/cron/discover'
import { dedup } from '../lib/cron/dedup'
import { enrichTool, type EnrichedToolData } from '../lib/cron/enrich'
import { loadCurateContext, curateCandidate } from '../lib/cron/curate'

const CATEGORY_MODEL = 'claude-haiku-4-5-20251001'

const categorySchema = z.object({
  slugs: z.array(z.string()).min(1).max(3),
})

function argValue(flag: string, fallback: string): string {
  const arg = process.argv.find((a) => a.startsWith(`${flag}=`))
  return arg ? arg.split('=')[1] : fallback
}

async function fetchCategorySlugs(supabase: ReturnType<typeof getAdminClient>): Promise<string[]> {
  const { data, error } = await supabase.from('categories').select('slug').order('slug')
  if (error) throw error
  return ((data ?? []) as { slug: string }[]).map((c) => c.slug).filter(Boolean)
}

async function predictCategories(
  name: string,
  enriched: EnrichedToolData,
  validSlugs: string[],
): Promise<string[]> {
  const client = getAnthropicClient()
  const prompt = `Pick 1-3 category slugs for this AI tool. Return ONLY slugs from the provided list — never invent.

Tool: ${name}
Tagline: ${enriched.tagline}
Description: ${enriched.description.slice(0, 600)}
Features: ${(enriched.features ?? []).slice(0, 6).join(', ')}

Valid category slugs (pick from these only):
${validSlugs.join(', ')}

Return JSON: {"slugs": ["slug-1", "slug-2"]}`

  try {
    const res = await client.messages.create({
      model: CATEGORY_MODEL,
      max_tokens: 200,
      messages: [{ role: 'user', content: prompt }],
    })
    const text = res.content[0]?.type === 'text' ? res.content[0].text : ''
    const match = text.match(/\{[\s\S]*\}/)
    if (!match) return []
    const parsed = categorySchema.parse(JSON.parse(match[0]))
    return parsed.slugs.filter((s) => validSlugs.includes(s))
  } catch (e) {
    console.error(`[predict-cat] ${name} —`, (e as Error).message)
    return []
  }
}

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''")
}

function pgArray(items: string[]): string {
  if (items.length === 0) return '{}'
  const escaped = items.map((s) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`)
  return `{${escaped.join(',')}}`
}

interface Survivor {
  name: string
  slug: string
  url: string
  enriched: EnrichedToolData
  categorySlugs: string[]
  source: string
  viability: number
}

function buildMigrationSql(batchNum: number, survivors: Survivor[]): string {
  const header = `-- ============================================================
-- Batch ${batchNum}: ${survivors.length} curated AI tools (Step 41 — scale 711 → 1500)
-- Generated by scripts/scale-catalog.ts. Each tool passed the Slice 1
-- curation gate (viability ≥30, valid URL, ≥80-char description, etc).
-- ============================================================

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES`

  const rows = survivors.map((s) => {
    const e = s.enriched
    return `(${[
      `'${sqlEscape(s.name)}'`,
      `'${sqlEscape(s.slug)}'`,
      `'${sqlEscape(e.tagline)}'`,
      `'${sqlEscape(e.description)}'`,
      `'${sqlEscape(s.url)}'`,
      `'${e.pricing_type}'`,
      `'${sqlEscape(JSON.stringify(e.pricing_details ?? []))}'`,
      `'${e.skill_level}'`,
      e.has_api ? 'true' : 'false',
      `'${pgArray(e.platforms ?? [])}'`,
      `'${pgArray(e.features ?? [])}'`,
      `'${pgArray(e.integrations ?? [])}'`,
      'true',
      `'${pgArray(e.best_for ?? [])}'`,
      `'${pgArray(e.not_for ?? [])}'`,
      `'${sqlEscape(e.editorial_verdict ?? '')}'`,
      'now()',
    ].join(', ')})`
  })

  const insertBlock = `${header}\n${rows.join(',\n')}\nON CONFLICT (slug) DO NOTHING;\n`

  const catRows: string[] = []
  for (const s of survivors) {
    for (const catSlug of s.categorySlugs) {
      catRows.push(
        `INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = '${sqlEscape(s.slug)}' AND c.slug = '${sqlEscape(catSlug)}' ON CONFLICT DO NOTHING;`,
      )
    }
  }

  return `${insertBlock}\n-- Category assignments\n${catRows.join('\n')}\n`
}

async function main() {
  const target = Number(argValue('--target', '50'))
  const batchNum = Number(argValue('--batch', '19'))
  const concurrency = Number(argValue('--concurrency', '3'))
  const dryRun = process.argv.includes('--dry-run')

  const supabase = getAdminClient()

  console.log(`[scale] target=${target} batch=${batchNum} concurrency=${concurrency} dryRun=${dryRun}`)

  console.log('[scale] discovering candidates…')
  const raw = await discoverTools()
  console.log(`[scale]   discovered ${raw.length} raw`)

  console.log('[scale] dedupe against existing tools…')
  const unique = await dedup(raw, supabase)
  console.log(`[scale]   ${unique.length} unique after dedup`)

  console.log('[scale] loading curation context + categories…')
  const [curateCtx, validSlugs] = await Promise.all([
    loadCurateContext(supabase),
    fetchCategorySlugs(supabase),
  ])
  console.log(`[scale]   ${validSlugs.length} valid category slugs · existing tool slugs=${curateCtx.existingSlugs.size}`)

  const survivors: Survivor[] = []
  let attempted = 0
  let enrichFailed = 0
  let gated = 0

  outer: for (let i = 0; i < unique.length; i += concurrency) {
    if (survivors.length >= target) break
    const batch = unique.slice(i, i + concurrency)
    const enrichedBatch = await Promise.all(
      batch.map(async (tool) => {
        attempted++
        const enriched = await enrichTool(tool.name, tool.url, tool.description)
        return { tool, enriched }
      }),
    )

    for (const { tool, enriched } of enrichedBatch) {
      if (survivors.length >= target) break outer
      if (!enriched) {
        enrichFailed++
        continue
      }
      const decision = curateCandidate({ name: tool.name, websiteUrl: tool.url, enriched }, curateCtx)
      if (!decision.pass) {
        gated++
        console.log(`[gate] ${tool.name} — ${decision.reasons.join(',')}`)
        continue
      }
      const cats = await predictCategories(tool.name, enriched, validSlugs)
      survivors.push({
        name: tool.name,
        slug: decision.slug,
        url: tool.url,
        enriched,
        categorySlugs: cats,
        source: tool.source,
        viability: decision.viabilityProxy,
      })
      curateCtx.existingSlugs.add(decision.slug)
      console.log(`[ok ${survivors.length}/${target}] ${tool.name} · viability=${decision.viabilityProxy} · cats=[${cats.join(',') || 'none'}]`)
    }
  }

  console.log(`[scale] done. attempted=${attempted} enrichFailed=${enrichFailed} gated=${gated} survivors=${survivors.length}`)

  if (survivors.length === 0) {
    console.log('[scale] no survivors — nothing to write')
    return
  }

  const sql = buildMigrationSql(batchNum, survivors)
  // Default: batch 19 → 038, 20 → 039 (37 was depth fields). Override with
  // --file-num if a non-seed migration lands between batches.
  const fileNum = argValue('--file-num', String(37 + batchNum - 18).padStart(3, '0'))
  const fileName = `${fileNum}_seed_tools_batch${batchNum}.sql`
  const path = `supabase/migrations/${fileName}`

  if (dryRun) {
    console.log(`[scale] --dry-run · would write ${path} (${sql.length} bytes)`)
    console.log(sql.slice(0, 500))
    return
  }

  await writeFile(path, sql, 'utf8')
  console.log(`[scale] wrote ${path} (${sql.length} bytes, ${survivors.length} tools)`)
  console.log(`[scale] next: review file, then \`supabase db push\` to apply`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
