-- ============================================================
-- RightAIChoice — Seed: Tools Batch 2 (~100 tools)
-- Categories: Writing, Marketing, Productivity, Business, Research
-- Run AFTER 003_seed_tools.sql
-- ============================================================

-- ── WRITING & CONTENT ────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Jasper', 'jasper', 'AI writing assistant for marketing and content teams', 'Jasper is an enterprise-grade AI writing platform built for marketing teams. It generates blog posts, ad copy, emails, and social media content at scale, with brand voice controls and team collaboration features. Integrates with Surfer SEO for optimized content.', 'https://jasper.ai', 'paid', '[{"plan":"Creator","price":"$39/mo","features":["1 seat","50+ templates","Browser extension"]},{"plan":"Teams","price":"$99/mo","features":["3 seats","Brand voice","Campaigns"]}]', 'beginner', true, '{web,api}', '{"50+ content templates","Brand voice control","SEO mode with Surfer","Team collaboration","Campaign management","Plagiarism checker"}', '{"Surfer SEO","Google Docs","Zapier","HubSpot"}', 'https://developers.jasper.ai', true),

('Copy.ai', 'copy-ai', 'AI that writes marketing copy in seconds', 'Copy.ai is a free-to-start AI writing tool focused on marketing copy. Create product descriptions, social posts, email sequences, blog outlines, and ad copy. Features a Chat mode powered by GPT-4 and 90+ content templates. Popular with solo founders and small teams.', 'https://copy.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["2000 words/mo","Chat","90+ templates"]},{"plan":"Pro","price":"$36/mo","features":["Unlimited words","Brand voice","Workflows"]}]', 'beginner', true, '{web,api}', '{"90+ templates","Chat mode (GPT-4)","Workflows automation","Brand voice","Long-form assistant","Multi-language"}', '{"Zapier","HubSpot","Salesforce"}', NULL, true),

('Writesonic', 'writesonic', 'AI writer for SEO-optimized articles, ads, and landing pages', 'Writesonic generates SEO-optimized long-form articles, landing pages, product descriptions, and ad copy. Features a Chatsonic chatbot with real-time web access, 1-click WordPress publishing, and Botsonic for building AI chatbots. Strong for content marketing at scale.', 'https://writesonic.com', 'freemium', '[{"plan":"Free","price":"$0","features":["10k words/mo","Chatsonic","Basic features"]},{"plan":"Individual","price":"$16/mo","features":["100 credits","All templates","GPT-4"]}]', 'beginner', true, '{web,api}', '{"Long-form article writer","Chatsonic (web access)","SEO optimizer","Botsonic chatbot builder","Paraphrasing tool","100+ templates"}', '{"WordPress","Zapier","Semrush"}', 'https://docs.writesonic.com', true),

('Grammarly', 'grammarly', 'AI writing assistant for grammar, clarity, and tone', 'Grammarly is the leading AI writing assistant for grammar checking, style improvements, and tone adjustments. The Premium plan adds plagiarism detection, vocabulary enhancement, and advanced style suggestions. The Business plan includes analytics and brand tones. Available as browser extension, desktop app, and API.', 'https://grammarly.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Grammar check","Spelling","Basic suggestions"]},{"plan":"Premium","price":"$12/mo","features":["Advanced suggestions","Tone detector","Plagiarism checker"]},{"plan":"Business","price":"$15/user/mo","features":["Team features","Brand tones","Analytics"]}]', 'beginner', true, '{web,desktop,plugin,api}', '{"Real-time grammar check","Tone detection","Plagiarism checker","Style guide","Browser extension","MS Word integration","Clarity scores"}', '{"Google Docs","Microsoft Word","Slack","Notion"}', 'https://developer.grammarly.com', true),

('Notion AI', 'notion-ai', 'AI assistant built into your Notion workspace', 'Notion AI is natively embedded in Notion, letting you generate content, summarize documents, translate text, and query your entire workspace with natural language. The Q&A feature searches across all your pages to find information. Best for teams already using Notion heavily.', 'https://notion.so/product/ai', 'freemium', '[{"plan":"Notion Free + AI","price":"$10/mo add-on","features":["Unlimited AI use","Q&A across workspace","All Notion plans"]}]', 'beginner', false, '{web,desktop,mobile}', '{"In-page AI editing","Workspace Q&A","Summarize documents","Translate content","Action items extraction","Draft with AI","Fix grammar and tone"}', '{"Slack","Google Drive","GitHub","Figma"}', 'https://www.notion.so/help/guides/using-notion-ai', true),

('Rytr', 'rytr', 'Affordable AI writing tool with 40+ use cases', 'Rytr is a budget-friendly AI writing assistant with 40+ use cases including blog posts, emails, social media, and ad copy. Supports 30+ languages and 20+ writing tones. Best for individual creators and freelancers who need high-volume content at low cost.', 'https://rytr.me', 'freemium', '[{"plan":"Free","price":"$0","features":["10k chars/mo","40+ use cases","20 tones"]},{"plan":"Saver","price":"$9/mo","features":["100k chars/mo","Custom use case"]},{"plan":"Unlimited","price":"$29/mo","features":["Unlimited generation"]}]', 'beginner', true, '{web,plugin,api}', '{"40+ use cases","30+ languages","20+ tones","Plagiarism checker","Browser extension","Content formatting"}', '{"Chrome Extension","Zapier"}', NULL, true),

('Hemingway Editor', 'hemingway-editor', 'Clarity editor that makes your writing bold and clear', 'Hemingway Editor highlights complex sentences, passive voice, adverbs, and hard-to-read sections. The web version is free; the desktop app ($19.99 one-time) adds AI-powered rewriting suggestions. Excellent for non-fiction, blogging, and business writing where clarity matters.', 'https://hemingwayapp.com', 'freemium', '[{"plan":"Web","price":"$0","features":["Readability scores","Highlights","Basic editing"]},{"plan":"Desktop","price":"$19.99 one-time","features":["AI rewrites","Offline","Export"]}]', 'beginner', false, '{web,desktop}', '{"Readability grade scoring","Passive voice detection","Adverb highlighting","Complex sentence detection","AI-powered rewrites","Export to Word/PDF"}', '{}', NULL, true),

('QuillBot', 'quillbot', 'AI paraphrasing and summarization tool', 'QuillBot is primarily an AI paraphrasing and summarization tool. The paraphraser offers 8 modes (standard, fluency, formal, academic, etc.) and can rewrite entire documents. Also includes a grammar checker, plagiarism checker, and co-writer. Popular with students and academic writers.', 'https://quillbot.com', 'freemium', '[{"plan":"Free","price":"$0","features":["125 word paraphrase","Standard mode","Grammar checker"]},{"plan":"Premium","price":"$9.95/mo","features":["Unlimited paraphrase","All modes","Plagiarism checker"]}]', 'beginner', false, '{web,plugin}', '{"8 paraphrase modes","Summarizer","Grammar checker","Plagiarism checker","Citation generator","Word flipper","Co-writer mode"}', '{"Google Docs","Chrome Extension","Microsoft Word"}', NULL, true),

('Wordtune', 'wordtune', 'AI tool for rewriting, expanding, and improving text', 'Wordtune helps rewrite sentences for clarity, formality, and style. Features include expanding (adds more context), shortening (makes concise), and the AI Editor mode for full document improvement. Best for non-native English writers and those who need quick sentence improvements.', 'https://wordtune.com', 'freemium', '[{"plan":"Free","price":"$0","features":["10 rewrites/day","Basic features"]},{"plan":"Advanced","price":"$13.99/mo","features":["Unlimited rewrites","AI Editor","All tones"]}]', 'beginner', false, '{web,plugin}', '{"Sentence rewriting","Expand text","Shorten text","Formality control","AI Editor mode","Chrome extension","Spices feature (AI suggestions)"}', '{"Chrome Extension","Microsoft Word","Google Docs"}', NULL, true),

('Sudowrite', 'sudowrite', 'AI writing tool built specifically for fiction writers', 'Sudowrite is purpose-built for novelists, screenwriters, and creative writers. Features include Describe (sensory details), Brainstorm (plot ideas), Write (continues your story), Rewrite (varies a scene), and Story Engine for full-book outlines. One of the few AI tools that truly understands narrative craft.', 'https://sudowrite.com', 'paid', '[{"plan":"Hobby","price":"$10/mo","features":["30k AI words","All features"]},{"plan":"Professional","price":"$25/mo","features":["90k AI words","Priority support"]},{"plan":"Max","price":"$100/mo","features":["300k AI words"]}]', 'intermediate', false, '{web}', '{"Story Engine","Describe (sensory AI)","Brainstorm","Canvas view","Poem generator","Character voice trainer","Full chapter writing"}', '{}', NULL, true);

-- ── SEO & MARKETING ──────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Surfer SEO', 'surfer-seo', 'AI-powered SEO content optimization platform', 'Surfer SEO analyzes top-ranking pages and provides data-driven guidelines for your content. The Content Editor shows target word count, keywords, and NLP score in real time. AI outline generator, keyword research, and SERP analyzer included. Integrates directly with Google Docs and Jasper.', 'https://surferseo.com', 'paid', '[{"plan":"Essential","price":"$89/mo","features":["30 articles/mo","Content Editor","Keyword Research"]},{"plan":"Scale","price":"$129/mo","features":["100 articles/mo","AI humanizer"]},{"plan":"Scale AI","price":"$219/mo","features":["Unlimited AI articles"]}]', 'intermediate', true, '{web,plugin}', '{"Content Editor with NLP","Keyword research","SERP analyzer","AI content generator","Internal linking","Audit existing pages","Google Docs integration"}', '{"Google Docs","Jasper","WordPress"}', 'https://docs.surferseo.com', true),

('Semrush', 'semrush', 'All-in-one SEO, PPC, and content marketing platform', 'Semrush is a comprehensive digital marketing platform covering SEO, PPC, content, social media, and competitive research. AI features include the SEO Writing Assistant, ContentShake for topic generation, and TrendFeed. Industry standard for professional marketers and agencies.', 'https://semrush.com', 'freemium', '[{"plan":"Free","price":"$0","features":["10 searches/day","Limited features"]},{"plan":"Pro","price":"$117/mo","features":["5 projects","500 keywords","SEO tools"]},{"plan":"Guru","price":"$208/mo","features":["15 projects","Content Marketing Platform"]}]', 'intermediate', true, '{web,api}', '{"Keyword research","Backlink analysis","Site audit","Rank tracking","SEO Writing Assistant","ContentShake AI","Competitive analysis","PPC research"}', '{"Google Analytics","Google Search Console","WordPress","HubSpot"}', 'https://developer.semrush.com', true),

('Ahrefs', 'ahrefs', 'Powerful backlink and SEO research tool', 'Ahrefs is an industry-leading SEO toolset for backlink analysis, keyword research, site auditing, and rank tracking. Its web crawler is one of the most active after Google. Best for SEO professionals who need deep backlink data and competitive analysis. Free Webmaster Tools available.', 'https://ahrefs.com', 'freemium', '[{"plan":"Webmaster Tools","price":"$0","features":["Site audit","Backlink data","Limited"]},{"plan":"Lite","price":"$99/mo","features":["5 projects","6 months history"]},{"plan":"Standard","price":"$199/mo","features":["20 projects","2 years history"]}]', 'intermediate', true, '{web,api}', '{"Backlink analysis","Keyword Explorer","Site Audit","Content Explorer","Rank Tracker","Competitive research","SERP overview","Domain comparison"}', '{"Google Search Console","Chrome Extension"}', 'https://ahrefs.com/api', true),

('Mailchimp', 'mailchimp', 'Email marketing with built-in AI content tools', 'Mailchimp is the most widely used email marketing platform, now enhanced with AI content generation, send-time optimization, and predictive segmentation. The free plan supports up to 500 contacts and 1000 sends/month. Best for small businesses starting email marketing.', 'https://mailchimp.com', 'freemium', '[{"plan":"Free","price":"$0","features":["500 contacts","1000 sends/mo","Email builder"]},{"plan":"Essentials","price":"$13/mo","features":["5000 sends/mo","A/B testing","Automation"]},{"plan":"Standard","price":"$20/mo","features":["Predictive segmentation","Send time AI"]}]', 'beginner', true, '{web,api,mobile}', '{"Email builder","AI content generator","A/B testing","Send-time optimization","Audience segmentation","Marketing automation","Landing pages","Analytics"}', '{"Shopify","WordPress","Salesforce","Zapier","Canva"}', 'https://mailchimp.com/developer', true),

('ActiveCampaign', 'activecampaign', 'Marketing automation and CRM with predictive AI', 'ActiveCampaign combines email marketing, marketing automation, and CRM in one platform. AI features include predictive sending, win probability scoring, and content personalization. Best for businesses that need complex, conditional automation workflows. More powerful but steeper learning curve than Mailchimp.', 'https://activecampaign.com', 'paid', '[{"plan":"Starter","price":"$15/mo","features":["1000 contacts","Email","Automation"]},{"plan":"Plus","price":"$49/mo","features":["CRM","Lead scoring","Landing pages"]},{"plan":"Professional","price":"$79/mo","features":["Predictive sending","AI content"]}]', 'intermediate', true, '{web,api}', '{"Visual automation builder","CRM","Lead scoring","Predictive sending","Site tracking","SMS marketing","Dynamic content","Reporting"}', '{"Shopify","WordPress","Zapier","Salesforce","Facebook Ads"}', 'https://developers.activecampaign.com', true),

('Buffer', 'buffer', 'Simple social media scheduling and analytics', 'Buffer is a clean, intuitive social media management tool for scheduling posts across Instagram, Twitter, LinkedIn, Facebook, TikTok, and Pinterest. AI features include caption generation, hashtag suggestions, and post idea generation. Free plan supports 3 channels.', 'https://buffer.com', 'freemium', '[{"plan":"Free","price":"$0","features":["3 channels","10 posts/channel","Basic analytics"]},{"plan":"Essentials","price":"$6/mo/channel","features":["Unlimited posts","Analytics","Engagement"]}]', 'beginner', true, '{web,mobile,api}', '{"Multi-platform scheduling","AI caption generator","Hashtag suggestions","Analytics","Start Page (link-in-bio)","Ideas board","Team collaboration"}', '{"Facebook","Instagram","Twitter/X","LinkedIn","TikTok","Pinterest"}', 'https://buffer.com/developers', true),

('Hootsuite', 'hootsuite', 'Enterprise social media management platform with AI', 'Hootsuite is the enterprise social media management platform used by the Fortune 500. Features AI-powered post scheduling, OwlyWriter AI for caption generation, social listening, and team collaboration. More powerful and expensive than Buffer but handles complex enterprise workflows.', 'https://hootsuite.com', 'paid', '[{"plan":"Professional","price":"$99/mo","features":["10 social accounts","Unlimited scheduling"]},{"plan":"Team","price":"$249/mo","features":["20 accounts","Team access","Streams"]}]', 'intermediate', true, '{web,mobile,api}', '{"OwlyWriter AI","Social listening","Bulk scheduling","Team workflows","Analytics & reports","Paid ads management","Streams monitoring"}', '{"Facebook","Instagram","Twitter/X","LinkedIn","TikTok","YouTube"}', 'https://developer.hootsuite.com', true),

('Later', 'later', 'Visual social media planner and link-in-bio tool', 'Later is a visual social media planner originally built for Instagram. Features a drag-and-drop calendar, Linkin.bio (link-in-bio page), AI caption writer, hashtag suggestions, and post analytics. Best for visual brands, creators, and e-commerce businesses heavy on Instagram.', 'https://later.com', 'freemium', '[{"plan":"Starter","price":"$18/mo","features":["1 user","30 posts/profile","3 social profiles"]},{"plan":"Growth","price":"$40/mo","features":["3 users","150 posts","Analytics"]}]', 'beginner', false, '{web,mobile}', '{"Visual calendar planner","Linkin.bio page","AI caption writer","Hashtag suggestions","Best time to post","Instagram analytics","Story scheduling"}', '{"Instagram","TikTok","Pinterest","Facebook","Twitter"}', NULL, true),

('Brevo', 'brevo', 'Email, SMS, and WhatsApp marketing platform', 'Brevo (formerly Sendinblue) is a multi-channel marketing platform for email, SMS, WhatsApp, and push notifications. The free plan includes 300 emails/day with no contact limit. AI features include predictive sending and subject line optimization. Better value than Mailchimp for high-contact-count users.', 'https://brevo.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Unlimited contacts","300 emails/day","Basic templates"]},{"plan":"Starter","price":"$25/mo","features":["20k emails/mo","No daily limit","Basic reports"]}]', 'beginner', true, '{web,api}', '{"Email campaigns","SMS marketing","WhatsApp campaigns","Marketing automation","Landing pages","CRM","Transactional email","A/B testing"}', '{"WordPress","Shopify","WooCommerce","Zapier","HubSpot"}', 'https://developers.brevo.com', true),

('Beehiiv', 'beehiiv', 'Newsletter platform built for growth with AI writing', 'Beehiiv is a newsletter platform built by former Morning Brew engineers with a focus on monetization and growth. Features AI writing assistant, paid subscriptions, referral program, and ad network. Fast becoming the go-to for professional newsletter operators over Substack.', 'https://beehiiv.com', 'freemium', '[{"plan":"Launch","price":"$0","features":["2500 subscribers","Newsletter","Website"]},{"plan":"Scale","price":"$39/mo","features":["Unlimited subs","AI writer","Paid subscriptions","Referral program"]}]', 'beginner', false, '{web}', '{"Newsletter builder","AI writing assistant","Paid subscriptions","Referral program","Beehiiv Ad Network","Automations","Analytics","Website builder"}', '{"Stripe","Zapier","Mailchimp migration"}', NULL, true);

-- ── PRODUCTIVITY & AUTOMATION ─────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Zapier', 'zapier', 'No-code automation connecting 6000+ apps', 'Zapier is the leading no-code automation platform connecting 6000+ apps. Build multi-step Zaps (automated workflows) without code. AI features include natural language Zap builder and AI Steps (built-in Claude/ChatGPT steps). Free plan includes 100 tasks/month.', 'https://zapier.com', 'freemium', '[{"plan":"Free","price":"$0","features":["100 tasks/mo","5 Zaps","2-step Zaps"]},{"plan":"Starter","price":"$19.99/mo","features":["750 tasks","Multi-step","Filters"]},{"plan":"Professional","price":"$49/mo","features":["2000 tasks","Custom logic"]}]', 'beginner', true, '{web,api}', '{"6000+ app integrations","Multi-step Zaps","AI Step (Claude/GPT)","Natural language builder","Webhooks","Filters & paths","Schedule triggers","Data formatter"}', '{"Gmail","Slack","Salesforce","HubSpot","Shopify","Airtable"}', 'https://docs.zapier.com', true),

('Make', 'make', 'Visual workflow automation platform (formerly Integromat)', 'Make (formerly Integromat) is a visual automation platform more powerful than Zapier for complex workflows. Its visual flowchart builder handles advanced branching, data transformation, and error handling. Better for developers and technical users. 1000 free operations/month.', 'https://make.com', 'freemium', '[{"plan":"Free","price":"$0","features":["1000 ops/mo","2 active scenarios","Basic apps"]},{"plan":"Core","price":"$10.59/mo","features":["10k ops","3 active scenarios"]},{"plan":"Pro","price":"$18.82/mo","features":["10k ops","Unlimited scenarios","Full execution log"]}]', 'intermediate', true, '{web,api}', '{"Visual flowchart builder","1000+ app integrations","Data transformation","Error handling","Webhooks","Advanced routing","Custom API calls","Scheduling"}', '{"Google Workspace","Slack","Airtable","HubSpot","Shopify","OpenAI"}', 'https://www.make.com/en/help', true),

('n8n', 'n8n', 'Open-source workflow automation with self-hosting option', 'n8n is an open-source workflow automation tool that can be self-hosted (free forever) or used via cloud plan. Supports 400+ integrations and custom code nodes (JavaScript/Python). Best for technical teams that need full control over their automation infrastructure and data privacy.', 'https://n8n.io', 'freemium', '[{"plan":"Self-hosted","price":"$0","features":["Open source","Unlimited workflows","All integrations"]},{"plan":"Cloud Starter","price":"$24/mo","features":["2500 executions","5 active workflows"]}]', 'advanced', true, '{web,desktop,api}', '{"400+ integrations","Custom code nodes (JS/Python)","Self-hosting option","AI nodes (LangChain)","Webhook support","Error workflows","Sub-workflows","Visual editor"}', '{"OpenAI","Anthropic","GitHub","Slack","Airtable","PostgreSQL"}', 'https://docs.n8n.io', true),

('Notion', 'notion', 'All-in-one workspace for notes, docs, and project management', 'Notion is a flexible workspace for notes, wikis, databases, and project management. Widely used by startups and knowledge workers. Notion AI is available as an add-on for AI writing and workspace Q&A. The free plan is generous for personal use.', 'https://notion.so', 'freemium', '[{"plan":"Free","price":"$0","features":["Unlimited blocks","5 guests","7-day history"]},{"plan":"Plus","price":"$10/mo","features":["Unlimited guests","30-day history","File uploads"]},{"plan":"Business","price":"$15/mo","features":["Audit log","SAML SSO","Advanced analytics"]}]', 'beginner', true, '{web,desktop,mobile,api}', '{"Flexible database views","Wiki builder","Project boards","Calendar","Document editor","Templates","Notion AI add-on","API access","Real-time collaboration"}', '{"Slack","GitHub","Figma","Zapier","Google Drive","Jira"}', 'https://developers.notion.com', true),

('Airtable', 'airtable', 'Spreadsheet-database hybrid with powerful automation', 'Airtable combines the flexibility of a spreadsheet with the power of a database. Used for project management, content calendars, product roadmaps, and CRM. AI features include field summarization, classification, and extraction. Automation builder supports 1000+ app integrations.', 'https://airtable.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 bases","1200 rows/base","2GB attachments"]},{"plan":"Team","price":"$20/seat/mo","features":["50k rows","50GB","Automation runs"]},{"plan":"Business","price":"$45/seat/mo","features":["AI features","Advanced permissions"]}]', 'beginner', true, '{web,mobile,api}', '{"Multiple views (grid, kanban, gallery)","Automation","AI field generation","Interface designer","Forms","Real-time collaboration","Linked records","CSV import"}', '{"Slack","Google Workspace","Zapier","Make","Salesforce","GitHub"}', 'https://airtable.com/developers', true),

('Linear', 'linear', 'Fast, modern project management for software teams', 'Linear is a project management tool built for speed, used by top engineering teams. Features instant-load UI, keyboard shortcuts for everything, GitHub integration, and Linear Asks (customer requests → issues). Now includes Linear AI for issue summarization and sub-issue generation.', 'https://linear.app', 'freemium', '[{"plan":"Free","price":"$0","features":["250 issues","Members","Cycles"]},{"plan":"Standard","price":"$8/seat/mo","features":["Unlimited issues","Admin","GitHub/GitLab"]},{"plan":"Plus","price":"$14/seat/mo","features":["Priority support","SAML","Scim"]}]', 'intermediate', false, '{web,desktop,mobile}', '{"Sub-second load times","Linear AI issue summaries","GitHub/GitLab integration","Roadmaps","Cycles (sprints)","Keyboard-first UX","Slack notifications","Linear Asks"}', '{"GitHub","GitLab","Figma","Slack","Zapier","Zendesk"}', NULL, true),

('Loom', 'loom', 'Async video messaging with AI summaries', 'Loom lets you record and share short screen + camera videos for async communication. AI features include automatic transcription, video summaries, action items extraction, and smart chapters. Widely adopted by remote teams to replace unnecessary meetings.', 'https://loom.com', 'freemium', '[{"plan":"Starter","price":"$0","features":["25 videos","5 min/video","720p"]},{"plan":"Business","price":"$12.50/creator/mo","features":["Unlimited videos","AI features","Custom branding"]}]', 'beginner', false, '{desktop,web,mobile}', '{"Screen + camera recording","AI video summaries","Auto transcription","Action items extraction","Smart chapters","Viewer reactions","Password protection","CTA overlays"}', '{"Slack","Gmail","Notion","Jira","Linear","GitHub"}', NULL, true),

('Otter.ai', 'otter-ai', 'AI meeting transcription and note-taking assistant', 'Otter.ai automatically transcribes meetings in real time and generates AI meeting notes with summaries, action items, and key topics. Works in Zoom, Microsoft Teams, Google Meet, and in-person. The OtterPilot feature auto-joins meetings and handles the note-taking entirely.', 'https://otter.ai', 'freemium', '[{"plan":"Basic","price":"$0","features":["300 min/mo transcription","3 AI summaries/mo"]},{"plan":"Pro","price":"$10/mo","features":["1200 min/mo","Unlimited summaries","Speaker ID"]},{"plan":"Business","price":"$20/mo","features":["OtterPilot","Shared workspaces","Admin"]}]', 'beginner', false, '{web,mobile,plugin}', '{"Real-time transcription","Meeting summaries","Action items","OtterPilot (auto-join)","Speaker identification","Slide capture","Chat integration","Export to PDF/DOCX"}', '{"Zoom","Google Meet","Microsoft Teams","Salesforce","Slack"}', NULL, true),

('Reclaim.ai', 'reclaim-ai', 'AI scheduling assistant that protects your focus time', 'Reclaim.ai automatically schedules tasks, habits, and meetings around your priorities. It defends focus time from meeting overload by intelligently placing deep work blocks. Integrates with Google Calendar and syncs with task managers. Best for knowledge workers drowning in meetings.', 'https://reclaim.ai', 'freemium', '[{"plan":"Lite","price":"$0","features":["3 tasks","5 habits","1 calendar"]},{"plan":"Starter","price":"$8/mo","features":["Unlimited tasks","Smart 1:1s","Buffer time"]},{"plan":"Business","price":"$12/mo","features":["Team features","Scheduling links"]}]', 'beginner', false, '{web}', '{"Smart task scheduling","Habit defense","Focus time protection","Buffer time","Team scheduling","Meeting optimization","Priority management","Google Calendar sync"}', '{"Google Calendar","Slack","Asana","Linear","Todoist"}', NULL, true),

('Motion', 'motion', 'AI calendar that automatically schedules your work', 'Motion uses AI to automatically schedule your tasks, meetings, and projects across your calendar. It continuously reschedules your day as new things come in, prioritizing by deadline and importance. Best for busy professionals who want a completely hands-off scheduling experience.', 'https://usemotion.com', 'paid', '[{"plan":"Individual","price":"$19/mo","features":["AI scheduling","Task manager","Calendar sync"]},{"plan":"Team","price":"$12/user/mo","features":["Team tasks","Meetings","Project management"]}]', 'beginner', false, '{web,mobile,desktop}', '{"AI auto-scheduling","Task manager","Project management","Meeting scheduler","Daily planner","Deadline protection","Recurring tasks","Google/Outlook integration"}', '{"Google Calendar","Outlook","Zoom","Slack","Asana"}', NULL, true),

('Todoist', 'todoist', 'Task manager with natural language input and AI features', 'Todoist is a clean, fast task manager with natural language input for quick task entry. AI features include task scheduling suggestions and project templates from plain language. Available on all platforms with offline support. One of the most popular personal productivity tools.', 'https://todoist.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 projects","5 collaborators","Basic features"]},{"plan":"Pro","price":"$5/mo","features":["300 projects","Reminders","AI features","Labels"]}]', 'beginner', false, '{web,mobile,desktop,plugin,api}', '{"Natural language input","Recurring tasks","Priority levels","Karma system","Templates","Filters","AI scheduling","Calendar integration","Integrations"}', '{"Google Calendar","Gmail","Outlook","Slack","Zapier","Asana"}', 'https://developer.todoist.com', true);

-- ── RESEARCH & EDUCATION ─────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Perplexity', 'perplexity', 'AI-powered search with cited, real-time answers', 'Perplexity is an AI-powered answer engine that searches the web and provides cited, up-to-date responses. Pro plan adds GPT-4o, Claude, image generation, and file uploads. Collections let you organize research. Growing as a serious Google alternative for research-heavy users.', 'https://perplexity.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Unlimited searches","Web access","Basic AI"]},{"plan":"Pro","price":"$20/mo","features":["300 Pro searches/day","GPT-4o","Claude","File upload","Image gen"]}]', 'beginner', true, '{web,mobile,api}', '{"Real-time web search","Cited answers","Multiple AI models","Collections","File analysis","Image generation","Pro search depth","Focus modes"}', '{}', 'https://docs.perplexity.ai', true),

('Elicit', 'elicit', 'AI research assistant for academic literature review', 'Elicit uses AI to search and analyze academic papers, extract key findings, and synthesize research across hundreds of papers simultaneously. Best for researchers, PhD students, and anyone doing evidence-based research. Can summarize study methodologies, outcomes, and limitations in structured tables.', 'https://elicit.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 searches/mo","Basic extraction"]},{"plan":"Basic","price":"$10/mo","features":["12 searches/mo","Full summaries"]},{"plan":"Plus","price":"$42/mo","features":["50 searches/mo","Table extraction","Team"]}]', 'intermediate', false, '{web}', '{"Academic paper search","Multi-paper summaries","Data extraction tables","Study comparison","Citation export","Concept mapping","Systematic review support"}', '{}', NULL, true),

('Consensus', 'consensus', 'Search engine for evidence-based research answers', 'Consensus searches over 200 million academic papers to find scientific evidence for or against a claim. Gives a Consensus Meter showing what percentage of studies agree. Best for fact-checking, literature search, and understanding the state of evidence on any topic.', 'https://consensus.app', 'freemium', '[{"plan":"Free","price":"$0","features":["20 searches/mo","Basic features"]},{"plan":"Premium","price":"$8.99/mo","features":["Unlimited searches","Consensus Meter","Full summaries"]}]', 'beginner', false, '{web}', '{"Scientific evidence search","Consensus Meter","Study summaries","Claim verification","GPT-4 powered synthesis","Citation links","Study quality indicators"}', '{}', NULL, true),

('NotebookLM', 'notebooklm', 'Google''s AI research notebook for document analysis', 'NotebookLM (by Google) lets you upload documents, PDFs, audio, and URLs, then have an AI chat with your sources. It grounds all answers in your uploaded materials and cites specific passages. Features auto-generated audio overviews (podcast-style summaries) of your research.', 'https://notebooklm.google.com', 'free', '[{"plan":"Free","price":"$0","features":["50 notebooks","100MB files","Audio overviews","All features"]}]', 'beginner', false, '{web}', '{"Document Q&A","Multi-source synthesis","Cited answers","Audio Overview (podcast)","Study guides","Timeline generation","Briefing documents","Notebook organization"}', '{"Google Drive","Google Docs"}', NULL, true),

('Scholarcy', 'scholarcy', 'AI tool for summarizing and extracting research papers', 'Scholarcy automatically creates structured summaries of academic papers, articles, and reports. Extracts key concepts, study design, findings, and limitations. Generates interactive flashcards for studying. Best for students and researchers who need to process large volumes of academic literature quickly.', 'https://scholarcy.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 summaries/mo","Basic extraction"]},{"plan":"Personal","price":"$9.99/mo","features":["Unlimited summaries","Flashcards","Library"]}]', 'beginner', false, '{web,plugin}', '{"Structured paper summaries","Key concept extraction","Interactive flashcards","Citation extraction","Figure analysis","Comparison tables","Browser extension","Reference manager export"}', '{"Mendeley","Zotero","Chrome Extension"}', NULL, true),

('Scite', 'scite', 'Smart citations that show how papers are cited in context', 'Scite shows not just how many times a paper is cited, but whether it was cited in a supporting or contradicting context. This helps researchers quickly gauge the reliability of a study. Features AI assistant, literature review tools, and citation databases across 1B+ citation statements.', 'https://scite.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited searches","Basic citation view"]},{"plan":"Individual","price":"$20/mo","features":["Unlimited searches","Assistant","Dashboards"]}]', 'intermediate', true, '{web,api,plugin}', '{"Supporting vs. contradicting citations","AI research assistant","Smart reference lists","Citation dashboards","Journal impact","Retraction tracking","Zotero plugin"}', '{"Zotero","Mendeley","Chrome Extension"}', NULL, true),

('Explainpaper', 'explainpaper', 'Upload a paper, highlight confusing text, get AI explanations', 'Explainpaper lets you upload any academic paper and ask questions about highlighted sections. The AI explains technical jargon, statistical methods, and complex concepts in plain language. Best for students encountering unfamiliar academic territory or researchers outside their specialty.', 'https://explainpaper.com', 'freemium', '[{"plan":"Free","price":"$0","features":["3 papers/mo","Basic explanations"]},{"plan":"Plus","price":"$12/mo","features":["Unlimited papers","Detailed explanations"]}]', 'beginner', false, '{web}', '{"Highlight and explain","Jargon simplification","Stats explanation","Follow-up questions","Paper annotation","Summary generation"}', '{}', NULL, true);

-- ── CUSTOMER SUPPORT & CHATBOTS ───────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Intercom', 'intercom', 'Customer service platform with AI agent Fin', 'Intercom is a leading customer communications platform featuring Fin, an AI support agent powered by GPT-4 that can resolve 40-60% of support tickets autonomously. Includes live chat, product tours, outbound messaging, and help center. Pricing is usage-based on resolutions.', 'https://intercom.com', 'paid', '[{"plan":"Essential","price":"$39/mo","features":["Inbox","Help center","Basic automation"]},{"plan":"Advanced","price":"$99/mo","features":["Fin AI","Multiple inboxes","Workflows"]},{"plan":"Expert","price":"$139/mo","features":["Workload management","SLA","SAML"]}]', 'intermediate', true, '{web,mobile,api}', '{"Fin AI agent","Live chat","Help center","Product tours","Outbound messaging","Conversation routing","AI summarization","Reporting"}', '{"Slack","Salesforce","HubSpot","Stripe","Shopify","Zendesk migration"}', 'https://developers.intercom.com', true),

('Tidio', 'tidio', 'Live chat and AI chatbot for small e-commerce businesses', 'Tidio combines live chat with an AI chatbot (Lyro) for small and medium businesses, especially e-commerce. Lyro AI answers customer questions automatically using your knowledge base. Free plan available. Connects to Shopify, WooCommerce, and major website platforms.', 'https://tidio.com', 'freemium', '[{"plan":"Free","price":"$0","features":["50 Lyro conversations","Live chat","Basic chatbot"]},{"plan":"Starter","price":"$29/mo","features":["100 Lyro conversations","Email marketing","Analytics"]},{"plan":"Growth","price":"$59/mo","features":["250 Lyro conversations","No Tidio branding"]}]', 'beginner', false, '{web,mobile,plugin}', '{"Lyro AI chatbot","Live chat","Email marketing","Automation flows","Shopify integration","Visitor tracking","Canned responses","Helpdesk"}', '{"Shopify","WooCommerce","WordPress","Wix","Squarespace"}', NULL, true),

('Crisp', 'crisp', 'Customer messaging platform with AI capabilities', 'Crisp is a customer messaging platform combining live chat, email, CRM, and help desk. MagicType shows you what the customer is typing before they send it. AI features include pre-written response suggestions and a shared inbox with automation. Good value alternative to Intercom.', 'https://crisp.chat', 'freemium', '[{"plan":"Free","price":"$0","features":["2 agents","Live chat","Mobile app"]},{"plan":"Pro","price":"$25/mo/workspace","features":["4 agents","Email","Integrations","AI features"]}]', 'beginner', false, '{web,mobile,desktop}', '{"Live chat","Shared inbox","AI response suggestions","MagicType (live typing preview)","CRM","Help center","Chatbot builder","Co-browsing","Analytics"}', '{"WordPress","Shopify","Slack","HubSpot","Zapier"}', NULL, true),

('Zendesk', 'zendesk', 'Enterprise customer service platform with AI', 'Zendesk is the enterprise standard for customer service operations. Zendesk AI features include automated ticket triage, Intelligent Triage, bot responses, and Quality Assurance. Best for companies with high-volume support teams. Heavy setup but highly scalable.', 'https://zendesk.com', 'paid', '[{"plan":"Suite Team","price":"$55/agent/mo","features":["Ticketing","Email","Chat","Voice"]},{"plan":"Suite Growth","price":"$89/agent/mo","features":["Help center","Multiple brands","Self-service"]},{"plan":"Suite Professional","price":"$115/agent/mo","features":["Routing","Reporting","AI features"]}]', 'intermediate', true, '{web,mobile,api}', '{"Ticket management","AI triage","Zendesk AI bot","Quality Assurance AI","Omnichannel support","Help center","Analytics","SLA management"}', '{"Salesforce","Slack","Shopify","Jira","HubSpot","Intercom migration"}', 'https://developer.zendesk.com', true);

-- ── DESIGN & CREATIVE ────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Canva', 'canva', 'Online design platform with Magic AI tools', 'Canva is the most widely used design platform for non-designers. Magic Studio AI features include Magic Design, Magic Write, Magic Eraser, background remover, and text-to-image. Used for social media graphics, presentations, videos, websites, and print materials.', 'https://canva.com', 'freemium', '[{"plan":"Free","price":"$0","features":["250k+ templates","5GB storage","Basic AI"]},{"plan":"Pro","price":"$12.99/mo","features":["Premium templates","Magic Studio","100GB storage","Background remover"]},{"plan":"Teams","price":"$14.99/seat/mo","features":["Team templates","Brand kit","Approval workflows"]}]', 'beginner', true, '{web,mobile,desktop}', '{"Magic Design","Magic Write (AI copy)","Magic Eraser","Text to Image","Background Remover","Video editor","Presentation builder","Print-ready export","Brand kit"}', '{"Google Drive","Dropbox","Mailchimp","HubSpot","Slack"}', 'https://www.canva.com/developers', true),

('Adobe Firefly', 'adobe-firefly', 'Generative AI for images and design, built into Adobe apps', 'Adobe Firefly is Adobe''s generative AI engine integrated across Photoshop, Illustrator, and Express. Features text-to-image, generative fill, generative expand, and style matching. Trained on Adobe Stock — commercially safe for enterprise use. Available standalone via web.', 'https://firefly.adobe.com', 'freemium', '[{"plan":"Free","price":"$0","features":["25 generative credits/mo","Web app"]},{"plan":"Premium","price":"$4.99/mo","features":["100 credits/mo","Premium models","Priority generation"]}]', 'intermediate', false, '{web,desktop}', '{"Text to image","Generative fill","Generative expand","Text effects","Style matching","Recolor artwork","Structure reference","Commercially safe content"}', '{"Photoshop","Illustrator","Adobe Express","Creative Cloud"}', NULL, true),

('Figma', 'figma', 'Collaborative design tool with AI-powered features', 'Figma is the industry standard for UI/UX design and prototyping. Figma AI (announced 2024) includes visual search, rename layers, remove background, and AI-generated designs from wireframes. The free plan is highly capable for individual designers.', 'https://figma.com', 'freemium', '[{"plan":"Starter","price":"$0","features":["3 files","3 pages","Collaboration"]},{"plan":"Professional","price":"$15/seat/mo","features":["Unlimited files","Dev Mode","Version history"]},{"plan":"Organization","price":"$45/seat/mo","features":["Design systems","Analytics","SSO"]}]', 'intermediate', false, '{web,desktop,plugin}', '{"Vector editing","Prototyping","Auto Layout","Components","Dev Mode","FigJam whiteboard","AI design features","Plugins ecosystem","Collaboration"}', '{"Slack","Jira","GitHub","Notion","Zeplin","Lottie"}', 'https://www.figma.com/developers', true),

('Uizard', 'uizard', 'AI design tool that turns screenshots and wireframes into UIs', 'Uizard converts hand-drawn wireframes and screenshots into editable UI designs using AI. Non-designers can generate app mockups from text prompts. Features auto-design, screenshot scanner, and design-to-code export. Best for founders and PMs who need rapid prototyping without a designer.', 'https://uizard.io', 'freemium', '[{"plan":"Free","price":"$0","features":["2 projects","Basic AI scans","Templates"]},{"plan":"Pro","price":"$12/mo","features":["Unlimited projects","All AI features","Export to Figma"]}]', 'beginner', false, '{web}', '{"Screenshot to design","Wireframe to design","Text to UI","Autodesigner","Component library","Figma export","Collaboration","Prototyping"}', '{"Figma","Sketch"}', NULL, true),

('Framer', 'framer', 'AI-powered website builder for designers', 'Framer is a web design tool that outputs production-ready websites, not just prototypes. Framer AI generates complete website sections from text descriptions. Features CMS, localization, and custom domains. Popular with startups for building marketing sites without developers.', 'https://framer.com', 'freemium', '[{"plan":"Free","price":"$0","features":["1 project","framer.site domain","100 visitors/mo"]},{"plan":"Mini","price":"$5/mo","features":["1 custom domain","1000 visitors/mo"]},{"plan":"Basic","price":"$15/mo","features":["3 domains","Unlimited pages","CMS"]}]', 'intermediate', false, '{web}', '{"AI site generation","Visual design editor","CMS","Localization","Animations","Custom code","SEO settings","Contact forms","Analytics"}', '{"Figma","Unsplash","Google Analytics","Mailchimp"}', NULL, true),

('Stable Diffusion', 'stable-diffusion', 'Open-source text-to-image AI model', 'Stable Diffusion is the most important open-source text-to-image model. Can be run locally for free (AUTOMATIC1111, ComfyUI) or via hosted APIs (Stability AI, Replicate). Highly customizable with LoRAs, ControlNet, and thousands of community models on Civitai. No content restrictions when self-hosted.', 'https://stability.ai', 'freemium', '[{"plan":"Self-hosted","price":"$0","features":["Unlimited images","Full control","NSFW capable"]},{"plan":"Stability AI API","price":"Pay-per-use","features":["Hosted API","Stable Diffusion 3","No GPU required"]}]', 'advanced', true, '{desktop,api}', '{"Text to image","Image to image","Inpainting","Outpainting","ControlNet","LoRA fine-tuning","Open source","ComfyUI/A1111 support","Thousands of community models"}', '{"ComfyUI","AUTOMATIC1111","Civitai","Replicate"}', 'https://platform.stability.ai/docs', true);

-- ── VOICE & AUDIO ────────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('ElevenLabs', 'elevenlabs', 'Most realistic AI voice synthesis and cloning', 'ElevenLabs is the leading AI voice synthesis platform, known for its ultra-realistic voices and instant voice cloning. Create custom voices from as little as 1 minute of audio. Features include multilingual dubbing, voice design, and an API used by major media companies.', 'https://elevenlabs.io', 'freemium', '[{"plan":"Free","price":"$0","features":["10k chars/mo","3 custom voices","Watermarked"]},{"plan":"Starter","price":"$5/mo","features":["30k chars/mo","10 custom voices","No watermark"]},{"plan":"Creator","price":"$22/mo","features":["100k chars/mo","30 custom voices","Professional clone"]}]', 'beginner', true, '{web,api}', '{"Text to speech","Voice cloning","Multilingual dubbing","Voice design","Projects (long-form)","Sound effects","AI dubbing","Real-time voice conversion"}', '{"Zapier","Make","Adobe","Unity"}', 'https://docs.elevenlabs.io', true),

('Murf.ai', 'murf-ai', 'AI voiceover studio for videos and presentations', 'Murf.ai is an AI voiceover platform used primarily for videos, presentations, e-learning, and explainer content. Features 120+ voices in 20+ languages, voice emphasis control, video sync, and a studio editor. Popular with content creators and e-learning developers.', 'https://murf.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["10 min/mo","Basic voices","Watermarked"]},{"plan":"Creator","price":"$19/mo","features":["2 hours/mo","120+ voices","No watermark"]},{"plan":"Business","price":"$26/mo","features":["4 hours/mo","Voice cloning","Team"]}]', 'beginner', false, '{web}', '{"120+ AI voices","20+ languages","Video sync","Voice emphasis","Background music","Pronunciation editor","E-learning export","Commercial license"}', '{"Google Slides","PowerPoint"}', NULL, true),

('Descript', 'descript', 'Video and podcast editor that works like a document', 'Descript lets you edit audio and video by editing the transcript — delete a word in the transcript and it removes it from the video. AI features include filler word removal, background noise reduction, Studio Sound, and Overdub (AI voice clone for corrections). Transformative for podcasters and video creators.', 'https://descript.com', 'freemium', '[{"plan":"Free","price":"$0","features":["1 hour transcription","1 Overdub voice","3 export watermarks"]},{"plan":"Creator","price":"$12/mo","features":["10 hours transcription","Filler word removal","Studio Sound"]},{"plan":"Pro","price":"$24/mo","features":["30 hours","Overdub","Screen recording","Remove filler words"]}]', 'beginner', false, '{desktop,web}', '{"Transcript-based editing","Filler word removal","Overdub AI voice clone","Studio Sound (noise reduction)","Screen recording","Multi-track audio","Chapters","Remote recording"}', '{"Zoom","YouTube","Dropbox","Google Drive"}', NULL, true),

('Whisper', 'whisper', 'OpenAI''s open-source speech recognition model', 'Whisper is OpenAI''s open-source automatic speech recognition (ASR) model, one of the most accurate available. Can be run locally or via API. Supports 100 languages and translates to English. Used as the engine inside many transcription products. Free to use self-hosted; API pricing per minute.', 'https://openai.com/research/whisper', 'freemium', '[{"plan":"Self-hosted","price":"$0","features":["Unlimited transcription","100 languages","Open source"]},{"plan":"API","price":"$0.006/min","features":["Hosted API","No GPU required","Fast"]}]', 'advanced', true, '{api,cli,desktop}', '{"100-language transcription","English translation","Speaker diarization (with add-ons)","Multiple model sizes","Timestamp generation","Open source","Low latency (large-v3)"}', '{"Python","Hugging Face","Replicate"}', 'https://platform.openai.com/docs/guides/speech-to-text', true),

('Suno', 'suno', 'AI that generates full songs from text prompts', 'Suno generates complete songs — with vocals, instruments, and lyrics — from a text prompt. Just describe the genre, mood, and theme. Creates 2-minute tracks with remarkably coherent composition. Free plan includes 50 credits/day. Best AI music generation tool for quick, song-format content.', 'https://suno.com', 'freemium', '[{"plan":"Basic","price":"$0","features":["50 credits/day","10 songs/day","Non-commercial use"]},{"plan":"Pro","price":"$8/mo","features":["2500 credits/mo","Commercial use","Priority generation"]},{"plan":"Premier","price":"$24/mo","features":["10k credits/mo"]}]', 'beginner', false, '{web,mobile}', '{"Text to song","Vocal generation","Instrumental tracks","Style control","Lyrics input","Song extension","Cover songs","Multiple genres"}', '{}', NULL, true),

('Udio', 'udio', 'AI music generation with fine-grained style control', 'Udio (made by ex-Google DeepMind team) generates high-quality, detailed music from text prompts with more fine-grained control than Suno. Allows specifying instruments, tempo, and mixing multiple styles. Produces longer tracks and has stronger composition quality for complex musical styles.', 'https://udio.com', 'freemium', '[{"plan":"Free","price":"$0","features":["300 credits/mo","100 songs/mo","Non-commercial"]},{"plan":"Standard","price":"$10/mo","features":["1200 credits/mo","Commercial use"]},{"plan":"Pro","price":"$30/mo","features":["4800 credits/mo","Priority"]}]', 'beginner', false, '{web}', '{"Text to music","Instrumental generation","Style mixing","Lyrics input","Long-form tracks","Genre blending","Remaster feature","Cover art generation"}', '{}', NULL, true);

-- ── DATA & ANALYTICS ─────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Julius AI', 'julius-ai', 'AI data analyst — upload data, ask questions, get charts', 'Julius AI lets you upload CSV, Excel, or connect databases and ask questions in plain English to get charts, analysis, and insights. Replaces manual Excel work for non-technical analysts. Generates Python/R code behind the scenes and explains its methodology.', 'https://julius.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["10 messages/day","1 data file","Basic charts"]},{"plan":"Essential","price":"$20/mo","features":["250 messages/day","Multiple files","Advanced analytics"]}]', 'beginner', true, '{web}', '{"Natural language data query","CSV/Excel upload","Chart generation","Regression analysis","Trend analysis","Code generation (Python/R)","Data cleaning","Export results"}', '{"Google Sheets","Excel","PostgreSQL"}', NULL, true),

('Obviously AI', 'obviously-ai', 'No-code machine learning and predictive analytics', 'Obviously AI builds predictive machine learning models from your data without writing code. Point at a dataset, choose a prediction target, and get an accurate model in minutes. Used for churn prediction, sales forecasting, fraud detection, and risk scoring.', 'https://obviously.ai', 'paid', '[{"plan":"Starter","price":"$75/mo","features":["5 models","1000 predictions/mo","Basic accuracy"]},{"plan":"Growth","price":"$175/mo","features":["15 models","Unlimited predictions","API access"]}]', 'intermediate', true, '{web,api}', '{"No-code ML model building","Churn prediction","Sales forecasting","Fraud detection","Feature importance","Model accuracy metrics","API deployment","CSV/database import"}', '{"Salesforce","HubSpot","Google Sheets","Snowflake"}', NULL, true),

('Akkio', 'akkio', 'AI analytics platform for agencies and consultants', 'Akkio is a no-code AI analytics platform built for agencies and consultants. Build predictive models, generate reports, and create AI-powered client dashboards without data science expertise. Features Chat Explore for natural language data analysis and automatic anomaly detection.', 'https://akkio.com', 'freemium', '[{"plan":"Free","price":"$0","features":["1 deployment","1000 rows","Basic analytics"]},{"plan":"Growth","price":"$49/mo","features":["10 deployments","Chat Explore","Client dashboards"]}]', 'intermediate', false, '{web}', '{"Predictive modeling","Chat Explore (NL queries)","Anomaly detection","Client reporting","Auto ML","Deployment to apps","CSV/database support","Dashboard builder"}', '{"HubSpot","Salesforce","Google Sheets","Airtable"}', NULL, true),

('Tableau', 'tableau', 'Enterprise business intelligence and visualization platform', 'Tableau is the leading enterprise BI platform for creating interactive dashboards and reports. Tableau AI (formerly Einstein Analytics) adds natural language queries, AI-recommended charts, and predictive analytics. Now owned by Salesforce. Tableau Public is free for public data visualization.', 'https://tableau.com', 'freemium', '[{"plan":"Tableau Public","price":"$0","features":["Public dashboards","Public data only"]},{"plan":"Creator","price":"$75/user/mo","features":["Full Tableau Desktop","Prep","Server publishing"]},{"plan":"Explorer","price":"$42/user/mo","features":["View and create dashboards"]}]', 'intermediate', true, '{desktop,web,api}', '{"Interactive dashboards","Natural language queries","AI chart recommendations","Predictive analytics","Data blending","Mobile-responsive","Tableau Prep (ETL)","API embedding"}', '{"Salesforce","AWS","Google Cloud","Snowflake","SQL databases"}', 'https://help.tableau.com/current/api', true),

('Metabase', 'metabase', 'Open-source business intelligence for teams', 'Metabase is an open-source BI tool that makes data accessible to non-technical team members. Features a no-code query builder, natural language questions, and auto-generated dashboard suggestions. The self-hosted version is free; the cloud version starts at $500/month for teams.', 'https://metabase.com', 'freemium', '[{"plan":"Open Source","price":"$0","features":["Self-hosted","Unlimited users","All core features"]},{"plan":"Pro","price":"$500/mo","features":["Hosted","Audit log","SSO","Priority support"]}]', 'intermediate', true, '{web,desktop,api}', '{"No-code query builder","AI question suggestions","Dashboard builder","Alerts","Embedding","Self-hosting option","Multiple database support","SQL editor","Slack integration"}', '{"PostgreSQL","MySQL","Redshift","BigQuery","MongoDB","Snowflake","Slack"}', 'https://www.metabase.com/docs/latest/api-documentation', true);

-- ── DEVELOPER & CODE ─────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('v0.dev', 'v0-dev', 'Vercel''s AI that generates React components from prompts', 'v0 by Vercel generates production-ready React + Tailwind CSS components from text descriptions and screenshots. Uses Claude and GPT-4 under the hood. Components render in a live preview and can be copied to any Next.js project. Best for rapid UI prototyping and component generation.', 'https://v0.dev', 'freemium', '[{"plan":"Free","price":"$0","features":["200 credits/mo","Basic generation"]},{"plan":"Premium","price":"$20/mo","features":["2000 credits/mo","Private components","Priority"]}]', 'intermediate', false, '{web}', '{"React component generation","Tailwind CSS output","Live preview","Screenshot to code","shadcn/ui components","Next.js compatible","Iterative editing","Code export"}', '{"Next.js","shadcn/ui","Tailwind CSS","Vercel"}', NULL, true),

('Bolt.new', 'bolt-new', 'AI full-stack web app builder in the browser', 'Bolt.new (by StackBlitz) builds and runs full-stack web applications entirely in the browser — no local setup. Generates Next.js, React, Svelte, and more from natural language prompts. Can install packages, run servers, and iterate on code with AI. Best for rapid prototyping without configuration overhead.', 'https://bolt.new', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited generations","Basic models"]},{"plan":"Pro","price":"$20/mo","features":["More tokens","Priority models","Private projects"]}]', 'intermediate', false, '{web}', '{"Full-stack generation","In-browser runtime","npm package install","Multiple frameworks","Live preview","Code editing","Deploy to Netlify","AI chat"}', '{"Netlify","GitHub"}', NULL, true),

('Lovable', 'lovable', 'AI-powered full-stack app builder, deploy in minutes', 'Lovable (formerly GPT Engineer) builds complete web applications from a description, including authentication, database, and UI. Uses Supabase for backend. Non-technical founders can ship real products. Features visual editing, GitHub sync, and one-click deploy.', 'https://lovable.dev', 'freemium', '[{"plan":"Free","price":"$0","features":["5 projects","Basic generation"]},{"plan":"Starter","price":"$20/mo","features":["Unlimited projects","GitHub sync","Custom domains"]},{"plan":"Launch","price":"$50/mo","features":["Advanced AI","Priority support"]}]', 'beginner', false, '{web}', '{"Full-stack app generation","Supabase backend","GitHub sync","Visual editor","Authentication built-in","Custom domains","Deploy to production","Non-technical friendly"}', '{"Supabase","GitHub","Netlify"}', NULL, true),

('Tabnine', 'tabnine', 'AI code completion that runs privately and on-premises', 'Tabnine is an AI code completion tool that runs models locally or on your own infrastructure — no code leaves your environment. This makes it suitable for enterprise environments with strict data security requirements. Supports 80+ languages and major IDEs.', 'https://tabnine.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Basic completions","50 languages","All IDEs"]},{"plan":"Pro","price":"$12/user/mo","features":["Full AI features","Private models","Team learning"]}]', 'intermediate', true, '{plugin,api}', '{"Private AI (no code upload)","On-premises deployment","80+ language support","All major IDEs","Team model training","Code review","Chat assistant","Test generation"}', '{"VS Code","JetBrains","Vim","Neovim","Emacs","Eclipse"}', 'https://docs.tabnine.com', true),

('Codeium', 'codeium', 'Free AI code completion and chat for developers', 'Codeium provides AI code completion and chat assistance for free, with no usage limits. Supports 70+ languages and 40+ IDEs. Faster autocomplete than Copilot according to benchmarks. The Windsurf IDE (Codeium''s own editor) adds agentic coding capabilities. Best free Copilot alternative.', 'https://codeium.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Unlimited completions","Chat","70+ languages"]},{"plan":"Teams","price":"$12/mo","features":["Admin controls","Analytics","Priority support"]}]', 'intermediate', false, '{plugin,desktop}', '{"Unlimited free completions","70+ languages","40+ IDE support","Chat assistant","In-line edits","Windsurf IDE","Function docstrings","Autocomplete from comments"}', '{"VS Code","JetBrains","Vim","Neovim","JupyterLab","Emacs"}', 'https://codeium.com/docs', true),

('Replit', 'replit', 'AI-powered browser IDE for building and deploying apps', 'Replit is a browser-based IDE that lets you build and deploy applications without setup. Replit AI (Ghostwriter) assists with code generation, debugging, and refactoring. Best for beginners learning to code, rapid prototyping, and educational settings. Free tier includes unlimited projects.', 'https://replit.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Unlimited projects","Basic Ghostwriter","500MB RAM"]},{"plan":"Core","price":"$20/mo","features":["Advanced AI","Stronger compute","Deployments","Private projects"]}]', 'beginner', true, '{web}', '{"Browser-based IDE","Ghostwriter AI","One-click deploy","Multiplayer coding","Database built-in","Mobile coding","100+ languages","Templates","Bounties"}', '{"GitHub","Google OAuth","Nix packages"}', 'https://docs.replit.com', true),

('Devin', 'devin', 'AI software engineer that autonomously completes coding tasks', 'Devin by Cognition is an AI software engineer that can take on entire software projects autonomously — writing code, running tests, fixing bugs, and deploying. Designed for professional engineering teams to handle routine tickets while engineers focus on higher-level work. Controversial but impressive capabilities.', 'https://cognition.ai/devin', 'paid', '[{"plan":"Teams","price":"Contact sales","features":["Autonomous coding","GitHub integration","Slack","Full codebase access"]}]', 'advanced', false, '{web}', '{"Autonomous coding agent","Bug fixing","PR review and creation","Full codebase understanding","Test writing","Deployment","Long-horizon tasks","Slack integration"}', '{"GitHub","Slack","Linear","Jira"}', NULL, true);

-- ── HEALTHCARE & SPECIALIZED ──────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES
('Nabla', 'nabla', 'AI clinical note-taking assistant for healthcare providers', 'Nabla is an AI ambient documentation tool for healthcare. It listens to provider-patient conversations and auto-generates clinical notes in SOAP format. Reduces documentation time by 70% according to studies. Integrates with major EHR systems. HIPAA compliant.', 'https://nabla.com', 'paid', '[{"plan":"Individual","price":"$99/provider/mo","features":["Unlimited consultations","SOAP notes","EHR integration"]},{"plan":"Enterprise","price":"Contact sales","features":["Team management","Analytics","Custom templates"]}]', 'intermediate', true, '{web,mobile}', '{"Ambient note generation","SOAP format","EHR integration","Voice recognition","Template customization","Real-time transcription","HIPAA compliant","Multilingual support"}', '{"Epic","Athenahealth","eClinicalWorks","Cerner"}', NULL, true),

('Sybill', 'sybill', 'AI that summarizes sales calls and generates CRM notes', 'Sybill records and transcribes sales calls, then generates CRM notes, email follow-ups, and behavioral analysis of buyer intent. Detects when prospects are engaged vs. disinterested based on verbal and nonverbal cues. Integrates with Salesforce, HubSpot, and Zoom.', 'https://sybill.ai', 'paid', '[{"plan":"Starter","price":"$49/user/mo","features":["Call recording","AI summaries","CRM sync"]},{"plan":"Pro","price":"$99/user/mo","features":["Behavioral analysis","Deal intelligence","Coaching"]}]', 'intermediate', false, '{web,plugin}', '{"Sales call transcription","AI CRM notes","Email follow-up generation","Buyer intent analysis","Deal health scoring","Coaching insights","Zoom integration","CRM sync"}', '{"Salesforce","HubSpot","Zoom","Gong","Outreach"}', NULL, true);
