-- ============================================================
-- Batch 3: ~120 more AI tools
-- Categories: Image Generation, Video AI, Presentation,
--   E-commerce, Business/Finance, Security, AI Agents,
--   Translation & Language, HR & Recruiting, Legal & Compliance
-- ============================================================

-- ─── IMAGE GENERATION ────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('DALL-E 3', 'dall-e-3', 'OpenAI''s most capable image generation model', 'DALL-E 3 creates highly detailed and accurate images from text descriptions, with improved understanding of nuance and context. Available via ChatGPT Plus and OpenAI API.', 'https://openai.com/dall-e-3', 'freemium', '[{"plan":"ChatGPT Free","price":0,"period":"month","features":["Limited generations"]},{"plan":"ChatGPT Plus","price":20,"period":"month","features":["Priority access","HD generations","Unlimited standard"]}]', 'beginner', true, '{web,api}', '{"Text-to-image generation","HD image output","Inpainting","Prompt rewriting","DALL-E API access","Safety filters"}', '{"ChatGPT","OpenAI API","Microsoft Designer","Bing Image Creator"}', 'https://platform.openai.com/docs/guides/images', true),

('Adobe Firefly', 'adobe-firefly', 'AI image and creative content generation built for creators', 'Adobe Firefly is a family of creative generative AI models that generates images, text effects, and vectors trained on licensed content. Deeply integrated into Adobe Creative Cloud apps.', 'https://firefly.adobe.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["25 generative credits/month"]},{"plan":"Creative Cloud","price":54.99,"period":"month","features":["100 generative credits/month","All CC apps"]}]', 'beginner', true, '{web,api}', '{"Text-to-image","Generative Fill","Text effects","Generative Recolor","Structure Reference","Style Reference"}', '{"Adobe Photoshop","Adobe Illustrator","Adobe Express","Adobe Premiere Pro"}', 'https://developer.adobe.com/firefly-services/', true),

('Leonardo.ai', 'leonardo-ai', 'AI image generation platform for game assets and creative content', 'Leonardo.ai specializes in generating consistent, high-quality game assets, concept art, and character designs. Offers fine-tuning, custom models, and a large community of trained models.', 'https://leonardo.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["150 tokens/day","Basic features"]},{"plan":"Apprentice","price":12,"period":"month","features":["8500 tokens/month","Priority generation"]},{"plan":"Artisan","price":30,"period":"month","features":["25000 tokens/month","Unlimited relaxed"]}]', 'intermediate', true, '{web,api}', '{"Text-to-image","Image-to-image","Inpainting","ControlNet","Motion (video)","Custom model training","Canvas editor"}', '{"Discord","Zapier","API integrations"}', 'https://docs.leonardo.ai', true),

('Ideogram', 'ideogram', 'AI image generator that actually gets text right', 'Ideogram excels at generating images with accurate, readable text embedded in them — a notoriously difficult challenge for AI art generators. Great for logos, posters, and graphics with typography.', 'https://ideogram.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["10 slow generations/day"]},{"plan":"Basic","price":7,"period":"month","features":["400 priority generations/month"]},{"plan":"Plus","price":16,"period":"month","features":["1000 priority generations/month"]}]', 'beginner', false, '{web}', '{"Text-in-image generation","Magic prompt","Remix","Describe (image to prompt)","Canvas","Reframe"}', '{}', 'https://about.ideogram.ai', true),

('Playground AI', 'playground-ai', 'Free-to-use AI image creator with powerful editing tools', 'Playground AI lets you create stunning images with a generous free tier. Supports multiple AI models (Stable Diffusion, DALL-E, playground-v2) with real-time editing, filters, and a social community.', 'https://playground.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["500 images/day","Playground v2 model"]},{"plan":"Pro","price":15,"period":"month","features":["Unlimited standard images","Priority queue"]}]', 'beginner', true, '{web}', '{"Multi-model support","Canvas editor","Image editing","Filters","Outpainting","Community gallery"}', '{"Stable Diffusion models","DALL-E"}', 'https://playground.com/blog', true),

('Getimg.ai', 'getimg-ai', 'AI image generation suite with 60+ models', 'Getimg.ai provides access to 60+ AI models for image generation, editing, and enhancement. Features face swap, text-to-image, image-to-image, and a real-time canvas editor for professionals.', 'https://getimg.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["100 images/month"]},{"plan":"Basic","price":12,"period":"month","features":["3000 images/month"]},{"plan":"Starter","price":29,"period":"month","features":["12000 images/month"]}]', 'intermediate', true, '{web,api}', '{"60+ AI models","Text-to-image","Image-to-image","Inpainting","Outpainting","Face swap","Upscaling","API access"}', '{}', 'https://docs.getimg.ai', true),

('Bing Image Creator', 'bing-image-creator', 'Free AI image generation powered by DALL-E 3', 'Microsoft''s free image generation tool powered by DALL-E 3, accessible directly in Bing and Edge browser. Generates high-quality images from text descriptions with no sign-up required for basic use.', 'https://www.bing.com/images/create', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Boosted generations with Microsoft account","Standard generations unlimited"]}]', 'beginner', false, '{web}', '{"DALL-E 3 powered","Free to use","Edge integration","Image History"}', '{"Microsoft Edge","Bing Chat","Copilot"}', 'https://www.bing.com/images/create', true),

('NightCafe', 'nightcafe', 'AI art generator with multiple creation modes', 'NightCafe is an AI art generator with a vibrant community, daily challenges, and support for multiple algorithms including Stable Diffusion, DALL-E, and SDXL. Features a credit system and social features.', 'https://creator.nightcafe.studio', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 free credits/day"]},{"plan":"AI Hobbyist","price":7.99,"period":"month","features":["100 credits/month"]},{"plan":"AI Enthusiast","price":15.99,"period":"month","features":["250 credits/month"]}]', 'beginner', false, '{web,mobile}', '{"Multiple AI algorithms","Text-to-image","Style transfer","Daily challenges","Community gallery","NFT minting"}', '{}', 'https://nightcafe.studio', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── VIDEO AI ────────────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Sora', 'sora', 'OpenAI''s text-to-video model for realistic video generation', 'Sora generates realistic and imaginative video scenes from text instructions, creating videos up to a minute long while maintaining visual quality and adhering to the user''s prompt.', 'https://sora.com', 'paid', '[{"plan":"ChatGPT Plus","price":20,"period":"month","features":["50 priority generations","Relaxed mode"]},{"plan":"ChatGPT Pro","price":200,"period":"month","features":["Unlimited relaxed","500 priority","1080p"]}]', 'beginner', false, '{web}', '{"Text-to-video","Image-to-video","Video-to-video","Storyboard","Remix","Blend","Loop","Cut","Re-cut"}', '{"ChatGPT"}', 'https://sora.com', true),

('Pika', 'pika', 'AI video creation and editing for everyone', 'Pika transforms text and images into cinematic videos with precise control over motion, camera angles, and style. Features sound effects generation and easy-to-use controls for non-technical users.', 'https://pika.art', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["150 credits/month"]},{"plan":"Standard","price":8,"period":"month","features":["700 credits/month","HD downloads"]},{"plan":"Pro","price":28,"period":"month","features":["2000 credits/month","4K","Priority"]}]', 'beginner', false, '{web,mobile}', '{"Text-to-video","Image-to-video","Video-to-video","Sound effects","Lip sync","Pikaffects","Camera controls"}', '{}', 'https://pika.art', true),

('Luma Dream Machine', 'luma-dream-machine', 'Photorealistic AI video generation from text and images', 'Luma AI''s Dream Machine generates high-quality, realistic videos from text and images. Known for exceptionally realistic physics, motion, and consistency in character appearance across frames.', 'https://lumalabs.ai/dream-machine', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["30 generations/month"]},{"plan":"Standard","price":29.99,"period":"month","features":["120 generations/month","720p"]},{"plan":"Plus","price":99.99,"period":"month","features":["400 generations/month","1080p"]}]', 'beginner', true, '{web,api}', '{"Text-to-video","Image-to-video","Keyframe control","Camera motion","Extend video","Photorealistic output"}', '{}', 'https://lumalabs.ai/api', true),

('Kling AI', 'kling-ai', 'Kuaishou''s powerful text-to-video and image-to-video model', 'Kling AI by Kuaishou generates high-quality 1080p videos up to 3 minutes long from text or images. Features 5-second and 10-second video generation with realistic motion and high consistency.', 'https://klingai.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["66 credits/month"]},{"plan":"Standard","price":9.99,"period":"month","features":["660 credits/month"]},{"plan":"Pro","price":29.99,"period":"month","features":["3000 credits/month"]}]', 'beginner', true, '{web,api}', '{"Text-to-video","Image-to-video","Face swap","Lip sync","Virtual try-on","1080p output","5 and 10 second videos"}', '{}', 'https://klingai.com/api', true),

('HeyGen', 'heygen', 'AI video generation with realistic avatars and voice cloning', 'HeyGen creates professional videos using AI avatars that speak in 175+ languages. Ideal for marketing, training, and product demos — upload a script, choose an avatar, and export a polished video.', 'https://heygen.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 video credits","1 min/video"]},{"plan":"Creator","price":29,"period":"month","features":["15 video credits","5 min/video"]},{"plan":"Team","price":89,"period":"month","features":["Unlimited seats","30 credits"]}]', 'beginner', true, '{web,api}', '{"AI avatars","Voice cloning","Script-to-video","Talking photo","Video translation","Custom avatar","175+ languages"}', '{"Zapier","HubSpot","Salesforce"}', 'https://docs.heygen.com', true),

('Synthesia', 'synthesia', 'Create professional AI videos from text in minutes', 'Synthesia turns text scripts into professional videos featuring AI presenters in 130+ languages. Used by 50,000+ businesses for training videos, marketing, and internal communications without cameras.', 'https://synthesia.io', 'paid', '[{"plan":"Starter","price":22,"period":"month","features":["3 video exports/month","120+ AI avatars"]},{"plan":"Creator","price":67,"period":"month","features":["10 video exports/month","Custom AI avatar"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom","API access"]}]', 'beginner', true, '{web,api}', '{"130+ languages","180+ AI avatars","Custom avatar","Screen recording","Templates","Brand kit","Collaboration"}', '{"PowerPoint","Google Slides","Canva","SharePoint","LMS integrations"}', 'https://help.synthesia.io', true),

('Invideo AI', 'invideo-ai', 'Turn ideas and scripts into polished videos with AI', 'InVideo AI converts text prompts or scripts into fully edited videos with stock footage, voiceover, music, and captions. Ideal for YouTube, social media, and marketing content at scale.', 'https://invideo.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["10 minutes export/week","Watermark"]},{"plan":"Plus","price":25,"period":"month","features":["50 AI videos/month","No watermark"]},{"plan":"Max","price":60,"period":"month","features":["200 AI videos/month","GPT-4o"]}]', 'beginner', false, '{web}', '{"Text-to-video","AI script writer","Stock footage","AI voiceover","Auto subtitles","Templates","Brand presets"}', '{"YouTube","iStock","Shutterstock","Storyblocks"}', 'https://invideo.io/help', true),

('Captions', 'captions', 'AI-powered video creation and editing app', 'Captions is an AI video app that auto-generates captions, removes filler words, enhances eye contact, and creates short-form content from long videos. Popular among creators for polished social media content.', 'https://captions.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Limited exports"]},{"plan":"Pro","price":16.99,"period":"month","features":["Unlimited exports","Eye contact correction","Green screen"]}]', 'beginner', false, '{mobile,web}', '{"Auto captions","Filler word removal","Eye contact correction","AI video creation","Background removal","Translation","AI script"}', '{"TikTok","Instagram","YouTube"}', 'https://captions.ai', true),

('Opus Clip', 'opus-clip', 'Repurpose long videos into viral short clips with AI', 'Opus Clip uses AI to analyze long-form videos (YouTube, podcasts, webinars) and automatically extracts the most engaging moments into short clips ready for TikTok, Reels, and Shorts.', 'https://opus.pro', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["60 upload minutes/month"]},{"plan":"Starter","price":9,"period":"month","features":["150 upload minutes/month"]},{"plan":"Pro","price":29,"period":"month","features":["Unlimited clipping","Brand kit"]}]', 'beginner', false, '{web}', '{"Auto clip generation","Viral score","Auto captions","Face tracking","Speaker detection","Brand templates","B-roll"}', '{"YouTube","Zoom","Google Drive","Dropbox","TikTok"}', 'https://opus.pro', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── PRESENTATION & SLIDES ───────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Gamma', 'gamma', 'AI-powered presentations, documents, and websites', 'Gamma uses AI to create beautiful, interactive presentations, documents, and web pages from a simple prompt or outline. Features a modern card-based format that works great for modern audiences.', 'https://gamma.app', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["400 AI credits","Gamma branding"]},{"plan":"Plus","price":10,"period":"month","features":["400 credits/month","Remove branding","Custom fonts"]},{"plan":"Pro","price":20,"period":"month","features":["Unlimited AI","Custom domain"]}]', 'beginner', false, '{web}', '{"AI generation","Presentation","Documents","Webpages","Templates","Analytics","Embed media","One-click redesign"}', '{"Figma","Loom","YouTube","Giphy","Unsplash"}', 'https://gamma.app', true),

('Beautiful.ai', 'beautiful-ai', 'AI-powered presentation software that designs itself', 'Beautiful.ai uses Smart Slide technology to automatically rearrange content and maintain design consistency as you edit. AI suggests layouts, icons, and images based on your content.', 'https://beautiful.ai', 'paid', '[{"plan":"Pro","price":12,"period":"month","features":["Unlimited slides","60+ templates","Priority support"]},{"plan":"Team","price":40,"period":"month","features":["Custom brand kit","Team analytics","SSO"]}]', 'beginner', false, '{web}', '{"Smart slide layouts","AI design","Templates","Brand kit","Real-time collaboration","Presenter mode","Analytics"}', '{"Slack","Google Drive","Dropbox","PowerPoint"}', 'https://support.beautiful.ai', true),

('Pitch', 'pitch', 'Collaborative presentation software for modern teams', 'Pitch combines AI-assisted design with real-time collaboration for teams to create polished presentations. Features AI content generation, custom fonts, video embedding, and powerful analytics.', 'https://pitch.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Unlimited presentations","3 workspaces"]},{"plan":"Pro","price":8,"period":"month","features":["Unlimited workspaces","Analytics","Priority support"]}]', 'beginner', false, '{web,desktop}', '{"AI content generation","Real-time collaboration","Templates","Analytics","Video recording","Custom fonts","Team workspace"}', '{"Figma","Unsplash","Giphy","YouTube","Google Analytics"}', 'https://help.pitch.com', true),

('Tome', 'tome', 'AI-native storytelling format for presentations', 'Tome is an AI-native presentation tool that generates complete narrative presentations from a single prompt. Features tiles, embedded video, 3D renderings, and live web content for interactive storytelling.', 'https://tome.app', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["500 AI credits"]},{"plan":"Pro","price":16,"period":"month","features":["Unlimited generations","Custom fonts","Remove branding"]}]', 'beginner', false, '{web}', '{"AI generation","Narrative format","3D tiles","Web embed","Prototype tiles","Dalle integration","Analytics"}', '{"Figma","Twitter/X","YouTube","Loom"}', 'https://tome.app', true),

('SlidesAI', 'slidesai', 'Create presentations from text in seconds with AI', 'SlidesAI converts any text or topic into fully designed Google Slides presentations. Summarizes content, suggests layouts, and generates speaker notes automatically.', 'https://slidesai.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 presentations/month","Max 2000 chars"]},{"plan":"Basic","price":10,"period":"month","features":["10 presentations/month"]},{"plan":"Pro","price":20,"period":"month","features":["Unlimited presentations"]}]', 'beginner', false, '{web}', '{"Text-to-presentation","Google Slides integration","Speaker notes","Multiple languages","Templates"}', '{"Google Slides","Google Workspace"}', 'https://slidesai.io/blog', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── E-COMMERCE & SALES ──────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Shopify Magic', 'shopify-magic', 'AI tools built directly into Shopify for merchants', 'Shopify Magic is a suite of AI features built into Shopify including AI-generated product descriptions, email subject lines, FAQ generation, and intelligent search for store owners.', 'https://www.shopify.com/magic', 'paid', '[{"plan":"Basic","price":29,"period":"month","features":["All Magic features included"]},{"plan":"Shopify","price":79,"period":"month","features":["All Magic features","Staff accounts"]}]', 'beginner', false, '{web}', '{"AI product descriptions","Email subject lines","FAQ generation","Sidekick AI assistant","Semantic search","Image background removal"}', '{"Shopify ecosystem"}', 'https://help.shopify.com', true),

('Octane AI', 'octane-ai', 'Quizzes and personalization for e-commerce brands', 'Octane AI helps e-commerce brands build product recommendation quizzes, personalized SMS/email flows, and zero-party data collection. Increases conversions and AOV through AI-driven personalization.', 'https://octaneai.com', 'paid', '[{"plan":"Octane","price":50,"period":"month","features":["Quizzes","Pop-ups","Opt-in tools"]},{"plan":"Plus","price":200,"period":"month","features":["Advanced flows","A/B testing","Analytics"]}]', 'intermediate', true, '{web,api}', '{"Product recommendation quizzes","Zero-party data","SMS marketing","Email flows","A/B testing","Klaviyo sync"}', '{"Shopify","Klaviyo","Attentive","Postscript"}', 'https://docs.octaneai.com', true),

('Tidio', 'tidio', 'AI customer service and live chat for e-commerce', 'Tidio combines live chat, AI chatbots, and email marketing in one platform for e-commerce stores. The Lyro AI chatbot handles up to 70% of customer inquiries automatically.', 'https://tidio.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["50 live chat conversations","Lyro 50 conversations"]},{"plan":"Starter","price":29,"period":"month","features":["Unlimited live chat","100 Lyro conversations"]},{"plan":"Growth","price":59,"period":"month","features":["250 Lyro conversations","Flows"]}]', 'beginner', true, '{web,api}', '{"Live chat","Lyro AI chatbot","Email marketing","Flows automation","Product recommendations","Abandoned cart"}', '{"Shopify","WooCommerce","Wix","BigCommerce","Klaviyo"}', 'https://help.tidio.com', true),

('Visily', 'visily', 'AI UI design tool for non-designers', 'Visily converts screenshots, PDFs, or text prompts into editable UI mockups instantly. Enables product managers and marketers to create wireframes and prototypes without design skills.', 'https://visily.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 active projects","Unlimited screens"]},{"plan":"Pro","price":20,"period":"month","features":["Unlimited projects","Advanced AI","Custom templates"]}]', 'beginner', false, '{web}', '{"Screenshot-to-UI","Text-to-UI","AI component generation","Wireframing","Prototyping","Design system","Export to Figma"}', '{"Figma","Jira","Confluence"}', 'https://help.visily.ai', true),

('Nosto', 'nosto', 'AI-powered personalization platform for e-commerce', 'Nosto delivers personalized shopping experiences through AI-driven product recommendations, content personalization, dynamic bundles, and behavioral targeting to increase conversion rates.', 'https://nosto.com', 'paid', '[{"plan":"Growth","price":0,"period":"month","features":["Revenue share model"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full feature set"]}]', 'intermediate', true, '{web,api}', '{"Product recommendations","Content personalization","Pop-ups","Search","Dynamic bundles","A/B testing","Segmentation"}', '{"Shopify","Magento","Salesforce Commerce","BigCommerce","Klaviyo"}', 'https://docs.nosto.com', true),

('Copy.ai for Sales', 'copy-ai-sales', 'AI outreach and sales copy automation', 'Copy.ai for Sales automates prospecting messages, follow-up sequences, LinkedIn outreach, and cold emails with personalized AI-generated content at scale.', 'https://copy.ai/sales', 'paid', '[{"plan":"Starter","price":36,"period":"month","features":["2000 workflow credits","5 seats"]},{"plan":"Advanced","price":186,"period":"month","features":["15000 credits","20 seats","CRM sync"]}]', 'intermediate', true, '{web,api}', '{"Cold email generation","LinkedIn outreach","Follow-up sequences","CRM enrichment","Persona-based messaging","Sales playbooks"}', '{"Salesforce","HubSpot","Outreach","Salesloft","LinkedIn"}', 'https://docs.copy.ai', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── BUSINESS / FINANCE ──────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Domo', 'domo', 'Business intelligence platform with AI insights', 'Domo is a cloud-based BI platform that combines data integration, visualization, and AI-powered insights. Features natural language queries, automated alerts, and collaboration tools for data-driven teams.', 'https://domo.com', 'paid', '[{"plan":"Standard","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Advanced AI"]}]', 'intermediate', true, '{web,mobile,api}', '{"800+ data connectors","AI natural language query","Automated alerts","Mobile dashboards","Domo Apps","DataFlows","Collaboration"}', '{"Salesforce","Google Analytics","Facebook Ads","Snowflake","AWS"}', 'https://developer.domo.com', true),

('Runway ML', 'runway-ml', 'Creative AI suite for video editing and generation', 'Runway is a professional creative AI platform with Gen-2 and Gen-3 video generation, along with 30+ AI tools for video editing, background removal, motion tracking, and visual effects.', 'https://runwayml.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["125 one-time credits"]},{"plan":"Standard","price":15,"period":"month","features":["625 credits/month","Export 720p"]},{"plan":"Pro","price":35,"period":"month","features":["2250 credits/month","Export 4K"]}]', 'intermediate', true, '{web,api}', '{"Gen-2 video generation","Gen-3 Alpha","Green screen","Background removal","Motion tracking","Inpainting","Frame interpolation","Custom AI training"}', '{"Adobe Premiere","Final Cut","Davinci Resolve"}', 'https://docs.runwayml.com', true),

('Trello AI', 'trello-ai', 'Atlassian Intelligence in project management', 'Trello with Atlassian Intelligence uses AI to auto-generate card descriptions, suggest due dates, summarize board activity, and surface blockers across your team''s projects.', 'https://trello.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["10 boards","Basic AI"]},{"plan":"Standard","price":5,"period":"month","features":["Unlimited boards","AI features"]},{"plan":"Premium","price":10,"period":"month","features":["Advanced AI","Admin controls"]}]', 'beginner', true, '{web,mobile,api}', '{"AI card generation","Smart due dates","Activity summary","Power-Ups","Automations","Timeline","Calendar","Maps"}', '{"Jira","Confluence","Slack","Google Drive","GitHub"}', 'https://developer.atlassian.com', true),

('Gong', 'gong', 'Revenue intelligence platform powered by AI', 'Gong records, transcribes, and analyzes all customer-facing conversations across calls, emails, and meetings. Uses AI to surface deal risks, coaching opportunities, and forecast accuracy.', 'https://gong.io', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Per seat model"]}]', 'intermediate', true, '{web,api}', '{"Call recording & transcription","Deal intelligence","Forecast accuracy","Coaching recommendations","Email analysis","CRM sync","Team performance"}', '{"Salesforce","HubSpot","Zoom","Microsoft Teams","Gmail","Outlook"}', 'https://help.gong.io', true),

('Chorus.ai', 'chorus-ai', 'Conversation intelligence for revenue teams', 'Chorus.ai (ZoomInfo) captures and analyzes all customer interactions to identify what separates top performers, improve onboarding, and forecast deals with AI-powered conversation intelligence.', 'https://chorus.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing"]}]', 'intermediate', true, '{web,api}', '{"Call recording","Meeting intelligence","Deal risk signals","Competitor mentions","Coaching playlists","CRM data enrichment"}', '{"Salesforce","HubSpot","ZoomInfo","Zoom","Microsoft Teams"}', 'https://help.chorus.ai', true),

('Workiva', 'workiva', 'AI-powered financial reporting and compliance platform', 'Workiva streamlines financial reporting, ESG reporting, and audit management with connected data and AI automation. Used by 6,000+ organizations for SEC filings, sustainability reports, and internal audits.', 'https://workiva.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full compliance suite"]}]', 'advanced', true, '{web,api}', '{"Financial reporting","ESG reporting","SEC filing","SOX compliance","Connected data","AI drafting","Audit management","Collaboration"}', '{"SAP","Oracle","NetSuite","Salesforce","Excel","Workday"}', 'https://docs.workiva.com', true),

('Mosaic', 'mosaic', 'AI-powered financial planning and analysis', 'Mosaic is a Strategic Finance Platform that brings together financial and operational data to enable FP&A teams to build models, analyze performance, and collaborate on financial strategy.', 'https://mosaic.tech', 'paid', '[{"plan":"Growth","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom","API access"]}]', 'intermediate', true, '{web,api}', '{"Financial modeling","Budget vs actuals","Scenario planning","Cash runway","Metric dashboards","AI narratives","Board reporting"}', '{"QuickBooks","NetSuite","Salesforce","HubSpot","Stripe","Rippling"}', 'https://help.mosaic.tech', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── SECURITY & COMPLIANCE ───────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Darktrace', 'darktrace', 'AI-powered cybersecurity for autonomous threat detection', 'Darktrace uses AI to detect, investigate, and autonomously respond to cyberthreats in real time. Its Self-Learning AI understands normal behavior for every user and device across web, email, and network.', 'https://darktrace.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Custom deployment"]}]', 'advanced', true, '{web,api}', '{"Autonomous threat detection","Email security","Cloud security","OT/IoT security","AI incident response","Threat visualization","SIEM integration"}', '{"Splunk","ServiceNow","Microsoft Sentinel","Okta","AWS","Azure"}', 'https://customerportal.darktrace.com', true),

('Snyk', 'snyk', 'AI-powered security for developers and code', 'Snyk helps developers find and fix vulnerabilities in code, open source dependencies, containers, and infrastructure-as-code. Integrates directly into developer workflows with IDE plugins and CI/CD.', 'https://snyk.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["200 tests/month","10 open source tests"]},{"plan":"Team","price":25,"period":"month","features":["Unlimited tests","Priority support"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom","SSO","SAML"]}]', 'intermediate', true, '{web,api,desktop}', '{"SAST","SCA","Container security","IaC scanning","License compliance","AI fix suggestions","PR checks","IDE plugins"}', '{"GitHub","GitLab","Bitbucket","Jira","Jenkins","CircleCI","VS Code","IntelliJ"}', 'https://docs.snyk.io', true),

('Orca Security', 'orca-security', 'Agentless cloud security platform with AI risk prioritization', 'Orca Security provides full-stack cloud security without agents, detecting vulnerabilities, misconfigurations, and threats across AWS, Azure, GCP. AI prioritizes risks by actual attack paths and business context.', 'https://orca.security', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing"]}]', 'advanced', true, '{web,api}', '{"Vulnerability management","CSPM","CWPP","CIEM","DSPM","Shift-left security","AI risk scoring","Compliance frameworks"}', '{"AWS","Azure","GCP","Kubernetes","Slack","Jira","ServiceNow","Splunk"}', 'https://docs.orca.security', true),

('Vanta', 'vanta', 'Automated security compliance for SOC 2, ISO 27001 and more', 'Vanta automates the complex process of achieving and maintaining security compliance including SOC 2, ISO 27001, HIPAA, GDPR, and PCI DSS. Continuously monitors and evidence-collects across your stack.', 'https://vanta.com', 'paid', '[{"plan":"Essentials","price":0,"period":"month","features":["Contact for pricing","1 framework"]},{"plan":"Growth","price":0,"period":"month","features":["Multiple frameworks","Risk management"]},{"plan":"Scale","price":0,"period":"month","features":["Custom","API access"]}]', 'intermediate', true, '{web,api}', '{"SOC 2 automation","ISO 27001","HIPAA","GDPR","PCI DSS","Continuous monitoring","Vendor risk management","Questionnaire automation"}', '{"AWS","GCP","Azure","GitHub","Okta","Google Workspace","Slack","Jira"}', 'https://docs.vanta.com', true),

('HackerOne', 'hackerone', 'AI-assisted bug bounty and vulnerability disclosure platform', 'HackerOne connects organizations with ethical hackers to find and fix vulnerabilities before attackers do. AI triages and deduplicates submissions, and provides continuous pentesting and attack surface management.', 'https://hackerone.com', 'paid', '[{"plan":"Starter","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Professional","price":0,"period":"month","features":["Bug bounty + pentest"]},{"plan":"Enterprise","price":0,"period":"month","features":["Full platform"]}]', 'advanced', true, '{web,api}', '{"Bug bounty programs","Vulnerability disclosure","AI triage","Attack surface management","Pentest as a service","CVE assistance","Remediation guidance"}', '{"Jira","Slack","ServiceNow","GitHub","GitLab","Splunk"}', 'https://docs.hackerone.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── AI AGENTS & AUTOMATION ──────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('AutoGPT', 'autogpt', 'Open-source autonomous AI agent framework', 'AutoGPT is a pioneering open-source AI agent that can autonomously complete complex tasks with minimal human input. Chains together multiple GPT-4 calls, uses memory, and executes actions like browsing and coding.', 'https://agpt.co', 'freemium', '[{"plan":"Open Source","price":0,"period":"month","features":["Self-hosted","Bring your own API keys"]},{"plan":"Cloud","price":0,"period":"month","features":["Hosted version","Credits system"]}]', 'advanced', true, '{web,api}', '{"Autonomous task execution","Long-term memory","Web browsing","Code execution","File management","Plugin system","Agent protocols"}', '{"OpenAI","Anthropic","Google AI","Pinecone","Redis"}', 'https://docs.agpt.co', true),

('LangChain', 'langchain', 'Framework for building LLM-powered applications and agents', 'LangChain is the most popular framework for building applications with large language models. Provides abstractions for chains, agents, memory, retrieval, and tool use to connect LLMs to external data and actions.', 'https://langchain.com', 'freemium', '[{"plan":"Open Source","price":0,"period":"month","features":["Full framework","Python & JS"]},{"plan":"LangSmith","price":39,"period":"month","features":["Observability","Testing","Deployment"]}]', 'advanced', true, '{api}', '{"LLM abstraction","Agent frameworks","RAG pipelines","Memory systems","Tool calling","LangGraph","LangSmith","LangServe"}', '{"OpenAI","Anthropic","Google","Pinecone","Chroma","Weaviate","Redis"}', 'https://docs.langchain.com', true),

('CrewAI', 'crewai', 'Multi-agent AI framework for collaborative task completion', 'CrewAI enables building multi-agent AI systems where specialized agents collaborate to complete complex tasks. Agents have defined roles, goals, and tools, and collaborate through a structured workflow.', 'https://crewai.com', 'freemium', '[{"plan":"Open Source","price":0,"period":"month","features":["Full framework"]},{"plan":"Enterprise","price":0,"period":"month","features":["Cloud hosting","Support","Monitoring"]}]', 'advanced', true, '{api}', '{"Multi-agent collaboration","Role-based agents","Task delegation","Process automation","Custom tools","Memory","Kickoff & replay"}', '{"LangChain","OpenAI","Anthropic","Groq","Ollama"}', 'https://docs.crewai.com', true),

('Zapier AI Actions', 'zapier-ai-actions', 'Connect AI to 6,000+ apps with natural language automation', 'Zapier AI Actions lets you build AI-powered workflows that can interact with 6,000+ apps using natural language commands. Enables ChatGPT, custom AI, and Claude to actually take actions in your software stack.', 'https://zapier.com/ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["100 tasks/month","5 Zaps"]},{"plan":"Starter","price":19.99,"period":"month","features":["750 tasks/month","20 Zaps"]},{"plan":"Professional","price":49,"period":"month","features":["2000 tasks/month","Unlimited Zaps"]}]', 'intermediate', true, '{web,api}', '{"6000+ app integrations","Natural language automation","AI Zap builder","AI chatbot templates","Webhook support","Multi-step Zaps"}', '{"ChatGPT","OpenAI","Anthropic","Gmail","Slack","Salesforce","HubSpot","Notion"}', 'https://docs.zapier.com/ai', true),

('Relevance AI', 'relevance-ai', 'Build and deploy AI agents and apps without code', 'Relevance AI enables teams to build custom AI agents and automated workflows with a no-code builder. Agents can handle tasks like lead research, content generation, and customer support at scale.', 'https://relevanceai.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["100 credits/day","3 agents"]},{"plan":"Team","price":199,"period":"month","features":["3000 credits/month","50 agents"]},{"plan":"Business","price":599,"period":"month","features":["10000 credits/month","Unlimited agents"]}]', 'intermediate', true, '{web,api}', '{"No-code agent builder","Multi-agent workforce","Custom tools","API integration","LLM abstraction","Knowledge base","Agent monitoring"}', '{"OpenAI","Anthropic","Cohere","Pinecone","Google Sheets","Zapier","HubSpot"}', 'https://docs.relevanceai.com', true),

('Taskade', 'taskade', 'AI-powered task management and team collaboration', 'Taskade combines project management, wikis, and AI in one platform. Features AI agents that can complete tasks, research topics, and generate content while teams collaborate in real time.', 'https://taskade.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 projects","AI assistant"]},{"plan":"Pro","price":8,"period":"month","features":["Unlimited projects","AI agents","Custom agents"]},{"plan":"Business","price":16,"period":"month","features":["Team features","Advanced AI"]}]', 'beginner', true, '{web,mobile,desktop,api}', '{"AI project management","Custom AI agents","Wikis","Real-time collaboration","AI workflows","Templates","Mind maps","Video chat"}', '{"Zapier","GitHub","Google Drive","Slack","Notion","Calendar"}', 'https://help.taskade.com', true),

('Coze', 'coze', 'Build and deploy AI bots and agents with no code', 'Coze (by ByteDance) is an AI bot creation platform that lets you build customized AI bots with plugins, memory, workflows, and scheduling. Deploy across Discord, Telegram, Slack, and web in minutes.', 'https://coze.com', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Unlimited bots","Community plugins","Basic workflow"]}]', 'intermediate', false, '{web}', '{"No-code bot builder","100+ plugins","Long-term memory","Scheduled tasks","Multi-agent workflow","Knowledge base","Database","Voice interaction"}', '{"Discord","Telegram","Slack","LINE","Twitter/X","Feishu"}', 'https://www.coze.com/docs', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── TRANSLATION & LANGUAGE ──────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('DeepL', 'deepl', 'AI translation with near-human accuracy', 'DeepL is renowned for producing translations that read naturally rather than sounding machine-translated. Supports 30+ languages with document translation, glossaries, and tone customization for professionals.', 'https://deepl.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 documents/month","500,000 chars/month API"]},{"plan":"Starter","price":10.99,"period":"month","features":["5 documents/month","Glossaries"]},{"plan":"Advanced","price":32.99,"period":"month","features":["20 documents/month","API included"]}]', 'beginner', true, '{web,desktop,mobile,api}', '{"30+ languages","Document translation","Glossaries","Tone selection","API","CAT tool integration","Browser extension","Formality control"}', '{"Microsoft Word","PowerPoint","Google Docs","SDL Trados","memoQ"}', 'https://developers.deepl.com', true),

('Lokalise', 'lokalise', 'AI-powered localization platform for software teams', 'Lokalise is a translation management platform for software localization. Features AI translation, in-context editing, workflow automation, and integrations with dev tools to streamline multi-language app releases.', 'https://lokalise.com', 'paid', '[{"plan":"Essential","price":120,"period":"month","features":["3 seats","3000 keys","AI translations"]},{"plan":"Pro","price":230,"period":"month","features":["10 seats","5000 keys","Advanced workflows"]}]', 'intermediate', true, '{web,api}', '{"AI machine translation","Translation memory","Glossaries","In-context editor","Branching","Screenshots","Quality assurance","Figma plugin"}', '{"GitHub","GitLab","Figma","Sketch","Slack","Jira","Contentful","Shopify"}', 'https://developers.lokalise.com', true),

('Phrase', 'phrase', 'Enterprise translation management and AI localization', 'Phrase provides an enterprise-grade translation management system with AI-assisted translation, workflow automation, and a neural machine translation engine for large-scale localization programs.', 'https://phrase.com', 'paid', '[{"plan":"Starter","price":27,"period":"month","features":["2 seats","Unlimited projects","Basic MT"]},{"plan":"Professional","price":0,"period":"month","features":["Custom","Advanced MT","TM"]}]', 'intermediate', true, '{web,api}', '{"Neural MT","Translation memory","Terminology management","QA automation","Git integration","In-context editing","Branching","Analytics"}', '{"GitHub","GitLab","WordPress","Figma","Adobe XD","Zendesk","Contentful"}', 'https://developers.phrase.com', true),

('Smartling', 'smartling', 'Translation platform with AI and human translation', 'Smartling combines AI translation with professional human translators and a powerful translation management platform. Helps global enterprises localize digital content at speed and scale.', 'https://smartling.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Custom setup"]}]', 'intermediate', true, '{web,api}', '{"AI translation","Human translation","Translation memory","Glossaries","Visual context","Workflow automation","Quality scoring","Cost tracking"}', '{"Contentful","Drupal","WordPress","Shopify","Marketo","Adobe","Salesforce"}', 'https://help.smartling.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── HR & RECRUITING ─────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Workday', 'workday', 'AI-powered enterprise HCM and financial management', 'Workday is a leading enterprise platform for human capital management, finance, and planning. AI capabilities include skills inference, candidate matching, workforce planning, and anomaly detection.', 'https://workday.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Full HCM suite"]}]', 'intermediate', true, '{web,mobile,api}', '{"HCM","Payroll","Recruiting","Skills cloud","Learning","Financial management","Planning","Analytics","AI recommendations"}', '{"Microsoft Teams","Slack","Salesforce","SAP","Oracle","ServiceNow"}', 'https://developer.workday.com', true),

('Greenhouse', 'greenhouse', 'Structured hiring platform with AI capabilities', 'Greenhouse is a recruiting software platform that brings structure and fairness to the hiring process. Features AI-assisted sourcing, interview planning, diversity analytics, and onboarding workflows.', 'https://greenhouse.com', 'paid', '[{"plan":"Essential","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Advanced","price":0,"period":"month","features":["AI sourcing","DEI tools"]},{"plan":"Expert","price":0,"period":"month","features":["Full AI suite"]}]', 'intermediate', true, '{web,api}', '{"AI job descriptions","Candidate sourcing","Interview kits","DEI analytics","Offer management","Onboarding","HRIS sync","Reporting"}', '{"LinkedIn","Indeed","Slack","Zoom","DocuSign","Workday","BambooHR","Okta"}', 'https://developers.greenhouse.io', true),

('Paradox', 'paradox', 'AI recruiting assistant that automates hiring conversations', 'Paradox''s Olivia AI automates candidate screening, scheduling, onboarding, and FAQ responses via conversational AI. Reduces time-to-hire by up to 80% by handling repetitive recruiting tasks.', 'https://paradox.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Custom deployment"]}]', 'intermediate', true, '{web,mobile,api}', '{"Conversational AI","Interview scheduling","Candidate screening","Onboarding automation","Career site chatbot","Multi-language","SMS","WhatsApp"}', '{"Workday","SAP SuccessFactors","Oracle HCM","ADP","iCIMS","Taleo"}', 'https://paradox.ai/resources', true),

('Fetcher', 'fetcher', 'AI-powered talent sourcing and outreach automation', 'Fetcher uses AI to automatically source candidates, craft personalized outreach emails, and manage multi-touch sequences. Integrates with your ATS to keep pipelines full with qualified passive candidates.', 'https://fetcher.ai', 'paid', '[{"plan":"Starter","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Professional","price":0,"period":"month","features":["Advanced AI","Custom sequences"]}]', 'intermediate', true, '{web,api}', '{"AI sourcing","Email automation","ATS integration","Diversity sourcing","Analytics","Candidate profiles","Team collaboration"}', '{"Greenhouse","Lever","Workday","BambooHR","Gmail","Outlook"}', 'https://help.fetcher.ai', true),

('Leena AI', 'leena-ai', 'Autonomous HR agent for employee self-service', 'Leena AI provides an autonomous HR agent that handles employee queries, automates HR workflows, and supports global HR teams. Reduces HR ticket volume by up to 90% through intelligent automation.', 'https://leena.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Full HR automation"]}]', 'intermediate', true, '{web,mobile,api}', '{"Employee self-service","HR chatbot","Onboarding automation","Policy answers","Leave management","IT helpdesk","100+ languages","Analytics"}', '{"Workday","SAP SuccessFactors","ServiceNow","Jira","Slack","Microsoft Teams"}', 'https://docs.leena.ai', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── LEGAL & COMPLIANCE ──────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Harvey', 'harvey', 'AI legal assistant for law firms and in-house counsel', 'Harvey is an AI platform for lawyers that drafts contracts, analyzes documents, conducts legal research, and answers complex legal questions. Trained on extensive legal data with high accuracy.', 'https://harvey.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","Custom deployment"]}]', 'advanced', true, '{web,api}', '{"Contract drafting","Legal research","Document review","Due diligence","Regulatory analysis","Litigation support","Multi-jurisdiction","Data room analysis"}', '{"Microsoft Word","iManage","NetDocuments","Relativity","Westlaw","LexisNexis"}', 'https://harvey.ai', true),

('Ironclad', 'ironclad', 'AI-powered contract lifecycle management', 'Ironclad is the leading digital contracting platform that uses AI to draft, redline, negotiate, and manage contracts. Reduces contracting time by 80% with AI workflows and smart clause suggestions.', 'https://ironcladapp.com', 'paid', '[{"plan":"Essentials","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Professional","price":0,"period":"month","features":["AI negotiation","Analytics"]},{"plan":"Enterprise","price":0,"period":"month","features":["Full suite","Custom AI"]}]', 'intermediate', true, '{web,api}', '{"Contract drafting","AI redlining","Clause suggestions","Approval workflows","Contract repository","Obligation tracking","Analytics","eSign"}', '{"Salesforce","DocuSign","Adobe Sign","Slack","Google Drive","SharePoint"}', 'https://developer.ironcladapp.com', true),

('Clio', 'clio', 'Legal practice management with AI features', 'Clio is the leading legal practice management software used by 150,000+ lawyers. Features AI document summarization, draft generation, client intake, billing, case management, and legal research.', 'https://clio.com', 'paid', '[{"plan":"EasyStart","price":39,"period":"month","features":["Case management","Time tracking"]},{"plan":"Essentials","price":69,"period":"month","features":["Document management","AI features"]},{"plan":"Advanced","price":99,"period":"month","features":["Full AI suite","Analytics"]}]', 'intermediate', true, '{web,mobile,api}', '{"Case management","AI document drafting","Billing","Client intake","Document templates","Calendar","Client portal","Legal research","Accounting"}', '{"Microsoft 365","Google Workspace","Zoom","QuickBooks","NetDocuments","DocuSign"}', 'https://app.clio.com/api/v4/documentation', true),

('Lex Machina', 'lex-machina', 'Legal analytics platform for litigation strategy', 'Lex Machina provides legal analytics drawn from millions of cases to help law firms develop winning litigation strategies. Uses AI to analyze judge behavior, opposing counsel patterns, and case outcomes.', 'https://lexmachina.com', 'paid', '[{"plan":"Professional","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom","API access"]}]', 'advanced', true, '{web,api}', '{"Case analytics","Judge analytics","Attorney analytics","Patent litigation","IP analytics","Timing analytics","Case outcome prediction","Custom reports"}', '{"LexisNexis","Relativity","iManage"}', 'https://lexmachina.com/resources', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── EDUCATION & LEARNING ────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Khan Academy Khanmigo', 'khanmigo', 'AI tutor and teacher assistant by Khan Academy', 'Khanmigo is Khan Academy''s AI guide that tutors students through problems with Socratic questioning rather than giving answers. Also helps teachers create lesson plans, rubrics, and feedback.', 'https://khanacademy.org/khan-labs', 'freemium', '[{"plan":"Free for students","price":0,"period":"month","features":["Limited AI sessions"]},{"plan":"Full access","price":4,"period":"month","features":["Unlimited Khanmigo","All subjects"]}]', 'beginner', false, '{web}', '{"Socratic tutoring","Math guidance","Writing coaching","SAT prep","Teacher tools","Lesson planning","Rubric creation","Safe for students"}', '{"Khan Academy","Google Classroom"}', 'https://khanacademy.org/khan-labs', true),

('Duolingo Max', 'duolingo-max', 'AI-powered language learning with conversation practice', 'Duolingo Max adds AI features including Explain My Answer (GPT-4 explanations for exercises) and Roleplay (real-world conversation practice with AI characters in 40+ situations).', 'https://duolingo.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Basic lessons","Limited AI"]},{"plan":"Plus","price":6.99,"period":"month","features":["No ads","Unlimited hearts"]},{"plan":"Max","price":13.99,"period":"month","features":["Explain My Answer","Roleplay AI"]}]', 'beginner', false, '{mobile,web}', '{"40+ languages","AI conversation roleplay","Explain My Answer","Streaks","Stories","Podcasts","Games","Leaderboards"}', '{}', 'https://duolingo.com', true),

('Quizlet AI', 'quizlet-ai', 'AI study tools with flashcards and practice tests', 'Quizlet''s AI features include Q-Chat (an AI tutor), Magic Notes (auto-generate flashcard sets from notes), and AI-written practice tests. Helps students study smarter with adaptive learning.', 'https://quizlet.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Basic flashcards","Limited AI"]},{"plan":"Quizlet Plus","price":7.99,"period":"month","features":["Unlimited AI","Magic Notes","Q-Chat"]}]', 'beginner', false, '{web,mobile}', '{"AI flashcard generation","Q-Chat AI tutor","Magic Notes","Practice tests","Spaced repetition","Diagrams","Audio","Teacher tools"}', '{"Google Classroom","Canvas","Schoology"}', 'https://help.quizlet.com', true),

('Courseware by Coursera', 'coursera-coach', 'AI learning coach on Coursera platform', 'Coursera''s AI learning tools include an AI Coach that helps learners understand concepts, provides hints, and personalizes learning paths across 7,000+ courses from top universities and companies.', 'https://coursera.org', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Audit courses","Limited AI"]},{"plan":"Coursera Plus","price":59,"period":"month","features":["All courses","AI Coach","Certificates"]}]', 'beginner', false, '{web,mobile}', '{"AI learning coach","7000+ courses","Certificates","Skill paths","Lab environments","Peer grading","Progress tracking"}', '{"LinkedIn","GitHub","AWS","Google Cloud"}', 'https://coursera.org', true),

('Krea AI', 'krea-ai', 'Real-time AI image generation for designers', 'Krea AI offers real-time AI image generation and enhancement tools that respond instantly to your edits. Features an upscaler, video generation, and AI canvas for creative professionals who want speed and control.', 'https://krea.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Limited generations"]},{"plan":"Standard","price":24,"period":"month","features":["3000 generations/month","HD"]},{"plan":"Pro","price":83,"period":"month","features":["30000 generations/month","4K","API"]}]', 'intermediate', true, '{web,api}', '{"Real-time generation","AI upscaler","Image-to-image","Video generation","Background removal","Object removal","Enhance","Patterns"}', '{}', 'https://krea.ai', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── AI WRITING TOOLS (MORE) ─────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Anyword', 'anyword', 'AI copywriting with predictive performance scoring', 'Anyword generates marketing copy across channels and uses predictive analytics to score content before publishing. Trained on billions of data points to predict conversion performance for specific audiences.', 'https://anyword.com', 'paid', '[{"plan":"Starter","price":39,"period":"month","features":["1 seat","Unlimited words","Performance scoring"]},{"plan":"Data-Driven","price":79,"period":"month","features":["3 seats","Custom AI model","Advanced analytics"]}]', 'intermediate', false, '{web,api}', '{"Performance prediction","Copy generation","Blog posts","Ad copy","Email","Social media","Custom AI model","Brand voice","Multiple languages"}', '{"HubSpot","Zapier","WordPress","Google Ads","Facebook Ads"}', 'https://anyword.com/blog', true),

('Shortly AI', 'shortly-ai', 'Distraction-free AI writing companion', 'Shortly AI is a clean, distraction-free AI writing tool designed to help authors and bloggers overcome writer''s block. Expand paragraphs, rewrite sections, and generate stories with simple keyboard shortcuts.', 'https://shortlyai.com', 'paid', '[{"plan":"Annual","price":65,"period":"month","features":["Unlimited AI writes","Long-form document editor"]}]', 'beginner', false, '{web}', '{"Long-form writing","Expand text","Rewrite","Article wizard","Keyboard shortcuts","Distraction-free editor"}', '{}', 'https://shortlyai.com/blog', true),

('Frase', 'frase', 'AI SEO content tool that researches, writes, and optimizes', 'Frase combines AI writing with SEO research to create content that ranks. Research SERPs, generate AI-written briefs and drafts, then optimize with real-time SEO scoring — all in one workflow.', 'https://frase.io', 'paid', '[{"plan":"Solo","price":15,"period":"month","features":["4 articles/month","AI writer"]},{"plan":"Basic","price":45,"period":"month","features":["30 articles/month","All features"]},{"plan":"Team","price":115,"period":"month","features":["Unlimited articles","3 seats"]}]', 'intermediate', false, '{web}', '{"SERP research","Content briefs","AI writer","SEO optimization score","Topic modeling","Answer questions","Templates","Integrations"}', '{"WordPress","Google Search Console","SEMrush"}', 'https://frase.io/blog', true),

('Hypotenuse AI', 'hypotenuse-ai', 'AI content generation for e-commerce and marketing teams', 'Hypotenuse AI specializes in e-commerce content — generate hundreds of product descriptions, category pages, and marketing copy at scale from product data. Features bulk generation and brand voice training.', 'https://hypotenuse.ai', 'paid', '[{"plan":"Starter","price":29,"period":"month","features":["50 articles/month","Basic tools"]},{"plan":"Growth","price":59,"period":"month","features":["100 articles/month","Bulk generation"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom","API","Brand AI"]}]', 'intermediate', true, '{web,api}', '{"Product descriptions","Bulk generation","SEO content","Blog posts","Ad copy","Brand voice","Batch CSV import","API"}', '{"Shopify","WooCommerce","Magento","WordPress","Google Sheets"}', 'https://docs.hypotenuse.ai', true),

('Writesonic Chatsonic', 'chatsonic', 'AI chatbot with real-time web search and image generation', 'Chatsonic is Writesonic''s ChatGPT alternative with real-time internet access, AI image generation, and a memory feature. Supports voice input/output and specialized AI personas for various use cases.', 'https://writesonic.com/chat', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["25 generations/month"]},{"plan":"Individual","price":16,"period":"month","features":["Unlimited GPT-3.5","100 GPT-4 messages"]},{"plan":"Teams","price":33,"period":"month","features":["All features","Team workspace"]}]', 'beginner', true, '{web,mobile,api}', '{"Real-time web search","AI image generation","Voice input","Memory","AI personas","Code generation","Factual content","Chrome extension"}', '{"Writesonic","Zapier","WordPress"}', 'https://docs.writesonic.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── DEVELOPER TOOLS (MORE) ──────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Warp', 'warp', 'AI-powered terminal for developers', 'Warp is a modern terminal with AI built in. Ask questions in natural language to get commands, debug errors, and understand shell output. Features intelligent autocomplete, command search, and team sharing.', 'https://warp.dev', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Unlimited local usage","AI completions"]},{"plan":"Team","price":22,"period":"month","features":["Shared workflows","Analytics","SSO"]}]', 'intermediate', false, '{desktop}', '{"AI command generation","Natural language shell","Intelligent autocomplete","Warp AI","Block-based input","Command history search","Team notebooks"}', '{"GitHub","VS Code","Fish","Zsh","Bash"}', 'https://docs.warp.dev', true),

('Continue', 'continue', 'Open-source AI code assistant for VS Code and JetBrains', 'Continue is an open-source autopilot for software development that integrates with VS Code and JetBrains. Connect any LLM, add custom context, and build personalized coding workflows with full control.', 'https://continue.dev', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Open source","Bring your own model","Unlimited"]}]', 'intermediate', true, '{desktop,api}', '{"Any LLM support","Tab autocomplete","Chat interface","Custom context","Codebase indexing","Slash commands","Model switching","Privacy mode"}', '{"VS Code","JetBrains","OpenAI","Anthropic","Ollama","Mistral","Gemini"}', 'https://docs.continue.dev', true),

('Pieces for Developers', 'pieces-for-developers', 'AI-powered code snippet manager and developer assistant', 'Pieces is an on-device AI toolkit that captures, enriches, and resurfaces code snippets with full context. Integrates across IDEs and browsers to save, search, and reuse code with AI assistance.', 'https://pieces.app', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Personal use","On-device AI","Unlimited snippets"]},{"plan":"Teams","price":0,"period":"month","features":["Shared snippets","Team features"]}]', 'intermediate', false, '{desktop,web}', '{"Code snippet capture","Context enrichment","On-device AI","Cross-IDE sync","Code search","Live context","Copilot chat","OCR snippets"}', '{"VS Code","JetBrains","Chrome","GitHub","Jira","Confluence","Slack"}', 'https://docs.pieces.app', true),

('Aider', 'aider', 'AI pair programming in your terminal', 'Aider is an open-source AI coding assistant that runs in your terminal and lets you pair program with Claude or GPT-4. Makes code changes across multiple files, runs tests, and commits with meaningful messages.', 'https://aider.chat', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Open source","Bring your own API key"]}]', 'advanced', true, '{desktop}', '{"Multi-file editing","Git integration","Auto commit","Test running","Map repository","Voice coding","Browser support","Any LLM"}', '{"Git","OpenAI","Anthropic","Groq","Ollama","DeepSeek"}', 'https://aider.chat/docs', true),

('Sweep AI', 'sweep-ai', 'AI software engineer that fixes bugs and builds features', 'Sweep is a GitHub-native AI developer that converts issues into pull requests. Describe a bug or feature in a GitHub issue, and Sweep reads your codebase, writes the code, tests it, and opens a PR.', 'https://sweep.dev', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 issues/month","Public repos"]},{"plan":"Pro","price":240,"period":"month","features":["Unlimited issues","Private repos","Priority"]}]', 'intermediate', false, '{web}', '{"Issue-to-PR automation","Codebase understanding","Test writing","Code review","Multi-file changes","GitHub Actions integration"}', '{"GitHub","Linear"}', 'https://docs.sweep.dev', true),

('CodiumAI', 'codiumai', 'AI for writing meaningful tests automatically', 'CodiumAI (now Qodo) analyzes your code and generates comprehensive test suites automatically. Identifies edge cases, suggests improvements, and ensures your code actually works as intended.', 'https://codium.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Individual use","VS Code plugin"]},{"plan":"Teams","price":19,"period":"month","features":["Team features","PR agent","Analytics"]}]', 'intermediate', false, '{desktop,web}', '{"Automated test generation","Edge case detection","Code integrity","PR agent","Test suggestions","Multi-language","VS Code + JetBrains"}', '{"VS Code","JetBrains","GitHub","GitLab","Bitbucket"}', 'https://docs.codium.ai', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── PRODUCTIVITY (MORE) ─────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Mem', 'mem', 'Self-organizing AI workspace for notes and knowledge', 'Mem is an AI-powered notes app that automatically organizes your information, surfaces relevant notes when you need them, and lets you chat with your entire knowledge base. No folders, no tags needed.', 'https://mem.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Limited AI","500 notes"]},{"plan":"Pro","price":14.99,"period":"month","features":["Unlimited notes","AI chat","Smart search"]}]', 'beginner', false, '{web,mobile,desktop}', '{"AI organization","Smart search","Chat with notes","Related notes","Capture everywhere","Calendar integration","Team spaces","Offline mode"}', '{"Slack","Gmail","Google Calendar","Zoom","Notion"}', 'https://help.mem.ai', true),

('Fireflies.ai', 'fireflies-ai', 'AI meeting assistant for transcription and summaries', 'Fireflies.ai records, transcribes, summarizes, and searches all your meetings. Integrates with every major video platform and syncs insights to your CRM, Slack, and project management tools automatically.', 'https://fireflies.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["800 min transcription storage","3 AI summaries"]},{"plan":"Pro","price":18,"period":"month","features":["Unlimited transcription","Unlimited AI summaries"]},{"plan":"Business","price":29,"period":"month","features":["Conversation intelligence","Analytics"]}]', 'beginner', false, '{web,mobile}', '{"Meeting transcription","AI summaries","Action items","Sentiment analysis","Speaker ID","Smart search","Meeting playlists","CRM sync"}', '{"Zoom","Google Meet","MS Teams","Webex","HubSpot","Salesforce","Slack","Notion"}', 'https://guide.fireflies.ai', true),

('Superhuman', 'superhuman', 'AI-powered email client built for speed', 'Superhuman is the fastest email client ever made, with AI writing assistance, instant search, follow-up reminders, and keyboard-first design. Claims users save 4+ hours per week on email.', 'https://superhuman.com', 'paid', '[{"plan":"Starter","price":30,"period":"month","features":["AI writing","Snippets","Read statuses"]},{"plan":"Business","price":40,"period":"month","features":["Team features","Analytics","Priority support"]}]', 'intermediate', false, '{web,desktop,mobile}', '{"AI email drafting","AI triage","Keyboard shortcuts","Split inbox","Snippets","Follow-up reminders","Read statuses","Instant search","Undo send"}', '{"Gmail","Outlook","Google Calendar","Zoom","Superhuman API"}', 'https://help.superhuman.com', true),

('Notion Calendar', 'notion-calendar', 'AI-powered calendar that connects to Notion', 'Notion Calendar (formerly Cron) combines a powerful calendar experience with Notion''s connected workspace. Schedule meetings, block focus time, and see your work alongside your events.', 'https://calendar.notion.so', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Full calendar","Notion integration","Meeting links"]}]', 'beginner', false, '{web,desktop,mobile}', '{"Google Calendar sync","Notion integration","Meeting scheduling","Focus time blocks","Meeting notes","Time zones","Multi-calendar","Keyboard shortcuts"}', '{"Notion","Google Calendar","Zoom","Google Meet","Apple Calendar"}', 'https://help.notion.so', true),

('Magical', 'magical', 'AI text expansion and workflow automation', 'Magical is a free Chrome extension that uses AI to auto-fill repetitive data between tabs, expand text shortcuts, and automate data entry. Works on any website without building integrations.', 'https://getmagical.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Unlimited shortcuts","AI message drafting"]},{"plan":"Teams","price":10,"period":"month","features":["Shared templates","Analytics","SSO"]}]', 'beginner', false, '{web}', '{"Text expansion","Auto data transfer","AI drafting","Shortcuts","Template sharing","CRM auto-fill","Works on any site","No integrations needed"}', '{"Chrome","Salesforce","HubSpot","LinkedIn","Gmail","Zendesk"}', 'https://help.getmagical.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── SOCIAL MEDIA & CONTENT ──────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Sprout Social', 'sprout-social', 'Social media management with AI-powered insights', 'Sprout Social is a comprehensive social media management platform with AI writing assistance, optimal send times, sentiment analysis, and competitive intelligence for brands and agencies.', 'https://sproutsocial.com', 'paid', '[{"plan":"Standard","price":249,"period":"month","features":["5 profiles","AI assist","Publishing"]},{"plan":"Professional","price":399,"period":"month","features":["Unlimited profiles","AI suggestions"]},{"plan":"Advanced","price":499,"period":"month","features":["AI automation","Advanced analytics"]}]', 'intermediate', true, '{web,mobile,api}', '{"AI content suggestions","Social scheduling","Inbox management","Analytics","Listening","Competitor analysis","Influencer tools","CRM"}', '{"Facebook","Instagram","X/Twitter","LinkedIn","TikTok","Pinterest","Google","Salesforce","HubSpot"}', 'https://developers.sproutsocial.com', true),

('Taplio', 'taplio', 'AI-powered LinkedIn growth tool', 'Taplio helps professionals grow their LinkedIn presence with AI post generation, carousel creation, post scheduling, and analytics. Includes a daily content inspiration feed and relationship management.', 'https://taplio.com', 'paid', '[{"plan":"Starter","price":49,"period":"month","features":["AI generation","Basic scheduling"]},{"plan":"Standard","price":65,"period":"month","features":["Advanced AI","Analytics","Carousel builder"]},{"plan":"Pro","price":199,"period":"month","features":["Team","CRM","API"]}]', 'beginner', false, '{web}', '{"AI LinkedIn posts","Carousel builder","Scheduling","Analytics","Lead finder","DM automation","Content inspiration","Relationship management"}', '{"LinkedIn","Zapier","HubSpot"}', 'https://taplio.com/help', true),

('Tweet Hunter', 'tweet-hunter', 'AI-powered X (Twitter) growth platform', 'Tweet Hunter helps creators and businesses grow on X/Twitter with AI tweet generation, viral thread creation, scheduling, automation, and CRM features to convert followers to customers.', 'https://tweethunter.io', 'paid', '[{"plan":"Starter","price":49,"period":"month","features":["AI tweets","Scheduling","Analytics"]},{"plan":"Growth","price":99,"period":"month","features":["Automation","CRM","Team"]}]', 'beginner', false, '{web}', '{"AI tweet generation","Thread builder","Scheduling","Auto retweet","Auto DM","Analytics","Audience research","Content library","Ghost writer"}', '{"Twitter/X","Zapier","Make","HubSpot"}', 'https://tweethunter.io/blog', true),

('Flick', 'flick', 'AI social media marketing assistant', 'Flick is an AI social media tool that helps create captions, generate content ideas, schedule posts, and research hashtags across Instagram, Facebook, TikTok, and LinkedIn. Ideal for solo creators and agencies.', 'https://flick.social', 'paid', '[{"plan":"Solo","price":14,"period":"month","features":["1 brand","AI writing","Scheduling"]},{"plan":"Growth","price":30,"period":"month","features":["2 brands","Hashtag analytics"]},{"plan":"Pro","price":65,"period":"month","features":["5 brands","AI content planner"]}]', 'beginner', false, '{web,mobile}', '{"AI caption writing","Content ideas","Hashtag research","Scheduling","Analytics","Content calendar","Repurposing","Brand voice"}', '{"Instagram","Facebook","TikTok","LinkedIn","Canva"}', 'https://help.flick.social', true),

('Loomly', 'loomly', 'Brand success platform with AI content suggestions', 'Loomly helps social media managers plan, create, publish, and analyze content across all major platforms. Features AI content suggestions, advanced analytics, ad management, and team collaboration.', 'https://loomly.com', 'paid', '[{"plan":"Base","price":42,"period":"month","features":["2 users","10 calendars","AI assist"]},{"plan":"Standard","price":80,"period":"month","features":["6 users","20 calendars"]},{"plan":"Advanced","price":175,"period":"month","features":["14 users","Unlimited calendars"]}]', 'beginner', false, '{web,mobile}', '{"AI content suggestions","Multi-channel publishing","Content calendar","Analytics","Ad management","Approval workflows","Hashtag suggestions","UTM tracking"}', '{"Facebook","Instagram","X/Twitter","LinkedIn","Pinterest","TikTok","YouTube","Google My Business"}', 'https://help.loomly.com', true)

ON CONFLICT (slug) DO NOTHING;
