-- ============================================================
-- Batch 4: ~120 more AI tools
-- Categories: 3D & AR, Music & Audio (more), Low-code/No-code,
--   Healthcare & Wellness, Real Estate, Agriculture,
--   Finance & Trading, Gaming & Game Dev, Fashion & Retail,
--   Science & Research, Accessibility, Communication
-- ============================================================

-- ─── 3D, AR & SPATIAL ────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Spline', 'spline', '3D design tool for the web with AI generation', 'Spline is a web-based 3D design tool that lets designers create interactive 3D content for websites without code. Features AI generation of 3D scenes from text prompts and real-time collaboration.', 'https://spline.design', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 projects","Community viewer"]},{"plan":"Pro","price":9,"period":"month","features":["Unlimited projects","Custom domain","Team"]}]', 'intermediate', true, '{web,api}', '{"3D modeling","AI text-to-3D","Physics simulation","Interactive states","Real-time collab","WebGL export","React Three Fiber","Code export"}', '{"Figma","React","Vue","Webflow","Framer"}', 'https://docs.spline.design', true),

('Luma AI Genie', 'luma-ai-genie', 'Text-to-3D and NeRF-based 3D capture', 'Luma AI creates photorealistic 3D models from video capture using NeRF technology, and generates 3D assets from text. Used by game developers, architects, and e-commerce for product visualization.', 'https://lumalabs.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 captures/month","Basic quality"]},{"plan":"Pro","price":24.99,"period":"month","features":["25 captures/month","Ultra quality"]}]', 'intermediate', true, '{web,mobile,api}', '{"NeRF 3D capture","Text-to-3D","Video-to-3D","AR export","glTF/USDZ export","Game engine ready","360 capture"}', '{"Unity","Unreal Engine","Blender","iOS","Android"}', 'https://lumalabs.ai/api', true),

('Meshy', 'meshy', 'AI 3D model generation for game developers', 'Meshy generates production-ready 3D models and textures from text or images in minutes. Supports PBR texturing, rigging, and animation, making it ideal for game asset creation and product visualization.', 'https://meshy.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["200 credits/month"]},{"plan":"Pro","price":20,"period":"month","features":["1000 credits/month","Priority GPU"]},{"plan":"Max","price":100,"period":"month","features":["4000 credits/month"]}]', 'intermediate', false, '{web}', '{"Text-to-3D","Image-to-3D","AI texturing","PBR materials","Auto-rigging","FBX/OBJ/GLB export","Batch generation"}', '{"Unity","Blender","Unreal Engine"}', 'https://docs.meshy.ai', true),

('Masterpiece Studio', 'masterpiece-studio', 'AI 3D creation for VR, AR, and games', 'Masterpiece Studio enables creators to design 3D characters and assets using AI assistance in VR or on desktop. Features AI pose generation, character sculpting, and game-ready mesh export.', 'https://masterpiecestudio.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 exports/month"]},{"plan":"Pro","price":20,"period":"month","features":["50 exports/month","Commercial license"]}]', 'intermediate', false, '{desktop,web}', '{"VR creation","AI character generation","Sculpting","Rigging","Pose generation","Texture painting","FBX export","Game-ready meshes"}', '{"Unity","Unreal Engine","SteamVR","Oculus"}', 'https://masterpiecestudio.com/learn', true),

('Blockade Labs', 'blockade-labs', 'AI skybox and 360 environment generation', 'Blockade Labs generates immersive 360° skyboxes and panoramic environments from text prompts. Used for game backgrounds, VR environments, and metaverse spaces — export as equirectangular HDR images.', 'https://skybox.blockadelabs.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["50 generations/month"]},{"plan":"Pro","price":9,"period":"month","features":["500 generations/month","Private","HD"]},{"plan":"Studio","price":49,"period":"month","features":["5000 generations/month","API access"]}]', 'beginner', true, '{web,api}', '{"360 skybox generation","Text-to-environment","HDR export","Panoramic images","Custom styles","Remix","Depth maps","VR-ready"}', '{"Unity","Unreal Engine","A-Frame","Three.js"}', 'https://api.blockadelabs.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── MUSIC & AUDIO (MORE) ────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Soundraw', 'soundraw', 'AI music generator for content creators', 'Soundraw lets you generate royalty-free music by selecting mood, genre, tempo, and length. Edit individual instruments and structure in a simple interface, then download for commercial use.', 'https://soundraw.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Generate unlimited","No download"]},{"plan":"Creator","price":16.99,"period":"month","features":["Unlimited downloads","Commercial license"]}]', 'beginner', true, '{web,api}', '{"AI music generation","Mood selection","Genre selection","BPM control","Instrument editing","Royalty-free","Commercial license","API access"}', '{"YouTube","TikTok","Adobe Premiere","Final Cut"}', 'https://soundraw.io/api', true),

('Boomy', 'boomy', 'Create original songs in seconds with AI', 'Boomy lets anyone create original AI music tracks in seconds by selecting a style. Save, submit to streaming platforms, and earn royalties — over 14 million songs created by the community.', 'https://boomy.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["25 song submissions"]},{"plan":"Personal","price":2.99,"period":"month","features":["Unlimited submissions","Streaming distribution"]},{"plan":"Professional","price":9.99,"period":"month","features":["Advanced editing","Custom samples"]}]', 'beginner', false, '{web,mobile}', '{"AI song creation","Style selection","Streaming distribution","Royalty earning","Song editing","Cover art","Social sharing"}', '{"Spotify","Apple Music","YouTube Music","TikTok"}', 'https://boomy.com', true),

('Aiva', 'aiva', 'AI music composition for film, games, and media', 'AIVA (Artificial Intelligence Virtual Artist) composes emotional soundtracks for film, TV, games, and ads. Upload a reference track or choose from styles, and AIVA generates orchestral and cinematic music.', 'https://aiva.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["3 downloads/month","MP3 only"]},{"plan":"Standard","price":11,"period":"month","features":["15 downloads/month","Commercial license"]},{"plan":"Pro","price":33,"period":"month","features":["300 downloads/month","Full ownership"]}]', 'beginner', false, '{web}', '{"Orchestral composition","Film scoring","Style profiles","Reference track upload","MIDI export","Full ownership option","Cinematic AI"}', '{}', 'https://help.aiva.ai', true),

('Musicfy', 'musicfy', 'AI voice cloning and cover song creation', 'Musicfy lets you create AI covers of any song with famous artist voice models, clone your own voice for music production, and generate original AI music. Popular for creating viral cover tracks.', 'https://musicfy.lol', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 creations/month"]},{"plan":"Pro","price":12.99,"period":"month","features":["Unlimited creations","Commercial license","Voice cloning"]}]', 'beginner', false, '{web}', '{"AI voice cloning","Artist voice models","Song covers","Text-to-song","Stem separation","Voice training","Commercial license"}', '{}', 'https://musicfy.lol', true),

('Beatoven.ai', 'beatoven-ai', 'AI music generation for podcasts and videos', 'Beatoven.ai creates unique, mood-based background music tailored for podcasts, videos, and games. Generates music section by section, matching the emotional arc of your content with royalty-free output.', 'https://beatoven.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["15 min free music/month"]},{"plan":"Pro","price":19,"period":"month","features":["120 min/month","Commercial license"]}]', 'beginner', true, '{web,api}', '{"Mood-based generation","Section editing","Genre selection","Instrument control","Podcast scoring","Royalty-free","API access","WAV/MP3 export"}', '{"Descript","Adobe Premiere","Final Cut"}', 'https://beatoven.ai/docs', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── LOW-CODE / NO-CODE ──────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Webflow', 'webflow', 'No-code web design platform with AI capabilities', 'Webflow lets designers build production-ready websites visually with the power of code. AI features include AI copywriting, AI image generation on canvas, and Webflow AI for layout suggestions.', 'https://webflow.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["2 projects","webflow.io subdomain"]},{"plan":"Basic","price":18,"period":"month","features":["Custom domain","No Webflow badge"]},{"plan":"CMS","price":29,"period":"month","features":["CMS","API access"]}]', 'intermediate', true, '{web,api}', '{"Visual builder","CMS","AI copywriting","AI image generation","Ecommerce","SEO tools","Interactions","Localization","Logic automation"}', '{"Zapier","Make","Airtable","HubSpot","Mailchimp","Shopify","Figma"}', 'https://developers.webflow.com', true),

('Bubble', 'bubble', 'No-code app builder with AI integration', 'Bubble is the leading no-code platform for building complex web apps without code. Supports databases, APIs, workflows, and AI plugins. Powers thousands of production SaaS startups.', 'https://bubble.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Test apps","bubble.io domain"]},{"plan":"Starter","price":32,"period":"month","features":["Custom domain","25 workflows/month"]},{"plan":"Growth","price":134,"period":"month","features":["Unlimited workflows","Custom plugins"]}]', 'intermediate', false, '{web}', '{"Visual editor","Database","API integrations","Workflows","User auth","AI plugins","Plugins marketplace","Responsive design","PWA"}', '{"Stripe","Twilio","SendGrid","Zapier","OpenAI","Anthropic","Google Maps"}', 'https://manual.bubble.io', true),

('AppGyver', 'appgyver', 'Low-code app builder by SAP for enterprise and citizen devs', 'SAP AppGyver (now SAP Build Apps) is a professional low-code platform for building web and mobile apps with logic, data binding, and enterprise integrations — no coding required.', 'https://www.sap.com/products/technology-platform/low-code.html', 'freemium', '[{"plan":"Community","price":0,"period":"month","features":["Up to 5 users","Basic apps"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full SAP integration"]}]', 'intermediate', true, '{web,mobile,api}', '{"Drag-and-drop builder","Mobile apps","Data binding","REST/GraphQL","Business logic","SAP integration","PWA","Offline support"}', '{"SAP","REST APIs","Firebase","Supabase"}', 'https://help.sap.com/docs/build-apps', true),

('Glide', 'glide', 'Build apps from spreadsheets and databases with AI', 'Glide turns your Google Sheets, Excel, or Airtable data into beautiful mobile and web apps in minutes. AI features help generate app structure, screen layouts, and automation flows from your data.', 'https://glideapps.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 projects","500 rows","glide.page domain"]},{"plan":"Maker","price":49,"period":"month","features":["Unlimited projects","25000 rows","Custom domain"]}]', 'beginner', true, '{web,mobile,api}', '{"Spreadsheet-to-app","AI app generation","CRUD operations","User roles","Data integrations","Forms","Computed columns","Custom actions"}', '{"Google Sheets","Excel","Airtable","MySQL","BigQuery","SQL Server"}', 'https://docs.glideapps.com', true),

('Adalo', 'adalo', 'No-code mobile and web app builder', 'Adalo lets you build native iOS and Android apps without code using a drag-and-drop interface. Features a database, actions, custom components, and app store publishing built in.', 'https://adalo.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["10 records/collection","adalo.com domain"]},{"plan":"Starter","price":45,"period":"month","features":["Unlimited records","Custom domain","App store"]},{"plan":"Professional","price":65,"period":"month","features":["API access","External collections"]}]', 'beginner', false, '{web,mobile}', '{"Native iOS/Android","Web app","Database","User auth","Push notifications","Custom components","App store publishing","Stripe payments"}', '{"Stripe","Zapier","Airtable","Google Sheets","Xano"}', 'https://help.adalo.com', true),

('Draftbit', 'draftbit', 'Low-code React Native app builder', 'Draftbit is a low-code platform for building React Native apps visually. Generates clean, exportable React Native code, connects to any REST API, and lets developers drop into code when needed.', 'https://draftbit.com', 'freemium', '[{"plan":"Starter","price":19,"period":"month","features":["3 apps","50 components"]},{"plan":"Pro","price":79,"period":"month","features":["Unlimited apps","Code export","Custom fonts"]}]', 'intermediate', false, '{web}', '{"Visual React Native builder","Code export","REST API connection","Custom components","Navigation","Authentication","Data tables","Responsive preview"}', '{"Firebase","Supabase","Airtable","Xano","REST APIs"}', 'https://docs.draftbit.com', true),

('FlutterFlow', 'flutterflow', 'Build Flutter apps visually with AI assistance', 'FlutterFlow is a visual development platform for building native mobile apps and web apps using Flutter. AI can generate entire app layouts, suggest database structures, and write Dart code snippets.', 'https://flutterflow.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["1 project","View mode only"]},{"plan":"Standard","price":30,"period":"month","features":["Code export","Custom domain","Unlimited projects"]},{"plan":"Pro","price":70,"period":"month","features":["GitHub sync","Custom code","Teams"]}]', 'intermediate', false, '{web}', '{"Flutter/Dart","Visual app builder","AI generation","Firebase integration","Custom code","GitHub sync","Responsive","Code export","Custom actions"}', '{"Firebase","Supabase","Stripe","RevenueCat","OpenAI","Google Maps"}', 'https://docs.flutterflow.io', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── HEALTHCARE & WELLNESS ───────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Ada Health', 'ada-health', 'AI-powered symptom checker and health guide', 'Ada Health''s AI helps people assess their symptoms, understand potential causes, and decide on next steps. Used by 11M+ people globally and integrated into health systems as a triage tool.', 'https://ada.com', 'freemium', '[{"plan":"Personal","price":0,"period":"month","features":["Free symptom assessment","Health diary"]},{"plan":"Enterprise","price":0,"period":"month","features":["API integration","White-label","Custom branding"]}]', 'beginner', true, '{web,mobile,api}', '{"Symptom assessment","Condition explanations","Next step guidance","Health diary","Multi-language","API integration","White-label","Evidence-based"}', '{}', 'https://ada.com/enterprise', true),

('Woebot', 'woebot', 'AI mental health support chatbot', 'Woebot is an AI-powered mental health app that provides CBT-based support, mood tracking, and coping strategies. Clinically validated to reduce symptoms of depression and anxiety in users.', 'https://woebothealth.com', 'freemium', '[{"plan":"Personal","price":0,"period":"month","features":["CBT exercises","Mood tracking","Daily check-ins"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom deployment","Clinical integration"]}]', 'beginner', false, '{mobile,web}', '{"CBT techniques","Mood tracking","Anxiety support","Daily check-ins","Psychoeducation","Crisis resources","Clinically validated","Evidence-based"}', '{"Epic","Cerner","Health systems"}', 'https://woebothealth.com', true),

('Suki AI', 'suki-ai', 'AI voice assistant for clinical documentation', 'Suki AI helps physicians create clinical notes using voice, reducing documentation time by 72%. Integrates with EHR systems, generates SOAP notes, and learns each physician''s preferences.', 'https://suki.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Contact for pricing","EHR integration","Custom training"]}]', 'intermediate', true, '{mobile,api}', '{"Voice clinical notes","SOAP notes","EHR integration","Ambient documentation","Dictation","Note summarization","ICD-10 coding"}', '{"Epic","Cerner","Athenahealth","DrChrono","eClinicalWorks"}', 'https://suki.ai', true),

('Spring Health', 'spring-health', 'Precision mental health benefits platform', 'Spring Health uses AI to match employees with the right mental health care including therapy, coaching, and medication. Analyzes clinical data to create personalized care plans for enterprise clients.', 'https://springhealth.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Clinical integration","Analytics"]}]', 'beginner', false, '{web,mobile}', '{"AI care matching","Therapist finder","Medication support","Crisis support","Care navigation","Analytics","EAP replacement","DEI reporting"}', '{"Workday","ADP","Salesforce","Epic"}', 'https://springhealth.com', true),

('Curai Health', 'curai-health', 'AI-first virtual care platform', 'Curai Health provides AI-powered primary care through text-based consultations with doctors and AI assistance. The AI collects patient history, suggests differential diagnoses, and drafts treatment plans for physician review.', 'https://curaihealth.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","API integration"]}]', 'beginner', true, '{mobile,web,api}', '{"AI patient intake","Differential diagnosis","Treatment plans","Prescription support","Lab orders","Specialist referrals","24/7 availability"}', '{"Epic","Surescripts"}', 'https://curaihealth.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── REAL ESTATE ─────────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Zillow AI', 'zillow-ai', 'AI-powered property valuation and search', 'Zillow''s AI tools include the Zestimate AVM, neural Zestimate, AI-generated listing descriptions, natural language property search, and personalized home recommendations.', 'https://zillow.com', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Full platform free","Agent tools separate"]}]', 'beginner', true, '{web,mobile,api}', '{"Zestimate valuation","Neural Zestimate","AI listing descriptions","Natural language search","Personalized recommendations","3D tours","Agent tools"}', '{"MLS","Dotloop","ShowingTime"}', 'https://bridgedataoutput.com', true),

('Restb.ai', 'restb-ai', 'Computer vision AI for real estate images', 'Restb.ai uses computer vision to analyze property photos, automatically tag features, score image quality, identify issues, and generate listing descriptions. Used by MLSs and portals globally.', 'https://restb.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","API access","Volume discounts"]}]', 'intermediate', true, '{api}', '{"Photo tagging","Feature detection","Room classification","Issue detection","Image quality scoring","Virtual staging","Listing description generation","Bulk processing"}', '{"MLS systems","Salesforce","Zillow","Realtor.com"}', 'https://docs.restb.ai', true),

('Skyline AI', 'skyline-ai', 'AI commercial real estate intelligence', 'Skyline AI (part of JLL Technologies) analyzes thousands of data points to predict commercial property performance, identify investment opportunities, and automate underwriting for CRE investors.', 'https://jllt.com/products/skyline', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","CRE analysis suite"]}]', 'expert', true, '{web,api}', '{"Property valuation","Investment analysis","Market intelligence","Risk scoring","NOI forecasting","Automated underwriting","Deal sourcing","Portfolio analytics"}', '{"CoStar","ARGUS","Yardi","RealPage"}', 'https://jllt.com', true),

('Lofty', 'lofty', 'AI-powered CRM and marketing for real estate agents', 'Lofty (formerly Chime) is an AI-powered CRM built for real estate agents. Features AI lead scoring, automated follow-up, predictive analytics, IDX websites, and team management tools.', 'https://lofty.com', 'paid', '[{"plan":"Standard","price":449,"period":"month","features":["AI CRM","IDX website","Lead gen"]},{"plan":"Plus","price":749,"period":"month","features":["Team features","Advanced AI","Video email"]}]', 'intermediate', false, '{web,mobile}', '{"AI lead scoring","Automated follow-up","IDX website","Predictive dialer","Market reports","Team management","Video email","Social ads"}', '{"Zillow","Realtor.com","BoomTown","Dotloop","DocuSign"}', 'https://help.lofty.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── FINANCE & TRADING ───────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Kensho', 'kensho', 'AI analytics for financial intelligence', 'Kensho (S&P Global) applies AI and ML to financial data to identify market patterns, predict macro-economic events, and automate research. Used by investment banks, hedge funds, and central banks.', 'https://kensho.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full platform"]}]', 'expert', true, '{web,api}', '{"Market pattern recognition","Macro event prediction","NLP on financial text","Financial data extraction","Portfolio analytics","Earnings call analysis","Regulatory filing parsing"}', '{"Bloomberg","FactSet","S&P Capital IQ","Refinitiv"}', 'https://kensho.com', true),

('Kavout', 'kavout', 'AI-powered stock analysis and investment signals', 'Kavout uses AI to generate stock scores (Kai Score), analyze financial fundamentals, and surface investment opportunities. Features a quantitative research platform for retail and institutional investors.', 'https://kavout.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Basic Kai Score","10 stocks/day"]},{"plan":"Pro","price":79,"period":"month","features":["Full Kai Score","Unlimited analysis","Portfolio tools"]}]', 'intermediate', true, '{web,api}', '{"AI stock scoring","Fundamental analysis","Technical analysis","Portfolio optimization","Watchlists","Backtesting","Sector analysis","Earnings predictions"}', '{"TD Ameritrade","Interactive Brokers","Robinhood"}', 'https://kavout.com/docs', true),

('AlphaSense', 'alphasense', 'AI search and intelligence for financial research', 'AlphaSense is an AI-powered market intelligence platform that searches across earnings calls, SEC filings, news, and broker research. Smart Synonyms and sentiment analysis surface insights other tools miss.', 'https://alpha-sense.com', 'paid', '[{"plan":"Professional","price":0,"period":"month","features":["Contact for pricing"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom","API access","Team features"]}]', 'intermediate', true, '{web,api}', '{"Earnings call search","SEC filing analysis","News intelligence","Smart Synonyms","Sentiment analysis","Competitive intelligence","Alert system","Export"}', '{"Bloomberg","FactSet","Salesforce","Slack"}', 'https://alpha-sense.com/resources', true),

('Composer', 'composer', 'AI-powered automated investing platform', 'Composer lets you build, backtest, and automate trading strategies using a no-code visual builder. Features AI that translates natural language strategy ideas into executable automated portfolios.', 'https://composer.trade', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Paper trading","Strategy builder"]},{"plan":"Premium","price":19,"period":"month","features":["Live trading","Unlimited strategies","Backtesting"]}]', 'intermediate', false, '{web}', '{"No-code strategy builder","AI strategy from text","Backtesting","Live trading automation","ETF strategies","Risk controls","Performance analytics","Portfolio rebalancing"}', '{"Alpaca","Interactive Brokers"}', 'https://help.composer.trade', true),

('Lex', 'lex-markets', 'AI-driven commercial real estate investing', 'Lex Markets democratizes commercial real estate investing through AI-driven deal analysis, fractional ownership, and liquidity through NYSE Arca listings. AI scores every property investment opportunity.', 'https://lex.markets', 'freemium', '[{"plan":"Investor","price":0,"period":"month","features":["Free to invest","0.5% transaction fee"]}]', 'intermediate', false, '{web,mobile}', '{"Fractional CRE investing","AI property scoring","NYSE-listed shares","Liquidity","Due diligence AI","Income distributions","Portfolio management"}', '{"NYSE Arca","DTC"}', 'https://lex.markets', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── GAMING & GAME DEVELOPMENT ───────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Scenario', 'scenario', 'AI art generation for game developers', 'Scenario is an AI platform for generating consistent game art assets. Train custom models on your art style, generate characters, environments, and items that match your game''s visual identity.', 'https://scenario.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["100 assets/month","3 custom generators"]},{"plan":"Indie","price":24,"period":"month","features":["2500 assets/month","10 generators"]},{"plan":"Studio","price":89,"period":"month","features":["10000 assets/month","API"]}]', 'intermediate', true, '{web,api}', '{"Custom model training","Style consistency","Character generation","Environment art","Item generation","ControlNet","Inpainting","Tiling textures","API"}', '{"Unity","Unreal Engine"}', 'https://docs.scenario.com', true),

('Inworld AI', 'inworld-ai', 'AI NPCs and characters for games and virtual worlds', 'Inworld AI creates game NPCs with memory, personality, and dynamic dialogue powered by LLMs. Characters remember players, have emotional responses, and can be given goals and backstories.', 'https://inworld.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Sandbox use","Basic characters"]},{"plan":"Developer","price":0,"period":"month","features":["Pay as you go","$20/1M tokens"]},{"plan":"Studio","price":0,"period":"month","features":["Custom pricing","SLA"]}]', 'intermediate', true, '{web,api}', '{"AI NPCs","Character memory","Emotional AI","Voice synthesis","Goal-driven behavior","Multi-character scenes","Safety filters","SDK support"}', '{"Unity","Unreal Engine","MetaHuman","AWS","GCP"}', 'https://docs.inworld.ai', true),

('G3D.AI', 'g3d-ai', 'AI-powered 3D game asset generation', 'G3D.AI (formerly Kaedim) converts 2D concept art and images into textured, game-ready 3D models using AI. Reduces the time to create 3D game assets from days to minutes.', 'https://g3d.ai', 'paid', '[{"plan":"Starter","price":100,"period":"month","features":["20 models/month","Basic quality"]},{"plan":"Studio","price":0,"period":"month","features":["Custom pricing","High quality","Priority"]}]', 'intermediate', false, '{web}', '{"Image-to-3D","Auto-texturing","Game-ready mesh","PBR materials","FBX/OBJ export","Batch processing","Style consistency"}', '{"Unity","Unreal Engine","Blender"}', 'https://g3d.ai', true),

('Latitude', 'latitude', 'AI-powered interactive fiction and game narratives', 'Latitude (AI Dungeon) creates infinite interactive narrative games with AI. Write stories that adapt to player choices, with persistent worlds, custom scenarios, and multiplayer storytelling.', 'https://latitude.io', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["AI Dungeon access","Standard quality"]},{"plan":"Premium","price":9.99,"period":"month","features":["Advanced AI","Unlimited","Adventure creation"]}]', 'beginner', true, '{web,mobile,api}', '{"Infinite narratives","Adaptive storytelling","World building","Multiplayer","Custom scenarios","Character memory","Dungeon Master mode","API"}', '{}', 'https://help.aidungeon.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── FASHION & RETAIL ────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Vue.ai', 'vue-ai', 'AI platform for fashion retail personalization', 'Vue.ai provides fashion retailers with AI for product tagging, visual search, personalized recommendations, virtual try-on, and automated catalog management. Used by 200+ global retailers.', 'https://vue.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full platform"]}]', 'intermediate', true, '{web,mobile,api}', '{"Product tagging","Visual search","Personalized recommendations","Virtual try-on","Catalog automation","Outfit recommendations","Size prediction","Trend forecasting"}', '{"Shopify","Magento","Salesforce Commerce","SAP Hybris"}', 'https://docs.vue.ai', true),

('Fashable', 'fashable', 'AI fashion design generation for clothing brands', 'Fashable helps fashion designers generate novel clothing designs, colorways, and patterns using AI. Accelerates the design process from concept to production-ready technical sheets.', 'https://fashable.ai', 'paid', '[{"plan":"Basic","price":39,"period":"month","features":["50 designs/month","3 collections"]},{"plan":"Pro","price":99,"period":"month","features":["200 designs/month","Unlimited collections","Tech sheets"]}]', 'intermediate', false, '{web}', '{"Design generation","Colorway variations","Pattern generation","Technical sheets","Collection management","Style transfer","Trend integration","Export to spec"}', '{}', 'https://fashable.ai', true),

('Heuritech', 'heuritech', 'AI trend forecasting for fashion brands', 'Heuritech analyzes millions of social media images daily using computer vision to identify emerging fashion trends 12-18 months in advance. Used by luxury brands to optimize product development and buying.', 'https://heuritech.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full trend platform"]}]', 'intermediate', false, '{web}', '{"Trend forecasting","Social image analysis","Micro-trend detection","Demand signals","Seasonal planning","Category analysis","Competitive tracking","Sustainability scoring"}', '{"SAP","PLM systems"}', 'https://heuritech.com', true),

('Stitch Fix Hybrid Design', 'stitch-fix-ai', 'AI-human hybrid styling and personalization', 'Stitch Fix uses AI algorithms to match customers with clothing based on style, fit, budget, and feedback. The AI handles initial curation while human stylists refine selections, creating a hybrid model.', 'https://stitchfix.com', 'paid', '[{"plan":"Standard","price":20,"period":"month","features":["Styling fee applied to purchase","Personal stylist","AI curation"]}]', 'beginner', false, '{web,mobile}', '{"AI style curation","Personal stylist","Style quiz","Outfit recommendations","Fit feedback","Size model","Keep what you like","Direct buy"}', '{}', 'https://stitchfix.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── ACCESSIBILITY ───────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Be My Eyes', 'be-my-eyes', 'AI visual assistance for blind and low-vision users', 'Be My Eyes connects blind and low-vision people with sighted volunteers and a GPT-4V AI assistant. The AI (Be My AI) can describe images, read documents, navigate websites, and answer visual questions instantly.', 'https://bemyeyes.com', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Free for users","AI assistant included"]}]', 'beginner', false, '{mobile,web}', '{"AI image description","Document reading","Product identification","Navigation help","Scene description","Label reading","Real-time volunteer connection","24/7 AI"}', '{}', 'https://bemyeyes.com', true),

('Speechify', 'speechify', 'AI text-to-speech for reading accessibility', 'Speechify converts any text — web pages, PDFs, docs, emails — into natural-sounding audio. Popular with people with dyslexia, ADHD, and visual impairments, as well as busy professionals who prefer audio.', 'https://speechify.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Basic voices","1x speed"]},{"plan":"Premium","price":139,"period":"year","features":["AI voices","4.5x speed","AI summaries","Offline mode"]}]', 'beginner', false, '{web,mobile,desktop}', '{"Text-to-speech","AI voices","OCR scanning","Speed control","AI summaries","Highlights","Offline","Chrome extension","Word highlighting"}', '{"Google Drive","Dropbox","Google Docs","Notion","Chrome"}', 'https://speechify.com/blog', true),

('UserWay', 'userway', 'AI-powered web accessibility widget', 'UserWay provides an AI accessibility widget that makes websites comply with WCAG, ADA, and other standards. Auto-remediates accessibility violations, adds keyboard navigation, and provides an accessibility menu for users.', 'https://userway.org', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Accessibility widget","Basic compliance"]},{"plan":"Professional","price":49,"period":"month","features":["Advanced AI","Manual audit","VPAT"]},{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","SLA","CDN"]}]', 'beginner', true, '{web,api}', '{"WCAG compliance","AI auto-remediation","Accessibility menu","Screen reader support","Keyboard navigation","Color contrast fix","Font adjustments","Audit reports"}', '{"WordPress","Shopify","Wix","Squarespace","Webflow"}', 'https://userway.org/developers', true),

('Otter.ai (Accessibility)', 'otter-ai-accessibility', 'Real-time captions and transcription for meetings', 'Otter.ai provides live transcription for meetings, lectures, and events in real time, making conversations accessible to deaf and hard-of-hearing users. AI generates summaries, action items, and searchable transcripts.', 'https://otter.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["300 min/month transcription","3 imports"]},{"plan":"Pro","price":17,"period":"month","features":["1200 min/month","Custom vocab","Summary actions"]}]', 'beginner', false, '{web,mobile}', '{"Real-time transcription","Live captions","AI summaries","Action items","Speaker ID","Custom vocabulary","Zoom integration","Searchable archive"}', '{"Zoom","Google Meet","Microsoft Teams","Webex","Dropbox","Salesforce"}', 'https://help.otter.ai', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── COMMUNICATION & OUTREACH ────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Lavender', 'lavender', 'AI email coaching for sales reps', 'Lavender is an AI sales email coach that analyzes emails in real time and gives a score with specific suggestions. Helps reps write emails that get more replies by analyzing what works in your industry.', 'https://lavender.ai', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 email analysis/week"]},{"plan":"Individual","price":27,"period":"month","features":["Unlimited analysis","AI compose","Personalization"]},{"plan":"Teams","price":49,"period":"month","features":["Team analytics","Manager dashboard"]}]', 'beginner', false, '{web}', '{"Email scoring","AI suggestions","Personalization","Spam analysis","Subject line grader","GIF recommendations","Mobile preview","Reply rate tracking"}', '{"Gmail","Outlook","Salesloft","Outreach","HubSpot","Salesforce"}', 'https://lavender.ai/blog', true),

('Instantly', 'instantly', 'AI cold email platform for unlimited outreach', 'Instantly is a cold email platform with AI personalization, unlimited sending accounts, and email warmup. Used by agencies and sales teams to send thousands of personalized cold emails daily.', 'https://instantly.ai', 'paid', '[{"plan":"Growth","price":47,"period":"month","features":["Unlimited email accounts","5000 contacts","AI writing"]},{"plan":"Hypergrowth","price":97,"period":"month","features":["50000 contacts","Advanced analytics","API"]}]', 'intermediate', true, '{web,api}', '{"Unlimited accounts","Email warmup","AI personalization","Sequences","Analytics","A/B testing","Inbox rotation","API","Lead finder"}', '{"HubSpot","Salesforce","Zapier","Slack","Webhooks"}', 'https://help.instantly.ai', true),

('Smartwriter', 'smartwriter', 'Hyper-personalized cold email and LinkedIn outreach', 'SmartWriter uses AI to generate highly personalized outreach messages based on prospect data from LinkedIn, news mentions, blog posts, and more — without manual research.', 'https://smartwriter.ai', 'paid', '[{"plan":"Basic","price":59,"period":"month","features":["400 leads/month","Icebreakers"]},{"plan":"Popular","price":149,"period":"month","features":["1500 leads/month","LinkedIn outreach"]},{"plan":"Pro","price":359,"period":"month","features":["5000 leads/month","API access"]}]', 'intermediate', true, '{web,api}', '{"Hyper-personalization","LinkedIn outreach","Backlink-based icebreakers","Email sequences","Prospect research","CSV bulk generation","Company news search","API"}', '{"LinkedIn","Hunter.io","Apollo","Lemlist","Salesforce"}', 'https://smartwriter.ai/blog', true),

('Typeform AI', 'typeform-ai', 'Conversational forms and surveys with AI', 'Typeform creates conversational, one-question-at-a-time forms that feel like real conversations. AI features generate form questions from prompts and provide logic branching for personalized experiences.', 'https://typeform.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["10 questions","10 responses/month"]},{"plan":"Basic","price":29,"period":"month","features":["Unlimited questions","100 responses/month"]},{"plan":"Plus","price":59,"period":"month","features":["1000 responses/month","Logic jump"]}]', 'beginner', true, '{web,api}', '{"Conversational forms","AI question generation","Logic branching","Conditional logic","Payment collection","File upload","Integrations","Analytics","Embed"}', '{"HubSpot","Salesforce","Slack","Google Sheets","Mailchimp","Zapier","Airtable"}', 'https://developer.typeform.com', true),

('Exceed.ai', 'exceed-ai', 'AI-powered conversational lead qualification', 'Exceed.ai automates lead qualification and nurturing through AI-driven conversations over email, chat, and SMS. The AI engages leads 24/7, qualifies them, and hands off to human reps when ready to buy.', 'https://exceed.ai', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full automation"]}]', 'intermediate', true, '{web,api}', '{"Conversational AI","Lead qualification","Multi-channel (email/chat/SMS)","Meeting scheduling","CRM sync","Lead scoring","Follow-up automation","Handoff to reps"}', '{"Salesforce","HubSpot","Marketo","Drift","Calendly"}', 'https://help.exceed.ai', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── SCIENCE & RESEARCH ──────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Semantic Scholar', 'semantic-scholar', 'AI-powered academic research engine', 'Semantic Scholar is a free AI-powered academic search engine from the Allen Institute for AI. Features semantic search, citation graphs, TLDR summaries of papers, and research recommendations.', 'https://semanticscholar.org', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Full access","API","No account required"]}]', 'intermediate', true, '{web,api}', '{"Semantic paper search","TLDR summaries","Citation graphs","Research recommendations","Author profiles","Topic feeds","Literature review","API access"}', '{}', 'https://api.semanticscholar.org', true),

('ResearchRabbit', 'researchrabbit', 'AI tool for literature discovery and mapping', 'ResearchRabbit is called the "Spotify for papers" — it builds interactive citation networks, discovers related papers, and creates visual research maps. Free for all researchers.', 'https://researchrabbitapp.com', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Full access","Unlimited papers","Team collections"]}]', 'intermediate', false, '{web}', '{"Citation network visualization","Paper discovery","Research maps","Similar work finder","Author tracking","Email alerts","Zotero sync","Team sharing"}', '{"Zotero","Semantic Scholar","PubMed"}', 'https://help.researchrabbitapp.com', true),

('Litmaps', 'litmaps', 'Visual literature mapping for researchers', 'Litmaps creates dynamic visual maps of academic literature showing how papers are connected through citations over time. Helps researchers discover gaps, key papers, and track field evolution.', 'https://litmaps.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 maps","20 seed articles"]},{"plan":"Individual","price":10,"period":"month","features":["Unlimited maps","Unlimited seeds","Alerts"]}]', 'intermediate', false, '{web}', '{"Citation maps","Literature discovery","Timeline view","Alert system","Collaboration","Export to reference managers","Gap analysis"}', '{"Zotero","Mendeley","Endnote","CSV export"}', 'https://app.litmaps.com', true),

('SciSpace', 'scispace', 'AI copilot for reading and understanding research papers', 'SciSpace (formerly Typeset) lets you chat with research papers, get plain-language explanations of complex concepts, extract data, and discover related literature. Covers 200M+ papers.', 'https://scispace.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["30 paper reads/month","5 questions/paper"]},{"plan":"Premium","price":12,"period":"month","features":["Unlimited reads","Unlimited questions","Export"]}]', 'beginner', true, '{web,api}', '{"Chat with papers","Plain language explanations","Data extraction","Literature discovery","Citation finder","Research notes","Chrome extension","API"}', '{}', 'https://help.scispace.com', true),

('Consensus', 'consensus', 'AI search engine for scientific research', 'Consensus searches across 200M+ research papers and uses AI to surface consensus findings on any question. Shows percentage of studies that agree, key claims, and evidence quality without paywalls.', 'https://consensus.app', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["20 searches/day","Basic extractions"]},{"plan":"Premium","price":10.99,"period":"month","features":["Unlimited searches","GPT-4 summaries","Filters"]}]', 'beginner', false, '{web}', '{"Scientific consensus search","Evidence synthesis","Study quality meter","Claim extraction","Related papers","AI study summary","Filter by year/design"}', '{}', 'https://consensus.app', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── AGRICULTURE & ENVIRONMENT ───────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Cropin', 'cropin', 'AI-powered agriculture intelligence platform', 'Cropin uses satellite imagery, AI, and IoT to provide farmers and agribusinesses with crop monitoring, yield prediction, weather intelligence, and disease detection across millions of acres.', 'https://cropin.com', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Full platform"]}]', 'intermediate', true, '{web,mobile,api}', '{"Crop monitoring","Yield prediction","Disease detection","Weather intelligence","Satellite imagery","Farm management","Supply chain","Carbon monitoring"}', '{"Google Earth Engine","AWS","Azure","Salesforce"}', 'https://cropin.com/resources', true),

('Prospera', 'prospera', 'AI computer vision for greenhouse and field crops', 'Prospera (acquired by Valmont) uses AI computer vision installed in greenhouses and fields to monitor crop health, detect pests, predict disease outbreaks, and optimize growing conditions in real time.', 'https://prospera.ag', 'paid', '[{"plan":"Enterprise","price":0,"period":"month","features":["Custom pricing","Hardware+software"]}]', 'expert', true, '{web,api}', '{"Computer vision monitoring","Pest detection","Disease prediction","Growth tracking","Yield forecasting","Labor optimization","Climate control","Alert system"}', '{"Climate control systems","Labor management"}', 'https://prospera.ag', true),

('Farmers Business Network', 'farmers-business-network', 'AI data platform for farm decision making', 'FBN (Farmers Business Network) uses AI to analyze agronomic data from thousands of farms to provide personalized seed recommendations, input pricing transparency, and crop marketing tools.', 'https://fbn.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Market data","Basic analytics"]},{"plan":"Membership","price":800,"period":"year","features":["Full analytics","Seed recommendations","Input pricing"]}]', 'intermediate', false, '{web,mobile}', '{"Seed recommendations","Input pricing","Crop marketing","Agronomic analytics","Weather data","Benchmarking","Crop insurance","Equipment marketplace"}', '{"John Deere Operations Center","Climate FieldView","Granular"}', 'https://fbn.com', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── DESIGN TOOLS (MORE) ─────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Looka', 'looka', 'AI logo and brand identity generation', 'Looka uses AI to generate logos and complete brand identities including color palettes, fonts, and brand assets. Create a professional brand package in minutes without a designer.', 'https://looka.com', 'paid', '[{"plan":"Logo","price":65,"period":"one-time","features":["High-res files","300+ formats","Color variations"]},{"plan":"Brand Kit","price":96,"period":"year","features":["Logo + brand assets","Business cards","Social media kit"]}]', 'beginner', false, '{web}', '{"AI logo generation","Brand kit","Color palette","Font selection","Business cards","Social media templates","Email signatures","Favicon","200+ industries"}', '{}', 'https://looka.com', true),

('Brandmark', 'brandmark', 'AI logo design that learns from your feedback', 'Brandmark creates unique logos using AI trained on thousands of professional designs. Enter your company name, slogan, and style preferences, and AI generates unique logo concepts with color variations.', 'https://brandmark.io', 'paid', '[{"plan":"Basic","price":25,"period":"one-time","features":["Low-res files","PNG"]},{"plan":"Designer","price":65,"period":"one-time","features":["High-res","SVG","Vector"]},{"plan":"Enterprise","price":175,"period":"one-time","features":["Source files","Trademark check"]}]', 'beginner', false, '{web}', '{"AI logo generation","Color variations","Font pairing","Icon library","Brand guidelines","SVG export","Trademark search","Social kit"}', '{}', 'https://brandmark.io', true),

('Designs.ai', 'designs-ai', 'AI-powered creative suite for visual content', 'Designs.ai provides an all-in-one AI creative suite with logo maker, video maker, mockup generator, speech generator, and color palette tool — aimed at small businesses and marketers.', 'https://designs.ai', 'paid', '[{"plan":"Basic","price":29,"period":"month","features":["All 6 tools","5000 icons","100 AI generations"]},{"plan":"Pro","price":69,"period":"month","features":["Unlimited generations","API access"]}]', 'beginner', true, '{web,api}', '{"Logo maker","Video maker","Mockup generator","AI writer","Speech synthesis","Color palette","5000+ icons","Templates","API"}', '{}', 'https://designs.ai/docs', true),

('Khroma', 'khroma', 'AI color tool that learns your color preferences', 'Khroma is a free AI tool that learns your color taste and generates unlimited color palettes, combinations, and gradients tailored to your preferences. Great for designers seeking inspiration.', 'https://khroma.co', 'free', '[{"plan":"Free","price":0,"period":"month","features":["Unlimited palettes","Personal algorithm","Type, poster, gradient views"]}]', 'beginner', false, '{web}', '{"AI color palettes","Personal algorithm","Combination view","Gradient view","Type view","Poster view","Search by hue/tone","Save favorites"}', '{}', 'https://khroma.co', true),

('Remove.bg', 'remove-bg', 'AI background removal in seconds', 'Remove.bg uses AI to automatically remove image backgrounds with precision, preserving hair and fine details. Supports bulk processing and API for e-commerce, design, and automation workflows.', 'https://remove.bg', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["50 preview downloads","1 full-res free"]},{"plan":"Subscription","price":9,"period":"month","features":["40 full-res images/month"]},{"plan":"Pay per use","price":1.99,"period":"image","features":["High-res single image"]}]', 'beginner', true, '{web,api,desktop}', '{"Background removal","Bulk processing","API","Photoshop plugin","Figma plugin","HD output","Transparent PNG","Custom background"}', '{"Photoshop","Figma","Canva","Shopify","WooCommerce","Zapier"}', 'https://www.remove.bg/api', true)

ON CONFLICT (slug) DO NOTHING;

-- ─── WRITING TOOLS (SPECIALIZED) ─────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published) VALUES

('Novelai', 'novelai', 'AI creative writing and story generation for fiction', 'NovelAI is a subscription service for AI-assisted storytelling and creative writing. Uses specially trained models to generate imaginative fiction, help with writer''s block, and maintain consistent characters and plot.', 'https://novelai.net', 'paid', '[{"plan":"Tablet","price":10,"period":"month","features":["1000 Anlas/month","Text generation"]},{"plan":"Scroll","price":15,"period":"month","features":["1000 Anlas","Higher quality models"]},{"plan":"Opus","price":25,"period":"month","features":["10000 Anlas","Best models","Unlimited text"]}]', 'beginner', false, '{web}', '{"Story generation","Character consistency","Lorebook","Image generation","Custom models","Memory","Author''s note","Text adventure","Collaboration"}', '{}', 'https://docs.novelai.net', true),

('Ink for All', 'ink-for-all', 'AI content editor with SEO and readability scoring', 'INK is an AI writing assistant that combines SEO optimization, readability scoring, and content generation in one editor. Real-time feedback helps writers produce content that ranks and engages.', 'https://inkforall.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["5 AI generations/month","SEO scoring"]},{"plan":"Professional","price":50,"period":"month","features":["Unlimited AI","SEO optimizer","All templates"]}]', 'intermediate', false, '{web,desktop}', '{"AI writing","SEO optimization","Readability score","Keyword targeting","Content brief","Plagiarism detection","Templates","Co-writing mode","Brand voice"}', '{"WordPress","Chrome extension"}', 'https://inkforall.com/support', true),

('Sassbook', 'sassbook', 'AI story writer and content tools for authors', 'Sassbook offers AI story writer, AI text summarizer, AI article writer, and AI paraphrase tools. Designed for fiction writers who want help generating plot ideas, character dialogue, and scene descriptions.', 'https://sassbook.com', 'freemium', '[{"plan":"Free","price":0,"period":"month","features":["Limited generations"]},{"plan":"Starter","price":9,"period":"month","features":["5000 words/day"]},{"plan":"Pro","price":20,"period":"month","features":["Unlimited generation"]}]', 'beginner', false, '{web}', '{"AI story writing","Article writing","Text summarizer","Paraphrase tool","Genre selection","Creativity control","Tone control"}', '{}', 'https://sassbook.com/faq', true),

('Closerscopy', 'closerscopy', 'AI copywriting platform with custom frameworks', 'ClosersCopy is a long-form AI copywriting tool with 700+ built-in marketing frameworks and the ability to train custom AI models on your brand voice. Focuses on sales and conversion copy.', 'https://closerscopy.com', 'paid', '[{"plan":"Power","price":49.99,"period":"month","features":["Unlimited AI writes","700 frameworks","5 AI models"]},{"plan":"Superpower","price":79.99,"period":"month","features":["Unlimited everything","Custom brand AI"]}]', 'intermediate', false, '{web}', '{"700+ copy frameworks","Custom AI training","Long-form editor","Sales copy","Email sequences","Ad copy","AIDA/PAS frameworks","Tone control","Audits"}', '{}', 'https://closerscopy.com/blog', true)

ON CONFLICT (slug) DO NOTHING;
