-- ============================================================
-- Batch 7: 55 AI tools
-- Categories: Writing & Content (more), Marketing & SEO (more),
--   Research & Education, Healthcare
-- ============================================================

-- ─── WRITING & CONTENT (15) ─────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES

('Anyword', 'anyword', 'AI copywriting with predictive performance scoring', 'Anyword combines AI text generation with a unique predictive performance score that estimates how well your copy will convert. It analyzes your brand voice and audience data to produce on-brand marketing content across ads, emails, landing pages, and social posts.', 'https://anyword.com', 'freemium', '[{"plan":"Starter","price":"$49/mo","features":["Unlimited words","Performance prediction","Blog wizard"]},{"plan":"Data-Driven","price":"$99/mo","features":["Copy intelligence","Brand voice","Target audience"]},{"plan":"Business","price":"$499/mo","features":["Custom AI models","Team workflows","Analytics"]}]', 'beginner', true, '{web,api}', '{"Predictive performance score","Brand voice training","Blog post wizard","Ad copy generator","Email copy","Landing page copy","A/B testing suggestions","Custom AI models"}', '{"HubSpot","Jasper","WordPress","Google Ads"}', 'https://anyword.com/api', true, '{"Marketing teams","Performance marketers","Copywriters"}', '{"Academic writing","Technical documentation"}', 'Strong differentiator with its performance prediction scoring, which sets it apart from generic AI writers. Best suited for data-driven marketing teams who want copy that converts.', now()),

('Writer', 'writer-ai', 'Enterprise AI writing platform for brand consistency', 'Writer is an enterprise-grade generative AI platform built for businesses that need on-brand, compliant content at scale. It enforces style guides, terminology, and tone across teams while offering AI text generation, rewriting, and content governance tools.', 'https://writer.com', 'paid', '[{"plan":"Team","price":"$18/user/mo","features":["Style guide","AI assistant","Snippets"]},{"plan":"Enterprise","price":"Custom","features":["Custom AI models","Knowledge graph","API access","SSO"]}]', 'intermediate', true, '{web,api,plugin}', '{"Brand voice enforcement","Style guide AI","Terminology management","AI text generation","Content governance","Knowledge graph","Custom AI models","Compliance checks"}', '{"Google Docs","Chrome","Figma","Contentful","HubSpot"}', 'https://developer.writer.com', true, '{"Enterprise content teams","Regulated industries","Brand managers"}', '{"Solo creators","Budget-conscious freelancers"}', 'The gold standard for enterprise AI writing. Excels at brand consistency and governance, though its price point puts it out of reach for smaller teams.', now()),

('Hypotenuse AI', 'hypotenuse-ai', 'AI content generation for e-commerce and product descriptions', 'Hypotenuse AI specializes in generating product descriptions, blog articles, and marketing copy tailored for e-commerce brands. It pulls from product data to create SEO-optimized content that matches your brand tone, with bulk generation for large catalogs.', 'https://hypotenuse.ai', 'freemium', '[{"plan":"Starter","price":"$29/mo","features":["50,000 words","25 images","Blog writer"]},{"plan":"Growth","price":"$59/mo","features":["Unlimited words","Bulk generation","Brand voice"]},{"plan":"Enterprise","price":"Custom","features":["API access","Custom models","Dedicated support"]}]', 'beginner', true, '{web,api}', '{"Product description generator","Bulk content generation","SEO optimization","Brand voice matching","Image generation","Blog article writer","Social media copy","Catalog integration"}', '{"Shopify","WooCommerce","BigCommerce","WordPress"}', 'https://docs.hypotenuse.ai', true, '{"E-commerce brands","Product marketers","Catalog managers"}', '{"Long-form editorial","Technical writing"}', 'Purpose-built for e-commerce content at scale. The bulk generation and direct Shopify integration make it a time-saver for brands with large product catalogs.', now()),

('Simplified', 'simplified', 'All-in-one AI content creation and design platform', 'Simplified combines AI writing, graphic design, video editing, and social media scheduling in one platform. Teams can create blog posts, social graphics, short videos, and schedule everything from a single dashboard with AI assistance throughout.', 'https://simplified.com', 'freemium', '[{"plan":"Free","price":"$0","features":["2,000 AI words","5 design projects"]},{"plan":"Small Team","price":"$30/mo","features":["50,000 AI words","Unlimited design","Brand kit"]},{"plan":"Business","price":"$50/mo","features":["Unlimited words","AI presenter","Priority support"]}]', 'beginner', false, '{web}', '{"AI writer","Graphic design editor","Video editor","Social media scheduler","Brand kit","AI image generation","Template library","Team collaboration"}', '{"Instagram","Facebook","Twitter","YouTube","TikTok","LinkedIn"}', 'https://help.simplified.com', true, '{"Small businesses","Social media managers","Content creators"}', '{"Enterprise teams needing deep analytics","Developers needing API access"}', 'A jack-of-all-trades that bundles writing, design, and scheduling into one affordable tool. Individual features are not best-in-class, but the convenience factor is hard to beat for small teams.', now()),

('Peppertype', 'peppertype', 'AI content marketing and generation platform', 'Peppertype.ai by Pepper Content helps marketing teams generate blog posts, social media captions, ad copy, and email content using AI. It includes a content quality audit feature and SEO suggestions to ensure high-performing output.', 'https://peppertype.ai', 'paid', '[{"plan":"Starter","price":"$35/mo","features":["50,000 words","35+ templates","Plagiarism check"]},{"plan":"Growth","price":"$199/mo","features":["Unlimited words","Content audit","Team workspace","SEO mode"]}]', 'beginner', true, '{web,api}', '{"AI content generation","Content audit scoring","SEO suggestions","35+ content templates","Plagiarism checker","Team workspace","Brand tone settings","Blog to social repurposing"}', '{"WordPress","Shopify","HubSpot","Semrush"}', 'https://docs.peppertype.ai', true, '{"Content marketing teams","Agencies","Blog-heavy brands"}', '{"Fiction writers","Non-English primary content"}', 'Solid AI content platform backed by Pepper Content marketplace. The content audit feature adds useful quality control that most AI writers lack.', now()),

('Scalenut', 'scalenut', 'AI-powered SEO content lifecycle management', 'Scalenut manages the entire content lifecycle from keyword research and topic clustering to AI-powered writing and real-time SEO optimization. It provides SERP-based outlines and NLP-driven content scoring to help pages rank.', 'https://scalenut.com', 'freemium', '[{"plan":"Essential","price":"$39/mo","features":["100,000 AI words","5 SEO reports"]},{"plan":"Growth","price":"$79/mo","features":["Unlimited AI words","30 SEO reports","Cruise mode"]},{"plan":"Pro","price":"$149/mo","features":["75 SEO reports","Topic clusters","API"]}]', 'intermediate', true, '{web,api,plugin}', '{"Cruise mode long-form writer","SERP analysis","NLP content scoring","Topic clustering","Keyword planner","Real-time SEO optimization","Content brief generator","Chrome extension"}', '{"WordPress","Semrush","Google Search Console","Copyscape"}', 'https://scalenut.com/api-docs', true, '{"SEO content writers","Content agencies","SaaS marketers"}', '{"Non-SEO creative writing","Social media copy"}', 'One of the most complete SEO content platforms available. Cruise Mode can produce a full SEO-optimized article in minutes, though it still needs human editing for nuance.', now()),

('Frase', 'frase', 'AI-powered SEO content research and optimization', 'Frase helps content teams research, write, and optimize SEO content faster. It analyzes top SERP results to generate comprehensive briefs, provides an AI writer for drafting, and scores content in real time against ranking competitors.', 'https://frase.io', 'paid', '[{"plan":"Solo","price":"$15/mo","features":["4 articles/mo","AI writer","SERP analysis"]},{"plan":"Basic","price":"$45/mo","features":["30 articles/mo","AI writer"]},{"plan":"Team","price":"$115/mo","features":["Unlimited articles","Team collaboration","API"]}]', 'intermediate', true, '{web,api}', '{"SERP research","AI content briefs","Real-time content scoring","AI article writer","Question research","Competitor analysis","Outline builder","Content analytics"}', '{"Google Search Console","WordPress","Google Docs"}', 'https://frase.io/api', true, '{"SEO specialists","Content strategists","Freelance writers"}', '{"E-commerce product copy","Social media management"}', 'Excellent research-first approach to content creation. The SERP analysis and brief generation are among the best, making it ideal for writers who want data-driven outlines before they write.', now()),

('MarketMuse', 'marketmuse', 'AI content strategy and planning platform', 'MarketMuse uses AI to audit your existing content, identify gaps, and plan a content strategy that builds topical authority. It provides content briefs with target topics, word counts, and internal linking suggestions based on competitive analysis.', 'https://marketmuse.com', 'freemium', '[{"plan":"Free","price":"$0","features":["10 queries/mo","Limited page analysis"]},{"plan":"Standard","price":"$149/mo","features":["100 queries/mo","Content briefs","Competitor analysis"]},{"plan":"Team","price":"$399/mo","features":["Unlimited queries","Team features","API"]}]', 'advanced', true, '{web,api}', '{"Content inventory audit","Topic modeling","Competitive content analysis","AI content briefs","Content scoring","Internal linking suggestions","Keyword difficulty","Personalized difficulty scores"}', '{"WordPress","Google Analytics","Google Search Console","Semrush"}', 'https://docs.marketmuse.com', true, '{"Content strategists","SEO directors","Enterprise publishers"}', '{"Casual bloggers","Small businesses with limited content"}', 'A strategic powerhouse for content planning and topical authority building. Expensive but delivers unique insights you cannot get from keyword tools alone.', now()),

('Clearscope', 'clearscope', 'Premium content optimization for search performance', 'Clearscope is a content optimization platform that uses NLP and competitor analysis to give writers real-time guidance on topics, terms, and readability needed to rank. Known for its simplicity and accuracy in content grading.', 'https://clearscope.io', 'paid', '[{"plan":"Essentials","price":"$170/mo","features":["10 content reports/mo","Google Docs integration"]},{"plan":"Business","price":"$1,200/mo","features":["100 reports/mo","API","Custom integrations"]},{"plan":"Enterprise","price":"Custom","features":["Unlimited reports","Dedicated support"]}]', 'intermediate', true, '{web,api}', '{"Content grading","NLP term suggestions","Readability scoring","Competitor content analysis","Google Docs integration","WordPress plugin","Keyword research","Content inventory"}', '{"Google Docs","WordPress","Semrush","Google Search Console"}', 'https://clearscope.io/api', true, '{"Enterprise SEO teams","Content agencies","B2B SaaS marketers"}', '{"Budget-conscious freelancers","Non-English content"}', 'The premium choice for content optimization with a clean, no-nonsense interface. Pricey, but its content grades correlate strongly with actual search rankings.', now()),

('INK Editor', 'ink-editor', 'AI writing and SEO assistant with real-time optimization', 'INK Editor combines AI writing with built-in SEO scoring, letting you draft and optimize content simultaneously. It offers a distraction-free editor, AI rewriting, and patent-pending SEO algorithms to maximize organic traffic potential.', 'https://inkforall.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited AI words","SEO scoring"]},{"plan":"Professional","price":"$39/mo","features":["Unlimited AI words","Full SEO tools","Keyword clustering"]},{"plan":"Enterprise","price":"$99/mo","features":["Team features","API","Priority support"]}]', 'beginner', true, '{web,desktop,api}', '{"AI writer","Real-time SEO scoring","Keyword clustering","Distraction-free editor","AI image generation","Content shield AI detection","Headline optimizer","Meta description generator"}', '{"WordPress","Google Docs","Shopify"}', 'https://inkforall.com/docs', true, '{"Bloggers","SEO content writers","Small business owners"}', '{"Enterprise content governance","Academic research"}', 'A solid mid-range option combining AI writing with SEO optimization in one editor. The AI content shield feature for reducing AI detection is a unique selling point.', now()),

('Longshot AI', 'longshot-ai', 'AI writer for long-form factual content with citations', 'Longshot AI specializes in creating long-form, factually accurate content with built-in fact-checking and source citations. It generates blog posts, articles, and reports while verifying claims against real-time web data to reduce hallucinations.', 'https://longshot.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited generations","Basic templates"]},{"plan":"Pro","price":"$29/mo","features":["Unlimited generations","Fact-check","Custom templates"]},{"plan":"Team","price":"$59/mo","features":["Team workspace","API access","Integrations"]}]', 'beginner', true, '{web,api,plugin}', '{"Fact-checking engine","Source citations","Long-form blog writer","FactGPT real-time data","Custom templates","Workflow builder","Chrome extension","SEO integration"}', '{"WordPress","Google Docs","Semrush","Copyscape"}', 'https://longshot.ai/api-docs', true, '{"Content marketers","Journalists","Research writers"}', '{"Fiction writers","Social media micro-content"}', 'Stands out with its fact-checking and citation features, addressing the biggest concern with AI-generated content. A smart choice for writers producing factual, authoritative articles.', now()),

('Narrato', 'narrato', 'AI content workspace for teams and agencies', 'Narrato is an AI-powered content workspace that combines content planning, creation, collaboration, and publishing in one platform. It offers AI templates, SEO briefs, workflow automation, and a content marketplace for outsourcing.', 'https://narrato.io', 'paid', '[{"plan":"Pro","price":"$36/mo","features":["Unlimited projects","AI writer","SEO briefs"]},{"plan":"Business","price":"$76/mo","features":["Custom workflows","API access","Guest access","Analytics"]}]', 'beginner', false, '{web}', '{"AI content templates","Editorial calendar","SEO content briefs","Team workflow automation","Content marketplace","Publishing integrations","Project management","Style guides"}', '{"WordPress","Webflow","Google Docs","Slack","Zapier"}', 'https://narrato.io/help', true, '{"Content agencies","Marketing teams","Freelance content managers"}', '{"Solo bloggers","Technical documentation teams"}', 'A well-rounded content operations platform that fills the gap between AI writing tools and project management. The built-in marketplace for hiring writers is a nice bonus.', now()),

('ContentBot', 'contentbot', 'AI content generation and automation for marketers', 'ContentBot provides AI-powered content generation with automation flows that can create and publish content on autopilot. It offers blog post generation, paraphrasing, landing page copy, and a unique automation builder for hands-off content pipelines.', 'https://contentbot.ai', 'freemium', '[{"plan":"Prepaid","price":"$0.5/1000 words","features":["Pay as you go","All templates"]},{"plan":"Starter","price":"$29/mo","features":["50,000 words","Automation flows"]},{"plan":"Premium","price":"$59/mo","features":["150,000 words","Advanced automation","API"]}]', 'beginner', true, '{web,api}', '{"AI blog writer","Content automation flows","Paraphrasing tool","Landing page generator","Press release writer","Auto-publish","Content imports","API access"}', '{"WordPress","Zapier","Medium","Shopify"}', 'https://contentbot.ai/api', true, '{"Digital marketers","Content agencies","Solopreneurs"}', '{"Enterprise teams","Highly regulated industries"}', 'The automation flow builder is the killer feature here, letting you set up recurring content pipelines. Good for marketers who want to put content generation on semi-autopilot.', now()),

('Writecream', 'writecream', 'AI copywriting with personalized outreach and icebreakers', 'Writecream generates marketing copy, blog posts, and personalized cold outreach messages using AI. Its standout feature is AI-generated icebreakers and personalized intros for cold emails and LinkedIn messages based on prospect data.', 'https://writecream.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited credits","Basic templates"]},{"plan":"Unlimited","price":"$29/mo","features":["Unlimited credits","All templates","Personalization"]},{"plan":"Extended","price":"$49/mo","features":["Priority support","Team features","API"]}]', 'beginner', true, '{web,api,plugin}', '{"Cold email icebreakers","LinkedIn personalization","Blog article writer","Ad copy generator","Voice over generation","Image generation","Podcast script writer","Chrome extension"}', '{"LinkedIn","Gmail","HubSpot","Outreach"}', 'https://writecream.com/api', true, '{"Sales teams","Outreach specialists","Growth hackers"}', '{"Long-form editorial content","Academic writing"}', 'Niche but effective for personalized cold outreach. The AI icebreaker feature saves hours of prospect research, though general writing capabilities are average compared to competitors.', now()),

('Koala Writer', 'koala-writer', 'AI SEO article writer with real-time SERP analysis', 'Koala Writer (KoalaWriter) generates SEO-optimized articles by analyzing top search results in real time. It produces well-structured long-form content with proper headings, internal links, and FAQ sections that are ready to publish with minimal editing.', 'https://koala.sh', 'freemium', '[{"plan":"Essentials","price":"$9/mo","features":["15,000 words","GPT-4o","SERP analysis"]},{"plan":"Professional","price":"$25/mo","features":["45,000 words","Real-time data","Amazon reviews"]},{"plan":"Premium","price":"$49/mo","features":["100,000 words","Bulk generation","API"]}]', 'beginner', true, '{web,api}', '{"One-click SEO articles","Real-time SERP analysis","Amazon product roundups","FAQ generation","Internal linking","Outline editor","Bulk article generation","WordPress integration"}', '{"WordPress","Shopify","Google Search Console"}', 'https://koala.sh/docs', true, '{"Affiliate marketers","Niche site builders","SEO content writers"}', '{"Brand storytelling","Technical documentation"}', 'One of the best tools for churning out SEO-focused articles quickly. The Amazon roundup feature is perfect for affiliate marketers, though output still benefits from human polish.', now())

ON CONFLICT (slug) DO NOTHING;

-- ─── MARKETING & SEO (15) ───────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES

('Unbounce', 'unbounce', 'AI-powered landing page builder and conversion optimization', 'Unbounce uses AI to help marketers build high-converting landing pages without developers. Its Smart Traffic feature automatically routes visitors to the page variant most likely to convert, and Smart Copy generates marketing text on demand.', 'https://unbounce.com', 'paid', '[{"plan":"Build","price":"$99/mo","features":["Unlimited landing pages","Popups","Sticky bars"]},{"plan":"Experiment","price":"$149/mo","features":["A/B testing","Smart Traffic"]},{"plan":"Optimize","price":"$249/mo","features":["AI optimization","Advanced targeting","AMP pages"]}]', 'intermediate', true, '{web,api}', '{"AI Smart Traffic","Drag-and-drop builder","A/B testing","Smart Copy AI","Popups and sticky bars","AMP landing pages","Dynamic text replacement","Template library"}', '{"Google Analytics","HubSpot","Salesforce","Mailchimp","Zapier","WordPress"}', 'https://developer.unbounce.com', true, '{"Performance marketers","PPC agencies","SaaS growth teams"}', '{"Full website building","E-commerce stores"}', 'The AI Smart Traffic feature is genuinely impressive, automatically optimizing conversions without manual A/B test management. A premium but worthwhile investment for teams running paid traffic.', now()),

('Mutiny', 'mutiny', 'AI-driven website personalization for B2B conversion', 'Mutiny enables B2B companies to personalize their website for different audience segments without engineering help. It uses AI to identify visitor segments and recommend personalized content, headlines, and CTAs that increase pipeline and conversion rates.', 'https://mutinyhq.com', 'paid', '[{"plan":"Growth","price":"Custom","features":["AI recommendations","Audience segmentation","A/B testing"]},{"plan":"Enterprise","price":"Custom","features":["Advanced integrations","Dedicated CSM","Multi-domain"]}]', 'advanced', true, '{web,api}', '{"AI visitor segmentation","Website personalization","No-code editor","A/B testing","Revenue attribution","Firmographic targeting","AI content suggestions","Playbook recommendations"}', '{"Salesforce","HubSpot","Clearbit","6sense","Google Analytics","Marketo"}', 'https://docs.mutinyhq.com', true, '{"B2B SaaS marketers","Demand generation teams","Growth marketers"}', '{"B2C companies","Small businesses with low traffic"}', 'A powerful personalization engine that makes ABM tangible on your website. Requires meaningful traffic volume to see results, but the AI-driven recommendations are genuinely actionable for B2B teams.', now()),

('Optimizely', 'optimizely', 'Digital experience and experimentation platform with AI', 'Optimizely is an enterprise experimentation platform for A/B testing, feature flagging, and content management. Its AI capabilities include automatic traffic allocation, predictive audiences, and AI-powered content recommendations across web and mobile.', 'https://optimizely.com', 'paid', '[{"plan":"Grow","price":"Custom","features":["A/B testing","Personalization","Basic analytics"]},{"plan":"Scale","price":"Custom","features":["Feature flags","Advanced audiences","Multi-armed bandit"]},{"plan":"Enterprise","price":"Custom","features":["Full stack","Multi-channel","Dedicated support"]}]', 'advanced', true, '{web,mobile,api}', '{"A/B testing","Multi-armed bandit","Feature flags","Personalization","AI audience targeting","CMS","Commerce platform","Statistical engine"}', '{"Salesforce","Google Analytics","Segment","Tealium","Adobe Analytics","Slack"}', 'https://docs.developers.optimizely.com', true, '{"Enterprise product teams","Growth engineers","Digital experience teams"}', '{"Small businesses","Teams without developer resources"}', 'The industry standard for enterprise experimentation. Deep statistical rigor and robust feature flagging, though the price and complexity make it overkill for smaller organizations.', now()),

('Albert.ai', 'albert-ai', 'Autonomous AI digital advertising platform', 'Albert is a self-learning AI platform that autonomously manages digital advertising campaigns across Google, Facebook, Instagram, and YouTube. It handles audience targeting, bidding, budget allocation, and creative optimization with minimal human intervention.', 'https://albert.ai', 'paid', '[{"plan":"Professional","price":"Custom","features":["Multi-channel management","AI optimization","Reporting"]},{"plan":"Enterprise","price":"Custom","features":["Dedicated strategist","Custom integrations","White-glove onboarding"]}]', 'advanced', true, '{web,api}', '{"Autonomous campaign management","Cross-channel optimization","AI bid management","Budget allocation","Creative testing","Audience discovery","Performance analytics","Real-time optimization"}', '{"Google Ads","Facebook Ads","Instagram","YouTube","Bing Ads","Google Analytics"}', 'https://albert.ai/resources', true, '{"Performance marketing agencies","Enterprise advertisers","Multi-channel ad teams"}', '{"Small ad budgets","Single-channel campaigns"}', 'Truly autonomous advertising AI that manages campaigns end-to-end. Requires substantial ad spend to justify the cost, but delivers impressive ROAS improvements for brands spending at scale.', now()),

('AdCreative.ai', 'adcreative-ai', 'AI-powered ad creative and banner generation', 'AdCreative.ai generates conversion-focused ad creatives, banners, and social media posts using AI trained on high-performing ads. It scores each creative with a conversion prediction and integrates directly with major ad platforms for seamless deployment.', 'https://adcreative.ai', 'paid', '[{"plan":"Starter","price":"$29/mo","features":["10 downloads/mo","Text and banner ads","1 brand"]},{"plan":"Professional","price":"$59/mo","features":["25 downloads/mo","5 brands","Competitor insights"]},{"plan":"Ultimate","price":"$149/mo","features":["Unlimited downloads","Unlimited brands","Priority"]}]', 'beginner', true, '{web,api}', '{"AI ad creative generation","Conversion scoring","Banner generation","Social media creatives","Competitor ad analysis","Brand kit","Direct ad platform push","Video ad generation"}', '{"Facebook Ads","Google Ads","LinkedIn Ads","Pinterest","Zapier"}', 'https://docs.adcreative.ai', true, '{"Performance marketers","Creative agencies","E-commerce advertisers"}', '{"Brand campaigns needing bespoke design","Print advertising"}', 'Impressively fast at generating ad variations with genuine conversion insights. The creative scoring helps prioritize winners before spending budget, a real competitive advantage.', now()),

('Predis.ai', 'predis-ai', 'AI social media content creation and scheduling', 'Predis.ai generates complete social media posts including captions, hashtags, and creatives from a single text prompt. It creates carousels, reels, and single-image posts with AI, plus offers scheduling and competitor analysis features.', 'https://predis.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["15 posts/mo","AI captions","1 brand"]},{"plan":"Lite","price":"$32/mo","features":["60 posts/mo","Scheduling","Competitor analysis"]},{"plan":"Premium","price":"$59/mo","features":["Unlimited posts","All formats","API"]}]', 'beginner', true, '{web,mobile,api}', '{"AI post generation","Carousel creator","Reel maker","Caption and hashtag AI","Scheduling","Competitor analysis","Brand kit","Multi-platform publishing"}', '{"Instagram","Facebook","LinkedIn","Twitter","TikTok","Pinterest"}', 'https://predis.ai/api-docs', true, '{"Social media managers","Small businesses","Digital agencies"}', '{"Enterprise social strategy","B2B thought leadership"}', 'Great for quickly spinning up social content across formats. The carousel and reel generation from a single prompt is particularly slick, saving hours of design work.', now()),

('Ocoya', 'ocoya', 'AI-powered social media management and content creation', 'Ocoya combines AI copywriting, graphic design with templates, and social media scheduling in one platform. It generates captions in 26+ languages, provides a Canva-like editor, and supports direct scheduling to all major social networks.', 'https://ocoya.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 posts/mo","AI writer"]},{"plan":"Silver","price":"$19/mo","features":["100 posts/mo","5 social profiles","Scheduling"]},{"plan":"Gold","price":"$49/mo","features":["500 posts/mo","20 profiles","E-commerce integration"]}]', 'beginner', false, '{web}', '{"AI caption generator","26+ language support","Visual editor","Social scheduling","E-commerce integration","Hashtag generator","Link shortener","Analytics dashboard"}', '{"Shopify","WooCommerce","Instagram","Facebook","Twitter","LinkedIn","TikTok"}', 'https://help.ocoya.com', true, '{"E-commerce brands","Multilingual teams","Social media managers"}', '{"Enterprise social listening","Influencer management"}', 'A compact social suite with an impressive multilingual AI writer. Particularly valuable for e-commerce brands that need to tie product catalogs directly to social content.', now()),

('Publer', 'publer', 'Social media scheduler with AI content assistance', 'Publer is a social media scheduling and analytics platform with built-in AI for generating captions, images, and post ideas. It supports bulk scheduling, recycling evergreen content, and auto-scheduling at optimal times across all major platforms.', 'https://publer.io', 'freemium', '[{"plan":"Free","price":"$0","features":["3 social accounts","AI writer","Scheduling"]},{"plan":"Professional","price":"$12/mo","features":["10 accounts","Analytics","Bulk scheduling"]},{"plan":"Business","price":"$21/mo","features":["25 accounts","Team features","White label"]}]', 'beginner', false, '{web,mobile}', '{"AI caption writer","Bulk scheduling","Auto-scheduling","Content recycling","Visual calendar","RSS automation","Link in bio","Analytics"}', '{"Instagram","Facebook","Twitter","LinkedIn","TikTok","Pinterest","Google Business"}', 'https://help.publer.io', true, '{"Freelancers","Small businesses","Social media consultants"}', '{"Enterprise teams needing approval workflows","Large agency operations"}', 'An affordable and straightforward social scheduler with useful AI touches. The content recycling and bulk scheduling features punch above the price point.', now()),

('Vista Social', 'vista-social', 'Modern social media management platform with AI tools', 'Vista Social is a full-featured social media management platform offering publishing, engagement, analytics, listening, and review management. AI features include caption generation, best time to post suggestions, and sentiment analysis on comments.', 'https://vistasocial.com', 'freemium', '[{"plan":"Free","price":"$0","features":["3 profiles","Publishing","AI assistant"]},{"plan":"Pro","price":"$25/mo","features":["8 profiles","Analytics","Listening","Reviews"]},{"plan":"Business","price":"$49/mo","features":["15 profiles","Team workflows","White label"]}]', 'beginner', false, '{web}', '{"Social publishing","AI caption generator","Social listening","Review management","Analytics","Sentiment analysis","Best time to post","Content calendar"}', '{"Instagram","Facebook","Twitter","LinkedIn","TikTok","YouTube","Google Business","Yelp"}', 'https://support.vistasocial.com', true, '{"Agencies","Multi-location businesses","Social media managers"}', '{"Solo creators needing design tools","Enterprise compliance teams"}', 'A feature-rich social management tool at a very competitive price. The built-in review management across Google and Yelp is an unusual bonus for local businesses.', now()),

('Sprout Social', 'sprout-social', 'Enterprise social media management with AI analytics', 'Sprout Social is an enterprise-grade social media management platform with publishing, engagement, analytics, and social listening. AI powers sentiment analysis, optimal send times, automated chatbots, and content suggestions across channels.', 'https://sproutsocial.com', 'paid', '[{"plan":"Standard","price":"$249/mo","features":["5 profiles","Publishing","Analytics","Review management"]},{"plan":"Professional","price":"$399/mo","features":["Unlimited profiles","Competitive reports","Custom workflows"]},{"plan":"Advanced","price":"$499/mo","features":["AI content suggestions","Sentiment analysis","Chatbots"]}]', 'intermediate', true, '{web,mobile,api}', '{"Social publishing","AI sentiment analysis","Social listening","Employee advocacy","Chatbot builder","Competitive benchmarking","Custom analytics","CRM integration"}', '{"Salesforce","HubSpot","Zendesk","Microsoft Teams","Slack","Google Analytics","Shopify"}', 'https://developers.sproutsocial.com', true, '{"Enterprise marketing teams","Agencies managing multiple clients","Customer care teams"}', '{"Solopreneurs","Budget-conscious small businesses"}', 'The Cadillac of social media management. Expensive but delivers enterprise-grade analytics, social listening, and CRM integration that cheaper tools simply cannot match.', now()),

('Brandwatch', 'brandwatch', 'AI-powered social intelligence and consumer insights', 'Brandwatch is a social listening and consumer intelligence platform that uses AI to analyze millions of online conversations. It provides brand monitoring, trend detection, sentiment analysis, and audience insights across social media, forums, blogs, and news.', 'https://brandwatch.com', 'paid', '[{"plan":"Consumer Intelligence","price":"Custom","features":["Social listening","Trend analysis","AI insights"]},{"plan":"Social Media Management","price":"Custom","features":["Publishing","Engagement","Analytics"]},{"plan":"Full Suite","price":"Custom","features":["All features","Influencer management","Crisis alerts"]}]', 'advanced', true, '{web,api}', '{"Social listening","AI trend detection","Sentiment analysis","Consumer insights","Crisis management","Competitive analysis","Influencer discovery","Image recognition"}', '{"Hootsuite","Slack","Google Analytics","Salesforce","Tableau","Power BI"}', 'https://developers.brandwatch.com', true, '{"Brand managers","Market researchers","PR and comms teams"}', '{"Small businesses","Social media scheduling focused teams"}', 'Best-in-class social listening with genuinely powerful AI-driven insights. The depth of conversation analysis is unmatched, though it requires investment in both cost and learning curve.', now()),

('Mention', 'mention', 'Real-time media monitoring and social listening', 'Mention monitors the web and social media in real time for brand mentions, competitor activity, and industry trends. It covers news, blogs, forums, and social networks, with AI-powered sentiment analysis and automated reporting.', 'https://mention.com', 'freemium', '[{"plan":"Free","price":"$0","features":["1 alert","250 mentions/mo"]},{"plan":"Solo","price":"$49/mo","features":["2 alerts","5,000 mentions","Sentiment analysis"]},{"plan":"Pro","price":"$99/mo","features":["5 alerts","10,000 mentions","Competitive reports"]},{"plan":"Company","price":"$179/mo","features":["Unlimited alerts","API","Team features"]}]', 'beginner', true, '{web,mobile,api}', '{"Real-time brand monitoring","Sentiment analysis","Competitive intelligence","Boolean search","Automated reports","Social media management","Influencer scoring","Crisis alerts"}', '{"Slack","Zapier","Buffer","HubSpot","Salesforce"}', 'https://mention.com/en/api', true, '{"PR professionals","Brand managers","Competitive analysts"}', '{"In-depth consumer research","Full social media management"}', 'An accessible entry point into media monitoring without enterprise pricing. Real-time alerts and sentiment tracking cover the essentials, though deeper analysis requires pricier alternatives.', now()),

('SparkToro', 'sparktoro', 'AI audience research and intelligence tool', 'SparkToro reveals where your target audience hangs out online, what they read, who they follow, and what they talk about. It crawls social and web profiles to provide audience intelligence that informs marketing, content, and PR strategies.', 'https://sparktoro.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 searches/mo","Limited results"]},{"plan":"Personal","price":"$38/mo","features":["50 searches/mo","Full results","List building"]},{"plan":"Business","price":"$150/mo","features":["Unlimited searches","Custom lists","Priority"]}]', 'beginner', false, '{web}', '{"Audience intelligence","Social profile analysis","Website and podcast discovery","Hashtag and keyword analysis","Demographic data","Hidden gems discovery","Competitor audience analysis","List export"}', '{"Google Analytics","Zapier","Ahrefs"}', 'https://sparktoro.com/help', true, '{"Content strategists","PR professionals","Niche marketers"}', '{"Paid advertising teams","E-commerce product teams"}', 'Unique and genuinely useful for understanding where audiences congregate online. No other tool provides this kind of audience intelligence so accessibly. A must-have for content and PR strategy.', now()),

('Ubersuggest', 'ubersuggest', 'Affordable SEO and keyword research tool with AI insights', 'Ubersuggest by Neil Patel provides keyword research, site audits, backlink analysis, and content ideas at a fraction of competitor pricing. AI features include content suggestions, keyword difficulty predictions, and automated SEO recommendations.', 'https://neilpatel.com/ubersuggest', 'freemium', '[{"plan":"Free","price":"$0","features":["3 searches/day","Limited data"]},{"plan":"Individual","price":"$12/mo","features":["150 searches/day","1 domain","SEO audit"]},{"plan":"Business","price":"$20/mo","features":["300 searches/day","7 domains","Full reports"]},{"plan":"Enterprise","price":"$40/mo","features":["900 searches/day","15 domains","API"]}]', 'beginner', true, '{web,plugin,api}', '{"Keyword research","Site audit","Backlink analysis","Content ideas","Competitor analysis","Rank tracking","Chrome extension","AI writing assistant"}', '{"Google Search Console","Chrome","WordPress"}', 'https://neilpatel.com/ubersuggest/documentation', true, '{"Beginner SEOs","Small business owners","Freelance marketers"}', '{"Enterprise SEO teams","Large agency operations"}', 'The best value in SEO tools for beginners and small businesses. Data depth does not match Ahrefs or Semrush, but covers 80% of what most small teams need at a fifth of the cost.', now()),

('SE Ranking', 'se-ranking', 'All-in-one SEO platform with AI content tools', 'SE Ranking is a comprehensive SEO platform offering rank tracking, site audit, backlink monitoring, keyword research, and an AI-powered content editor. It provides competitor analysis and local SEO tools at competitive pricing for agencies and in-house teams.', 'https://seranking.com', 'paid', '[{"plan":"Essential","price":"$55/mo","features":["500 keywords","Site audit","Backlink checker"]},{"plan":"Pro","price":"$109/mo","features":["2,000 keywords","Competitor research","Content editor"]},{"plan":"Business","price":"$239/mo","features":["5,000 keywords","API access","White label"]}]', 'intermediate', true, '{web,api}', '{"Rank tracking","Site audit","Backlink monitoring","AI content editor","Keyword research","Competitor analysis","Local SEO","White label reporting"}', '{"Google Analytics","Google Search Console","WordPress","Zapier","Slack"}', 'https://seranking.com/api.html', true, '{"SEO agencies","In-house SEO teams","Freelance consultants"}', '{"Casual bloggers","Non-technical marketers"}', 'A strong Ahrefs and Semrush alternative that delivers most enterprise features at a lower price. The AI content editor is a nice addition that removes the need for a separate tool.', now())

ON CONFLICT (slug) DO NOTHING;

-- ─── RESEARCH & EDUCATION (15) ──────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES

('Consensus', 'consensus', 'AI-powered academic search engine for research papers', 'Consensus uses AI to search across millions of peer-reviewed papers and extract key findings. Instead of returning links, it synthesizes answers from the scientific literature with citations, making academic research accessible to everyone.', 'https://consensus.app', 'freemium', '[{"plan":"Free","price":"$0","features":["20 AI searches/mo","Basic filters"]},{"plan":"Premium","price":"$8.99/mo","features":["Unlimited AI searches","Copilot analysis","Study snapshots","Bookmarks"]},{"plan":"Team","price":"Custom","features":["Team features","API access","Bulk analysis"]}]', 'beginner', true, '{web,api}', '{"AI research synthesis","Citation extraction","Consensus meter","Study snapshots","Copilot deep analysis","Bookmark collections","PDF access","Filter by study type"}', '{"Zotero","Mendeley","Google Scholar"}', 'https://consensus.app/api', true, '{"Researchers","Students","Evidence-based professionals"}', '{"Non-academic searches","Real-time news research"}', 'A game-changer for anyone who needs evidence-based answers. The consensus meter showing agreement across studies is brilliant for quickly gauging scientific support.', now()),

('Elicit', 'elicit', 'AI research assistant for finding and analyzing papers', 'Elicit uses language models to help researchers find relevant papers, extract key claims, and synthesize findings across studies. It automates systematic literature reviews by identifying methodologies, sample sizes, and results from thousands of papers simultaneously.', 'https://elicit.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5,000 paper credits","Basic extraction"]},{"plan":"Plus","price":"$10/mo","features":["25,000 credits","Advanced extraction","Tables"]},{"plan":"Enterprise","price":"Custom","features":["Unlimited","API","Team features"]}]', 'intermediate', true, '{web,api}', '{"Paper discovery","Data extraction","Systematic review automation","Methodology analysis","Result synthesis","Custom columns","CSV export","Abstract summarization"}', '{"Zotero","Google Scholar","Semantic Scholar"}', 'https://elicit.com/api', true, '{"Academic researchers","Systematic reviewers","PhD students"}', '{"Casual readers","Non-academic research"}', 'The most sophisticated AI research tool available, capable of extracting structured data across hundreds of papers. Essential for anyone conducting systematic reviews or meta-analyses.', now()),

('Semantic Scholar', 'semantic-scholar', 'AI-powered academic paper search and recommendation engine', 'Semantic Scholar, built by the Allen Institute for AI, uses machine learning to index over 200 million papers across all scientific fields. It provides TLDR summaries, citation context, influential citations, and AI-powered paper recommendations.', 'https://semanticscholar.org', 'free', '[{"plan":"Free","price":"$0","features":["Unlimited search","TLDR summaries","Citation analysis","API access"]}]', 'beginner', true, '{web,api}', '{"200M+ papers indexed","AI TLDR summaries","Influential citation detection","Research feeds","Author profiles","Citation context","Paper recommendations","Open API"}', '{"Zotero","Mendeley","Google Scholar","Research Rabbit"}', 'https://api.semanticscholar.org', true, '{"Researchers","Students","Data scientists"}', '{"Non-academic searches","Patent research"}', 'The best free academic search engine with genuinely useful AI features. The TLDR summaries and influential citation detection save enormous time when scanning literature.', now()),

('Scholarcy', 'scholarcy', 'AI research paper summarizer and flashcard generator', 'Scholarcy reads research papers, reports, and book chapters, then generates summary flashcards highlighting key findings, methods, contributions, and limitations. It extracts tables, figures, and references into structured, skimmable summaries.', 'https://scholarcy.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Chrome extension","3 summaries/day"]},{"plan":"Personal Library","price":"$9.99/mo","features":["Unlimited summaries","Personal library","Reference extraction"]},{"plan":"Institution","price":"Custom","features":["Team access","LMS integration","API"]}]', 'beginner', false, '{web,plugin}', '{"Paper summarization","Flashcard generation","Key finding extraction","Reference extraction","Figure and table extraction","Chrome extension","Personal library","Comparative analysis"}', '{"Chrome","Google Scholar","Open Access Button","Zotero"}', 'https://scholarcy.com/help', true, '{"Students","Researchers doing literature reviews","Busy professionals"}', '{"Deep methodological analysis","Primary research"}', 'Excellent for quickly digesting research papers when time is limited. The flashcard format is surprisingly effective for retaining key findings across many papers.', now()),

('Connected Papers', 'connected-papers', 'Visual tool for discovering related academic papers', 'Connected Papers creates a visual graph of papers related to a seed paper, showing how research is connected. It helps researchers discover prior and derivative works, identify seminal papers, and explore literature landscapes visually.', 'https://connectedpapers.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 graphs/mo","Basic features"]},{"plan":"Academic","price":"$3/mo","features":["Unlimited graphs","Prior and derivative works","Multi-origin"]}]', 'beginner', false, '{web}', '{"Visual paper graph","Prior works view","Derivative works view","Multi-origin graphs","Paper details panel","Export references","Similarity clustering","Literature landscape mapping"}', '{"Google Scholar","Semantic Scholar","Zotero"}', 'https://connectedpapers.com/about', true, '{"Researchers starting new topics","PhD students","Literature reviewers"}', '{"Non-academic use","Large-scale data mining"}', 'Beautifully simple tool that solves a real problem: discovering related work visually. The prior and derivative works views are perfect for understanding how a research area evolved.', now()),

('Scite.ai', 'scite-ai', 'Smart citation analysis showing how papers cite each other', 'Scite.ai goes beyond citation counts by classifying how a paper is cited: supporting, contrasting, or mentioning. This helps researchers assess the real impact and reliability of findings by seeing whether subsequent work supports or challenges a claim.', 'https://scite.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited searches","Basic citation data"]},{"plan":"Premium","price":"$20/mo","features":["Unlimited searches","Smart citations","Dashboards","API"]},{"plan":"Institution","price":"Custom","features":["Campus-wide access","Admin dashboard"]}]', 'intermediate', true, '{web,plugin,api}', '{"Smart citation classification","Supporting vs contrasting citations","Citation dashboards","Research assistant","Browser extension","Reference check","Journal analysis","API access"}', '{"Zotero","Chrome","Google Scholar","WordPress"}', 'https://scite.ai/api', true, '{"Researchers evaluating evidence","Journal editors","Systematic reviewers"}', '{"General web search","Non-academic research"}', 'A genuinely novel approach to understanding research impact. Knowing whether citations support or challenge a finding is invaluable for evidence assessment, and no other tool does this as well.', now()),

('Iris.ai', 'iris-ai', 'AI science assistant for R&D and research teams', 'Iris.ai provides AI-powered research tools for R&D teams, including automated literature review, patent landscape analysis, and data extraction from scientific documents. It uses NLP to map research spaces and identify relevant papers, patents, and trends.', 'https://iris.ai', 'paid', '[{"plan":"Researcher","price":"$50/mo","features":["Unlimited searches","Smart filters","Workspace"]},{"plan":"Team","price":"Custom","features":["Team workspace","API access","Patent analysis"]},{"plan":"Enterprise","price":"Custom","features":["Custom models","Full platform","Dedicated support"]}]', 'advanced', true, '{web,api}', '{"Automated literature review","Patent landscape analysis","Research space mapping","Data extraction","Smart filters","Team workspace","API access","Document clustering"}', '{"PubMed","Semantic Scholar","Google Patents","Zotero"}', 'https://iris.ai/api-docs', true, '{"R&D teams","Patent analysts","Pharmaceutical researchers"}', '{"Casual research","Student use on a budget"}', 'Purpose-built for serious R&D teams doing systematic research and patent analysis. The research space mapping is powerful but requires investment in both cost and learning.', now()),

('Research Rabbit', 'research-rabbit', 'Free research discovery and paper recommendation tool', 'Research Rabbit is a free tool that helps researchers discover related work through paper recommendations, author networks, and citation analysis. Add seed papers to collections and the platform continuously suggests relevant new publications.', 'https://researchrabbit.ai', 'free', '[{"plan":"Free","price":"$0","features":["Unlimited collections","Paper recommendations","Author networks","Alerts"]}]', 'beginner', false, '{web}', '{"Paper recommendations","Author network mapping","Collection-based discovery","New paper alerts","Citation visualization","Collaboration features","Zotero sync","Similar work suggestions"}', '{"Zotero","Semantic Scholar","Google Scholar"}', 'https://researchrabbit.ai/help', true, '{"Graduate students","Early-career researchers","Literature reviewers"}', '{"Full-text paper access","Data extraction needs"}', 'The Spotify of research papers and completely free. Its recommendation engine surfaces genuinely relevant work you would not find through keyword search alone. An essential tool for any researcher.', now()),

('Litmaps', 'litmaps', 'Literature mapping and citation network visualization', 'Litmaps creates visual maps of academic literature showing citation networks and how papers connect over time. It helps researchers identify seminal works, track research evolution, and discover new relevant papers through interactive timelines and citation graphs.', 'https://litmaps.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 maps","Basic visualization"]},{"plan":"Pro","price":"$10/mo","features":["Unlimited maps","Alerts","Full export"]},{"plan":"Team","price":"Custom","features":["Team maps","Collaboration","API"]}]', 'beginner', false, '{web}', '{"Citation network visualization","Interactive timelines","Seed-based discovery","New paper alerts","Map sharing","Reference export","Research evolution tracking","Collaborative maps"}', '{"Zotero","Mendeley","Google Scholar","Semantic Scholar"}', 'https://help.litmaps.com', true, '{"PhD students","Systematic reviewers","Research teams"}', '{"Non-academic use","Real-time topic monitoring"}', 'Fills a useful niche between Connected Papers and full reference managers. The timeline view showing how research evolved is particularly useful for understanding field development.', now()),

('Explainpaper', 'explainpaper', 'AI tool that explains confusing sections of research papers', 'Explainpaper lets you upload a research paper and highlight any confusing text to get a plain-language AI explanation. It breaks down complex jargon, equations, and methodologies into understandable language, making dense academic papers accessible.', 'https://explainpaper.com', 'freemium', '[{"plan":"Free","price":"$0","features":["3 papers/day","Basic explanations"]},{"plan":"Plus","price":"$12/mo","features":["Unlimited papers","Better model","Faster responses"]}]', 'beginner', false, '{web}', '{"Highlight-to-explain","Jargon simplification","Equation explanation","PDF upload","Follow-up questions","Paper library","Methodology breakdown","Accessible summaries"}', '{"Google Scholar","arXiv","PubMed"}', 'https://explainpaper.com/help', true, '{"Students new to a field","Non-specialists reading papers","Self-learners"}', '{"Expert researchers","Comprehensive literature review"}', 'Brilliantly simple concept perfectly executed. Highlight confusing text, get a clear explanation. Invaluable for students entering a new research area or reading outside their expertise.', now()),

('Coursera', 'coursera', 'Online learning platform with AI-powered tutoring', 'Coursera partners with top universities and companies to offer courses, certificates, and degrees online. AI features include personalized learning paths, AI tutoring assistance, automated grading, and course recommendations based on career goals.', 'https://coursera.org', 'freemium', '[{"plan":"Free","price":"$0","features":["Audit courses","Limited access"]},{"plan":"Plus","price":"$59/mo","features":["7,000+ courses","Certificates","AI coach"]},{"plan":"Enterprise","price":"Custom","features":["Team learning","Analytics","Custom content"]}]', 'beginner', false, '{web,mobile}', '{"University courses","Professional certificates","AI tutor","Personalized learning paths","Automated grading","Peer assessments","Mobile learning","Career recommendations"}', '{"Google","LinkedIn","Slack","Microsoft Teams"}', 'https://coursera.org/developers', true, '{"Career changers","Professional development","University students"}', '{"Hands-on trade skills","Real-time mentorship seekers"}', 'The largest high-quality course catalog from top universities. AI tutoring features are steadily improving, making self-paced learning more effective than ever.', now()),

('Khan Academy', 'khan-academy', 'Free education platform with AI tutor Khanmigo', 'Khan Academy provides free, world-class education with AI-powered tutoring through Khanmigo. The AI tutor helps students work through problems step-by-step, offers personalized practice, and provides teachers with lesson planning assistance and student insights.', 'https://khanacademy.org', 'free', '[{"plan":"Free","price":"$0","features":["All courses","Practice exercises","Progress tracking"]},{"plan":"Khanmigo","price":"$44/year","features":["AI tutor","Debate partner","Writing coach","Teacher tools"]}]', 'beginner', false, '{web,mobile}', '{"AI tutor Khanmigo","Personalized practice","Step-by-step guidance","Progress tracking","Teacher dashboard","Mastery learning","Video lessons","Writing coach"}', '{"Google Classroom","Clever","Schoology","Canvas"}', 'https://khanacademy.org/computing', true, '{"K-12 students","Teachers","Self-learners"}', '{"Professional certification","University-level specialization"}', 'Khanmigo represents the future of AI tutoring done right: Socratic, patient, and free for most users. A remarkable achievement in democratizing quality education.', now()),

('Duolingo', 'duolingo', 'AI-powered language learning with gamification', 'Duolingo is the world''s most popular language learning app, using AI to personalize lesson difficulty and content. Duolingo Max features GPT-4-powered roleplay conversations and explain-my-answer functionality for deeper, contextual language practice.', 'https://duolingo.com', 'freemium', '[{"plan":"Free","price":"$0","features":["All languages","Basic lessons","Ads"]},{"plan":"Super","price":"$6.99/mo","features":["No ads","Unlimited hearts","Progress quizzes"]},{"plan":"Max","price":"$13.99/mo","features":["AI roleplay","Explain my answer","All Super features"]}]', 'beginner', false, '{web,mobile}', '{"AI-personalized lessons","Gamified learning","AI roleplay conversations","Explain my answer AI","40+ languages","Streak tracking","Leaderboards","Podcast content"}', '{"iOS","Android","Google Classroom"}', 'https://duolingo.com/approach', true, '{"Language beginners","Casual learners","Students"}', '{"Professional interpreters","Advanced fluency seekers"}', 'The gold standard for gamified language learning. Duolingo Max AI features add genuinely useful conversation practice, though reaching true fluency still requires real-world immersion.', now()),

('Quizlet', 'quizlet', 'AI-powered study tools and adaptive flashcards', 'Quizlet uses AI to create adaptive study experiences from flashcard sets. Its Q-Chat AI tutor helps students practice through conversation, while Learn mode adapts to individual knowledge gaps and focuses on weak areas for more efficient studying.', 'https://quizlet.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Flashcards","Basic study modes","Community sets"]},{"plan":"Plus","price":"$7.99/mo","features":["Q-Chat AI tutor","Advanced study modes","No ads","Offline access"]}]', 'beginner', false, '{web,mobile}', '{"Adaptive flashcards","Q-Chat AI tutor","Learn mode","Test mode","Match game","Community study sets","Image support","Spaced repetition"}', '{"Google Classroom","Canvas","Schoology","Khan Academy"}', 'https://quizlet.com/help', true, '{"Students","Exam preparers","Language learners"}', '{"Deep conceptual learning","Professional training"}', 'A study staple upgraded with AI. Q-Chat makes studying feel more like tutoring than rote memorization, and the adaptive algorithms genuinely help focus on weak spots.', now()),

('Brainly', 'brainly', 'AI homework helper and peer learning community', 'Brainly combines a community of students helping each other with AI-powered answer generation and step-by-step explanations. Students can ask questions in any subject and receive both peer answers and AI-generated solutions with detailed reasoning.', 'https://brainly.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited questions","Community answers"]},{"plan":"Plus","price":"$4.99/mo","features":["Unlimited AI answers","Step-by-step solutions","No ads","Expert verification"]}]', 'beginner', false, '{web,mobile}', '{"AI step-by-step solutions","Community answers","Math solver","Photo question scan","Expert-verified answers","Subject coverage","Mobile app","Textbook solutions"}', '{"Google Lens","iOS","Android"}', 'https://brainly.com/help', true, '{"K-12 students","Parents helping with homework","Self-study learners"}', '{"University-level research","Professional development"}', 'Effective for getting quick homework help with AI explanations that teach, not just give answers. The community aspect adds reliability, though quality varies by subject complexity.', now())

ON CONFLICT (slug) DO NOTHING;

-- ─── HEALTHCARE (10) ────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES

('Google Health AI', 'google-health-ai', 'AI-powered health research and medical imaging tools', 'Google Health AI develops foundational AI models for healthcare, including Med-PaLM for medical question answering and AI tools for medical imaging analysis. Its research covers dermatology screening, diabetic retinopathy detection, and clinical documentation.', 'https://health.google', 'free', '[{"plan":"Research","price":"$0","features":["Published models","Research papers","Open datasets"]}]', 'advanced', true, '{web,api}', '{"Med-PaLM medical LLM","Medical imaging AI","Dermatology screening","Diabetic retinopathy detection","Clinical documentation","Health research tools","Open datasets","FHIR integration"}', '{"Google Cloud","TensorFlow","EHR systems","FHIR"}', 'https://health.google/developers', true, '{"Healthcare researchers","Hospital AI teams","Medical AI developers"}', '{"Direct patient care","Consumer health apps"}', 'Cutting-edge medical AI research from Google, though most tools are research-stage rather than production-ready consumer products. Essential reading for anyone building healthcare AI.', now()),

('Ada Health', 'ada-health', 'AI-powered symptom assessment and health companion', 'Ada Health is an AI symptom checker that guides users through a conversational assessment to identify possible conditions. Used by over 13 million people, it combines medical knowledge with personalized AI to provide accurate symptom assessments and care navigation.', 'https://ada.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Symptom assessment","Condition information","Care guidance"]},{"plan":"Enterprise","price":"Custom","features":["White-label integration","Clinical decision support","API access","Analytics"]}]', 'beginner', true, '{web,mobile,api}', '{"AI symptom assessment","Conversational interface","Condition library","Care navigation","Personal health journal","Multilingual support","Clinical decision support","Enterprise API"}', '{"EHR systems","Telehealth platforms","Health insurance portals"}', 'https://ada.com/for-enterprise', true, '{"Health-conscious consumers","Telehealth providers","Health insurers"}', '{"Emergency diagnosis","Replacing doctor visits"}', 'One of the most medically validated AI symptom checkers available with strong clinical accuracy. Useful for initial triage but should never replace professional medical advice.', now()),

('Babylon Health', 'babylon-health', 'AI-powered virtual healthcare and telemedicine', 'Babylon Health combines AI-powered symptom checking with telemedicine consultations. Its AI chatbot assesses symptoms, triages patients, and connects them with doctors via video. The platform also offers health monitoring and personalized health assessments.', 'https://babylonhealth.com', 'freemium', '[{"plan":"Free","price":"$0","features":["AI symptom checker","Health assessments"]},{"plan":"Subscription","price":"Varies by region","features":["Video consultations","Prescriptions","Referrals","Health monitoring"]}]', 'beginner', false, '{web,mobile}', '{"AI symptom checker","Video consultations","Health assessments","Digital twin technology","Prescription management","Care navigation","Health monitoring","Clinical triage"}', '{"NHS","Insurance providers","EHR systems","Pharmacy networks"}', 'https://babylonhealth.com/product', true, '{"Patients seeking quick access","Health systems","Insurance providers"}', '{"Emergency care","Complex specialist referrals"}', 'Ambitious vision of AI-first healthcare delivery. The AI triage is effective for common conditions, though the service availability varies significantly by region.', now()),

('K Health', 'k-health', 'AI-powered primary care and clinical decision support', 'K Health uses AI trained on billions of clinical data points to help patients understand symptoms and connect with doctors. The app provides AI-driven assessments, text-based doctor consultations, and prescription management for common conditions.', 'https://khealth.com', 'freemium', '[{"plan":"Free","price":"$0","features":["AI symptom checker","Health information"]},{"plan":"Primary Care","price":"$49/visit","features":["Doctor consultation","Prescriptions","Follow-ups"]},{"plan":"Membership","price":"$9/mo","features":["Unlimited messaging","Reduced visit cost"]}]', 'beginner', false, '{mobile}', '{"AI health assessment","Text-based consultations","Prescription management","Symptom analysis","Clinical data insights","Pediatric care","Mental health support","Follow-up messaging"}', '{"Pharmacy networks","Insurance providers","Lab networks"}', 'https://khealth.com/how-it-works', true, '{"Patients without easy doctor access","Parents","People with common conditions"}', '{"Complex chronic conditions","Emergency situations"}', 'Makes primary care genuinely more accessible with AI-powered triage that leads to real doctor consultations. The data-driven approach provides surprisingly accurate initial assessments.', now()),

('Viz.ai', 'viz-ai', 'AI-powered stroke detection and care coordination', 'Viz.ai uses AI to analyze CT scans and automatically detect suspected large vessel occlusion strokes, alerting the specialist stroke team in real time. This reduces time-to-treatment, which is critical for stroke outcomes, and has expanded to other conditions.', 'https://viz.ai', 'paid', '[{"plan":"Hospital","price":"Custom","features":["AI stroke detection","Real-time alerts","Care coordination"]},{"plan":"Health System","price":"Custom","features":["Multi-site deployment","Analytics dashboard","Expanded condition coverage"]}]', 'advanced', true, '{web,mobile,api}', '{"AI stroke detection","Real-time specialist alerts","CT scan analysis","Care coordination","Time-to-treatment tracking","Pulmonary embolism detection","Aortic disease detection","Clinical analytics"}', '{"PACS systems","Hospital EHR","Radiology systems","Mobile alerting"}', 'https://viz.ai/solutions', true, '{"Hospital stroke centers","Radiologists","Emergency departments"}', '{"Outpatient clinics","Direct consumer use"}', 'A life-saving AI application with FDA clearance that has demonstrably reduced stroke treatment times. One of the clearest examples of AI making a measurable difference in patient outcomes.', now()),

('PathAI', 'pathai', 'AI-powered pathology for diagnostic precision', 'PathAI develops AI technology for pathology that helps pathologists make faster, more accurate diagnoses. Its platform analyzes tissue samples and biopsies using computer vision, supporting cancer detection, biomarker quantification, and clinical trial analysis.', 'https://pathai.com', 'paid', '[{"plan":"Clinical","price":"Custom","features":["AI-assisted diagnosis","Biomarker quantification","Quality assurance"]},{"plan":"Biopharma","price":"Custom","features":["Clinical trial pathology","Companion diagnostics","Endpoint analysis"]}]', 'advanced', true, '{web,api}', '{"AI tissue analysis","Cancer detection","Biomarker quantification","Digital pathology","Clinical trial support","Quality assurance","Slide digitization","Diagnostic precision"}', '{"Lab information systems","Digital slide scanners","EHR systems","Clinical trial platforms"}', 'https://pathai.com/technology', true, '{"Pathology labs","Biopharma companies","Clinical trial organizations"}', '{"Direct patient use","Small clinics"}', 'Leading the digital pathology revolution with AI that genuinely augments pathologist accuracy. Particularly impactful for cancer diagnosis and biopharma clinical trials.', now()),

('Tempus', 'tempus', 'AI-driven precision medicine and clinical data analysis', 'Tempus uses AI to analyze clinical and molecular data at scale, helping doctors make data-driven treatment decisions. Its platform combines genomic sequencing, clinical data structuring, and AI models to personalize cancer treatment and advance drug discovery.', 'https://tempus.com', 'paid', '[{"plan":"Clinical","price":"Custom","features":["Genomic profiling","AI treatment insights","Clinical matching"]},{"plan":"Research","price":"Custom","features":["De-identified data access","AI models","Real-world evidence"]}]', 'advanced', true, '{web,api}', '{"Genomic sequencing","AI treatment recommendations","Clinical trial matching","Real-world evidence","Data structuring","Molecular profiling","Outcome analytics","Drug discovery support"}', '{"EHR systems","Lab systems","Clinical trial databases","Oncology platforms"}', 'https://tempus.com/genomic-profiling', true, '{"Oncologists","Pharmaceutical companies","Research hospitals"}', '{"General practitioners","Consumer health"}', 'One of the most impactful AI healthcare companies, using data at unprecedented scale to personalize cancer treatment. Their clinical data library is a genuine asset for advancing precision medicine.', now()),

('Butterfly Network', 'butterfly-network', 'AI-powered handheld ultrasound imaging', 'Butterfly Network makes the Butterfly iQ+, a handheld, whole-body ultrasound device connected to a smartphone. AI features include auto-capture, image quality guidance, and AI-powered measurements that make point-of-care ultrasound accessible to more clinicians.', 'https://butterflynetwork.com', 'paid', '[{"plan":"Device + Subscription","price":"$3,299 + $420/yr","features":["Handheld device","AI guidance","Cloud storage","20 presets"]},{"plan":"Enterprise","price":"Custom","features":["Fleet management","Analytics","EHR integration","Training"]}]', 'intermediate', false, '{mobile}', '{"Handheld whole-body ultrasound","AI image guidance","Auto-capture","AI measurements","Cloud storage","Telemedicine sharing","20 clinical presets","iPhone and iPad compatible"}', '{"iPhone","iPad","Cloud PACS","Telehealth platforms","EHR systems"}', 'https://support.butterflynetwork.com', true, '{"Point-of-care clinicians","Emergency medicine","Rural healthcare providers"}', '{"Specialized diagnostic radiology","Research-grade imaging"}', 'Democratizing ultrasound access with a device that fits in a coat pocket. The AI guidance is particularly valuable for less experienced users, making quality imaging possible in resource-limited settings.', now()),

('Regard', 'regard', 'AI clinical assistant for hospital physicians', 'Regard is an AI-powered clinical assistant that automatically reviews patient charts, identifies missed diagnoses, and generates diagnostic suggestions for physicians. It integrates with EHR systems to reduce cognitive burden and improve diagnostic completeness.', 'https://withregard.com', 'paid', '[{"plan":"Hospital","price":"Custom","features":["AI chart review","Missed diagnosis detection","EHR integration"]},{"plan":"Health System","price":"Custom","features":["Multi-facility deployment","Analytics","Custom conditions"]}]', 'advanced', true, '{web,api}', '{"AI chart review","Missed diagnosis detection","Diagnostic suggestions","EHR integration","Automated documentation","Clinical alerts","Condition monitoring","Physician dashboard"}', '{"Epic","Cerner","EHR systems","Hospital IT infrastructure"}', 'https://withregard.com/product', true, '{"Hospital physicians","Hospitalists","Clinical documentation teams"}', '{"Outpatient care","Direct patient use"}', 'Addresses a critical problem: diagnostic errors from information overload. Physicians report catching genuinely missed conditions, making it one of the most clinically impactful AI tools in hospitals.', now()),

('Hippocratic AI', 'hippocratic-ai', 'Safety-focused AI agents for healthcare', 'Hippocratic AI builds large language models specifically for healthcare with an emphasis on safety and reducing harm. Its AI agents handle non-diagnostic patient interactions like post-discharge follow-up, medication reminders, and patient education at scale.', 'https://hippocratic.ai', 'paid', '[{"plan":"Enterprise","price":"Custom","features":["AI health agents","Post-discharge follow-up","Patient education","Medication adherence"]}]', 'advanced', true, '{web,api}', '{"Safety-focused health LLM","Patient follow-up agents","Medication reminders","Health education","Multilingual support","Nurse-supervised AI","Empathetic communication","Scalable outreach"}', '{"EHR systems","Hospital call centers","Patient portals","Telehealth platforms"}', 'https://hippocratic.ai/technology', true, '{"Health systems","Patient engagement teams","Post-acute care providers"}', '{"Clinical diagnosis","Direct consumer use without oversight"}', 'A thoughtful approach to healthcare AI that focuses on safety-first design for non-diagnostic tasks. Their emphasis on nurse-supervised AI agents shows maturity in a space where caution is warranted.', now())

ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- CATEGORY LINKS
-- ============================================================

-- Writing & Content
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'anyword' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'writer-ai' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'hypotenuse-ai' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'simplified' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'peppertype' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'scalenut' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'frase' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'marketmuse' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'clearscope' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ink-editor' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'longshot-ai' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'narrato' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'contentbot' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'writecream' AND c.slug = 'writing-content';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'koala-writer' AND c.slug = 'writing-content';

-- Marketing & SEO (primary)
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'unbounce' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mutiny' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'optimizely' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'albert-ai' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'adcreative-ai' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'predis-ai' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ocoya' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'publer' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'vista-social' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'sprout-social' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'brandwatch' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mention' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'sparktoro' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ubersuggest' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'se-ranking' AND c.slug = 'marketing-seo';

-- Cross-category: some writing tools also belong to marketing-seo
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'scalenut' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'frase' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'marketmuse' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'clearscope' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ink-editor' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'koala-writer' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'anyword' AND c.slug = 'marketing-seo';

-- Research & Education
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'consensus' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'elicit' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'semantic-scholar' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'scholarcy' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'connected-papers' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'scite-ai' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'iris-ai' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'research-rabbit' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'litmaps' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'explainpaper' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'coursera' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'khan-academy' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'duolingo' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'quizlet' AND c.slug = 'research-education';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'brainly' AND c.slug = 'research-education';

-- Healthcare
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'google-health-ai' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ada-health' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'babylon-health' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'k-health' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'viz-ai' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'pathai' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'tempus' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'butterfly-network' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'regard' AND c.slug = 'healthcare';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'hippocratic-ai' AND c.slug = 'healthcare';

-- Cross-category: Simplified also belongs to design
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'simplified' AND c.slug = 'design-ui';

-- ============================================================
-- TAG LINKS
-- ============================================================

-- Writing & Content tags
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'anyword' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'anyword' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'writer-ai' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'writer-ai' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'writer-ai' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'hypotenuse-ai' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'hypotenuse-ai' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'hypotenuse-ai' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'simplified' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'simplified' AND tg.slug = 'design';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'simplified' AND tg.slug = 'image-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'peppertype' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'peppertype' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scalenut' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scalenut' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scalenut' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'frase' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'frase' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'frase' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'marketmuse' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'marketmuse' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'clearscope' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'clearscope' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ink-editor' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ink-editor' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ink-editor' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'longshot-ai' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'longshot-ai' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'longshot-ai' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'narrato' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'narrato' AND tg.slug = 'workflow';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'contentbot' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'contentbot' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'contentbot' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'writecream' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'writecream' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'koala-writer' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'koala-writer' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'koala-writer' AND tg.slug = 'text-generation';

-- Marketing & SEO tags
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'unbounce' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'unbounce' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mutiny' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mutiny' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'optimizely' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'optimizely' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'optimizely' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'albert-ai' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'albert-ai' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'adcreative-ai' AND tg.slug = 'image-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'adcreative-ai' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'adcreative-ai' AND tg.slug = 'design';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'predis-ai' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'predis-ai' AND tg.slug = 'image-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'predis-ai' AND tg.slug = 'video-editing';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ocoya' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ocoya' AND tg.slug = 'translation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'publer' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'publer' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'vista-social' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'vista-social' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'sprout-social' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'sprout-social' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'sprout-social' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'brandwatch' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'brandwatch' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mention' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mention' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'sparktoro' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'sparktoro' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ubersuggest' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ubersuggest' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'se-ranking' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'se-ranking' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'se-ranking' AND tg.slug = 'writing-assistant';

-- Research & Education tags
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'consensus' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'consensus' AND tg.slug = 'summarization';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'elicit' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'elicit' AND tg.slug = 'summarization';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'elicit' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'semantic-scholar' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'semantic-scholar' AND tg.slug = 'summarization';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'semantic-scholar' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scholarcy' AND tg.slug = 'summarization';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scholarcy' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'connected-papers' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'connected-papers' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scite-ai' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'scite-ai' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'iris-ai' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'iris-ai' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'iris-ai' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'research-rabbit' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'litmaps' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'litmaps' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'explainpaper' AND tg.slug = 'summarization';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'explainpaper' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'coursera' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'khan-academy' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'duolingo' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'duolingo' AND tg.slug = 'translation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'quizlet' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'brainly' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'brainly' AND tg.slug = 'summarization';

-- Healthcare tags
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'google-health-ai' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'google-health-ai' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ada-health' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ada-health' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'babylon-health' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'k-health' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'viz-ai' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'viz-ai' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'pathai' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'pathai' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'tempus' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'tempus' AND tg.slug = 'research';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'butterfly-network' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'regard' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'regard' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'hippocratic-ai' AND tg.slug = 'agent';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'hippocratic-ai' AND tg.slug = 'chatbot';
