-- ============================================================
-- Batch 9: 55 AI tools
-- Categories: AI Chatbots & LLM Platforms, No-Code/Low-Code AI,
--   AI for Sales, E-commerce AI, AI Infrastructure
-- ============================================================

-- ─── AI CHATBOTS & LLM PLATFORMS ────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Gemini', 'gemini', 'Google''s multimodal AI model and assistant', 'Gemini is Google''s most capable AI model family, powering conversational search, code generation, image understanding, and multimodal reasoning. Available via Google AI Studio and Vertex AI for developers.', 'https://gemini.google.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Gemini 1.5 Flash","Basic features"]},{"plan":"Advanced","price":"$19.99/mo","features":["Gemini Ultra","2TB storage","Google One"]}]', 'beginner', true, '{web,mobile,api}', '{"Multimodal reasoning","Code generation","Image understanding","Long context window","Google Search integration","Real-time information"}', '{"Google Workspace","Google Cloud","Android","Chrome"}', 'https://ai.google.dev/docs', true, '{"Developers needing multimodal AI","Google ecosystem users","Enterprise teams"}', '{"Those needing fully open-source models"}', 'Best multimodal model in the Google ecosystem with an enormous context window; free tier is generous for casual use.', now()),
('Mistral', 'mistral', 'Open-weight European AI models for developers', 'Mistral AI builds efficient open-weight language models that rival much larger competitors. Their models range from the compact Mistral 7B to the powerful Mixtral MoE, all available for self-hosting or via API.', 'https://mistral.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Le Chat free tier","Open models"]},{"plan":"API","price":"Usage-based","features":["All models","Fine-tuning","Guardrails"]}]', 'intermediate', true, '{web,api}', '{"Open-weight models","Mixture of experts","Fine-tuning","Function calling","JSON mode","Guardrails","Multilingual support"}', '{"Hugging Face","AWS Bedrock","Azure","Google Cloud"}', 'https://docs.mistral.ai', true, '{"Developers wanting open models","European data sovereignty","Cost-conscious teams"}', '{"Non-technical users wanting plug-and-play"}', 'Leading open-weight model provider with excellent price-to-performance ratio; strong choice for teams that want to self-host.', now()),
('Cohere', 'cohere', 'Enterprise AI platform for language understanding', 'Cohere provides enterprise-grade language AI with models specialized for search, retrieval-augmented generation, and text classification. Known for strong multilingual capabilities and data privacy controls.', 'https://cohere.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Trial API access","Rate limited"]},{"plan":"Production","price":"Usage-based","features":["Higher limits","SLA","Fine-tuning"]},{"plan":"Enterprise","price":"Custom","features":["Private deployment","Custom models"]}]', 'intermediate', true, '{web,api}', '{"RAG pipelines","Semantic search","Text classification","Reranking","Embeddings","Fine-tuning","Multilingual support"}', '{"AWS","Google Cloud","Azure","Elasticsearch","Pinecone"}', 'https://docs.cohere.com', true, '{"Enterprise search teams","RAG application developers","Multilingual organizations"}', '{"Consumer chatbot builders"}', 'Purpose-built for enterprise search and RAG with excellent multilingual embeddings; not designed for general-purpose chat.', now()),
('AI21 Labs', 'ai21-labs', 'Advanced language models with contextual understanding', 'AI21 Labs develops Jamba, a powerful hybrid SSM-Transformer model, alongside specialized APIs for paraphrasing, summarization, and text improvements. Known for long-context efficiency and enterprise reliability.', 'https://ai21.com', 'freemium', '[{"plan":"Free","price":"$0","features":["API trial","Limited requests"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["All models","Higher limits"]},{"plan":"Enterprise","price":"Custom","features":["SLA","Custom deployment"]}]', 'intermediate', true, '{web,api}', '{"Jamba model","Long context","Task-specific APIs","Paraphrasing","Summarization","Text improvements","RAG support"}', '{"AWS Bedrock","Azure","Google Cloud","LangChain"}', 'https://docs.ai21.com', true, '{"Enterprise NLP teams","Developers needing task-specific APIs","Long-document processing"}', '{"Casual users wanting a chatbot"}', 'Solid enterprise LLM provider with unique hybrid architecture; task-specific APIs are a standout differentiator.', now()),
('Together AI', 'together-ai', 'Fast inference platform for open-source models', 'Together AI provides a cloud platform for running, fine-tuning, and deploying open-source AI models at high speed. Offers 100+ models including Llama, Mistral, and StableDiffusion with industry-leading inference throughput.', 'https://together.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["$5 free credits"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["100+ models","Fine-tuning","Dedicated instances"]}]', 'intermediate', true, '{web,api}', '{"100+ open models","Fast inference","Fine-tuning","Dedicated GPUs","Serverless endpoints","JSON mode","Function calling"}', '{"LangChain","LlamaIndex","Hugging Face","OpenAI-compatible API"}', 'https://docs.together.ai', true, '{"Developers using open-source models","Startups optimizing inference costs","ML teams needing fine-tuning"}', '{"Non-technical users"}', 'One of the fastest inference platforms for open-source models with a generous free tier; great OpenAI-compatible API.', now()),
('Groq', 'groq', 'Ultra-fast AI inference with custom LPU hardware', 'Groq builds custom Language Processing Units (LPUs) that deliver the fastest inference speeds available, often 10x faster than GPU-based solutions. Supports popular open-source models via a simple API.', 'https://groq.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Rate-limited access","Popular models"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["Higher limits","All models","Priority"]}]', 'intermediate', true, '{web,api}', '{"Ultra-fast inference","Custom LPU chips","OpenAI-compatible API","Open-source models","Low latency","JSON mode","Tool use"}', '{"LangChain","LlamaIndex","Vercel AI SDK","OpenAI SDK"}', 'https://console.groq.com/docs', true, '{"Developers needing fast inference","Real-time AI applications","Latency-sensitive products"}', '{"Teams needing fine-tuning capabilities"}', 'Unmatched inference speed thanks to custom hardware; the free tier is remarkably fast and generous for prototyping.', now()),
('Fireworks AI', 'fireworks-ai', 'Production-grade inference for generative AI models', 'Fireworks AI offers a fast, reliable inference platform optimized for production workloads. Supports open-source LLMs, image models, and embeddings with features like function calling, JSON mode, and grammar-based generation.', 'https://fireworks.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["600 RPM","Starter credits"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["Higher limits","All models"]},{"plan":"Enterprise","price":"Custom","features":["Dedicated GPUs","SLA","On-prem"]}]', 'intermediate', true, '{web,api}', '{"Fast inference","Open-source models","Function calling","JSON mode","Grammar mode","Image generation","Embeddings","Fine-tuning"}', '{"LangChain","LlamaIndex","OpenAI SDK","Vercel AI SDK"}', 'https://docs.fireworks.ai', true, '{"Production AI applications","Developers needing reliable inference","Teams wanting model variety"}', '{"Non-technical users"}', 'Strong production inference platform with excellent uptime and competitive pricing; grammar mode is a unique advantage.', now()),
('Replicate', 'replicate', 'Run open-source AI models in the cloud with one line of code', 'Replicate makes it easy to run open-source machine learning models in the cloud. Push your own models or run thousands of community models covering text, image, video, and audio generation with a simple API.', 'https://replicate.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Some free model runs"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["All models","Custom models","Webhooks"]}]', 'intermediate', true, '{web,api}', '{"Thousands of models","Custom model deployment","Cog containers","Webhooks","Streaming","Fine-tuning","GPU scaling","Version control"}', '{"Zapier","Make","Vercel","GitHub Actions","LangChain"}', 'https://replicate.com/docs', true, '{"Developers wanting easy model deployment","Prototypers testing AI models","Teams without ML infrastructure"}', '{"High-volume production needing cost optimization"}', 'The easiest way to run open-source models; perfect for prototyping but per-prediction pricing adds up at scale.', now()),
('Modal', 'modal', 'Serverless cloud for AI and data-intensive applications', 'Modal provides serverless GPU infrastructure for running AI workloads. Define your environment in Python, and Modal handles containers, GPUs, scaling, and caching. Popular for fine-tuning, batch inference, and data pipelines.', 'https://modal.com', 'freemium', '[{"plan":"Free","price":"$0","features":["$30/month free credits"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["All GPUs","Unlimited concurrency","Secrets management"]}]', 'advanced', true, '{web,api,cli}', '{"Serverless GPU","Python-native","Auto-scaling","Container caching","Secrets management","Scheduled jobs","Web endpoints","Volume storage"}', '{"Hugging Face","Weights & Biases","GitHub","Python ecosystem"}', 'https://modal.com/docs', true, '{"ML engineers running training jobs","Developers building AI pipelines","Teams wanting serverless GPUs"}', '{"Non-Python developers","No-code users"}', 'Elegant developer experience for serverless GPU computing; the Python-native approach eliminates Docker complexity.', now()),
('Anyscale', 'anyscale', 'Production platform for scalable AI built on Ray', 'Anyscale provides a managed platform for Ray, the open-source framework for distributed computing. Scale AI workloads from training to serving with production-grade infrastructure and monitoring.', 'https://anyscale.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Community Ray","Basic support"]},{"plan":"Enterprise","price":"Custom","features":["Managed Ray","SLA","Priority support","Monitoring"]}]', 'advanced', true, '{web,api,cli}', '{"Managed Ray","Distributed training","Model serving","Auto-scaling","Monitoring","Ray Serve","Ray Train","GPU orchestration"}', '{"AWS","GCP","Azure","Hugging Face","PyTorch","TensorFlow"}', 'https://docs.anyscale.com', true, '{"ML teams scaling distributed workloads","Companies using Ray","Large-scale training operations"}', '{"Small teams with simple inference needs"}', 'The definitive platform for Ray-based distributed AI; essential for teams already invested in the Ray ecosystem.', now()),
('OctoAI', 'octoai', 'Efficient AI inference for generative models', 'OctoAI provides optimized inference infrastructure for running generative AI models efficiently. Offers pre-optimized endpoints for popular models with automatic batching, quantization, and hardware selection.', 'https://octoai.cloud', 'freemium', '[{"plan":"Free","price":"$0","features":["Free trial credits"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["All models","Higher limits"]},{"plan":"Enterprise","price":"Custom","features":["Dedicated endpoints","SLA"]}]', 'intermediate', true, '{web,api}', '{"Optimized inference","Auto-batching","Quantization","Image generation","Text generation","Embeddings","Fine-tuning","Asset orchestration"}', '{"Hugging Face","LangChain","OpenAI-compatible API","Vercel"}', 'https://docs.octoai.cloud', true, '{"Teams optimizing inference costs","Image generation at scale","Production AI applications"}', '{"Developers wanting to self-host"}', 'Excellent inference optimization with competitive pricing; particularly strong for image generation workloads.', now()),
('Cerebras', 'cerebras', 'Wafer-scale AI compute for fastest model inference', 'Cerebras builds the world''s largest AI chip (wafer-scale engine) enabling record-breaking training and inference speeds. Their cloud API provides instant access to fast inference for popular open-source models.', 'https://cerebras.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Rate-limited API access"]},{"plan":"Pay-as-you-go","price":"Usage-based","features":["Higher throughput","Priority access"]}]', 'intermediate', true, '{web,api}', '{"Wafer-scale compute","Fastest inference","Open-source models","OpenAI-compatible API","Low latency","High throughput"}', '{"OpenAI SDK","LangChain","LlamaIndex"}', 'https://docs.cerebras.ai', true, '{"Developers needing maximum speed","Real-time AI applications","Researchers pushing model limits"}', '{"Budget-conscious small projects"}', 'Pushing the boundaries of AI hardware with wafer-scale chips; inference speed is genuinely remarkable.', now()),
('DeepSeek', 'deepseek', 'High-performance open-source AI models from China', 'DeepSeek develops powerful open-source language models including DeepSeek-V2 and DeepSeek Coder. Known for strong reasoning and coding capabilities that rival proprietary models at a fraction of the cost.', 'https://deepseek.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Web chat","Basic access"]},{"plan":"API","price":"Usage-based","features":["All models","High rate limits"]}]', 'intermediate', true, '{web,api}', '{"Open-source models","Strong reasoning","Code generation","Math capabilities","Long context","MoE architecture","Low-cost inference"}', '{"Hugging Face","OpenAI-compatible API","LangChain","Ollama"}', 'https://platform.deepseek.com/docs', true, '{"Developers wanting powerful open models","Cost-conscious AI teams","Coding assistant builders"}', '{"Teams requiring US-based data residency"}', 'Remarkably capable open-source models that punch well above their weight; pricing is extremely competitive.', now()),
('Yi', 'yi-ai', 'Bilingual large language models by 01.AI', 'Yi is a series of bilingual (English-Chinese) language models from 01.AI, founded by AI pioneer Kai-Fu Lee. Models range from 6B to 34B parameters with strong performance on benchmarks and practical tasks.', 'https://01.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Open-source models","Community support"]},{"plan":"API","price":"Usage-based","features":["Managed inference","Higher limits"]}]', 'intermediate', true, '{web,api}', '{"Bilingual models","Long context","Code generation","Vision capabilities","Open-source","Multiple model sizes","Fine-tuning support"}', '{"Hugging Face","LangChain","Ollama","vLLM"}', 'https://platform.01.ai/docs', true, '{"Bilingual English-Chinese applications","Developers needing open models","Research teams"}', '{"Users needing only English language support"}', 'Strong bilingual models with competitive benchmark scores; excellent choice for Chinese-English use cases.', now()),
('Zhipu AI', 'zhipu-ai', 'Chinese AI platform with GLM series models', 'Zhipu AI develops the GLM (General Language Model) series, powering ChatGLM and other applications. Offers multimodal capabilities including text, image, and video generation for the Chinese market and beyond.', 'https://zhipuai.cn', 'freemium', '[{"plan":"Free","price":"$0","features":["Limited chat access"]},{"plan":"API","price":"Usage-based","features":["All models","Higher limits","Fine-tuning"]}]', 'intermediate', true, '{web,api}', '{"GLM models","Multimodal AI","Chinese language strength","Code generation","Image understanding","Video generation","Agent capabilities"}', '{"Hugging Face","LangChain","Chinese cloud platforms"}', 'https://open.bigmodel.cn/dev/howuse/introduction', true, '{"Chinese market AI applications","Multilingual teams","Researchers studying Chinese LLMs"}', '{"Teams needing primarily English models"}', 'Leading Chinese AI model provider with strong multimodal capabilities; best suited for Chinese-language applications.', now())
ON CONFLICT (slug) DO NOTHING;

-- ─── NO-CODE / LOW-CODE AI ──────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Softr', 'softr', 'Build client portals and internal tools from Airtable', 'Softr turns your Airtable or Google Sheets data into professional web apps, client portals, and internal tools without code. Features pre-built blocks, user authentication, and conditional visibility.', 'https://softr.io', 'freemium', '[{"plan":"Free","price":"$0","features":["1 app","softr.io domain"]},{"plan":"Basic","price":"$49/mo","features":["Custom domain","5 internal users"]},{"plan":"Professional","price":"$139/mo","features":["Unlimited users","API access"]}]', 'beginner', true, '{web,api}', '{"Airtable integration","Pre-built blocks","User authentication","Conditional visibility","Custom domains","Stripe payments","Charts","List/detail views"}', '{"Airtable","Google Sheets","Stripe","Zapier","Make"}', 'https://docs.softr.io', true, '{"Small businesses building portals","Airtable power users","Non-technical founders"}', '{"Complex application development"}', 'The fastest way to turn Airtable data into a polished web app; limited if you outgrow Airtable as your backend.', now()),
('AppSheet', 'appsheet', 'Google''s no-code app platform for business', 'AppSheet, now part of Google Cloud, lets anyone build mobile and web apps from spreadsheets and databases without code. Features AI-powered data extraction, predictive models, and deep Google Workspace integration.', 'https://about.appsheet.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Personal use","10 users"]},{"plan":"Starter","price":"$5/user/mo","features":["Basic apps","Google integration"]},{"plan":"Core","price":"$10/user/mo","features":["AI features","Automation"]}]', 'beginner', true, '{web,mobile,api}', '{"Spreadsheet-to-app","AI predictions","OCR data capture","Offline support","Barcode scanning","GPS tracking","Automation bots","Google Workspace integration"}', '{"Google Sheets","Google Drive","Salesforce","SQL databases","Zapier"}', 'https://support.google.com/appsheet', true, '{"Google Workspace organizations","Field workers needing mobile apps","Small business automation"}', '{"Consumer-facing app development"}', 'Excellent for internal business apps within Google ecosystem; AI features like predictions and OCR add real value.', now()),
('Retool', 'retool', 'Build internal tools remarkably fast', 'Retool is a low-code platform for building internal tools like admin panels, dashboards, and CRUD apps. Connect to any database or API, drag and drop UI components, and write JavaScript for custom logic.', 'https://retool.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 users","Unlimited apps"]},{"plan":"Team","price":"$10/user/mo","features":["Custom branding","Version history"]},{"plan":"Business","price":"$50/user/mo","features":["SSO","Audit logs","Environments"]}]', 'intermediate', true, '{web,api}', '{"Drag-and-drop builder","Database connectors","REST/GraphQL APIs","JavaScript customization","Version control","Workflows","Mobile apps","AI integration"}', '{"PostgreSQL","MySQL","MongoDB","Stripe","Twilio","Slack","Salesforce","Firebase"}', 'https://docs.retool.com', true, '{"Engineering teams building internal tools","Startups needing admin panels","Data teams building dashboards"}', '{"Customer-facing products","Non-technical users"}', 'The gold standard for internal tool building; saves weeks of development time but requires some technical knowledge.', now()),
('Internal.io', 'internal-io', 'Build internal tools on top of your databases', 'Internal.io lets you quickly build admin panels, dashboards, and workflows on top of your existing databases and APIs. Features a visual builder with pre-built components optimized for common internal tool patterns.', 'https://internal.io', 'freemium', '[{"plan":"Free","price":"$0","features":["3 users","Basic features"]},{"plan":"Pro","price":"$20/user/mo","features":["Unlimited users","Custom branding"]},{"plan":"Enterprise","price":"Custom","features":["SSO","Audit logs"]}]', 'intermediate', true, '{web,api}', '{"Database connectors","Visual builder","CRUD operations","Role-based access","Dashboards","Workflows","API integration","Audit logs"}', '{"PostgreSQL","MySQL","MongoDB","REST APIs","Stripe"}', 'https://docs.internal.io', true, '{"Teams needing quick admin panels","Database-heavy operations","Support teams"}', '{"Consumer-facing apps"}', 'Solid Retool alternative with a gentler learning curve; best for teams that need database-connected admin panels fast.', now()),
('Budibase', 'budibase', 'Open-source low-code platform for internal tools', 'Budibase is an open-source low-code platform for building internal apps, admin panels, and workflows. Self-host or use cloud, connect to databases and APIs, and build with drag-and-drop components.', 'https://budibase.com', 'freemium', '[{"plan":"Free","price":"$0","features":["5 users","Unlimited apps","Self-host"]},{"plan":"Premium","price":"$50/mo","features":["Custom branding","SSO","Backups"]},{"plan":"Enterprise","price":"Custom","features":["Air-gapped","Audit logs"]}]', 'intermediate', true, '{web,api,cli}', '{"Open-source","Self-hostable","Database connectors","REST/GraphQL","Drag-and-drop","Automation","Role-based access","Custom plugins"}', '{"PostgreSQL","MySQL","MongoDB","REST APIs","S3","Airtable"}', 'https://docs.budibase.com', true, '{"Teams wanting self-hosted solutions","Open-source advocates","Budget-conscious organizations"}', '{"Non-technical users"}', 'Best open-source alternative to Retool; self-hosting option makes it ideal for data-sensitive organizations.', now()),
('Appsmith', 'appsmith', 'Open-source framework for building internal tools', 'Appsmith is an open-source platform for building admin panels, CRUD apps, and dashboards. Connect to 25+ databases and APIs, build UI with 45+ widgets, and write custom JS anywhere in the app.', 'https://appsmith.com', 'freemium', '[{"plan":"Community","price":"$0","features":["Unlimited apps","Self-host","All connectors"]},{"plan":"Business","price":"$40/user/mo","features":["SSO","Audit logs","Git sync"]},{"plan":"Enterprise","price":"Custom","features":["Air-gapped","Priority support"]}]', 'intermediate', true, '{web,api,cli}', '{"Open-source","45+ widgets","25+ database connectors","JavaScript everywhere","Git sync","Role-based access","Themes","Auto-generated UI"}', '{"PostgreSQL","MySQL","MongoDB","Elasticsearch","Redis","S3","Slack","Twilio"}', 'https://docs.appsmith.com', true, '{"Developer teams building internal tools","Open-source-first organizations","Self-hosted requirements"}', '{"Non-technical builders","Consumer apps"}', 'Excellent open-source internal tool builder with strong community; the JS-everywhere approach gives developers maximum flexibility.', now())
ON CONFLICT (slug) DO NOTHING;

-- ─── AI FOR SALES ───────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Apollo.io', 'apollo-io', 'All-in-one sales intelligence and engagement platform', 'Apollo.io combines a database of 270M+ contacts with email sequencing, calling, and AI-powered engagement tools. AI helps write personalized emails, score leads, and optimize outreach timing.', 'https://apollo.io', 'freemium', '[{"plan":"Free","price":"$0","features":["250 emails/day","Basic filters"]},{"plan":"Basic","price":"$49/mo","features":["Unlimited emails","Advanced filters"]},{"plan":"Professional","price":"$79/mo","features":["AI writing","Dialer","Workflows"]}]', 'beginner', true, '{web,api}', '{"270M+ contacts","Email sequencing","AI email writing","Lead scoring","Dialer","Intent data","Data enrichment","Workflow automation"}', '{"Salesforce","HubSpot","Outreach","Zapier","LinkedIn","Gmail","Outlook"}', 'https://apolloio.github.io/apollo-api-docs', true, '{"SDRs and sales teams","B2B lead generation","Startups building pipelines"}', '{"B2C sales teams","Enterprise accounts only"}', 'Best value in sales intelligence with a massive contact database; the free tier is unusually generous for prospecting.', now()),
('Outreach', 'outreach', 'AI-powered sales execution platform', 'Outreach is a leading sales engagement platform that uses AI to optimize sequences, predict deal outcomes, and coach reps. Manages the full sales cycle from prospecting to deal management and forecasting.', 'https://outreach.io', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Full platform","AI features","Forecasting","Coaching"]}]', 'intermediate', true, '{web,api}', '{"AI sequence optimization","Deal intelligence","Revenue forecasting","Sales coaching","Email tracking","Dialer","Meeting scheduler","Sentiment analysis"}', '{"Salesforce","Microsoft Dynamics","HubSpot","LinkedIn","Gmail","Outlook","Zoom"}', 'https://api.outreach.io/api/v2/docs', true, '{"Enterprise sales teams","Revenue operations","Sales managers"}', '{"Solo entrepreneurs","Small teams under 10 reps"}', 'Enterprise-grade sales engagement with genuinely useful AI coaching; the price tag matches the sophistication.', now()),
('Salesloft', 'salesloft', 'AI-driven revenue workflow platform', 'Salesloft provides a comprehensive revenue platform with AI-powered cadences, conversation intelligence, deal management, and forecasting. Helps sales teams execute consistent, data-driven outreach at scale.', 'https://salesloft.com', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Cadences","Conversations","Deals","Forecasting"]}]', 'intermediate', true, '{web,api}', '{"AI cadences","Conversation intelligence","Deal management","Forecasting","Email tracking","Dialer","Analytics","Coaching"}', '{"Salesforce","HubSpot","Microsoft Dynamics","LinkedIn","Outlook","Zoom","Slack"}', 'https://developers.salesloft.com', true, '{"Mid-market to enterprise sales teams","Revenue leaders","Sales operations"}', '{"Very small teams","Non-sales use cases"}', 'Direct Outreach competitor with strong conversation intelligence; choose based on which CRM integration matters most.', now()),
('Lemlist', 'lemlist', 'AI-powered cold outreach with personalization at scale', 'Lemlist specializes in personalized cold email campaigns with AI-generated personalized images, landing pages, and copy. Features deliverability tools, multichannel sequences, and a B2B lead database.', 'https://lemlist.com', 'paid', '[{"plan":"Email Starter","price":"$39/mo","features":["Unlimited campaigns","AI writer"]},{"plan":"Email Pro","price":"$69/mo","features":["Warm-up","CRM integration"]},{"plan":"Multichannel","price":"$99/mo","features":["LinkedIn automation","Calls"]}]', 'beginner', true, '{web,api}', '{"Personalized images","AI copywriting","Email warm-up","Multichannel sequences","Lead database","Landing pages","Deliverability tools","A/B testing"}', '{"Salesforce","HubSpot","Pipedrive","Zapier","Slack","LinkedIn"}', 'https://help.lemlist.com', true, '{"Cold email specialists","Agencies running outreach","Growth hackers"}', '{"Warm lead nurturing","Enterprise sales teams"}', 'King of personalized cold outreach with clever image personalization; deliverability tools are a real differentiator.', now()),
('Instantly', 'instantly-ai', 'Scale cold email outreach with unlimited accounts', 'Instantly lets you connect unlimited email accounts and send thousands of cold emails daily with automated warm-up. AI helps write and optimize email sequences, while smart rotation prevents deliverability issues.', 'https://instantly.ai', 'paid', '[{"plan":"Growth","price":"$30/mo","features":["1000 leads","5000 emails/mo"]},{"plan":"Hypergrowth","price":"$77.6/mo","features":["25000 leads","75000 emails/mo"]},{"plan":"Light Speed","price":"$286.3/mo","features":["500000 emails/mo","100000 leads"]}]', 'beginner', true, '{web,api}', '{"Unlimited email accounts","Auto warm-up","AI sequence writer","Smart sending","Lead database","A/B testing","Analytics","Unibox inbox"}', '{"Zapier","HubSpot","Pipedrive","Webhooks","Slack"}', 'https://instantly.ai/help', true, '{"High-volume cold emailers","Agencies","Lead generation teams"}', '{"Relationship-based selling","Enterprise deals"}', 'Best for pure volume cold email at an aggressive price point; the unlimited accounts model is a game-changer.', now()),
('Smartlead', 'smartlead', 'Cold email infrastructure for agencies and teams', 'Smartlead provides cold email infrastructure with unlimited mailboxes, auto warm-up, and unified inbox. Built specifically for agencies managing multiple clients and high-volume outreach campaigns.', 'https://smartlead.ai', 'paid', '[{"plan":"Basic","price":"$39/mo","features":["2000 active leads","6000 emails/mo"]},{"plan":"Pro","price":"$94/mo","features":["30000 leads","150000 emails/mo"]},{"plan":"Custom","price":"$174/mo","features":["Unlimited leads","Custom limits"]}]', 'beginner', true, '{web,api}', '{"Unlimited mailboxes","Auto warm-up","Unified inbox","Sub-sequences","Webhook triggers","White-label","API access","Lead rotation"}', '{"Zapier","HubSpot","Salesforce","Clay","Webhooks"}', 'https://help.smartlead.ai', true, '{"Cold email agencies","High-volume senders","Lead gen businesses"}', '{"Warm outreach","Small-scale personal outreach"}', 'Agency-focused cold email platform with excellent white-label options; a strong Instantly competitor with better agency features.', now()),
('Lavender', 'lavender', 'AI email coach that helps you write better sales emails', 'Lavender analyzes your sales emails in real-time and provides AI coaching to improve open and reply rates. Scores emails, suggests improvements, generates personalized openers, and provides recipient intelligence.', 'https://lavender.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["5 emails/mo","Basic scoring"]},{"plan":"Starter","price":"$29/mo","features":["Unlimited emails","Full coaching"]},{"plan":"Team","price":"$49/user/mo","features":["Team analytics","Manager dashboard"]}]', 'beginner', false, '{web,plugin}', '{"Email scoring","AI coaching","Personalized openers","Recipient intelligence","GIF integration","Team analytics","Gmail/Outlook plugin","Mobile optimization check"}', '{"Gmail","Outlook","Salesloft","Outreach","HubSpot","LinkedIn"}', 'https://lavender.ai/resources', true, '{"SDRs improving reply rates","Sales teams standardizing quality","Email-heavy sellers"}', '{"Automated mass email campaigns"}', 'Genuinely improves email quality with real-time coaching; the email scoring creates a helpful feedback loop for reps.', now()),
('Regie.ai', 'regie-ai', 'AI-powered content and outreach for sales teams', 'Regie.ai uses AI to generate personalized sales sequences, social posts, and prospect research. Auto-pilots prospecting by identifying intent signals and generating relevant outreach for each buyer.', 'https://regie.ai', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["AI sequences","Auto-pilot prospecting","Intent signals","Analytics"]}]', 'intermediate', true, '{web,api}', '{"AI sequence generation","Auto-pilot prospecting","Intent signals","Personalized outreach","Content generation","Social selling","Analytics","A/B testing"}', '{"Salesforce","Outreach","Salesloft","HubSpot","LinkedIn","6sense"}', 'https://regie.ai', true, '{"Enterprise sales organizations","Account-based selling teams","Revenue operations"}', '{"Solo founders","Very small teams"}', 'Ambitious auto-pilot approach to prospecting; most valuable when paired with intent data from 6sense or similar.', now()),
('Clari', 'clari', 'AI-powered revenue intelligence platform', 'Clari captures and analyzes signals across the entire revenue process to provide AI-driven forecasting, pipeline management, and deal inspection. Helps revenue teams identify risk and opportunity in every deal.', 'https://clari.com', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Forecasting","Pipeline management","Deal inspection","Revenue intelligence"]}]', 'intermediate', true, '{web,api}', '{"AI forecasting","Pipeline management","Deal inspection","Revenue intelligence","Activity capture","Mutual action plans","Analytics","CRM hygiene"}', '{"Salesforce","HubSpot","Microsoft Dynamics","Outlook","Gmail","Slack","Zoom"}', 'https://clari.com', true, '{"VP Sales and CROs","Revenue operations teams","Enterprise sales organizations"}', '{"Small sales teams","Non-sales forecasting"}', 'The best revenue forecasting tool available; genuinely reduces forecast error by capturing signals reps forget to log.', now()),
('People.ai', 'people-ai', 'AI revenue intelligence from activity data', 'People.ai automatically captures sales activity data from emails, calls, and meetings to provide AI-driven insights about pipeline health, rep productivity, and buyer engagement. Eliminates manual CRM data entry.', 'https://people.ai', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Activity capture","Revenue intelligence","Coaching","Analytics"]}]', 'intermediate', true, '{web,api}', '{"Automatic activity capture","Revenue intelligence","Rep productivity","Buyer engagement scoring","Account mapping","Coaching insights","CRM enrichment","Pipeline analytics"}', '{"Salesforce","Microsoft Dynamics","Outreach","Salesloft","Gmail","Outlook","Zoom"}', 'https://people.ai', true, '{"Enterprise revenue teams","Sales operations","VP Sales tracking productivity"}', '{"SMB sales teams","Non-sales departments"}', 'Eliminates CRM data entry by auto-capturing activities; the engagement scoring helps identify deals going cold.', now())
ON CONFLICT (slug) DO NOTHING;

-- ─── E-COMMERCE AI ──────────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Shopify Magic', 'shopify-magic', 'AI-powered tools built into Shopify', 'Shopify Magic brings AI directly into the Shopify platform with features like AI product descriptions, AI image editing, Sidekick AI assistant, and AI-generated marketing content — all free for Shopify merchants.', 'https://shopify.com/magic', 'freemium', '[{"plan":"Included","price":"$0","features":["Included with any Shopify plan","AI descriptions","Sidekick assistant"]}]', 'beginner', false, '{web}', '{"AI product descriptions","Background removal","Sidekick assistant","Email generation","Blog writing","SEO suggestions","Image editing","FAQ generation"}', '{"Shopify","Shopify POS","Shopify Email","Shopify Inbox"}', 'https://help.shopify.com/en/manual/shopify-magic', true, '{"Shopify merchants","E-commerce store owners","Small business owners"}', '{"Non-Shopify stores","Enterprise custom platforms"}', 'Genuinely useful AI built right into Shopify at no extra cost; Sidekick assistant saves hours on store management tasks.', now()),
('Nosto', 'nosto', 'AI-powered personalization for e-commerce', 'Nosto uses AI to deliver personalized product recommendations, content, and merchandising across e-commerce stores. Analyzes shopper behavior in real-time to optimize every touchpoint and increase conversions.', 'https://nosto.com', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Product recommendations","Personalized content","A/B testing","Analytics"]}]', 'intermediate', true, '{web,api}', '{"Product recommendations","Behavioral targeting","Dynamic bundles","Category merchandising","Pop-ups","A/B testing","Email personalization","UGC integration"}', '{"Shopify","Magento","BigCommerce","Klaviyo","Yotpo","Trustpilot"}', 'https://docs.nosto.com', true, '{"Mid-market e-commerce stores","Merchandising teams","CRO specialists"}', '{"Very small stores","Non-e-commerce sites"}', 'Sophisticated personalization engine that demonstrably lifts conversion rates; ROI usually justifies the enterprise pricing.', now()),
('Dynamic Yield', 'dynamic-yield', 'AI personalization and experience optimization', 'Dynamic Yield, a Mastercard company, provides AI-powered personalization across web, mobile, email, and kiosks. Features predictive targeting, product recommendations, and A/B testing for enterprise retailers and brands.', 'https://dynamicyield.com', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Full personalization suite","Predictive targeting","Recommendations"]}]', 'advanced', true, '{web,mobile,api}', '{"Predictive targeting","Product recommendations","A/B testing","Dynamic content","Email personalization","Audience management","Experience APIs","Server-side testing"}', '{"Shopify","Salesforce","Adobe Commerce","Tealium","Segment","Braze"}', 'https://support.dynamicyield.com', true, '{"Enterprise retailers","Omnichannel brands","Digital experience teams"}', '{"Small businesses","Budget-conscious startups"}', 'Enterprise-grade personalization with deep ML capabilities; the Mastercard backing adds financial data insights.', now()),
('Algolia', 'algolia', 'AI-powered search and discovery platform', 'Algolia provides lightning-fast, AI-powered search and recommendation APIs for websites and apps. Features include typo tolerance, faceted search, AI re-ranking, and personalized recommendations used by 17,000+ companies.', 'https://algolia.com', 'freemium', '[{"plan":"Free","price":"$0","features":["10K requests/mo","1M records"]},{"plan":"Grow","price":"Usage-based","features":["$0.50/1K requests"]},{"plan":"Premium","price":"Custom","features":["AI features","SLA","Support"]}]', 'intermediate', true, '{web,api}', '{"Instant search","AI re-ranking","Typo tolerance","Faceted search","Personalization","Recommendations","Analytics","A/B testing"}', '{"Shopify","Magento","WordPress","React","Vue","Salesforce Commerce","Contentful"}', 'https://algolia.com/doc', true, '{"E-commerce search","Content-heavy websites","Developers building search UIs"}', '{"Simple sites with few pages"}', 'The gold standard for search-as-a-service with incredible speed; AI re-ranking and recommendations justify the premium.', now()),
('Klevu', 'klevu', 'AI search and merchandising for e-commerce', 'Klevu provides AI-powered search, product recommendations, and smart merchandising for e-commerce stores. Uses NLP to understand shopper intent and automatically optimizes results based on revenue performance.', 'https://klevu.com', 'contact', '[{"plan":"Enterprise","price":"Custom","features":["Smart search","Recommendations","Merchandising","Analytics"]}]', 'intermediate', true, '{web,api}', '{"AI search","NLP understanding","Smart merchandising","Product recommendations","Visual merchandising","Analytics","Personalization","Category navigation"}', '{"Shopify","Magento","BigCommerce","Salesforce Commerce","Hydrogen"}', 'https://docs.klevu.com', true, '{"E-commerce merchandisers","Online retailers","Search optimization teams"}', '{"Non-e-commerce search needs"}', 'Strong Algolia alternative specifically optimized for e-commerce; revenue-based optimization is a practical differentiator.', now()),
('Yotpo', 'yotpo', 'AI-powered e-commerce retention marketing platform', 'Yotpo provides a retention marketing platform with AI-powered reviews, loyalty programs, SMS marketing, email, and subscriptions. Uses AI to collect and display UGC that drives purchase decisions.', 'https://yotpo.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Basic reviews","Photos"]},{"plan":"Growth","price":"$15/mo","features":["Review request flows","Rich snippets"]},{"plan":"Prime","price":"$119/mo","features":["Full platform","AI insights"]}]', 'beginner', true, '{web,api}', '{"AI review collection","Loyalty programs","SMS marketing","Email marketing","Subscriptions","Visual UGC","Smart filters","Review insights"}', '{"Shopify","BigCommerce","Magento","Salesforce Commerce","Klaviyo","Gorgias"}', 'https://developers.yotpo.com', true, '{"Shopify stores wanting reviews","DTC brands building loyalty","E-commerce marketers"}', '{"Non-e-commerce businesses"}', 'Comprehensive retention suite anchored by best-in-class review collection; the all-in-one approach reduces tool sprawl.', now()),
('Gorgias', 'gorgias', 'AI-powered helpdesk built for e-commerce', 'Gorgias is a customer support helpdesk designed specifically for e-commerce. AI automates responses, suggests macros, and pulls in order data so agents can resolve tickets faster with full customer context.', 'https://gorgias.com', 'paid', '[{"plan":"Starter","price":"$10/mo","features":["50 tickets/mo","3 agents"]},{"plan":"Basic","price":"$60/mo","features":["300 tickets/mo","Unlimited agents"]},{"plan":"Pro","price":"$360/mo","features":["2000 tickets/mo","Revenue stats"]}]', 'beginner', true, '{web,api}', '{"AI auto-responses","Order management","Macro suggestions","Revenue tracking","Multi-channel","Self-service","Intent detection","Sentiment analysis"}', '{"Shopify","BigCommerce","Magento","Klaviyo","Yotpo","Instagram","Facebook"}', 'https://docs.gorgias.com', true, '{"E-commerce support teams","Shopify stores","DTC brands scaling support"}', '{"Non-e-commerce customer support"}', 'Purpose-built for e-commerce support with deep Shopify integration; AI automation handles repetitive order inquiries well.', now()),
('Privy', 'privy', 'AI-powered email and pop-ups for e-commerce growth', 'Privy helps small e-commerce brands grow their email list and sales with AI-optimized pop-ups, email campaigns, and SMS. Easy to use with templates designed for Shopify stores and DTC brands.', 'https://privy.com', 'freemium', '[{"plan":"Free","price":"$0","features":["100 email contacts","Pop-ups"]},{"plan":"Starter","price":"$30/mo","features":["1500 contacts","Email campaigns"]},{"plan":"Growth","price":"$45/mo","features":["SMS","Advanced targeting"]}]', 'beginner', false, '{web}', '{"Pop-ups","Email campaigns","SMS marketing","Cart saver","Welcome series","Spin-to-win","Exit intent","A/B testing"}', '{"Shopify","BigCommerce","Wix","Squarespace","Klaviyo","Mailchimp"}', 'https://privy.helpscoutdocs.com', true, '{"Small Shopify stores","DTC brands starting email marketing","Non-technical merchants"}', '{"Large enterprises","Advanced marketers"}', 'Simplest email/pop-up tool for small Shopify stores; limited compared to Klaviyo but much easier to set up.', now()),
('Octane AI', 'octane-ai', 'AI-powered quizzes and zero-party data for e-commerce', 'Octane AI helps e-commerce brands build product recommendation quizzes that collect zero-party data and personalize the shopping experience. Quizzes integrate with Klaviyo and Shopify for targeted marketing.', 'https://octaneai.com', 'paid', '[{"plan":"Octane","price":"$50/mo","features":["Quiz builder","Basic integrations"]},{"plan":"Octane Plus","price":"$200/mo","features":["Advanced logic","Deep Klaviyo sync","Custom CSS"]}]', 'beginner', false, '{web}', '{"Product quizzes","Zero-party data collection","Conditional logic","Personalized recommendations","Opt-in collection","Results pages","Analytics","Custom design"}', '{"Shopify","Klaviyo","Recharge","Zapier","Attentive"}', 'https://help.octaneai.com', true, '{"DTC brands with complex product lines","Shopify stores wanting personalization","Marketers collecting zero-party data"}', '{"Simple single-product stores"}', 'Excellent at converting browsers into buyers through guided quizzes; the Klaviyo integration makes the data actionable.', now()),
('Rebuy', 'rebuy', 'AI-powered personalization engine for Shopify', 'Rebuy uses AI to power smart product recommendations, dynamic bundles, checkout upsells, and post-purchase offers on Shopify stores. Processes millions of data points to maximize revenue per customer.', 'https://rebuyengine.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Up to 50 orders/mo"]},{"plan":"Starter","price":"$99/mo","features":["1000 orders/mo","All widgets"]},{"plan":"Scale","price":"$249/mo","features":["2500 orders/mo","A/B testing"]}]', 'beginner', true, '{web,api}', '{"AI recommendations","Dynamic bundles","Checkout upsells","Post-purchase offers","Smart cart","Reorder landing pages","A/B testing","Revenue analytics"}', '{"Shopify","Klaviyo","Recharge","Loop Returns","Stamped","Okendo"}', 'https://rebuyengine.com/docs', true, '{"Shopify Plus stores","DTC brands optimizing AOV","Growth-focused e-commerce teams"}', '{"Non-Shopify platforms","Very low traffic stores"}', 'Best-in-class Shopify upsell engine with measurable ROI; most stores see meaningful AOV increases within weeks.', now())
ON CONFLICT (slug) DO NOTHING;

-- ─── AI INFRASTRUCTURE ──────────────────────────────────────

INSERT INTO tools (name, slug, tagline, description, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, docs_url, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Weights & Biases', 'weights-and-biases', 'ML experiment tracking and model management platform', 'Weights & Biases (W&B) provides experiment tracking, model versioning, dataset management, and collaborative ML dashboards. The standard tool for ML teams to log, compare, and reproduce experiments.', 'https://wandb.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Personal projects","100GB storage"]},{"plan":"Teams","price":"$50/user/mo","features":["Unlimited projects","Reports","Service accounts"]},{"plan":"Enterprise","price":"Custom","features":["SSO","On-prem","Dedicated support"]}]', 'advanced', true, '{web,api,cli}', '{"Experiment tracking","Model versioning","Dataset management","Collaborative dashboards","Hyperparameter sweeps","Artifacts","Reports","Model registry"}', '{"PyTorch","TensorFlow","Keras","Hugging Face","LangChain","scikit-learn","XGBoost"}', 'https://docs.wandb.ai', true, '{"ML engineers tracking experiments","Research teams","MLOps teams"}', '{"Non-ML software teams"}', 'The undisputed leader in ML experiment tracking; virtually every serious ML team uses it. Free tier is generous enough for individuals.', now()),
('MLflow', 'mlflow', 'Open-source platform for the ML lifecycle', 'MLflow is an open-source platform for managing the end-to-end ML lifecycle including experiment tracking, model packaging, deployment, and registry. Created by Databricks and widely adopted across the industry.', 'https://mlflow.org', 'free', '[{"plan":"Open Source","price":"$0","features":["Full platform","Self-host","Community support"]},{"plan":"Databricks Managed","price":"Included","features":["Managed MLflow","Unity Catalog","Databricks integration"]}]', 'advanced', true, '{web,api,cli}', '{"Experiment tracking","Model registry","Model deployment","Pipeline management","LLM tracking","Open-source","REST API","UI dashboard"}', '{"Databricks","AWS SageMaker","Azure ML","PyTorch","TensorFlow","Spark","Delta Lake"}', 'https://mlflow.org/docs/latest', true, '{"MLOps teams wanting open-source","Databricks users","Data science teams"}', '{"Teams wanting managed-only solutions"}', 'The open-source standard for MLOps; pairs perfectly with Databricks but works well standalone. No vendor lock-in.', now()),
('Comet', 'comet-ml', 'ML experiment management and model production monitoring', 'Comet provides experiment tracking, model monitoring, and debugging tools for ML teams. Stands out with production model monitoring that detects data drift, performance degradation, and model failures in real-time.', 'https://comet.com', 'freemium', '[{"plan":"Free","price":"$0","features":["Personal projects","100 experiments"]},{"plan":"Teams","price":"$179/mo","features":["Unlimited experiments","Model monitoring"]},{"plan":"Enterprise","price":"Custom","features":["On-prem","SSO","Priority support"]}]', 'advanced', true, '{web,api,cli}', '{"Experiment tracking","Model monitoring","Data drift detection","Code tracking","Hyperparameter optimization","Panels","Reports","LLM tracing"}', '{"PyTorch","TensorFlow","Hugging Face","scikit-learn","Ray","Spark"}', 'https://comet.com/docs', true, '{"ML teams needing production monitoring","Data scientists","MLOps engineers"}', '{"Teams already committed to W&B"}', 'Strong W&B alternative with excellent production monitoring; the model monitoring capabilities are a genuine differentiator.', now()),
('Neptune.ai', 'neptune-ai', 'Metadata store for ML model building and management', 'Neptune.ai is a metadata store for MLOps that tracks experiments, models, and data. Designed for teams running many experiments in parallel with features for comparison, collaboration, and model lineage tracking.', 'https://neptune.ai', 'freemium', '[{"plan":"Free","price":"$0","features":["Individual use","200 hours tracking"]},{"plan":"Team","price":"$49/user/mo","features":["Unlimited tracking","Collaboration"]},{"plan":"Enterprise","price":"Custom","features":["SSO","On-prem","SLA"]}]', 'advanced', true, '{web,api,cli}', '{"Experiment tracking","Model registry","Metadata management","Collaboration","Custom dashboards","Query API","Integrations","Model lineage"}', '{"PyTorch","TensorFlow","Keras","XGBoost","LightGBM","Optuna","scikit-learn"}', 'https://docs.neptune.ai', true, '{"ML teams with many parallel experiments","Research labs","MLOps infrastructure teams"}', '{"Small projects with few experiments"}', 'Excellent for metadata-heavy ML workflows; the query API for accessing experiment data programmatically is a standout feature.', now()),
('DVC', 'dvc', 'Open-source version control for ML data and pipelines', 'DVC (Data Version Control) brings Git-like version control to ML data, models, and pipelines. Track large files, create reproducible pipelines, and manage experiments without leaving your Git workflow.', 'https://dvc.org', 'free', '[{"plan":"Open Source","price":"$0","features":["Full platform","Self-host","Community"]},{"plan":"DVC Studio","price":"$75/user/mo","features":["Visual dashboard","Collaboration","Model registry"]}]', 'advanced', true, '{cli,web,api}', '{"Data versioning","Pipeline management","Experiment tracking","Model registry","Git integration","Remote storage","Metrics tracking","Reproducibility"}', '{"Git","GitHub","GitLab","AWS S3","Google Cloud Storage","Azure Blob","HDFS"}', 'https://dvc.org/doc', true, '{"ML engineers wanting Git-native workflows","Teams versioning large datasets","Reproducibility-focused teams"}', '{"Non-technical data scientists","Teams wanting GUI-first tools"}', 'Essential tool for ML data versioning; if you use Git, DVC extends it naturally to handle large datasets and models.', now())
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- CATEGORY LINKS
-- ============================================================

-- AI Chatbots & LLM Platforms → code-development
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'gemini' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'gemini' AND c.slug = 'productivity';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mistral' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'cohere' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ai21-labs' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'together-ai' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'groq' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'fireworks-ai' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'replicate' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'modal' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'anyscale' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'octoai' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'cerebras' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'deepseek' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'yi-ai' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'zhipu-ai' AND c.slug = 'code-development';

-- No-Code/Low-Code → automation-agents, productivity
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'softr' AND c.slug = 'automation-agents';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'softr' AND c.slug = 'productivity';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'appsheet' AND c.slug = 'automation-agents';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'appsheet' AND c.slug = 'productivity';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'retool' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'retool' AND c.slug = 'automation-agents';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'internal-io' AND c.slug = 'automation-agents';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'budibase' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'budibase' AND c.slug = 'automation-agents';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'appsmith' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'appsmith' AND c.slug = 'automation-agents';

-- AI for Sales → marketing-seo, business-finance
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'apollo-io' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'apollo-io' AND c.slug = 'business-finance';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'outreach' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'salesloft' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'lemlist' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'instantly-ai' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'smartlead' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'lavender' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'regie-ai' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'clari' AND c.slug = 'business-finance';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'people-ai' AND c.slug = 'business-finance';

-- E-commerce AI → marketing-seo, customer-support
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'shopify-magic' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'nosto' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'dynamic-yield' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'algolia' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'klevu' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'yotpo' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'gorgias' AND c.slug = 'customer-support';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'privy' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'octane-ai' AND c.slug = 'marketing-seo';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'rebuy' AND c.slug = 'marketing-seo';

-- AI Infrastructure → data-analytics, code-development
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'weights-and-biases' AND c.slug = 'data-analytics';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'weights-and-biases' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mlflow' AND c.slug = 'data-analytics';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mlflow' AND c.slug = 'code-development';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'comet-ml' AND c.slug = 'data-analytics';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'neptune-ai' AND c.slug = 'data-analytics';
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'dvc' AND c.slug = 'code-development';

-- ============================================================
-- TAG LINKS
-- ============================================================

-- LLM Platforms
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'gemini' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'gemini' AND tg.slug = 'code-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'gemini' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mistral' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mistral' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mistral' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'cohere' AND tg.slug = 'rag';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'cohere' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ai21-labs' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'ai21-labs' AND tg.slug = 'summarization';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'together-ai' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'together-ai' AND tg.slug = 'fine-tuning';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'groq' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'groq' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'fireworks-ai' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'fireworks-ai' AND tg.slug = 'fine-tuning';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'replicate' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'replicate' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'modal' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'modal' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'anyscale' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'anyscale' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'octoai' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'octoai' AND tg.slug = 'image-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'cerebras' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'cerebras' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'deepseek' AND tg.slug = 'code-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'deepseek' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'yi-ai' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'yi-ai' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'zhipu-ai' AND tg.slug = 'text-generation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'zhipu-ai' AND tg.slug = 'chatbot';

-- No-Code
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'softr' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'softr' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'appsheet' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'appsheet' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'retool' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'retool' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'internal-io' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'budibase' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'budibase' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'appsmith' AND tg.slug = 'no-code';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'appsmith' AND tg.slug = 'open-source';

-- Sales
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'apollo-io' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'apollo-io' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'outreach' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'outreach' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'salesloft' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'salesloft' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'lemlist' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'lemlist' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'instantly-ai' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'instantly-ai' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'smartlead' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'lavender' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'lavender' AND tg.slug = 'writing-assistant';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'regie-ai' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'regie-ai' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'clari' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'people-ai' AND tg.slug = 'data-analysis';

-- E-commerce
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'shopify-magic' AND tg.slug = 'copywriting';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'shopify-magic' AND tg.slug = 'seo';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'nosto' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'dynamic-yield' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'algolia' AND tg.slug = 'api-tool';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'klevu' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'yotpo' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'gorgias' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'gorgias' AND tg.slug = 'automation';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'privy' AND tg.slug = 'email';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'octane-ai' AND tg.slug = 'chatbot';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'rebuy' AND tg.slug = 'automation';

-- Infrastructure
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'weights-and-biases' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'weights-and-biases' AND tg.slug = 'fine-tuning';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mlflow' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'mlflow' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'comet-ml' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'neptune-ai' AND tg.slug = 'data-analysis';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'dvc' AND tg.slug = 'open-source';
INSERT INTO tool_tags (tool_id, tag_id) SELECT t.id, tg.id FROM tools t, tags tg WHERE t.slug = 'dvc' AND tg.slug = 'workflow';
