-- ============================================================
-- Batch 13: 100 AI tools (auto-scraped from Futurepedia)
-- ============================================================

INSERT INTO tools (name, slug, tagline, description, logo_url, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Fimo', 'fimo', 'Create and manage website content faster with AI.', 'Create and manage website content faster with AI.', 'https://cdn.futurepedia.io/2026-01-21T22-23-15.529Z-hcrIBlxYlwESGhF1Hx0r7jcBIO3HSnE66.png', 'https://fimo.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Premium", "price": "$25 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-assisted content editing","Structured Strapi foundation","Versioning and rollback","Visual plus code editing","Faster iteration","Safety for live sites"}', '{}', true, '{}', '{}', '', now()),
('Freshchat', 'freshchat', 'Elevate customer conversations with AI, omnichannel support, and analytics.', 'Elevate customer conversations with AI, omnichannel support, and analytics.', 'https://cdn.futurepedia.io/a267f15fa7892dd985c5c943d639aac60e4b737a-2511x1225.png', 'https://www.freshworks.com/freshchat/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Growth Tier", "price": "$15", "features": []}]', 'beginner', false, '{"web"}', '{"AI-powered Chatbots","Omnichannel Messaging","Proactive Campaigns","In-depth Analytics","Enhanced Customer Experience","Scalability"}', '{}', true, '{}', '{}', '', now()),
('Tripplanner', 'tripplanner', 'Optimizes travel with AI-driven, personalized itinerary planning.', 'Imagine a tool that not only helps plan your trips but also optimizes them for the best possible experience. That''s what Tripplanner offers. As a frequent traveler and tech enthusiast, I''ve had my fair share of experiences with travel planning tools, but Tripplanner stands out with its AI-driven capabilities. Designed for everyone from vacationers to digital nomads, this tool simplifies the creation of itineraries by considering your preferences for sights, dining, and lodging to craft a personalized travel plan.', 'https://cdn.futurepedia.io/3a69d1971d65319cbcc284df5f3e4c93cc5d0859-2484x1218.png', 'https://tripplanner.ai/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Itinerary Creation","Optimal Route Planning","Local Cuisine Recommendations","Community-Driven Insights","User-Friendly Interface","Customization Options"}', '{}', true, '{}', '{}', '', now()),
('Dubs', 'dubs', 'AI-powered video dubbing and subtitles for global reach.', 'AI-powered video dubbing and subtitles for global reach.', 'https://cdn.futurepedia.io/30tVr4O84WXc8kO6Ta4GMg.png', 'https://dubs.io/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Video Dubbing","Auto-Subtitle Generator","Customizable Subtitles","Dynamic Animations","Time Efficiency","Global Reach"}', '{}', true, '{}', '{}', '', now()),
('MarsX', 'marsx', 'Unleash rapid app development with AI, NoCode, and MicroApps ecosystem.', 'Unleash rapid app development with AI, NoCode, and MicroApps ecosystem.', 'https://cdn.futurepedia.io/420cb4922db0f0338c29691b2ab51524446b10d7-2534x1311.png', 'https://www.marsx.dev/', 'free', '[{"plan": "Free Version", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Powered Landing Page Builder","Micro AppStore","NFT Marketplace","No-Code Builder","Rapid Development","Versatility"}', '{}', true, '{}', '{}', '', now()),
('Thumbly', 'thumbly', 'Revolutionize YouTube engagement with AI-driven, captivating thumbnail creation.', 'Revolutionize YouTube engagement with AI-driven, captivating thumbnail creation.', 'https://cdn.futurepedia.io/bdb9d2f7a886517fa7dbba743e5148b6ebf7909e-1887x947.png', 'https://www.thumbly.io/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Thumbnail Generator","User-Friendly Interface","Title Generator","Free Thumbnail Rating Tool","Boosts Viewer Engagement","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('FusionAds.ai', 'fusionads-ai', 'Revolutionize ad creation and testing with AI-powered efficiency.', 'In the bustling world of digital marketing, where time is money and efficiency is king, FusionAds.ai emerges as a revolutionary AI-powered platform designed to streamline the advertising process for businesses and agencies alike. Its core functionality lies in generating and publishing professional ads in mere seconds. Aimed at both seasoned marketers and those with no prior marketing experience, FusionAds.ai simplifies the creation of omnichannel content with just a single click, ensuring that your campaigns are not only high-quality but also highly effective.', 'https://cdn.futurepedia.io/2026-04-09T20-15-56.078Z-rZQsxQjPt6aiODa1NaBPiCYk4fhzoKaXm.png', 'https://l.fusionos.ai/iIEtRevd9Nb', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Subscription Plans", "price": "$10 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Generative AI Advertising","One-Click Content Creation","A/B Testing Automation","No Experience Required"}', '{}', true, '{}', '{}', '', now()),
('Haiper', 'haiper', 'Revolutionize video creation with AI, high-quality, scalable solutions.', 'Revolutionize video creation with AI, high-quality, scalable solutions.', 'https://cdn.futurepedia.io/2e506b724879315ad9072161ef4e6a25d18d70b8-2538x1228.png', 'https://haiper.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Basic Plan", "price": "$10 per month", "features": []}, {"plan": "Professional Plan", "price": "$30 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Video Creation","Customization Options","High-Quality Rendering","Scalability","Efficiency","User-Friendly"}', '{}', true, '{}', '{}', '', now()),
('Gencraft', 'gencraft', 'AI-powered tool for creating stunning digital art effortlessly.', 'Gencraft revolutionizes the world of digital art creation with its cutting-edge AI technology, offering AI art generation, AI photos, AI image variations, and a versatile editor. Designed for artists, designers, and creative professionals, it simplifies the process of creating stunning visuals, allowing users to explore endless creative possibilities with ease.', 'https://cdn.futurepedia.io/6bb8fcb6468d869d8929f7781740e9cfa9f20b20-2538x1245.jpg', 'https://gencraft.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$19.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Art Generator","AI Photos","Image Variations","Versatile Editor","Innovative Creativity","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Looq AI', 'looq-ai', 'Revolutionize image analysis with advanced AI-powered recognition and insights.', 'Revolutionize image analysis with advanced AI-powered recognition and insights.', 'https://cdn.futurepedia.io/44f0e1f228a3ac7b3a3cb6ba605c3fee16eccf4d-2469x1229.png', 'https://www.looq.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$29.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Image Recognition","Data Enrichment","Scalable Solutions","User-Friendly Interface","Enhanced Accuracy","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Quizgecko', 'quizgecko', 'Transforms content into quizzes, flashcards, and podcasts.', 'Quizgecko is an innovative AI-driven platform designed to revolutionize the way quizzes, flashcards, and study materials are created and utilized. By leveraging advanced AI technology, Quizgecko transforms various content formats into interactive quizzes, flashcards, podcasts, and study notes. This tool is tailored for students, educators, and businesses looking to optimize learning and assessment processes, making it easier to generate, customize, and distribute educational content efficiently.', 'https://cdn.futurepedia.io/2026-02-27T11-14-41.760Z-MjM0OO-KMgVCTmatriaU6mT95SQ5Rk6Dn.png', 'https://quizgecko.com/', 'freemium', '[{"plan": "Basic", "price": "$0 per month", "features": []}, {"plan": "Premium", "price": "$16 per month", "features": []}, {"plan": "Ultra", "price": "$29 per month", "features": []}, {"plan": "Organization", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Question Generator","AI Flashcard Generator","AI Podcast Generator","Customizable Study Tools","Comprehensive Content Transformation","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Vexub', 'vexub', 'Transform text or audio into captivating AI-generated videos.', 'Transform text or audio into captivating AI-generated videos.', 'https://cdn.futurepedia.io/2026-02-27T10-19-08.598Z-FRkxC8cOD6bG8OP5noak_o9NvUOlY_rtS.png', 'https://vexub.com/', 'freemium', '[{"plan": "Basic Plan", "price": "$30 per month", "features": []}, {"plan": "Plus Plan", "price": "$50 per month", "features": []}, {"plan": "Pro Plan", "price": "$100 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Text to Video","MP3 to Video","SMS Video Creation","Advanced Customization","Ease of Use","Versatile Output"}', '{}', true, '{}', '{}', '', now()),
('Magic Studio', 'magic-studio', 'Unleash AI to edit, upscale, and create images effortlessly.', 'Magic Studio is an AI-powered tool revolutionizing image creation and editing. With its user-friendly interface and advanced AI capabilities, it caters to both professionals and beginners. From crafting product pages to designing ads and social media posts, Magic Studio ensures high-quality visual content is easily accessible with just a few clicks.', 'https://cdn.futurepedia.io/2026-02-04T16-43-18.998Z-3BG4UHemOO4cktq8nbmxLV8OG2uI254w7.webp', 'https://magicstudio.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Editing","Background Transformation","Text-to-Image Creation","Upscaling Capabilities","Accessibility","Speed of Creation"}', '{}', true, '{}', '{}', '', now()),
('Teal Resume Builder', 'teal-resume-builder', 'Optimize resumes with AI, tailored to each job application.', 'Teal Resume Builder is a cutting-edge tool revolutionizing resume creation with AI technology. It assists job seekers in crafting custom resumes tailored to stand out in competitive markets. Designed for diverse users, from fresh graduates to seasoned professionals, Teal simplifies the process, making it efficient and tailored for each job application.', 'https://cdn.futurepedia.io/28d62ac3d965c1b0773a5653f579f26b86604932-2538x1261.jpg', 'https://www.tealhq.com/tools/resume-builder', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Premium Tier", "price": "$9", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Customization","User-Friendly Interface","Multiple Resume Versions","Real-Time Content Suggestions","Time-Saving","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Hostinger Reach', 'hostinger-reach', 'The AI-Powered Email Marketing Tool.', 'The AI-Powered Email Marketing Tool.', 'https://cdn.futurepedia.io/2026-02-27T11-13-53.339Z-BzKTwdF-z4wUFNjDyRHaT_z2A6hKdefL5.png', 'https://www.hostg.xyz/aff_c', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Reach 500", "price": "$5.99 per month", "features": []}, {"plan": "Reach 1000", "price": "$3.99 per month", "features": []}, {"plan": "Reach 2500", "price": "$8.99 per month", "features": []}, {"plan": "Reach 5K", "price": "$15.99 per month", "features": []}, {"plan": "Reach 10K", "price": "$25.99 per month", "features": []}, {"plan": "Reach 50K", "price": "$79.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Email Generation","Customizable Templates","Contact Management","Performance Tracking","Efficiency in Campaign Management","Enhanced Personalization"}', '{}', true, '{}', '{}', '', now()),
('Trade Ideas', 'trade-ideas', 'Revolutionize trading with AI-driven signals and real-time scanning.', 'Revolutionize trading with AI-driven signals and real-time scanning.', 'https://cdn.futurepedia.io/2026-02-27T11-14-00.998Z-jkNqpjJR8Xt35Aczya_Wb2kSCP7VY_PO8.png', 'https://www.trade-ideas.com/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Standard Plan", "price": "$118 per month", "features": []}, {"plan": "Premium Plan", "price": "$228 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Signals","Advanced Charting Tools","Real-Time Market Scanning","Customizable Alerts","Enhanced Decision Making","Educational Resources"}', '{}', true, '{}', '{}', '', now()),
('Drafthorse AI', 'drafthorse-ai', 'Boost online presence with AI-driven, SEO-optimized content creation and publishing.', 'Boost online presence with AI-driven, SEO-optimized content creation and publishing.', 'https://cdn.futurepedia.io/ee8c727e6abac7f6d00588f00060ec3763b266ea-2537x1260.jpg', 'https://www.drafthorseai.com/', 'freemium', '[{"plan": "Hobby Tier", "price": "$0 per month", "features": []}, {"plan": "Professional Tier", "price": "$49 per month", "features": []}, {"plan": "Custom Tier", "price": "$100 per month", "features": []}, {"plan": "Pay as you go", "price": "$2.50", "features": []}]', 'beginner', false, '{"web"}', '{"SEO-Optimized Content Generation","Integration with Major Platforms","Content Refreshing Tool","Auto Indexing","Efficiency in Content Creation","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Ollama', 'ollama', 'Chat, build, and explore with open AI models.', 'Chat, build, and explore with open AI models.', 'https://cdn.futurepedia.io/2026-02-27T11-14-43.748Z-OPjygVDdAcP09tQd2WlwiMRUJ-Yvt14P-.png', 'https://ollama.com/', 'free', '[{"plan": "Free", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Open Model Access","Cross-Platform Availability","Community Engagement","Partnership with OpenAI","Versatile Model Options","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('AI Flashcard Maker by Coursebox', 'ai-flashcard-maker-by-coursebox', 'Turn training content into branded multilingual flashcards.', 'Turn training content into branded multilingual flashcards.', 'https://cdn.futurepedia.io/2026-03-02T12-45-17.810Z-WlyFMWcyKbgSaIdlEBHOQoZI7Q0RWrZia.png', 'https://www.coursebox.ai/pricing?fpr=futurepedia26', 'freemium', '[{"plan": "Free plan", "price": "Free", "features": []}, {"plan": "Free trial on paid tiers", "price": "Free", "features": []}, {"plan": "Paid plans", "price": "$2.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI prompt‑based card creation","100+ language support","Huge time savings for content-heavy teams","Tight connection to full courses"}', '{}', true, '{}', '{}', '', now()),
('X-Design', 'x-design', 'Enhance e-commerce visuals effortlessly with AI-powered editing.', 'Enhance e-commerce visuals effortlessly with AI-powered editing.', 'https://cdn.futurepedia.io/2026-02-27T11-14-45.560Z-OjtL5rjMsXvUS3o3UKLt8zzVGIjezAFPV.png', 'https://www.x-design.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$12.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Product Photography","AI Fashion Model","Image Background Remover","AI Image Enhancer","Time Efficiency","Cost-Effective Solutions"}', '{}', true, '{}', '{}', '', now()),
('Runware', 'runware', 'Generate media instantly with cost-effective API.', 'Generate media instantly with cost-effective API.', 'https://cdn.futurepedia.io/2025-05-28T22-44-57.693Z-DSgf5A2arNF-YHNg-IWvwSp7IkLtb8a6A.png', 'https://runware.ai/', 'paid', '[{"plan": "FLUX Schnell", "price": "$0.0006", "features": []}, {"plan": "FLUX Dev", "price": "$0.0038", "features": []}, {"plan": "SD 1.5", "price": "$0.0006", "features": []}, {"plan": "SDXL", "price": "$0.0026", "features": []}, {"plan": "SD 3", "price": "$0.0019", "features": []}]', 'beginner', false, '{"web"}', '{"Sub-second Generative AI","Flexible API Integration","Advanced Orchestration","Extensive Model Library","Cost-Effective Media Generation","Environmentally Friendly"}', '{}', true, '{}', '{}', '', now()),
('Replika', 'replika', 'AI companion for personalized chat, emotional support, and self-growth.', 'AI companion for personalized chat, emotional support, and self-growth.', 'https://cdn.futurepedia.io/522e075fe76fafba6aa54f62ae710893169652e6-1846x937.jpg', 'https://replika.com/', 'freemium', '[{"plan": "Free Version", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Personalized Interaction","Emotional Support","Augmented Reality (AR) Experience","Video Calling","Accessibility","Privacy"}', '{}', true, '{}', '{}', '', now()),
('AI Text Humanizer', 'ai-text-humanizer', 'Transforms AI-generated text into natural, human-like language.', 'AI Text Humanizer revolutionizes the way we interact with AI-generated content by transforming it into natural, human-like text. This tool is specifically designed to help users bypass AI detectors by turning machine-generated prose from platforms like ChatGPT, Claude, or Jasper into convincing, readable text. It''s an ideal solution for students, writers, marketers, and anyone needing to polish AI-generated content for better readability and acceptance.', 'https://cdn.futurepedia.io/2025-01-24T17-35-45.062Z-9FIUYXoZ89ze-QRRbFGaGC6IPG8z3bLJH.png', 'https://ai-text-humanizer.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Humanization of AI Content","AI Detector Bypass","Readability Enhancement","API Access for PRO Users","Time Efficiency","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('AI Prompt Library', 'ai-prompt-library', 'Enhance AI interactions with 30,000+ tailored prompts.', 'AI Prompt Library, offered by God of Prompt, is a comprehensive collection of expertly crafted AI prompts designed to enhance the utility of platforms like ChatGPT and Midjourney. This tool is specifically tailored for businesses and professionals looking to streamline operations, boost productivity, and maximize the potential of AI technologies. By providing over 30,000 prompts across various categories such as marketing, SEO, and productivity, AI Prompt Library simplifies the task of generating high-quality content and strategies, making it an invaluable resource for users aiming to optimize their AI interactions.', 'https://cdn.futurepedia.io/2026-02-27T11-14-03.365Z-XVDb-ujjfzC8aaXCyDkKMtISHXn7mNVAT.png', 'https://godofprompt.ai/pricing', 'freemium', '[]', 'beginner', false, '{"web"}', '{"Extensive Prompt Collection","Category-Specific Bundles","Regular Updates","Comprehensive Guides and Resources","Time Efficiency","Cost-Effective Solutions"}', '{}', true, '{}', '{}', '', now()),
('Mumble Note', 'mumble-note', 'Transforms spoken words into structured notes instantly.', 'Mumble Note is your go-to AI voice notetaker designed to transform spoken words into structured notes, tasks, and outputs instantly. Whether you''re capturing meeting details, brainstorming ideas, or jotting down quick notes, Mumble Note simplifies the process, making it ideal for professionals and creatives who thrive on efficiency and innovation.', 'https://cdn.futurepedia.io/2026-02-04T13-20-49.961Z-y6olx2-R02rS5JUZzAeGzZ064_Vs7L_Y2.webp', 'https://www.mumblenote.com/', 'freemium', '[{"plan": "Monthly", "price": "$15.00 per month", "features": []}, {"plan": "Annual", "price": "$119.99 per year", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Transcriptions","Task Automation","Multi-Format Note Capture","Language Support"}', '{}', true, '{}', '{}', '', now()),
('Vance Video AI', 'vance-video-ai', 'Enhance video quality with AI upscaling, denoising, stabilization.', 'Enhance video quality with AI upscaling, denoising, stabilization.', 'https://cdn.futurepedia.io/2026-02-04T16-49-05.157Z-HaVliuymp5Di4lRujY62S-Jdn1MJWHm85.webp', 'https://vance.ai/', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Video Upscaler","AI Denoiser","AI Deinterlace","AI Deshake","Time Efficiency","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Angry Email Translator', 'angry-email-translator', 'Transforms angry emails to professional; enhances communication with AI-powered rephrasing.', 'In the digital age where email communication is paramount, the Angry Email Translator emerges as a beacon of diplomacy and understanding. This unique AI tool is ingeniously designed to transform heated or negatively-toned emails into professional, polite, and constructive messages. It''s a godsend for individuals and professionals alike who seek to maintain harmony and effectiveness in their digital correspondence.', 'https://cdn.futurepedia.io/d28eb6c53d15ca43c3a9f80c8c2ca46e38b41f30-2533x1269.jpg', 'https://angryemailtranslator.com/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Emotion Detection","Content Rewriting","Tone Adjustment","Multilingual Support","Improved Communication","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('ActiveCampaign AI', 'activecampaign-ai', 'Boost marketing with AI-driven campaign optimization.', 'Boost marketing with AI-driven campaign optimization.', 'https://cdn.futurepedia.io/304aa31e45b51e5ed104c296752207f7a9fd9536-2520x1238.png', 'https://www.activecampaign.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$15 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Brandkit","AI-suggested Segments","Campaign Calendar View","Campaign Reporting Co-pilot","Enhanced Campaign Performance","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('SmartStudi Sidebar', 'smartstudi-sidebar', 'Streamline content creation with AI detection, paraphrasing, and generation.', 'Streamline content creation with AI detection, paraphrasing, and generation.', 'https://cdn.futurepedia.io/2026-02-04T16-47-12.053Z-mONLyu0zUzVhowoTd3WHpO_V6UOZeuB55.webp', 'https://chromewebstore.google.com/detail/smartstudi-sidebar-ai-det/hcbkeogkclchohipphaajhjhdcpnejko', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$9.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI and Plagiarism Detection","Paraphrasing Tool","Content Generation","Citation and Summarization","Versatile Functionality","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Eightfold', 'eightfold', 'AI-driven platform optimizing recruitment, retention, and workforce planning.', 'Eightfold is reshaping the talent management landscape by leveraging AI to streamline recruitment, retention, and overall workforce planning. Designed for HR professionals and organizations of all sizes, Eightfold simplifies the intricacies of talent acquisition and management, offering a comprehensive platform that integrates AI-driven insights to optimize hiring and employee development.', 'https://cdn.futurepedia.io/179810bb2d7486fea9270b797005a2b1b8cfc84e-2532x1222.png', 'https://eightfold.ai/', 'contact', '[{"plan": "Custom Pricing", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Talent Matching","Diversity and Bias Mitigation","Comprehensive Talent Database","Career Site Personalization","Enhanced Recruitment Efficiency","Improved Candidate Experience"}', '{}', true, '{}', '{}', '', now()),
('EbSynth', 'ebsynth', 'Transform videos by editing a single frame.', 'EbSynth is a versatile VFX software designed to transform videos by editing just a single frame. Whether you''re into creative video transformations, retouching, or rotoscopy, EbSynth caters to your needs. By allowing users to paint over keyframes, this tool simplifies the process of turning performances into hand-drawn animations, making video editing more intuitive and artistically liberating.', 'https://cdn.futurepedia.io/2025-10-10T22-41-44.043Z-0xufOcXzri76lD70Y1_QZvRna2uLYzWyD.png', 'https://ebsynth.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$20 per month", "features": []}, {"plan": "Studio Plan", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Frame-Based Editing","Texture-Synthesis Algorithm","Retouching and Colorizing","Offline and Secure Processing","Creative Freedom","Cost-Effective Plans"}', '{}', true, '{}', '{}', '', now()),
('Dreamina', 'dreamina', 'Effortlessly transform text prompts into stunning visual art.', 'Effortlessly transform text prompts into stunning visual art.', 'https://cdn.futurepedia.io/2026-02-27T11-14-47.720Z-FqaWdkwGlMN8GNAa0jgu1YGdk3ZSf-eG-.png', 'https://dreamina.capcut.com/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Basic", "price": "$18 per month", "features": []}, {"plan": "Standard", "price": "$42 per month", "features": []}, {"plan": "Advanced", "price": "$84 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Text-to-Image Generation","Image-to-Image Transformation","Multi-Layer Editing","Diverse Application Support","Creative Flexibility","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Animoto', 'animoto', 'Create marketing videos from photos, clips, and text.', 'Create marketing videos from photos, clips, and text.', 'https://cdn.futurepedia.io/2026-03-03T14-26-16.999Z-ozt0MOuI3eXqfGFerNlOk6dS8nWdRW4jO.png', 'https://ps.animoto.com/Futurepedia', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Basic", "price": "$19 per month", "features": []}, {"plan": "Professional", "price": "$29 per month", "features": []}, {"plan": "Professional Plus", "price": "$79 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI‑Assisted Templates & Storyboards","Extensive Stock & Music Library","Branding & Saved Templates","Voice‑Over, Screen Capture & Audio Tools","Very low barrier to entry","Huge built‑in media catalog"}', '{}', true, '{}', '{}', '', now()),
('Shopify', 'shopify', 'Build and manage online stores with ease, globally.', 'Build and manage online stores with ease, globally.', 'https://cdn.futurepedia.io/dea587ed3beaf6d13f6c8b5143119236428c3301-2508x1152.png', 'https://accounts.shopify.com/store-create', 'freemium', '[{"plan": "Basic Shopify Plan", "price": "$29 per month", "features": []}, {"plan": "Shopify Plan", "price": "$79 per month", "features": []}, {"plan": "Advanced Shopify Plan", "price": "$299 per month", "features": []}, {"plan": "Shopify Plus", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Online Store Builder","Sales Channels Integration","Shopify POS","Shopify Payments","User-Friendly Interface","Extensive App Marketplace"}', '{}', true, '{}', '{}', '', now()),
('Arya.ai', 'arya-ai', 'Revolutionize banking and insurance with AI-driven efficiency and security.', 'Revolutionize banking and insurance with AI-driven efficiency and security.', 'https://cdn.futurepedia.io/c468612f6b5abd714ac0f298b4d8906a98875edd-2526x1302.png', 'https://arya.ai/', 'contact', '[{"plan": "Custom Pricing Model", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"KYC Extraction","Bank Statement Analyzer","Signature and Face Verification APIs","AryaXAI - ML Observability Tools","Enhanced Accuracy","Cost Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Xano', 'xano', 'Build scalable backends and APIs without coding.', 'Build scalable backends and APIs without coding.', 'https://cdn.futurepedia.io/2026-02-27T11-14-05.421Z-l_eZvDhBO69QXYh6HDW1hvmffSUNta7nG.png', 'https://www.xano.com/', 'freemium', '[{"plan": "Build", "price": "Free", "features": []}, {"plan": "Starter", "price": "$29 per month", "features": []}, {"plan": "Pro", "price": "$249 per month", "features": []}, {"plan": "Custom", "price": "Custom", "features": []}]', 'intermediate', false, '{"web"}', '{"No-Code API Builder","Scalable Infrastructure","Integrated Database Management","Automated API Documentation","User-Friendly Interface","Cost-Effective Solution"}', '{}', true, '{}', '{}', '', now()),
('Pth.AI', 'pth-ai', 'Empower your professional goals with AI-driven insights, tailored action plans, and intuitive domain navigation.', 'Empower your professional goals with AI-driven insights, tailored action plans, and intuitive domain navigation.', 'https://cdn.futurepedia.io/2026-02-27T11-14-49.521Z-MReea4nMS0smqBrbBoBQIFUs7vF6rXVt6.png', 'https://pth.ai/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}, {"plan": "Contact for Custom Plans", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Guided Domain Exploration","Drill-Down Capabilities","Persistent AI Context","Tailored for Non-Experts","Goal-Oriented Design","Personalized Action Plans"}', '{}', true, '{}', '{}', '', now()),
('Option Alpha', 'option-alpha', 'Empower your options trading with automated bots, backtesting, and robust education.', 'Option Alpha is a cutting-edge platform specializing in options trading education and software. It aims to empower traders with sophisticated tools and comprehensive educational resources, enabling them to make more informed decisions in the options market. With a suite of automated trading bots, backtesting capabilities, and a vibrant community, Option Alpha streamlines the options trading process for both novice and seasoned investors.', 'https://cdn.futurepedia.io/2651c3252e9322d0c033c6aa69b534b13e0375d3-1900x917.png', 'https://join.optionalpha.com/l2uv4ghey7yl', 'paid', '[{"plan": "Free Tools", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Trading Bots","Backtesting Engine","Educational Resources","Community Engagement","Strategy Optimization","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Personal AI', 'personal-ai', 'Revolutionize workflows with customizable, secure AI personas integration.', 'Personal, is a groundbreaking AI platform designed to revolutionize how individuals and organizations leverage artificial intelligence. It offers a suite of tools to create AI personas—digital representations of job functions, people, and organizations—that enhance operational efficiency and collaboration. This platform is crafted for professionals and enterprises aiming to streamline workflows, boost productivity, and maintain data privacy and security.', 'https://cdn.futurepedia.io/2026-02-04T16-44-57.923Z-gX42PRgTmgDHd8fiPphEmX5YxV2_8_1e-.webp', 'https://www.personal.ai/', 'freemium', '[{"plan": "Enterprise Use", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Training Studio","Native Messaging Platform","Advanced Security Protocols","Custom Integrations","Enhanced Efficiency","Data Ownership"}', '{}', true, '{}', '{}', '', now()),
('Slazzer', 'slazzer', 'AI tool automates precision image background removal effortlessly.', 'AI tool automates precision image background removal effortlessly.', 'https://cdn.futurepedia.io/e2896f065e4626fb4a412c6fc8de7db53b6ed543-1907x916.png', 'https://www.slazzer.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$13 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Background Removal","High-Quality Cutouts","Desktop Application","API and Integrations","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Freed', 'freed', 'Revolutionize healthcare documentation: AI scribe, real-time, HIPAA-compliant, EHR-integrated.', 'Revolutionize healthcare documentation: AI scribe, real-time, HIPAA-compliant, EHR-integrated.', 'https://cdn.futurepedia.io/2026-02-27T11-15-13.260Z-xnG9U12zK4z80oJRGYkxsnQeKKn8b3PCg.png', 'https://getfreed.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Freed Plan", "price": "$99", "features": []}]', 'beginner', false, '{"web"}', '{"Transcription and Summary","Custom SOAP Notes","Self-Learning AI","HIPAA Compliance","Time-Saving","Increased Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Lumana', 'lumana', 'Revolutionize security with real-time AI alerts and scalable cloud management.', 'Revolutionize security with real-time AI alerts and scalable cloud management.', 'https://cdn.futurepedia.io/cfcec9a7b1041238c0435dde56baa5fd9312a8ac-1920x1080.jpg', 'https://www.lumana.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Custom Pricing", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Real-Time Alerts","Unified Management Platform","Advanced AI Search Tools","Scalable Cloud Infrastructure","Enhanced Security and Safety","Ease of Installation"}', '{}', true, '{}', '{}', '', now()),
('Mindy', 'mindy', 'Transform your email into an AI-powered command center.', 'Transform your email into an AI-powered command center.', 'https://cdn.futurepedia.io/ffdf2d4d75187010bd3ccab368a941b72289ed83-1920x1080.png', 'https://mindy.com/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Premium Tier", "price": "$20 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Email Integration","Task Automation","Customized Assistance","Real-Time Responses","Increased Productivity","User-Friendly"}', '{}', true, '{}', '{}', '', now()),
('Castmagic', 'castmagic', 'AI Content Platform For Podcasts, Meetings, and More.', 'CastMagic is a cutting-edge tool designed to revolutionize content creation and management. This AI-powered platform is specifically crafted to automate the workflow of converting audio and video content into a variety of written formats. With its ability to transcribe, summarize, and even generate ready-to-publish content, CastMagic is a boon for professionals and creators who take content seriously and seek to optimize their time and resources.', 'https://cdn.futurepedia.io/5189df63f5e2ec5af84f75dbef1fc4595618ba42-2046x1426.png', 'https://www.castmagic.io/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Content Generation","AI-Driven Transcription","Contextual AI Writing","Diverse Content Output","Time-Saving","Versatility"}', '{}', true, '{}', '{}', '', now()),
('MimicPC', 'mimicpc', 'Unlock AI tools instantly, browser-based, no installs needed.', 'Unlock AI tools instantly, browser-based, no installs needed.', 'https://cdn.futurepedia.io/2025-02-11T15-18-40.279Z-wypSNc8l-2tF4Hv6JPXj9IWwhGEuViybh.png', 'https://www.mimicpc.com/', 'freemium', '[{"plan": "Medium Tier", "price": "$0.49", "features": []}, {"plan": "SDXL Tier", "price": "$0.99", "features": []}]', 'beginner', false, '{"web"}', '{"Instant App Launches","Pre-Deployed AI Apps","Cloud-Based File Management","Adaptive Performance","Ease of Use","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Sapien', 'sapien', 'Human-augmented AI data labeling for scalable, high-quality training.', 'Human-augmented AI data labeling for scalable, high-quality training.', 'https://cdn.futurepedia.io/457353f7f06c00c0dbd8bf6aa51e1b328f3ea1c4-1920x1080.jpg', 'https://www.sapien.io/', 'contact', '[]', 'beginner', false, '{"web"}', '{"Expert Human Feedback","Scalable Labeling Operations","Customizable Labeling Solutions","Global Reach","Accuracy and Scalability","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Meshcapade', 'meshcapade', 'Revolutionize digital human creation and animation with intuitive, lifelike results.', 'Revolutionize digital human creation and animation with intuitive, lifelike results.', 'https://cdn.futurepedia.io/2e0744973974d053ed7035f446254d3a0cb58808-2527x1311.png', 'https://meshcapade.com/?amp%3Butm_medium=marketplace&amp%3Butm_campaign=futurepedia', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Motion from Text","Motion from Video","Body Shape from Images","Platform API","Innovative Animation Techniques","Highly Detailed Avatars"}', '{}', true, '{}', '{}', '', now()),
('Orchids', 'orchids', 'Your fullstack AI engineer.', 'Your fullstack AI engineer.', 'https://cdn.futurepedia.io/2026-02-27T11-14-07.779Z-2TnZ3UdnRfa0qlE60x3FGUF09796IbbxV.png', 'https://www.orchids.app/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$25 per month", "features": []}, {"plan": "Premium", "price": "$50 per month", "features": []}, {"plan": "Ultra", "price": "$99 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Driven Development","Prototyping Capabilities","User-Friendly Interface","Versatile Application Creation","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('NXN Labs', 'nxn-labs', 'Revolutionizing AI-driven visual content creation for modern markets.', 'Revolutionizing AI-driven visual content creation for modern markets.', 'https://cdn.futurepedia.io/eb0c9ba5ce0aa3fbabe5d53b9f791aeb58275ec9-1920x1080.jpg', 'https://nxn.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Subscription Plans", "price": "$99.00 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Atelier AI","Proprietary Image Model","Advanced Customization","Scalable Solutions","Innovation in Imagery","Cost-Effectiveness"}', '{}', true, '{}', '{}', '', now()),
('DaVinci Resolve', 'davinci-resolve', 'Unify editing, color, VFX, and audio post-production.', 'DaVinci Resolve 19 is not just any video editing software; it''s a comprehensive suite designed for high-end film and television post-production. Combining editing, color correction, visual effects, motion graphics, and audio post-production all in one software tool, DaVinci Resolve simplifies the post-production process, allowing you to stay in one program from start to finish. Aimed at professionals in the industry as well as enthusiastic amateurs, its robust feature set is crafted to handle projects from large cinema productions to quick-paced television content.', 'https://cdn.futurepedia.io/e5da98445454a74d8a92a8cac3d108a3418417db-2492x1233.png', 'https://www.blackmagicdesign.com/products/davinciresolve', 'freemium', '[{"plan": "DaVinci Resolve Free", "price": "Free", "features": []}, {"plan": "DaVinci Resolve Studio", "price": "$295,", "features": []}]', 'beginner', false, '{"web"}', '{"Professional Editing Tools","Advanced Color Correction","Fusion VFX","Fairlight Audio Post","All-In-One Solution","Industry-Standard Quality"}', '{}', true, '{}', '{}', '', now()),
('Loom', 'loom', 'Enhance communication with video messaging, editing, and AI integration.', 'Enhance communication with video messaging, editing, and AI integration.', 'https://cdn.futurepedia.io/1a46233af646e1e35046c987ac1b95b23bc4151d-2501x1199.png', 'https://www.loom.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$12.50 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Screen and Camera Recording","AI-Powered Workflows","Advanced Editing Tools","Seamless Integration","Enhanced Productivity","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Twistly', 'twistly', 'Create incredible PowerPoint presentations from any content.', 'Create incredible PowerPoint presentations from any content.', 'https://cdn.futurepedia.io/2026-02-27T11-14-09.871Z-frXJjhTZD7PPjMZfyb79gJIJhVb22M3T4.png', 'https://twistly.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$10 per month", "features": []}, {"plan": "Pro", "price": "$20 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Slide Generation","AI Image Generation","Speaker Notes Generator","Translation Capabilities","Time Efficiency","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('PaperBrain', 'paperbrain', 'Transform academic research with AI-driven summarization and smart literature management.', 'PaperBrain is a state-of-the-art AI tool aimed at revolutionizing how students and researchers engage with academic papers. With its array of powerful features, it simplifies the tasks of organizing, annotating, and referencing literature, serving as a valuable companion for those deeply involved in scholarly research.', 'https://cdn.futurepedia.io/366bdc3f28c68f161d8a0d056d2fd0576ffef3ca-1483x883.jpg', 'https://paperbrain.org/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Premium Tier", "price": "$9.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Smart Organization","Intuitive Annotation","Reference Manager","Collaborative Workspaces","Enhanced Productivity","User-Centric Design"}', '{}', true, '{}', '{}', '', now()),
('SnowSEO', 'snowseo', 'Enhance online visibility with automated SEO solutions.', 'Enhance online visibility with automated SEO solutions.', 'https://cdn.futurepedia.io/2026-02-27T11-14-12.019Z-GOvaWN-BtdFFhp6cBXWGlRHX_b9w-aibC.png', 'https://snowseo.com/', 'paid', '[{"plan": "Starter", "price": "$59 per month", "features": []}, {"plan": "Pro", "price": "$79 per month", "features": []}, {"plan": "Scale", "price": "$129 per month", "features": []}]', 'beginner', false, '{"web"}', '{"All-in-One SEO & AI-SEO Tool","Automated SEO Pipeline","Human-like Content Generation","Performance Tracking","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Atoms', 'atoms', 'Describe needs, build and launch web apps fast.', 'Describe needs, build and launch web apps fast.', 'https://cdn.futurepedia.io/2026-02-05T15-18-21.766Z-jBbuq7U9YGXi46kHa7yIPzEn8U_4oeIIn.blob', 'https://atoms.dev/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$20 per month", "features": []}, {"plan": "Max", "price": "$100 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Multi‑agent AI team","Full‑stack generation and hosting","Visual editor plus code access","Race Mode and deep research","End‑to‑end workflow in one place","Beginner friendly but not toy‑like"}', '{}', true, '{}', '{}', '', now()),
('GitaGPT', 'gitagpt', 'Unlock ancient wisdom with AI; explore spirituality, philosophy, and culture.', 'GitaGPT is a fascinating blend of spirituality and cutting-edge artificial intelligence technology. At its core, GitaGPT aims to provide insights and answers to life''s profound questions, drawing inspiration from the ancient wisdom of the Bhagavad Gita. This tool is designed for individuals seeking spiritual guidance and a deeper understanding of philosophical texts, offering a unique approach to exploring such topics through an AI lens.', 'https://cdn.futurepedia.io/b1f9da639c172a365f4b14f584fdc2c69bbb698d-2535x1296.png', 'https://www.gitagpt.in/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Spiritual Inquiry Assistance","Bhagavad Gita Analysis","Versatile User Base","Cultural Education","Cultural Integration","Educational Tool"}', '{}', true, '{}', '{}', '', now()),
('Storycraft', 'storycraft', 'Craft, explore, and connect in a mobile multiverse of endless possibilities.', 'Craft, explore, and connect in a mobile multiverse of endless possibilities.', 'https://cdn.futurepedia.io/5a57b45ad21c07d5370222fef75a1071e8fc8f88-2514x1220.png', 'https://www.storycraft.gg/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Infinite Crafting Possibilities","AI-Powered Companions","Community Storyline","Mobile Multiverse","Unlimited Creativity","Dynamic Interactions"}', '{}', true, '{}', '{}', '', now()),
('TaxGPT', 'taxgpt', 'Revolutionary AI-driven, error-reducing tax filing assistant.', 'Revolutionary AI-driven, error-reducing tax filing assistant.', 'https://cdn.futurepedia.io/d3decd3ab4a1b924d09464228d263e0b6d12888a-2507x1232.png', 'https://www.taxgpt.com/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Tax Assistance","User-Friendly Interface","Error Reduction","24/7 Availability","Efficiency in Tax Filing","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Vectorize', 'vectorize', 'Streamlines AI data retrieval for efficient processing.', 'Streamlines AI data retrieval for efficient processing.', 'https://cdn.futurepedia.io/2026-02-27T11-15-14.879Z-CWyaI1BDbelgBTbWRT24s_g1KS5BJf7Xn.png', 'https://vectorize.io/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$99 per month", "features": []}, {"plan": "Pro", "price": "$399 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Agent-First Retrieval","Multimodal Extraction","Custom Metadata Filters","Configurable Pipelines","Enhanced Data Access","No-Code Setup"}', '{}', true, '{}', '{}', '', now()),
('Civils.ai', 'civils-ai', 'Automates construction data extraction, compliance checks, and reporting.', 'Automates construction data extraction, compliance checks, and reporting.', 'https://cdn.futurepedia.io/2025-02-14T19-59-06.716Z-jIaeDXske6iqMlB0ZHRWJ9ZJi_SLv3v62.png', 'https://civils.ai/', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$250", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Data Extraction","Compliance Checking","Customizable AI Bots","Collaborative Workflows","Time Efficiency","Error Reduction"}', '{}', true, '{}', '{}', '', now()),
('Numeric', 'numeric', 'Revolutionizing accounting with AI-driven automation and analysis.', 'Revolutionizing accounting with AI-driven automation and analysis.', 'https://cdn.futurepedia.io/767d6b72539e21e54591e9b7c0ab25ff1b7209b7-1920x1080.png', 'https://www.numeric.io/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Automation","Smart Subledgers","Flux Analysis Tool","Technical Accounting AI","Efficiency Gains","Accuracy and Audit-readiness"}', '{}', true, '{}', '{}', '', now()),
('Talefy', 'talefy', 'Interactive, illustrated storytelling across genres with community engagement.', 'Interactive, illustrated storytelling across genres with community engagement.', 'https://cdn.futurepedia.io/c00438a22e1c37fc780dc58a5d0bc14784b67bd9-2523x1237.png', 'https://talefy.ai/', 'paid', '[]', 'beginner', false, '{"web"}', '{"Diverse Genre Selection","Interactive Storytelling","Story Illustration Functionality","Community Engagement","Engagement Through Choice","Visual Appeal"}', '{}', true, '{}', '{}', '', now()),
('Hey Internet', 'hey-internet', 'Transforms text messaging into an AI-driven personal assistant for instant, tailored support.', 'Hey Internet is an innovative AI tool that revolutionizes the way we interact with information and manage our daily tasks. It''s designed as an AI-powered text message assistant that simplifies the way we learn, work, and stay connected. By leveraging the power of AI, Hey Internet provides quick, accurate answers to a myriad of questions, making it an invaluable tool for', 'https://cdn.futurepedia.io/fd1fa4444bc588b23bc51ad62bce0f1e53ec226e-2533x1272.jpg', 'https://heyinternet.ai/', 'freemium', '[]', 'beginner', false, '{"web"}', '{"AI-Powered Responses","Text Messaging Interface","24/7 Availability","Customized Support","Enhanced Learning","Increased Productivity"}', '{}', true, '{}', '{}', '', now()),
('Tortus', 'tortus', 'Transform healthcare with AI-driven EHR efficiency and support.', 'Transform healthcare with AI-driven EHR efficiency and support.', 'https://cdn.futurepedia.io/cf66facbbb31ff65fa5f7c6130cbc1c2fd69a5aa-1920x1080.png', 'https://tortus.ai/', 'contact', '[{"plan": "Subscription Model", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Speech Recognition","Automated Documentation","Workflow Automation","Clinical AI Co-working","Enhanced Efficiency","Data Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Hypotenuse', 'hypotenuse', 'Elevate content creation with AI; SEO-optimized, brand-unique, scalable.', 'As someone who has spent a considerable amount of time exploring and reviewing AI writing tools, I''m always thrilled to come across solutions that promise to streamline the content creation process for various users. Hypotenuse AI is a tool that positions itself as more than just a writing assistant; it''s an AI-powered platform designed to generate high-quality, SEO-optimized content at scale. Whether it''s crafting blog articles, product descriptions, or social media posts, Hypotenuse AI aims to deliver content that resonates with your brand''s voice and audience.', 'https://cdn.futurepedia.io/2026-02-27T11-15-16.508Z-eK0bQ3kus_n23tmxTutyYZqRcanCemdbf.png', 'https://hypotenuse.ai/', 'freemium', '[{"plan": "Starter Plan", "price": "$29", "features": []}, {"plan": "Business Plan", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Product Description Generator","Bulk Generation","SEO & Conversion Tools","Content Customization","Efficiency in Content Creation","SEO Optimization"}', '{}', true, '{}', '{}', '', now()),
('Textero AI Essay Writer', 'textero-ai-essay-writer', 'Your reliable AI academic assistant for tasks of any scale. From idea generation and research assistance to text editing and paper summarizing, Textero.ai will make your academic journey less stressfu', 'Textero AI is an innovative tool designed to break writer''s block by leveraging artificial intelligence to assist writing. It''s the partner you need when words fail you. Textero AI revolutionizes the writing aid arena with its AI-driven platform that helps generate ideas, construct essay outlines, and source citations effortlessly. Its intuitive interface and', 'https://cdn.futurepedia.io/d9e114ce70fbe9037974d27a97c35624c87d4ae7-1402x672.png', 'https://www.textero.ai/', 'freemium', '[]', 'beginner', false, '{"web"}', '{"AI-Driven Text Generation","User-Friendly Tutorials","Advanced Citation and Sourcing Tools","Integrated AI Chat","Prefilled Document Ideas","Interactive Tutorials"}', '{}', true, '{}', '{}', '', now()),
('Notta', 'notta', 'Transforms audio/video to summarized text, instantly, across platforms.', 'Transforms audio/video to summarized text, instantly, across platforms.', 'https://cdn.futurepedia.io/2026-02-04T16-44-32.443Z-RLdrEUkltwutRlqa81KOcOXK7IXQQrqE8.webp', 'https://www.notta.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Premium Plans", "price": "$9.00 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Real-Time Transcription and Translation","AI-Powered Summarization","Cross-Platform Compatibility","Advanced Search and Tagging","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('JanitorAI', 'janitorai', 'Streamline data cleaning with AI-driven automation and accuracy.', 'Streamline data cleaning with AI-driven automation and accuracy.', 'https://cdn.futurepedia.io/17c65c20b1d164fb2fd44cf65404d45400b018d2-1920x1080.png', 'https://janitorai.com/?amp%3Butm_medium=marketplace&amp%3Butm_campaign=futurepedia', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$29.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Data Cleaning","Real-Time Processing","User-Friendly Dashboard","Customizable Rules and Filters"}', '{}', true, '{}', '{}', '', now()),
('MIRI', 'miri', 'Revolutionize wellness with AI: personalized health coaching, expert nutrition, fitness guidance, anytime access.', 'As someone who''s always on the lookout for innovative AI tools, I''m excited to introduce you to MIRI, a digital wellness coach that''s redefining personal health guidance. With MIRI, you have 24/7 access to an AI coach trained by leading diet and nutrition experts, like Shannon Morse. Whether you''re seeking advice on nutrition, fitness, or overall wellness, MIRI is designed to offer personalized support and recommendations to help you achieve your health goals.', 'https://cdn.futurepedia.io/2026-02-27T11-15-20.701Z-M5qOKWsfRvNX51MnR9Dl4m96AjwHlCeKZ.png', 'https://www.miri.health/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Personalized Coaching","Nutrition and Fitness Guidance","Integrated Shopping Lists","Supercharged Meal Plans","Accessibility","Customization"}', '{}', true, '{}', '{}', '', now()),
('Solvely', 'solvely', 'All-in-one AI homework helper with step-by-step solutions.', 'All-in-one AI homework helper with step-by-step solutions.', 'https://cdn.futurepedia.io/IfHVNXcCrD6at9ZImDZd8C.png', 'https://solvely.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$12.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Step-by-Step Explanations","High Accuracy","Multi-Level Support","Integration with Study Platforms","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Luma AI', 'luma-ai', 'Transform text into detailed 3D models, interact with dynamic scenes.', 'Transform text into detailed 3D models, interact with dynamic scenes.', 'https://cdn.futurepedia.io/2026-02-27T11-15-23.379Z-29dC6mWn-gJCC0ekwBHIJ07kEuJyG0szI.png', 'https://lumalabsai.partnerlinks.io/Futurepedia', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Genie","Interactive Scenes","My Captures","Featured Captures","Innovation at its Core","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('ACE Studio', 'ace-studio', 'Create studio-ready vocals, choirs, and instruments from MIDI.', 'Create studio-ready vocals, choirs, and instruments from MIDI.', 'https://cdn.futurepedia.io/2026-02-04T16-31-02.388Z-x0bxHb_fj4mj9ORS7INHW5GJqYkFFUDB_.webp', 'https://acestudio.ai/', 'paid', '[{"plan": "Artist", "price": "$398", "features": []}, {"plan": "Artist Pro", "price": "$528", "features": []}]', 'beginner', false, '{"web"}', '{"AI Vocal Synth from MIDI and Lyrics","AI Choir and Voice Designer","Voice Cloning and Voice Changer","AI Instruments (Violin and More)","High Vocal Realism","Deep Performance Control"}', '{}', true, '{}', '{}', '', now()),
('RowSpeak', 'rowspeak', 'Turn messy spreadsheets into clear, ready reports.', 'Turn messy spreadsheets into clear, ready reports.', 'https://cdn.futurepedia.io/2026-04-02T17-05-18.457Z-tRCgsetsKgRLirlJ2zZ6KoLkf5Fhxvg_8.png', 'https://rowspeak.ai/', 'paid', '[{"plan": "Essential", "price": "$9.90 per month", "features": []}, {"plan": "Professional", "price": "$29.90 per month", "features": []}, {"plan": "Premium", "price": "$59.90 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Spreadsheet Assistant","Messy Data Understanding","Business-Aware AI Analysis","Report-Quality Output","Huge time savings for operators","Friendly for non-analysts"}', '{}', true, '{}', '{}', '', now()),
('Flowstep', 'flowstep', 'AI-driven design suggestions and seamless real-time collaboration for creatives.', 'AI-driven design suggestions and seamless real-time collaboration for creatives.', 'https://cdn.futurepedia.io/4f04935d0e240c347e3e9762f7d13338f9901bdd-1920x1080.png', 'https://flowstep.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Professional Tier", "price": "$20 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Design Suggestions","Real-Time Collaboration Tools","Extensive Template Library","Drag-and-Drop Interface","Enhanced Creativity","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Buildpad', 'buildpad', 'Guides product ideas to launch with AI-powered structure.', 'Guides product ideas to launch with AI-powered structure.', 'https://cdn.futurepedia.io/2025-04-23T19-33-02.770Z-2l-GME7oewMaqantVOhp2YHXMU6Nc76mn.png', 'https://buildpad.io/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$20 per month", "features": []}, {"plan": "Pro", "price": "$40 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Guided 10-Phase Framework","Contextual AI Memory","Reddit Validation Tool","User Persona Generator","Structured Development Process","Personalized AI Assistance"}', '{}', true, '{}', '{}', '', now()),
('GPT Engineer', 'gpt-engineer', 'Transforms natural language into executable code; boosts development efficiency.', 'Transforms natural language into executable code; boosts development efficiency.', 'https://cdn.futurepedia.io/8e2a15814c05fef82e842bc0dd61cace72e9817c-2538x1276.jpg', '', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"Natural Language Understanding","Interactive Clarification Process","Automated Code Generation","Support for Multiple Python Versions","Efficiency Booster","User-Friendly"}', '{}', true, '{}', '{}', '', now()),
('Kustomer', 'kustomer', 'Revolutionize customer service with AI, CRM integration, and proactive support.', 'Revolutionize customer service with AI, CRM integration, and proactive support.', 'https://cdn.futurepedia.io/2b3ac84cd391503e6a43bcd0e24492384cd489bb-2492x1225.png', 'https://www.kustomer.com/', 'paid', '[{"plan": "Standard Plan", "price": "$89 per user", "features": []}, {"plan": "Enterprise Plan", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"CRM Integration","AI Chatbots","Proactive Support","App Marketplace","Enhanced Efficiency","Cost Reduction"}', '{}', true, '{}', '{}', '', now()),
('Code Genius', 'code-genius', 'Streamlines React, Vue JS, and Tailwind CSS development.', 'Streamlines React, Vue JS, and Tailwind CSS development.', 'https://cdn.futurepedia.io/2026-02-27T11-14-14.981Z-UVsMj6xohkuXjYQZoweGNUklj-RbGYeZ9.png', 'https://www.code-genius.dev/', 'freemium', '[{"plan": "Starter", "price": "$0 per month", "features": []}, {"plan": "Premium", "price": "$8 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Powered Code Suggestions","Automated Unit Test Generation","Conversational AI Buddy","Workflow Synchronization","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Instories', 'instories', 'Easily create shorts from long-form videos.', 'Easily create shorts from long-form videos.', 'https://cdn.futurepedia.io/2026-02-27T11-14-20.501Z-5wrQ-_o6rKo4aih77_nNjaq9nnCHSn-4X.png', 'https://instories.com/', 'freemium', '[{"plan": "Instories Pro (Monthly Plan)", "price": "$14.99 per month", "features": []}, {"plan": "Instories Pro (Yearly Plan)", "price": "$10 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Template Library","Animation Tools","Text and Font Options","Music Integration","User-Friendly Interface","Fast Content Creation"}', '{}', true, '{}', '{}', '', now()),
('Final Touch', 'final-touch', 'Effortlessly transform product photos into captivating, professional scenes.', 'Final Touch revolutionizes the art of product photography by offering AI-powered solutions that transform ordinary product photos into captivating, professional-grade scenes. Designed for e-commerce businesses, marketers, and creative professionals, it simplifies the complex task of creating visually appealing product imagery. With just a click, Final Touch enables users to generate stunning images that breathe new life into their digital presence.', 'https://cdn.futurepedia.io/2025-01-27T02-39-43.939Z-C4gP527DcFhws1Hi5m2nhKsq-iUHfDLVQ.PNG', 'https://final-tou.ch/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Scene Generation","No Design Skills Needed","Advanced Editing Mode","Instant Results","Time Efficiency","Creative Control"}', '{}', true, '{}', '{}', '', now()),
('Artigen Pro AI', 'artigen-pro-ai', 'Transform text into realistic images instantly, free and user-friendly.', 'Transform text into realistic images instantly, free and user-friendly.', 'https://cdn.futurepedia.io/2026-02-27T11-14-22.078Z-CBYz-WB1ydqJjEFOY3ulX5i5nA3QEFOOo.png', 'https://aiconvert.online/artigen-pro-ai', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"High-Quality, Realistic Images","Language Flexibility","Rapid Image Creation","User-Friendly Interface","Cost-Effectiveness","No Signup Required"}', '{}', true, '{}', '{}', '', now()),
('Book AI Writer', 'book-ai-writer', 'Revolutionizes storytelling with AI writing and automatic cover design.', 'Revolutionizes storytelling with AI writing and automatic cover design.', 'https://cdn.futurepedia.io/e9b07b10991ce2288131775a3dee47950bfee77f-2497x1208.png', 'https://www.bookaiwriter.com/', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Writing Assistant","Customizable Story Blueprints","Automatic Cover Design","Intuitive User Interface","Streamlined Writing Process","Enhanced Creativity"}', '{}', true, '{}', '{}', '', now()),
('VEED.IO', 'veedio', 'Create, edit, subtitle, and translate pro-grade videos instantly.', 'Create, edit, subtitle, and translate pro-grade videos instantly.', 'https://cdn.futurepedia.io/2026-02-27T11-14-25.620Z-mkkpwGdNaT23O3INhCiRMvqQ6zjULxxOX.png', 'https://www.veed.io/', 'freemium', '[]', 'beginner', false, '{"web"}', '{"AI Subtitles and Transcription","Magic Cut","AI Avatars and Cloning","Text to Speech and AI Voice Cloning"}', '{}', true, '{}', '{}', '', now()),
('Smartsheet', 'smartsheet', 'Streamline workflows, automate tasks, enhance team collaboration.', 'Streamline workflows, automate tasks, enhance team collaboration.', 'https://cdn.futurepedia.io/2025-10-30T15-31-09.848Z-TWj7d7HG3_l6Y21rls2-hYYaX8JsZ3O2p.png', 'https://www.smartsheet.com/', 'paid', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"Automation","Team Collaboration","Dashboards and Reporting","Integration Capabilities","Enhanced Productivity","Scalability"}', '{}', true, '{}', '{}', '', now()),
('MeetGeek', 'meetgeek', 'Automate, summarize, and integrate meetings for peak productivity.', 'Automate, summarize, and integrate meetings for peak productivity.', 'https://cdn.futurepedia.io/0adb4d1fdb5cf70f8cf82327c8f8e997fbdf1eec-1807x857.jpg', 'https://get.meetgeek.ai/futurepedia', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Auto-recording and Transcription","Automatic Summaries","Highlights and Keyword Detection","Searchable Meeting Archive","Enhanced Meeting Productivity","Comprehensive Meeting Records"}', '{}', true, '{}', '{}', '', now()),
('Box', 'box', 'Summarizes, extracts, and rewrites content from files.', 'Summarizes, extracts, and rewrites content from files.', 'https://cdn.futurepedia.io/2026-02-27T11-14-27.720Z-Gsa7HGYsNAWW_Fg6AZ5by949jLrsCWfcP.png', '', 'freemium', '[{"plan": "Individuals", "price": "$14 per month", "features": []}, {"plan": "Individual Plan", "price": "Free", "features": []}, {"plan": "Personal Pro Plan", "price": "$14 per month", "features": []}, {"plan": "Businesses", "price": "$7 per user", "features": []}, {"plan": "Business Starter Plan", "price": "$7 per user", "features": []}, {"plan": "Business Plan", "price": "$20 per user", "features": []}, {"plan": "Business Plus Plan", "price": "$33 per user", "features": []}, {"plan": "Enterprise Plan", "price": "$47 per user", "features": []}, {"plan": "Enterprise Plus Plan", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Document Querying","Instant Summarization","AI-Powered Data Extraction","Generative Content Creation","Time-Saver","Automation-rich"}', '{}', true, '{}', '{}', '', now()),
('YouMind', 'youmind', 'Transform ideas into high-quality creations.', 'Transform ideas into high-quality creations.', 'https://cdn.futurepedia.io/2026-02-27T11-14-30.241Z-SClkyKiJxjRU3xjHtCSRWXtrTtSICVnRx.png', 'https://youmind.com/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$20 per month", "features": []}, {"plan": "Max", "price": "$100 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Assistance","Project Boards","Browser Extension","Enhanced Productivity","Versatile AI Models"}', '{}', true, '{}', '{}', '', now()),
('PhotoTag.ai', 'phototag-ai', 'Transform digital chaos into searchable libraries with AI-powered tagging.', 'Transform digital chaos into searchable libraries with AI-powered tagging.', 'https://cdn.futurepedia.io/bcbf53fdddbc4408a5bb65553e650c0084c18b8c-2530x1242.png', 'https://www.phototag.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Keyword Generation","User-Friendly Interface","Bulk Processing Capability","Cross-Platform Compatibility","Time Efficiency","Enhanced Discoverability"}', '{}', true, '{}', '{}', '', now()),
('Lucidpic', 'lucidpic', 'Revolutionize your visuals with AI-powered 3D photo transformations for engaging, lifelike content.', 'Lucidpic is an innovative platform revolutionizing the way users interact with images through its AI-driven 3D photo creation feature. Tailored for photographers, marketers, and social media enthusiasts, Lucidpic adds depth and interactivity to visual content, offering a new dimension to traditional images.', 'https://cdn.futurepedia.io/67559b8ffa002db4d690d9aeb1892e0cf7af6460-2856x1578.png', 'https://lucidpic.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"3D Photo Creation","User-Friendly Interface","Social Media Integration","High-Quality Output","Enhanced Engagement","Innovative Technology"}', '{}', true, '{}', '{}', '', now()),
('BeeDone', 'beedone', 'A Gamified Task Management App', 'BeeDone is a cutting-edge productivity application designed to transform your to-do lists into a fun and engaging game. Utilizing the latest in AI technology, BeeDone offers a unique approach to managing tasks, routines, and habits by incorporating gamification elements that motivate and reward users for their accomplishments. Tailored for individuals who seek to enhance their productivity in both personal and professional spheres, BeeDone makes staying on top of your responsibilities not just manageable, but enjoyable.', 'https://cdn.futurepedia.io/b194b67683f495651d06509196d540652dfad0a7-2519x1233.png', 'https://beedone.co/', 'freemium', '[{"plan": "Freemium Tier", "price": "Free", "features": []}, {"plan": "Premium Tier", "price": "$8.50 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Gamified Task Management","AI Task Organization","Flexible Habit Tracking","Smart Daily Routines","Enhanced Motivation","Personalized Productivity"}', '{}', true, '{}', '{}', '', now()),
('Redactable', 'redactable', 'Automated AI tool for fast, secure document redaction.', 'Automated AI tool for fast, secure document redaction.', 'https://cdn.futurepedia.io/VPFM43ceMH3HdJvR7mCUJT.png', 'https://redactable.com/', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Redaction","Redaction Wizard","Cloud-Based Platform","Built-in Integrations","Time Efficiency","User-Friendly"}', '{}', true, '{}', '{}', '', now()),
('Stable Horde', 'stable-horde', 'Harness AI for efficient, community-driven image and text generation.', 'Harness AI for efficient, community-driven image and text generation.', 'https://cdn.futurepedia.io/0befac3977af1e9d2ecc60f7890b3e34921e5fae-1880x762.jpg', 'https://stablehorde.net/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Distributed AI Processing","Real-Time Performance Stats","Flexible Integration","Community-Driven Development","Scalability","Developer-Friendly"}', '{}', true, '{}', '{}', '', now()),
('Huntr', 'huntr', 'Streamline job applications, optimize resumes, track progress efficiently.', 'Streamline job applications, optimize resumes, track progress efficiently.', 'https://cdn.futurepedia.io/c0948f6c0fd4e9538f3738578e85d73affaa7ecc-2484x1231.png', 'https://huntr.co/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$15 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Resume Builder","Resume Optimization Tools","Job Tracker System","One-Click Application Autofill","Streamlined Job Search Management","Customization of Applications"}', '{}', true, '{}', '{}', '', now()),
('AI First', 'ai-first', 'Create autonomous agents for sales, support, & HR.', 'Create autonomous agents for sales, support, & HR.', 'https://cdn.futurepedia.io/2026-01-13T18-20-06.636Z-FA0Qlwins0C9wt55K2xRp7p2DZqbQm5WH.png', 'https://aifirst.app/', 'paid', '[{"plan": "Individual", "price": "$94 per month", "features": []}, {"plan": "Enterprise Basic", "price": "$450 per month", "features": []}, {"plan": "Enterprise Starter", "price": "$2,615 per month", "features": []}, {"plan": "Enterprise Premium", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Autonomous Decision-Making","Agent Marketplace","Architect Agent Builder","No-Code Creation","Fast Time to Value","No-Code Accessibility"}', '{}', true, '{}', '{}', '', now()),
('Aidoc', 'aidoc', 'Enhances radiology with real-time AI-driven image analysis.', 'Enhances radiology with real-time AI-driven image analysis.', 'https://cdn.futurepedia.io/50bfb941f2df3a67572817a740be2e620f9574dc-1920x1080.jpg', 'https://www.aidoc.com/', 'contact', '[{"plan": "Enterprise Solutions", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Analysis","Seamless Integration","Real-Time Alerts","Continuous Learning","Enhanced Diagnostic Accuracy","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('GAJIX', 'gajix', 'Revolutionize learning with AI: instant insights, comprehensive syllabus, enhanced understanding.', 'GAJIX is an innovative AI learning assistant designed to revolutionize the process of acquiring knowledge and mastering new subjects. Positioned as a tool to enhance learning speed, efficiency, and depth, GAJIX employs advanced artificial intelligence algorithms to analyze diverse subjects or webpages, offering instant insights and summaries to facilitate comprehensive understanding. Targeting a broad spectrum of users, ranging from students and self-learners to professionals seeking to expand their expertise, GAJIX aims to make learning faster, more effective, and more accessible.', 'https://cdn.futurepedia.io/0e5cc7590fbcf452033fe24cf76c355ba48c320d-2506x1223.jpg', 'https://appsumo.8odi.net/xkbAPO', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Instant Insights","Comprehensive Syllabus","Enhanced Understanding","Thought-Provoking Exercises","Versatile Learning","Productivity Boost"}', '{}', true, '{}', '{}', '', now()),
('Bagoodex', 'bagoodex', 'Enhances search, chat, and privacy for business efficiency.', 'Bagoodex is an advanced AI tool designed to enhance the efficiency and effectiveness of search and chat functionalities within private and corporate environments. Its core purpose revolves around optimizing information retrieval and communication processes, making it a vital asset for businesses aiming to streamline operations and improve productivity.', 'https://cdn.futurepedia.io/e613b228dcc0ae765d9865145f607f8abfaec875-2504x1229.png', 'https://bagoodex.io/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Search Capabilities","Private Chat Functions","User-Friendly Interface","Customizable Settings","Enhanced Privacy","Increased Productivity"}', '{}', true, '{}', '{}', '', now()),
('VideoIdeas.ai', 'videoideas-ai', 'Effortlessly generate viral YouTube scripts and growth strategies.', 'Effortlessly generate viral YouTube scripts and growth strategies.', 'https://cdn.futurepedia.io/2026-02-27T11-15-25.038Z-SU5X5CZwUXblap_3ffiC8hquoKs8BweH-.png', 'https://www.videoideas.ai/', 'freemium', '[{"plan": "Basic Plan", "price": "$9 per month", "features": []}, {"plan": "Pro Plan", "price": "$29 per month", "features": []}, {"plan": "Teams Plan", "price": "$99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Full Video Scripts","Channel Analysis","Viral Short-Form Content","Video Ad Scripts","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('HubSpot', 'hubspot', 'Unify marketing, sales, CRM; AI-driven insights—boost efficiency.', 'Unify marketing, sales, CRM; AI-driven insights—boost efficiency.', 'https://cdn.futurepedia.io/b451d6a711fba543e09c5a2a1471b03e99cc4757-2498x1227.png', 'https://go.try-hubspot.com/c/4792963/1001264/12893', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Starter Plan", "price": "$90 per month", "features": []}, {"plan": "Professional Plan", "price": "$800 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Insights","Comprehensive CRM","AI-Powered Content Creation","Marketing Automation","Unified Platform","Scalability"}', '{}', true, '{}', '{}', '', now()),
('PromptPerfect', 'promptperfect', 'Revolutionize AI prompt creation with real-time optimization and templates.', 'Revolutionize AI prompt creation with real-time optimization and templates.', 'https://cdn.futurepedia.io/dcc05033dcc156b16a7998211f8579e006ebf98a-2500x1217.png', 'https://promptperfect.jina.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$20.00 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Dynamic Prompt Engineering","Real-Time Optimization","User-Friendly Interface","Extensive Template Library","Enhanced AI Performance","Time-Saving"}', '{}', true, '{}', '{}', '', now())
ON CONFLICT (slug) DO NOTHING;

-- Category assignments
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'fimo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'freshchat' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'freshchat' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'tripplanner' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'tripplanner' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'dubs' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'dubs' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'marsx' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'marsx' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'thumbly' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'fusionads-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'fusionads-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'haiper' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'gencraft' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'looq-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'quizgecko' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'vexub' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'magic-studio' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'teal-resume-builder' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'hostinger-reach' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'trade-ideas' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'trade-ideas' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'drafthorse-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'ollama' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'ollama' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'ai-flashcard-maker-by-coursebox' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'x-design' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'x-design' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'x-design' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'runware' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'replika' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'replika' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'ai-text-humanizer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'ai-prompt-library' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'mumble-note' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'mumble-note' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'mumble-note' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'vance-video-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'angry-email-translator' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'angry-email-translator' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'activecampaign-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'activecampaign-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'smartstudi-sidebar' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'eightfold' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'ebsynth' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'dreamina' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'animoto' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'animoto' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'shopify' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'shopify' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'shopify' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'arya-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'arya-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'xano' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'pth-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'pth-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'option-alpha' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'option-alpha' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'personal-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'personal-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'slazzer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'slazzer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'freed' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'lumana' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'mindy' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'castmagic' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'castmagic' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'mimicpc' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'mimicpc' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'sapien' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'meshcapade' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'orchids' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'nxn-labs' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'davinci-resolve' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'loom' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'loom' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'twistly' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'paperbrain' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'snowseo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'atoms' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'gitagpt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'storycraft' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'storycraft' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'taxgpt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'vectorize' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'civils-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'numeric' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'numeric' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'talefy' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'hey-internet' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'hey-internet' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'tortus' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'hypotenuse' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'hypotenuse' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'textero-ai-essay-writer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'notta' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'notta' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'janitorai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'janitorai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'miri' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'solvely' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'luma-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'ace-studio' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'rowspeak' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'rowspeak' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'rowspeak' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'flowstep' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'flowstep' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'buildpad' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'gpt-engineer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'kustomer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'kustomer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'code-genius' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'instories' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'instories' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'final-touch' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'final-touch' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'artigen-pro-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'book-ai-writer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'veedio' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'veedio' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'smartsheet' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'meetgeek' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'meetgeek' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'meetgeek' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'box' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'youmind' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'phototag-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'phototag-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'lucidpic' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'beedone' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'redactable' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'stable-horde' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'stable-horde' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'huntr' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ai-first' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'aidoc' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'gajix' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'gajix' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'gajix' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'bagoodex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'bagoodex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'videoideas-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'videoideas-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'hubspot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'hubspot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'hubspot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'promptperfect' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'promptperfect' ON CONFLICT DO NOTHING;

