-- ============================================================
-- Batch 15: 100 AI tools (auto-scraped from Futurepedia)
-- ============================================================

INSERT INTO tools (name, slug, tagline, description, logo_url, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Design.com', 'design-com', 'Create all types of brand visuals with AI-driven tools.', 'Create all types of brand visuals with AI-driven tools.', 'https://cdn.futurepedia.io/2026-02-27T11-16-52.139Z-9wuaPKrZFKrOipPD51MSfnJBOL98fWYjy.png', 'https://www.design.com/?sv1=affiliate&sv_campaign_id=2345079&ssaid=2345079&sscid=101111_1775900361_08cc8c2bc6d18f3b0d7fe8913950be7c&awc=101111_1775900361_08cc8c2bc6d18f3b0d7fe8913950be7c', 'freemium', '[{"plan": "Starter Plan", "price": "$15 per month", "features": []}, {"plan": "Value Plan", "price": "$24 per month", "features": []}, {"plan": "Premium Plan", "price": "$29 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Logo Generator","AI Background Remover","AI Business Card Generator","AI Presentation Maker","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Dcipher Insight Booster', 'dcipher-insight-booster', 'Automate research, trend discovery, and instant report creation.', 'Automate research, trend discovery, and instant report creation.', 'https://cdn.futurepedia.io/2026-02-27T11-16-22.401Z-O9fT2aTjTXBGHvs0zTBWfRnI5J2E9udOT.png', 'https://www.dcipheranalytics.com/products/dcipher-insight-booster', 'freemium', '[{"plan": "Pay-as-you-go", "price": "$0.55", "features": []}, {"plan": "14-day Trial", "price": "Free", "features": []}, {"plan": "Starter", "price": "$435 per month", "features": []}, {"plan": "Pro", "price": "$760 per month", "features": []}, {"plan": "Wizard", "price": "$1,520 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Rich Knowledge Base Creation","Multilingual Research Agents","Visual Content Mapping","Automated Report Generator","Time Efficiency","Multilingual Support"}', '{}', true, '{}', '{}', '', now()),
('LogoAI', 'logoai', 'Revolutionize branding with AI: logos, identities, and content made simple.', 'LogoAI emerges as a cutting-edge tool in the digital branding world, redefining logo design for businesses and individuals. This AI-powered platform takes logo creation to new heights, offering a simplified process with smart AI technology that not only generates logos but also incorporates design best practices. Tailored for entrepreneurs, small businesses, and marketing professionals, LogoAI promises professionalism, automation, and aesthetic appeal in logo design.', 'https://cdn.futurepedia.io/ad4bd0ae7e25985789c00366ba05cebefc286531-2528x1230.png', 'https://www.logoai.com/', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Smart AI Engine","Professional Design Outputs","Automated Branding Solutions","Comprehensive Branding Platform","Efficiency in Design","Cost-Effectiveness"}', '{}', true, '{}', '{}', '', now()),
('TutorAI', 'tutorai', 'Unleash AI-driven, personalized, and interactive learning for all.', 'TutorAI presents an intriguing promise to revolutionize the learning experience through artificial intelligence. This platform is tailored to cater to the diverse interests and learning preferences of curious minds across a multitude of subjects, ranging from physics to history and even personal exploration.', 'https://cdn.futurepedia.io/6e44b719a15419bd315246e16c12216c2240ab69-1902x967.jpg', 'https://www.tutorai.me/', 'freemium', '[{"plan": "Customization and Flexibility", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Customized Learning Paths","Wide Range of Topics","Interactive Learning Experience","Self-paced Study","Accessibility","User Empowerment"}', '{}', true, '{}', '{}', '', now()),
('Noisee AI', 'noisee-ai', 'Find powerful Noisee AI alternatives for creators.', 'Find powerful Noisee AI alternatives for creators.', 'https://cdn.futurepedia.io/2025-01-30T20-41-22.706Z-VyV9zw0pZ578xNva-8-N7ty79GE_rG3Vr.jpg', 'https://kaiber.ai/', 'free', '[]', 'beginner', false, '{"web"}', '{}', '{}', true, '{}', '{}', '', now()),
('Jinna.ai', 'jinna-ai', 'Automates invoicing and follow-ups for small businesses.', 'Automates invoicing and follow-ups for small businesses.', 'https://cdn.futurepedia.io/2026-02-27T11-16-01.500Z-yOjpLz4LpXEKMhaGkVNuVrcDHA84Cm7uv.png', 'https://jinna.ai/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Invoicing","Automated Follow-Ups","Real-Time Payment Tracking","Contextual Understanding","Time Efficiency","User-Friendly Design"}', '{}', true, '{}', '{}', '', now()),
('SayWhatt', 'saywhatt', 'Revolutionize e-commerce with AI-driven, personalized sales chats.', 'Revolutionize e-commerce with AI-driven, personalized sales chats.', 'https://cdn.futurepedia.io/d80965adb7e3c030dba16db8cc1bc58a640a8926-2500x1214.png', 'https://www.saywhatt.com/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI & ML Powered Sales Conversations","Customized Solutions Per Brand","Data-Driven Action","Full Analytics & Insights","Increased Sales Conversion Rates","Scalability"}', '{}', true, '{}', '{}', '', now()),
('Aidelly', 'aidelly', 'AI-driven tool streamlining marketing with automation and analytics.', 'AI-driven tool streamlining marketing with automation and analytics.', 'https://cdn.futurepedia.io/aJA0gE9Ae6FKGd0dIBvYod.png', 'https://aidelly.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$19 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Campaign Management","Predictive Analytics","Content Generation","Automation Tools","Enhanced Efficiency","Cost Savings"}', '{}', true, '{}', '{}', '', now()),
('Caffeine', 'caffeine', 'Build, launch, and update decentralized apps using chat.', 'Build, launch, and update decentralized apps using chat.', 'https://cdn.futurepedia.io/2025-11-07T18-10-02.383Z-Bh5NhEYhJSxAkL_BG1ywGu3P8OyHlZ9gF.png', 'https://caffeine.ai/', 'freemium', '[{"plan": "Starter Plan", "price": "$15.99 per month", "features": []}, {"plan": "Plus Plan", "price": "$29.99 per month", "features": []}, {"plan": "Pro Plan", "price": "$99.99 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Natural Language App Creation","Decentralized Deployment","Real-Time Iteration","Web3 Integration","No Coding Required","Fully Decentralized"}', '{}', true, '{}', '{}', '', now()),
('StudyX', 'studyx', 'Revolutionize learning: AI chatbots, 200M+ papers, writing aid, cross-platform.', 'Revolutionize learning: AI chatbots, 200M+ papers, writing aid, cross-platform.', 'https://cdn.futurepedia.io/f5e4bcda7d7207c70b6f101bb2676ce1e74c3a1c-2483x1201.png', 'https://studyx.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"All-in-One Learning Assistance","Advanced AI Chatbots","Comprehensive Research Aid","AI Writing Assistance","Time-Saving","Versatile Learning Tools"}', '{}', true, '{}', '{}', '', now()),
('Layer AI', 'layer-ai', 'Revolutionize game asset creation with AI, ensuring style consistency and boosting productivity.', 'Revolutionize game asset creation with AI, ensuring style consistency and boosting productivity.', 'https://cdn.futurepedia.io/f7920e57a098c9f5e4c4a09d1c0e0d46bcee79d5-2490x1218.png', 'https://www.layer.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Custom Packages", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Enhanced Productivity","Cost Reduction"}', '{}', true, '{}', '{}', '', now()),
('Ask Layla', 'ask-layla', 'Revolutionize travel with AI-driven planning and seamless bookings.', 'Revolutionize travel with AI-driven planning and seamless bookings.', 'https://cdn.futurepedia.io/47faedc0550193b88a630bc63c8d2b1545ed94bb-2492x1228.png', 'https://justasklayla.com/', 'free', '[{"plan": "Free Version", "price": "Free", "features": []}, {"plan": "Premium Subscription", "price": "$9.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Itinerary Planning","Personalized Travel Suggestions","Integrated Booking Options","Interactive Chat Interface","User-Friendly Experience","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Ceartas DMCA', 'ceartas-dmca', 'AI-driven tool swiftly removes unauthorized content and deepfakes.', 'AI-driven tool swiftly removes unauthorized content and deepfakes.', 'https://cdn.futurepedia.io/bc518b5846d075cc5bdd577418f5ae079e61db48-1920x1080.png', 'https://www.ceartas.io/', 'freemium', '[{"plan": "For Creators", "price": "$39", "features": []}, {"plan": "For Enterprises", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Monitoring","Real-Time Takedown","Deepfake Detection and Removal","24/7 Brand Protection","Efficient Content Protection","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Minion AI', 'minion-ai', 'Revolutionize customer service with intelligent, automated, omnichannel support.', 'Revolutionize customer service with intelligent, automated, omnichannel support.', 'https://cdn.futurepedia.io/2024-09-18T20-18-54.662Z-mn.PNG', 'https://www.minion.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced NLP Capabilities","24/7 Customer Support","Omnichannel Integration","Customizable Chatbots","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Wisedocs', 'wisedocs', 'AI-driven platform streamlines medical document analysis.', 'AI-driven platform streamlines medical document analysis.', 'https://cdn.futurepedia.io/3ebb20bde32c2a0169f48e5ebe991918361edb8f-1920x1080.png', 'https://www.wisedocs.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Medical Chronologies","Intelligent OCR","Deduplication","Workflow Integration","Efficiency Gains","Accuracy and Insight"}', '{}', true, '{}', '{}', '', now()),
('AI Home Design', 'ai-home-design', 'Revolutionize real estate and interior design with AI-driven virtual staging and renovations.', 'AI Home Design is a groundbreaking platform that leverages artificial intelligence to transform the way we approach real estate and interior design. Its suite of tools is crafted to empower property listings, facilitate effortless renovations, and bring design dreams to life. From virtual staging and interior design to photo editing and home renovation, AI Home Design offers a comprehensive solution for enhancing properties and creating visually appealing spaces. Designed for real estate professionals, designers, and home enthusiasts alike, this platform simplifies the design process, making it accessible, efficient, and enjoyable.', 'https://cdn.futurepedia.io/232637a070001479935e4b8fc160eb43fb6a0697-2540x1259.png', 'https://aihomedesign.com/', 'freemium', '[{"plan": "Starter Plan", "price": "Free", "features": []}, {"plan": "Lite Plan", "price": "$6.67 per month", "features": []}, {"plan": "Pro Plan", "price": "$16.67 per month", "features": []}, {"plan": "Pro Plus Plan", "price": "$33.33 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Virtual Staging","Interior Design","Photo Editing","Home Renovation","Cost-Effective Solutions","High-Quality, Listing-Ready Results"}', '{}', true, '{}', '{}', '', now()),
('Whoop', 'whoop', 'Optimize fitness, sleep, and recovery with real-time health insights.', 'Optimize fitness, sleep, and recovery with real-time health insights.', 'https://cdn.futurepedia.io/f0715ef51bd6068453408120d9ef09e79098d96c-2500x1217.png', 'https://www.whoop.com/', 'paid', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Annual Membership", "price": "$239", "features": []}, {"plan": "24 Month Membership", "price": "$399", "features": []}]', 'beginner', false, '{"web"}', '{"24/7 Heart Rate Monitoring","Sleep Tracking and Analysis","Strain Coach","Recovery Optimization","Data Accuracy","User Engagement"}', '{}', true, '{}', '{}', '', now()),
('MarketAlerts.ai', 'marketalerts-ai', 'AI-powered tool delivers real-time market alerts and insights.', 'MarketAlerts.ai revolutionizes market monitoring, offering real-time alerts and in-depth insights into market trends and financial data. Designed for financial analysts, traders, and investment professionals, it simplifies the complex task of staying abreast of market fluctuations and making informed decisions.', 'https://cdn.futurepedia.io/2vtJukrG0XC5h9QMlCDsiX.png', 'https://www.marketalerts.com/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Real-Time Alerts","Comprehensive Data Analysis","Customizable Dashboards","Integration with Trading Platforms","Time Efficiency","Enhanced Decision-Making"}', '{}', true, '{}', '{}', '', now()),
('Wegic', 'wegic', 'Revolutionize web design: AI-driven, chat-based, versatile, with supportive assistants.', 'Revolutionize web design: AI-driven, chat-based, versatile, with supportive assistants.', 'https://cdn.futurepedia.io/2026-02-27T11-16-34.719Z-abK6il7fxhKSo15vRAw3I6RvWDYhm-nwv.png', 'https://wegic.ai/?plan=pedia', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Design and Development","Conversational Interface","Versatile Project Scope","Supportive Assistants","Ease of Use","Customization"}', '{}', true, '{}', '{}', '', now()),
('Coris', 'coris', 'Screen merchants, detect fraud, and automate reviews.', 'Screen merchants, detect fraud, and automate reviews.', 'https://cdn.futurepedia.io/2026-02-27T11-16-59.898Z-6dDAav6nbbUBfswtWwEDoOWC8FQItCvvE.png', 'https://www.coris.ai/', 'contact', '[{"plan": "Demo Required", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"MerchantProfiler","CorShield","Transaction Monitoring","Risk Platform","Time Efficiency","Return on Investment"}', '{}', true, '{}', '{}', '', now()),
('Unriddle', 'unriddle', 'Boost research, streamline writing, visualize connections—AI-powered, multilingual, collaborative.', 'Boost research, streamline writing, visualize connections—AI-powered, multilingual, collaborative.', 'https://cdn.futurepedia.io/2026-02-27T11-16-55.520Z-pGbUFbjUEsgw_03afJ9YQ7a8qg0FqfdBO.png', 'https://www.unriddle.ai/', 'freemium', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Research Assistant","Contextual Links","AI-Enhanced Writing","Visualization Tools","Efficiency in Research","Enhanced Writing Quality"}', '{}', true, '{}', '{}', '', now()),
('PublicAI', 'publicai', 'Revolutionize Web3 data management with AI-driven, secure blockchain integration.', 'Revolutionize Web3 data management with AI-driven, secure blockchain integration.', 'https://cdn.futurepedia.io/b5aaba194f7e1047a15a2ea427041f903099a0aa-1920x1080.png', 'https://publicai.io/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Decentralized Data Handling","AI-Driven Analytics","Scalable Infrastructure","User-Friendly Interface","Enhanced Security","Increased Transparency"}', '{}', true, '{}', '{}', '', now()),
('xpander.ai', 'xpander-ai', 'Efficiently build, deploy, and scale AI agents.', 'Efficiently build, deploy, and scale AI agents.', 'https://cdn.futurepedia.io/2026-02-27T11-17-01.581Z-Y87TrZBWRIQaHmtXD42JOu6j0BhXE45GU.png', 'https://xpander.ai/', 'freemium', '[{"plan": "Free Tier", "price": "$0 per month", "features": []}, {"plan": "Pay-as-you-go", "price": "$0 per month", "features": []}, {"plan": "Custom", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Agent Templates","MCP and Tool Repository","Event Streaming","Multi-Agent Orchestration","Rapid Development","Infrastructure Management"}', '{}', true, '{}', '{}', '', now()),
('Leya AI', 'leya-ai', 'Transform English fluency with AI-driven personalized learning.', 'Transform English fluency with AI-driven personalized learning.', 'https://cdn.futurepedia.io/bd15a57b6164dfd51b9469e24fcc563354982536-1920x1080.png', 'https://leyaai.com/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Monthly Subscription", "price": "$19.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Personalized Learning Plans","Real-Time Feedback","Progress Tracking","Interactive Learning Sessions","Rapid Improvement","Highly Customizable"}', '{}', true, '{}', '{}', '', now()),
('Nabla', 'nabla', 'Automated clinical note generation, seamless EHR integration, and HIPAA-compliant documentation streamline healthcare workflows effortlessly."', 'Nabla is a cutting-edge tool designed to revolutionize the way clinicians handle medical documentation. At its core, Nabla''s Copilot application automates the generation of clinical notes, thereby reducing stress and enhancing the quality of patient care. Aimed at healthcare professionals, Nabla streamlines the documentation process for both in-person and video consultations without storing any data, ensuring compliance with privacy regulations.', 'https://cdn.futurepedia.io/bf7de2a8cf8b5fff5a79583e12b32b71400bb378-2541x1273.jpg', 'https://www.nabla.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$119", "features": []}, {"plan": "Enterprise Tier", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Automatic Clinical Note Generation","Integration with Electronic Health Records (EHRs)","HIPAA and GDPR Compliance","User-Friendly Interface","Time Savings","Reduction in Fatigue"}', '{}', true, '{}', '{}', '', now()),
('Falcon LLM', 'falcon-llm', 'Multilingual, multimodal, scalable AI tool; open-source.', 'Multilingual, multimodal, scalable AI tool; open-source.', 'https://cdn.futurepedia.io/66142414dbfe721542f736035d1ed8771b6795b1-2514x1228.png', 'https://falconllm.tii.ae/', 'contact', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Multilingual Capabilities","Multimodal Functions","Open-Source Accessibility","High Scalability","Innovative Technology","Customization"}', '{}', true, '{}', '{}', '', now()),
('1forAll', '1forall', 'Streamlines content creation with AI-generated voices, images, videos.', 'Streamlines content creation with AI-generated voices, images, videos.', 'https://cdn.futurepedia.io/2025-04-15T15-08-58.935Z-h84rEVc1zZVG21jgHb5C6Bo22UEhLdAzr.png', 'https://www.1forall.ai/', 'freemium', '[{"plan": "Basic", "price": "$1.07 per month", "features": []}, {"plan": "Advance", "price": "$11.80 per month", "features": []}, {"plan": "Pro", "price": "$53 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Text to Speech","Voice Cloning","Excel to Speech or Image","Video Generation","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Microsoft Designer', 'microsoft-designer', 'Unleash creativity with AI-driven design simplicity and Microsoft integration.', 'Unleash creativity with AI-driven design simplicity and Microsoft integration.', 'https://cdn.futurepedia.io/c7e28ae20f48896ca8563a895f562111e62f7aa6-1849x964.jpg', 'https://designer.microsoft.com/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Design Suggestions","Templates Library","Seamless Integration","Accessibility Features","User-Friendly Interface","Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Gigasheet', 'gigasheet', 'Transform big data with spreadsheet ease; no-code, AI-enhanced analysis.', 'Transform big data with spreadsheet ease; no-code, AI-enhanced analysis.', 'https://cdn.futurepedia.io/d54bfe517a562c69f656a82dca195b704cef4682-2496x1224.png', 'https://www.gigasheet.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"Big Data Compatibility","No-Code Analysis","Automated Workflows","Collaboration Tools","Ease of Use","Scalability"}', '{}', true, '{}', '{}', '', now()),
('Adobe Photoshop', 'adobe-photoshop', 'Master image editing, AI, 3D design, and more.', 'Master image editing, AI, 3D design, and more.', 'https://cdn.futurepedia.io/1208bba7d8dc87ab363f24418dd372d8f00d6c61-2512x1218.png', 'https://adobe.prf.hn/click/camref:1011l4m7s2', 'paid', '[{"plan": "Photography Plan", "price": "$19.99 per month", "features": []}, {"plan": "Photoshop Single App", "price": "$20.99 per month", "features": []}, {"plan": "All Apps Plan", "price": "$52.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Generative AI Tools","Advanced Layer System","Comprehensive Toolset","Customizable Workspace","Unmatched Editing Capability","Highly Customizable Interface"}', '{}', true, '{}', '{}', '', now()),
('Jasper Art', 'jasper-art', 'Transform text into stunning, royalty-free images instantly.', 'Transform text into stunning, royalty-free images instantly.', 'https://cdn.futurepedia.io/98e4d90871a4de8d60b64937f64ce19a614ccdac-2505x1236.png', 'https://www.jasper.ai/art', 'paid', '[{"plan": "Pro Plan", "price": "$49 per month", "features": []}, {"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Creativity","High-Resolution Outputs","Royalty-Free Usage","Diverse Styles and Mediums","Enhanced Productivity","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Profile Picture Maker', 'profile-picture-maker', 'Transform your digital identity with AI-enhanced, professional profile pictures effortlessly.', 'In today''s digital age, a first impression is often made online, making a professional and eye-catching profile picture more important than ever. Enter Profile Picture Maker, an AI-powered tool from pfpmaker.com that promises to transform your digital presence. Whether you''re aiming for a polished look on LinkedIn, a creative flair for Instagram, or simply seeking to enhance your online persona across various platforms, Profile Picture Maker offers an array of options to create the perfect avatar. With its user-friendly interface and advanced AI features, crafting a profile picture that reflects your style, confidence, and professionalism has never been easier.', 'https://cdn.futurepedia.io/32f33026f36ebdeee53c222257403e8dcaec15bd-2058x1182.jpg', 'https://pfpmaker.com/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Portrait Editor","Background Removal and Replacement","AI Portrait Enhancer","Professional Templates","Ease of Use","Versatility"}', '{}', true, '{}', '{}', '', now()),
('DataSnipper', 'datasnipper', 'Streamlines Excel data extraction, verification, and analysis.', 'Streamlines Excel data extraction, verification, and analysis.', 'https://cdn.futurepedia.io/4140d43a3d8d2573cefa6bd812e81e4ce7dcfd74-1920x1080.png', 'https://www.datasnipper.com/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Standard Tier", "price": "$50 per month", "features": []}, {"plan": "Enterprise Solutions", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Document Matching","Form Extraction","Table Snip","Cloud Collaboration Suite","Enhanced Productivity","Error Reduction"}', '{}', true, '{}', '{}', '', now()),
('Jace', 'jace', 'Automate tasks, optimize workflows, enhance productivity with AI.', 'Automate tasks, optimize workflows, enhance productivity with AI.', 'https://cdn.futurepedia.io/2025-02-14T20-05-20.550Z-YTTlc8NuoyH4gAo0A_QHSeAR4axqGDW85.png', 'https://www.jace.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$20 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Marketing Efficiency","Hiring Assistance","Tutoring Business Management","User-Friendly Interface","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Pykaso AI', 'pykaso-ai', 'Generate lifelike images and videos.', 'Generate lifelike images and videos.', 'https://cdn.futurepedia.io/2026-02-04T16-45-39.697Z-4FvaTCN_MLS0EtjilUvQV9Vo0d6rW4ZB2.webp', 'https://www.pykaso.ai/', 'paid', '[{"plan": "Gem-based Pricing", "price": "$0.12.", "features": []}, {"plan": "Premium Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Ultra-Realistic AI Generation","Image-to-Image Transformation","AI Video Generator","Skin Enhancer Tool","High-Quality Output","Versatile Tools"}', '{}', true, '{}', '{}', '', now()),
('MagicPhotos', 'magicphotos', 'Transform everyday photos into stunning, personalized portraits.', 'Transform everyday photos into stunning, personalized portraits.', 'https://cdn.futurepedia.io/2026-02-27T11-16-57.781Z-_HVVJCA2yVubZDYZ33DZxSyL6jyb6KPfP.png', 'https://magicphotos.com/', 'paid', '[{"plan": "The Spark", "price": "$49", "features": []}, {"plan": "The Flame", "price": "$59", "features": []}, {"plan": "The Fire", "price": "$69", "features": []}]', 'beginner', false, '{"web"}', '{"Rapid Photo Generation","Diverse Style Options","AI Personalization","User-Friendly Process","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Durable AI', 'durable-ai', 'Create custom software effortlessly with AI-powered development.', 'Create custom software effortlessly with AI-powered development.', 'https://cdn.futurepedia.io/2025-01-27T02-18-36.671Z-ARKygK7nX7RYEzny2kYSHEsnmC3-kqx-I.PNG', 'https://durable.ai/', 'contact', '[]', 'intermediate', false, '{"web"}', '{"Generative AI-Powered Development","User-Centric Design","Neurosymbolic AI Integration","Continuous Learning","Accessibility","Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Zoer', 'zoer', 'Generate production web apps from database schemas.', 'Generate production web apps from database schemas.', 'https://cdn.futurepedia.io/2026-03-26T19-35-39.451Z-p3MT9eNAr8aozV3Sq2BEnC0qUQybvET3A.png', 'https://zoer.ai/', 'freemium', '[{"plan": "Starter", "price": "$10 per month", "features": []}, {"plan": "Pro", "price": "$30 per month", "features": []}, {"plan": "Max", "price": "$99 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Backend‑first generation","Zoer Database, auth, and payments","Zoer Copilot","Projects, publishing, and code export","Production‑minded approach","Fast generation"}', '{}', true, '{}', '{}', '', now()),
('Freepik AI Voice Generator', 'freepik-ai-voice-generator', 'Transform text into lifelike speech with customizable options.', 'Freepik AI Voice Generator is an innovative tool designed to transform text into lifelike speech, offering a seamless solution for individuals and businesses looking to enhance their audio content creation. Situated at the intersection of technology and creativity, this tool is crafted for content creators, educators, marketers, and anyone who requires high-quality voiceovers. It simplifies the process of generating professional-grade audio, allowing users to focus on creativity and engagement rather than technical complexity.', 'https://cdn.futurepedia.io/2026-02-04T16-41-13.633Z-eX1OuUqqG4qUMnnFHEhg21A7o5Ux1Onl1.webp', 'https://www.freepik.com/ai/voice-generator', 'freemium', '[{"plan": "Essential Tier", "price": "$9 per month", "features": []}, {"plan": "Premium Tier", "price": "$20 per month", "features": []}, {"plan": "Premium+ Tier", "price": "$39 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Natural Sounding Voices","Multilingual Support","Customizable Speech Parameters","Seamless Integration","User-Friendly Interface","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('HarmonAI', 'harmonai', 'Unleash music creativity with AI-powered, open-source production tools.', 'Unleash music creativity with AI-powered, open-source production tools.', 'https://cdn.futurepedia.io/9e2d59dcc58ff0124fb09cad9dc265b6cfdea3b4-1920x1080.png', 'https://www.harmonai.org/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Generative Audio Tools","Open-Source Platform","User-Centric Design","Community Engagement","Accessibility","Creative Freedom"}', '{}', true, '{}', '{}', '', now()),
('Air', 'air', 'Automate team workflows with parallel agents and approvals.', 'Automate team workflows with parallel agents and approvals.', 'https://cdn.futurepedia.io/2026-03-17T18-00-26.685Z-91GUBzPwE8wYNPTFVkSzbneYUchtGsZP2.png', 'https://air.dev/', 'contact', '[{"plan": "All Plans", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Multi-agent task management","Human-in-the-loop controls","Tool and data integrations","Reusable playbooks","Control-first design","Speed from parallelism"}', '{}', true, '{}', '{}', '', now()),
('SYSTRAN', 'systran', 'Revolutionize multilingual communication with rapid, secure translation solutions.', 'Revolutionize multilingual communication with rapid, secure translation solutions.', 'https://cdn.futurepedia.io/4a92ee8709ad8d8f840ef3cae84a6f03774a8243-2480x1223.png', 'https://www.systransoft.com/', 'paid', '[{"plan": "Enterprise Solutions", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"High-Speed Translation","Wide Language Selection","Integration Capabilities","Efficiency Boost","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('MurmurCast', 'murmurcast', 'Condense YouTube, podcasts, newsletters into fast email briefs', 'Condense YouTube, podcasts, newsletters into fast email briefs', 'https://cdn.futurepedia.io/2026-04-01T20-55-26.362Z-simmJAL9SCIcnn904nIukn3LRHLqrshYf.png', 'https://murmurcast.com/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$8 per month", "features": []}, {"plan": "Pro", "price": "$15 per month", "features": []}, {"plan": "Power", "price": "$49 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Multi‑Source Aggregation","Auto‑Transcription Engine","AI Summaries","Personalized Daily Briefs","Serious Time Saver","Inbox‑First Experience"}', '{}', true, '{}', '{}', '', now()),
('Monica', 'monica', 'AI assistant revolutionizing chat, writing, coding, and more.', 'Monica is an all-in-one AI assistant designed to revolutionize how we interact with digital content, whether for chatting, writing, coding, or searching. Utilizing cutting-edge AI models such as GPT-4o, Claude 3.5, and Gemini 1.5, Monica aims to simplify and enhance user experiences across multiple platforms, including browser extensions for Chrome and Edge, as well as desktop and mobile applications. This tool is perfect for professionals and individuals seeking to streamline their workflows, offering features that range from AI-assisted chat and writing to sophisticated code assistance.', 'https://cdn.futurepedia.io/2025-02-01T00-10-55.684Z-JAdtjOWA0hXybQuRXEf3ccj9yoKYjuAiv.PNG', 'https://monica.im/invitation-affiliate?ref_aff=yzawntq', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Powered Chat and Writing","Multilingual Support","AI Image Tools","PDF and Document Management","Comprehensive Toolset","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Giftpack', 'giftpack', 'AI-driven, global gifting platform automates personalized gift delivery.', 'AI-driven, global gifting platform automates personalized gift delivery.', 'https://cdn.futurepedia.io/2026-02-27T11-17-04.881Z-mQ8N8qByJGEDkqs09Jcsv3srTNuD4xql1.png', 'https://giftpack.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Global Catalog Access","AI-Powered Personalization","Automated Integration","Real-Time Tracking and Analytics","Efficiency in Operations","Enhanced Personalization"}', '{}', true, '{}', '{}', '', now()),
('SEOWriteX', 'seowritex', 'Revolutionize content creation with SEO-optimized, AI-driven versatility across languages.', 'In the ever-evolving digital landscape, SEOWriteX emerges as a beacon for those seeking to revolutionize their content creation process. At its core, SEOWriteX is an AI-driven platform designed to enhance the efficiency and effectiveness of content marketing. From crafting compelling blog posts to', 'https://cdn.futurepedia.io/288ac2595aeb47ae97e976352f87a440abf69d0f-2303x1232.jpg', '', 'freemium', '[{"plan": "Monthly Subscription", "price": "$20 per month", "features": []}]', 'beginner', false, '{"web"}', '{"SEO Optimization","Versatile Content Templates","Multi-language Support","Time-saving","SEO-Driven Results"}', '{}', true, '{}', '{}', '', now()),
('Parspec', 'parspec', 'Revolutionize product selection and quoting with AI-driven efficiency.', 'Revolutionize product selection and quoting with AI-driven efficiency.', 'https://cdn.futurepedia.io/cee7f5a37508ad9f775bcf4d79e80cba33aef124-1920x1080.png', 'https://parspec.io/', 'paid', '[{"plan": "Custom Pricing Model", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Product Finder","Automated Quoting System","Submittal and O&M Automation","Cloud-Based Tools","Increased Efficiency","Enhanced Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Text2SQL', 'text2sql', 'Transform natural language into optimized SQL queries effortlessly.', 'Transform natural language into optimized SQL queries effortlessly.', 'https://cdn.futurepedia.io/5e867b35a7f61702c0ce7dea113e6f65f1e67438-2509x1208.png', 'https://www.text2sql.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Standard Plan", "price": "$7 per month", "features": []}, {"plan": "Pro Plan", "price": "$29 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Natural Language Processing","Support for Multiple SQL Dialects","Custom Database Schema Integration","Multilingual Support","Enhanced Productivity","Accuracy and Efficiency"}', '{}', true, '{}', '{}', '', now()),
('PostSam', 'postsam', 'Create, schedule, and publish viral content.', 'Create, schedule, and publish viral content.', 'https://cdn.futurepedia.io/2026-02-04T16-45-16.719Z-CJ7YCW8gW3GJ0eiIVoNjPyjA3Ts3UeW-_.webp', 'https://postsam.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$19.99 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Content Creation","Automatic Scheduling","Unified Dashboard","Viral Content Ideas","Time Efficiency","Increased Engagement"}', '{}', true, '{}', '{}', '', now()),
('Tennr', 'tennr', 'Streamline healthcare paperwork with AI-driven document automation.', 'Streamline healthcare paperwork with AI-driven document automation.', 'https://cdn.futurepedia.io/d3168ba78509a678ecfe4aa2ba5bf02fb8fe28fa-1920x1080.png', 'https://www.tennr.com/', 'contact', '[{"plan": "Custom Quotes", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Requests and Follow-ups","Insurance and Authorization Handling","EHR Integration","Patient Communication","Efficiency in Document Handling","High Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Liberate', 'liberate', 'Revolutionizes insurance with AI-driven CX and process automation.', 'Revolutionizes insurance with AI-driven CX and process automation.', 'https://cdn.futurepedia.io/528b12083bba040b633a846c8aa2ecd3c00e4005-1920x1080.png', 'https://www.liberateinc.com/', 'contact', '[{"plan": "Custom Pricing Model", "price": "Custom", "features": []}, {"plan": "Subscription-Based Tiers", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Claims Automation","Underwriting Workbench","Digital Quote & Bind","Document AI & Inference","Enhanced Customer Experience","Operational Efficiency"}', '{}', true, '{}', '{}', '', now()),
('ToolSpend', 'toolspend', 'Unify AI/SaaS spend, catch waste, avoid bill shocks.', 'Unify AI/SaaS spend, catch waste, avoid bill shocks.', 'https://cdn.futurepedia.io/2026-02-19T16-33-39.602Z-gqlTNORyjBAMeNiLsLIS1dEbsNrNIIbM0.blob', 'https://toolspend.com/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Pro Plan", "price": "$14.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Unified AI and SaaS Spend Dashboard","Real-Time Cost Tracking and Forecasting","Usage, Seat, and Duplicate Detection","Anomaly and Spike Alerts","Clear AI and SaaS Visibility","Practical Cost Reduction"}', '{}', true, '{}', '{}', '', now()),
('Deci', 'deci', 'Optimize AI model performance and reduce costs with advanced tools.', 'Optimize AI model performance and reduce costs with advanced tools.', 'https://cdn.futurepedia.io/039feb8f161399140d5f5e9915daf1e6f1ee793b-2503x1222.png', 'https://deci.ai/', 'contact', '[{"plan": "Foundation Models", "price": "Custom", "features": []}, {"plan": "Custom Model Development", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AutoNAC (Neural Architecture Search Engine)","SuperGradients™ PyTorch Training Library","Infery Optimization & Inference Engine SDK","DataGradients™ Dataset Analyzer","Enhanced Performance","Cost Reduction"}', '{}', true, '{}', '{}', '', now()),
('Hear', 'hear', 'AI-driven insights and automation for exceptional customer service.', 'AI-driven insights and automation for exceptional customer service.', 'https://cdn.futurepedia.io/4d4e506ffea62099008aa22f68b66dcbc4a9d4d1-1920x1080.png', 'https://hear.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Subscription Model", "price": "$299 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Comprehensive Analysis","Automated Quality Assurance","Generative AI Native","Real-Time Insights","Increased Efficiency","Cost Reduction"}', '{}', true, '{}', '{}', '', now()),
('Vmake', 'vmake', 'Record, polish, caption, and reuse talking clips.', 'Record, polish, caption, and reuse talking clips.', 'https://cdn.futurepedia.io/2026-04-03T04-15-24.600Z-pdf8z8RH-DJe5NqTuPE3AW7kZ9MeAy1bf.png', 'https://vmake.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Plus", "price": "$9.99 per month", "features": []}, {"plan": "Pro", "price": "$29.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI talking video studio","AI enhancement suite","Auto captions and transcription","AI image and thumbnail tools","Built around talking videos","Strong quality boost for everyday footage"}', '{}', true, '{}', '{}', '', now()),
('Offrs', 'offrs', 'Revolutionize real estate with AI-driven lead prediction and management.', 'Revolutionize real estate with AI-driven lead prediction and management.', 'https://cdn.futurepedia.io/836f7fa7547e48ee271403bee0b9c1fb6bb067c7-2503x1228.png', 'https://offrs.com/', 'contact', '[]', 'beginner', false, '{"web"}', '{"Predictive Analytics","AI-Powered Lead Generation","Comprehensive Lead Management","Real-Time Data Access","Efficiency in Lead Generation","Cost-Effective Marketing"}', '{}', true, '{}', '{}', '', now()),
('Fliz', 'fliz', 'Transform text to engaging videos swiftly with AI-driven simplicity and creativity.', 'Fliz', 'https://cdn.futurepedia.io/8d2a0fe715314df189ddff095daf21cacf6a8ccc-2531x1251.png', 'https://fliz.ai/', 'freemium', '[{"plan": "Trial Offer", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Content Transformation","Multiple Video Styles","Custom Video Formats","Speedy Video Generation","User-Friendly Interface","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('InsightBase', 'insightbase', 'AI-driven analytics, no-code interface, custom coding options.', 'AI-driven analytics, no-code interface, custom coding options.', 'https://cdn.futurepedia.io/2026-02-27T11-17-33.201Z-yNpu0eIyuhoWXQvAPPlBtHtgosEVLWMd7.png', 'https://insightbase.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Powered Analytics","Visual Builder","Custom SQL and Javascript","Data Monitoring","Efficiency","Accessibility"}', '{}', true, '{}', '{}', '', now()),
('Zapt', 'zapt', 'Effortlessly create AI apps with no coding required.', 'Zapt is an innovative AI tool that empowers users to create AI applications effortlessly, without any coding expertise. Designed primarily for individuals and businesses seeking to streamline their processes through AI technology, Zapt simplifies the traditionally complex task of app development. Whether you''re a small business owner looking to automate workflows or a creative professional aiming to enhance your digital projects, Zapt provides a user-friendly platform to bring your AI ideas to life.', 'https://cdn.futurepedia.io/2026-02-27T11-17-31.561Z-VZsJd4gFxIaVEswYTCekbRpse0Yh-Co9q.png', 'https://www.zapt.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$29.99 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"No-Code Development","Rapid Deployment","Customizable Templates","AI-Driven Insights","User-Friendly","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Playcode', 'playcode', 'Describe it; get live, editable sites and apps.', 'Describe it; get live, editable sites and apps.', 'https://cdn.futurepedia.io/2026-03-26T19-38-33.869Z-roQeZTyNwyeesHuDPwBk4dJP8BXa_46c0.png', 'https://playcode.io/', 'freemium', '[{"plan": "Free", "price": "$0.", "features": []}, {"plan": "Playcode Pro", "price": "$21 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Conversational AI site builder","AI generated visuals","Visual editor plus real code","Built in hosting and PWAs","Fast idea to production","Friendly for non coders"}', '{}', true, '{}', '{}', '', now()),
('Casper AI', 'casper-ai', 'AI tool for summarizing content, enhancing productivity seamlessly.', 'Casper AI revolutionizes the way professionals digest and manage information, offering a seamless experience in summarizing articles, creating content, and sharing insights. As a Chrome extension, it is specifically designed for analysts, strategists, policymakers, and business developers, aiming to simplify their workflow and enhance productivity. By enabling users to quickly understand web pages and PDFs without reading every detail, Casper AI helps individuals stay updated on industry news, prepare for exams, research investments, and comprehend new laws effectively.', 'https://cdn.futurepedia.io/f625f56d82f33bff4f28962cebc6388807ad7c6d-1550x837.jpg', 'https://chrome.google.com/webstore/detail/casper-ai/fgfiokgecpkambjildjleljjcihnocel', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Summarization","Seamless Integration","Data Collection and Analysis","User-Friendly Interface","Time Efficiency","Enhanced Productivity"}', '{}', true, '{}', '{}', '', now()),
('Heidi', 'heidi', 'Streamline healthcare admin tasks, and enhance patient focus.', 'Streamline healthcare admin tasks, and enhance patient focus.', 'https://cdn.futurepedia.io/2026-02-27T11-17-37.760Z-Z9r_LU-zowcdzarZ42_pQFDgvrGKI-VhY.png', 'https://www.heidihealth.com/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$90 per user", "features": []}, {"plan": "Practice", "price": "$120 per user", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Scribe Functionality","Integration with EHR Systems","Customizable Templates","Real-time Transcription and Summarization","Time Efficiency","User-Centric Customization"}', '{}', true, '{}', '{}', '', now()),
('HeyMilo AI', 'heymilo-ai', 'Revolutionize hiring with AI-driven automated voice interviews.', 'HeyMilo AI revolutionizes the recruitment process with its generative AI-powered voice agents designed to conduct two-way conversational interviews at scale. Tailored for hiring managers, recruiters, and staffing agencies, it streamlines candidate evaluation, offering a seamless and interactive interview experience that adapts intelligently to each candidate''s responses. The tool is crafted to save time, enhance productivity, and ensure a fair assessment process.', 'https://cdn.futurepedia.io/ff5aa8874bf6368a7ce0ab1101b171f599075ace-1920x1080.png', 'https://www.heymilo.ai/', 'contact', '[]', 'beginner', false, '{"web"}', '{"Conversational AI Agents","Real-Time Insights","Customizable Interview Process","Seamless Integration","Time Efficiency","Scalability"}', '{}', true, '{}', '{}', '', now()),
('Topview AI', 'topview-ai', 'Turn product links into polished, viral-ready marketing videos.', 'Turn product links into polished, viral-ready marketing videos.', 'https://cdn.futurepedia.io/2026-02-04T16-48-36.554Z-OjAGCKUDZGl61G8c4yHLgOKgFQt5t7v29.webp', 'https://www.topview.ai/', 'freemium', '[{"plan": "Free Plan", "price": "$0 per month", "features": []}, {"plan": "Pro Plan", "price": "$29 per month", "features": []}, {"plan": "Business Plan", "price": "$75 per month", "features": []}, {"plan": "Enterprise Plan", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Avatars","Automated Video Generation","AI Script, Voice, and Auto-Caption","Product Anyshoot and Character Swap"}', '{}', true, '{}', '{}', '', now()),
('TradeOS AI', 'tradeos-ai', 'Turn trading ideas into 24/7 automated agents.', 'Turn trading ideas into 24/7 automated agents.', 'https://cdn.futurepedia.io/2026-02-16T14-36-48.934Z-ZznFTGkIiYcsu-HjO6LTfs32WC73G1iZT.blob', 'https://ai.tradeos.xyz/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Plus", "price": "$4.50 per month", "features": []}, {"plan": "Pro", "price": "$9.50 per month", "features": []}, {"plan": "Ultimate", "price": "Custom", "features": []}]', 'intermediate', false, '{"web"}', '{"Natural-language strategy builder","Multimodal technical analysis","24/7 autonomous agents","Unified Open Market for data","No-code automation for non-programmers","Scales personal “edge” across markets"}', '{}', true, '{}', '{}', '', now()),
('Replica Studios', 'replica-studios', 'Revolutionize voice production with realistic, multi-language AI technology.', 'Replica Studios is an innovative AI tool designed to revolutionize voice production in creative and professional environments. With its advanced voice AI and text-to-speech technology, Replica Studios offers a suite of tools that cater to various industries, including gaming, animation, film, and e-learning. By enabling users to generate realistic voice-overs and dialogues in multiple languages, this tool simplifies the process of creating dynamic vocal content without the need for extensive recording setups.', 'https://cdn.futurepedia.io/52865f10e30c2fd71702c2a20a64f0bcb3f9eebb-2509x1234.png', 'https://www.replicastudios.com/', 'paid', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Professional Plan", "price": "$24.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Realistic Voice Generation","Multi-Language Support","Voice Lab","Integration-Friendly","Versatility","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('MagicForm AI', 'magicform-ai', 'AI-driven tool for 24/7 lead qualification and conversion.', 'MagicForm AI is an innovative AI-powered tool tailored for lead generation, designed to streamline and enhance the top-of-funnel process by qualifying, converting, and following up with leads 24/7. Targeted at businesses looking to optimize their sales processes, Magic Form simplifies the lead management journey by learning about your business, engaging with potential customers, and providing personalized follow-ups, ensuring a seamless and efficient conversion process.', 'https://cdn.futurepedia.io/2025-01-21T17-47-56.104Z-BYwaAXTbPUMTQ5mrKbJepPPD66WuiKUjQ.PNG', 'https://www.magicform.ai/', 'freemium', '[{"plan": "Starter Plan", "price": "$49 per month", "features": []}, {"plan": "Professional Plan", "price": "$99 per month", "features": []}, {"plan": "Premium Plan", "price": "$399 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Learning Capabilities","Continuous Improvement","Customization and Integration","24/7 Availability","Scalable Solution"}', '{}', true, '{}', '{}', '', now()),
('Flowjin', 'flowjin', 'Transform long-form content into engaging clips with AI-driven repurposing.', 'Flowjin is a platform designed to meet the growing demand for short-form video content on social media platforms. By analyzing long-form audio or video content, Flowjin generates multiple short videos under one minute in just 10 minutes, making it effortless to scale content creation.', 'https://cdn.futurepedia.io/8e9d6a50263d8985ff5c5f210ddc088a0571bd7f-2507x1231.png', 'https://www.flowjin.com/', 'paid', '[]', 'beginner', false, '{"web"}', '{"AI-picked short videos","AI Video Editor","AI-Generated Audio Soundbites","AI Face Detection","Optimized for short-form videos","Text-based short-form video editor"}', '{}', true, '{}', '{}', '', now()),
('Siteline', 'siteline', 'Turn AI agent traffic into customers.', 'Turn AI agent traffic into customers.', 'https://cdn.futurepedia.io/2026-02-25T22-23-16.797Z-y8PTSFoSz1n42DJlNfcCIJaAmPdnY2VpR.png', 'https://siteline.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$49 per month", "features": []}, {"plan": "Scale", "price": "$99 per month", "features": []}, {"plan": "Pro", "price": "$299 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Agent Analytics","Prompt & Visibility Tracking","Citation Monitoring","Traffic & Conversion Analytics","AI search focus","Clear, actionable insights"}', '{}', true, '{}', '{}', '', now()),
('Syllaby', 'syllaby', 'AI tool automating educational content creation and collaboration.', 'Syllaby, found at syllaby.io, is an innovative AI tool designed to streamline content creation processes for businesses and individual professionals. By leveraging advanced AI-driven algorithms, Syllaby revolutionizes how users generate and organize educational content, making it particularly beneficial for educators, content creators, and digital marketers. Its core purpose is to simplify the development of structured syllabi and lesson plans, ensuring that users can focus more on delivering engaging and effective content rather than getting bogged down in administrative details.', 'https://cdn.futurepedia.io/2025-01-06T12-52-55.036Z-_gosn0BiMAYE0EvrbM48Dqr600-3GVjdH.PNG', 'https://www.syllaby.io/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$25 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Content Generation","Customizable Templates","Seamless Integration","Real-Time Collaboration","Time Efficiency","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('KwaKwa', 'kwakwa', 'Revolutionizes learning with personalized, bite-sized mobile courses.', 'Revolutionizes learning with personalized, bite-sized mobile courses.', 'https://cdn.futurepedia.io/2025-02-03T16-55-42.433Z-AaQ8sdJfeloVXtB1SZsgNHGhsPrQ7C-fv.png', 'https://kwakwa.com/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Generated Course Structure","AI-Powered Quiz Maker","Automated Video Captions","AI-Recommended Resources","Simplifies Course Creation","Enhances Learner Engagement"}', '{}', true, '{}', '{}', '', now()),
('Rodin', 'rodin', 'Effortlessly generate realistic 3D models with AI.', 'Effortlessly generate realistic 3D models with AI.', 'https://cdn.futurepedia.io/2026-02-27T11-17-09.379Z-Pv6g-qYmPHrMBR2ljwEPJ4hX7DAhqF7in.png', 'https://hyper3d.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Education", "price": "$15 per month", "features": []}, {"plan": "Creator", "price": "$20 per month", "features": []}, {"plan": "Business", "price": "$60 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Modeling","Real-Time Rendering","Intuitive Interface","Cross-Platform Compatibility","Time Efficiency","User-Friendly"}', '{}', true, '{}', '{}', '', now()),
('MarsCode', 'marscode', 'Revolutionize coding: real-time assistance, error detection, code optimization.', 'MarsCode is a cutting-edge AI-powered tool designed to revolutionize the way developers code and innovate. By integrating advanced machine learning algorithms, MarsCode offers real-time coding assistance, error detection, and automated code optimization. This tool is specifically tailored for software developers, data scientists, and IT professionals looking to enhance their productivity and streamline their development processes.', 'https://cdn.futurepedia.io/d90fef6e284808c70d72ecd3a46c78ac8b2b3190-2519x1236.png', 'https://marscode.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$19.99 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Smart Code Completion","Real-time Error Detection","Automated Code Optimization","Customizable Coding Templates","Enhanced Productivity","Increased Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Immersity AI', 'immersity-ai', 'Transform 2D images and videos into immersive 3D experiences.', 'Transform 2D images and videos into immersive 3D experiences.', 'https://cdn.futurepedia.io/91a81442fbea9536ced52d57e892656d5a172b61-2543x1305.png', 'https://www.immersity.ai/', 'freemium', '[]', 'beginner', false, '{"web"}', '{"Neural Depth Engine","Platform Compatibility","Time Efficiency","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Spiritt', 'spiritt', 'Empowers startups with planning, analysis, and networking tools.', 'Empowers startups with planning, analysis, and networking tools.', 'https://cdn.futurepedia.io/c09efbe217c99d286fb72232e7209a3530475870-1920x1080.jpg', 'https://spiritt.io/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Premium Tier", "price": "$29.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Robust Business Planning Tools","Market Analysis Capabilities","Financial Modeling","Mentorship and Networking Opportunities","Comprehensive Guidance","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Painnt', 'painnt', 'Transform photos into high-res art with 1000+ filters.', 'Transform photos into high-res art with 1000+ filters.', 'https://cdn.futurepedia.io/a68fa4d7354d2d336e59bb3702e730f974d140d9-1582x1224.png', 'https://apps.apple.com/us/app/painnt-art-cartoon-filters/id1106627874', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$4.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Extensive Filter Library","High-Resolution Output","Real-Time Preview","Multi-Platform Availability","Diverse Artistic Styles","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Goals', 'goals', 'Turns plain-language goals into adaptive daily tasks.', 'Turns plain-language goals into adaptive daily tasks.', 'https://cdn.futurepedia.io/2026-04-01T17-40-50.551Z-R14HG2VsjWEdhhMvnLJRGXLdeqB39SOVa.png', 'https://www.makegoals.app/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$1.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-generated step-by-step plans","One-action-per-day focus","Check-ins and adaptive feedback","Streaks and visual timelines","Reduces planning overhead","Keeps attention on action"}', '{}', true, '{}', '{}', '', now()),
('Bardeen AI', 'bardeen-ai', 'Automate workflows and enhance GTM productivity.', 'Automate workflows and enhance GTM productivity.', 'https://cdn.futurepedia.io/2026-02-27T11-17-10.900Z-X-nAblPMGzJrVDh1NrrxBQbM-Vd4tfgv7.png', 'https://www.bardeen.ai/', 'paid', '[{"plan": "Starter", "price": "$129 per month", "features": []}, {"plan": "Teams", "price": "$500 per month", "features": []}, {"plan": "Enterprise", "price": "$1,500 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Magic Box","No-Code Builder","CRM Enrichment","AI Web Scraper","Time Efficiency","Integration Capabilities"}', '{}', true, '{}', '{}', '', now()),
('Ambience', 'ambience', 'Transform tabs into inspiring, visually rich workspaces with AI art and quotes.', 'Transform tabs into inspiring, visually rich workspaces with AI art and quotes.', 'https://cdn.futurepedia.io/bd05a37d34c629c2bf467c3557c369ed524e804b-2560x1172.jpg', 'https://chrome.google.com/webstore/detail/ambience-ai-wallpapers-qu/ndgjbbjefciomenkpggaepmhbkhmapap', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Generated Wallpapers","Inspirational Quotes","Leap API Integration","Interactive Experience","Constantly Refreshing Content","Inspiration on Demand"}', '{}', true, '{}', '{}', '', now()),
('Donely', 'donely', 'Run OpenClaw employees fleetwide without managing servers.', 'Run OpenClaw employees fleetwide without managing servers.', 'https://cdn.futurepedia.io/2026-03-17T17-41-51.350Z-XPvTQctmmcpn1jDCF1ZRt8h4TPVve7Sc5.png', 'https://donely.ai/', 'freemium', '[{"plan": "Free Forever", "price": "$0 per month", "features": []}, {"plan": "Personal", "price": "$25", "features": []}, {"plan": "Team", "price": "$50", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Multi instance OpenClaw control","AI employees marketplace","Deep integrations","Security and governance","Fast to ship","Scales neatly"}', '{}', true, '{}', '{}', '', now()),
('Lambda', 'lambda', 'Deploy GPU clusters swiftly; extensive AI model training support.', 'Deploy GPU clusters swiftly; extensive AI model training support.', 'https://cdn.futurepedia.io/289aaf4579ab68186a0db2e761244bdfd50f118a-1920x1080.png', 'https://lambdalabs.com/', 'contact', '[{"plan": "On-Demand Cloud", "price": "$2.49", "features": []}]', 'beginner', false, '{"web"}', '{"1-Click Clusters","Versatile Product Range","Cutting-edge Technology","Lambda Stack","Scalability","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Evalyze', 'evalyze', 'Use AI to target investors and refine pitches.', 'Use AI to target investors and refine pitches.', 'https://cdn.futurepedia.io/2026-03-17T03-50-17.450Z-AvP56rPG2vMekqaUcSjRO0sjgwK_OGStO.png', 'https://evalyze.ai/', 'freemium', '[{"plan": "Starter", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$20 per month", "features": []}, {"plan": "Managed", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Startup Analyzer & Investment Readiness Score","Pitch Deck Analysis & Coaching","Advanced Investor Discovery","Fundraising Workflow Support","Better investor targeting","Useful fundraising feedback"}', '{}', true, '{}', '{}', '', now()),
('Originality.AI', 'originality-ai', 'Detects AI content, checks plagiarism, verifies facts efficiently.', 'Originality.AI is a cutting-edge tool designed to ensure the integrity of digital content in the era of AI-generated text. Tailored for web publishers, content marketers, and writers, it provides robust features including AI content detection, plagiarism checking, and fact verification, ensuring original and accurate content.', 'https://cdn.futurepedia.io/28759a2e38d82a28f322ce34a8202bf2d6ad98c7-2513x1237.png', 'https://originality.ai/', 'paid', '[{"plan": "Pay As You Go", "price": "$30", "features": []}, {"plan": "Pro Plan", "price": "$14.95", "features": []}, {"plan": "Enterprise Plan", "price": "$179", "features": []}]', 'beginner', false, '{"web"}', '{"Most Accurate AI Content Detector","Plagiarism Checker","Fact Checking Aid","Readability Score Analysis","Enhanced Content Integrity","Efficiency in Content Verification"}', '{}', true, '{}', '{}', '', now()),
('Amazon Sage Maker', 'amazon-sage-maker', 'AI-powered tool for precise, scalable business forecasting.', 'AI-powered tool for precise, scalable business forecasting.', 'https://cdn.futurepedia.io/2025-01-31T23-11-19.949Z-nACkzwRedhpcJdcquociqqtSgM3osYRef.PNG', 'https://aws.amazon.com/sagemaker/', 'freemium', '[{"plan": "AWS Free Tier", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"Machine Learning Integration","Scalability","Granular Forecasting","AWS Free Tier","High Accuracy","Automation"}', '{}', true, '{}', '{}', '', now()),
('Conversica', 'conversica', 'AI-driven customer engagement, 24/7, with CRM integration.', 'AI-driven customer engagement, 24/7, with CRM integration.', 'https://cdn.futurepedia.io/928b54b38da0235dc05b0c27ac8f7af7ad255b5f-2509x1226.png', 'https://www.conversica.com/', 'contact', '[{"plan": "Standard Plan", "price": "$2,999 per month", "features": []}, {"plan": "Pro Plan", "price": "$4,999 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Conversations","Lead Scoring and Qualification","24/7 Availability","Customizable AI Personalities","Enhanced Engagement","Increased Conversion Rates"}', '{}', true, '{}', '{}', '', now()),
('VidMage', 'vidmage', 'Effortlessly transform faces in photos and videos.', 'Effortlessly transform faces in photos and videos.', 'https://cdn.futurepedia.io/2026-02-27T11-17-12.500Z-E1eGRGD9iGOUSYVAOPKPv2vcmEEW8Iu_Z.png', 'https://vidmage.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Monthly Plan", "price": "$9.99 per month", "features": []}, {"plan": "Yearly Plan", "price": "$5.83 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Face Swap","Multi Face Swap","Celebrity and Movie Role Swap","Head Swap and Face Morphing","User-Friendly Experience","High-Quality Output"}', '{}', true, '{}', '{}', '', now()),
('Wondershare Virbo', 'wondershare-virbo', 'AI-driven video creation with realistic avatars and customization.', 'WonderShare Virbo is an AI-powered video marketing solution designed to streamline the creation of engaging video content. As a one-stop platform, Virbo offers a suite of tools that enable users to generate AI-driven videos with realistic avatars, making it an ideal choice for businesses, marketers, educators, and content creators looking to enhance their video marketing strategies. With its comprehensive features, Virbo simplifies the process of video creation, allowing users to produce high-quality content efficiently and effectively.', 'https://cdn.futurepedia.io/2026-02-27T11-17-41.361Z-5ivyk2WvXYgPVrAQFDeuQUzFJ77VYxpGf.png', 'https://click.linksynergy.com/fs-bin/click?id=GSx8STe5NEU&offerid=764692.911&type=3&subid=0', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$9.9 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Video Generator","AI Montage Maker","Text to Video Conversion","AI Voice Generator","Time Efficiency","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('BrandWell', 'brandwell', 'Boost brand growth with AI-driven content and insights.', 'BrandWell is a comprehensive AI-driven platform designed to facilitate brand growth and development. It offers an all-in-one solution that integrates content creation, SEO optimization, and brand intelligence to enhance online visibility and authority. Primarily targeted at marketers, agencies, and content creators, BrandWell simplifies the process of generating high-quality, SEO-optimized content that drives traffic and revenue.', 'https://cdn.futurepedia.io/2025-02-05T22-51-45.978Z-Zj588GU9wUHWN5sciJYT3LtETN1m7jxpY.png', 'https://brandwell.ai/', 'paid', '[{"plan": "Essentials", "price": "$249", "features": []}, {"plan": "Agency", "price": "$499", "features": []}]', 'beginner', false, '{"web"}', '{"WriteWell AI Writing Assistant","TrafficID","Content Intelligence Suite","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('ChatComparison.ai', 'chatcomparison-ai', 'Side-by-side comparisons of leading chatbot models.', 'Side-by-side comparisons of leading chatbot models.', 'https://cdn.futurepedia.io/2026-02-27T11-17-43.192Z-NB_L_8vsp9iPyhblg9xMnYHSfaUR-z1TI.png', 'https://www.chatcomparison.ai/', 'freemium', '[{"plan": "Monthly Plan", "price": "$33.50 per month", "features": []}, {"plan": "Annual Plan", "price": "$17.50 per month", "features": []}, {"plan": "Lifetime Deal", "price": "$575.00", "features": []}]', 'beginner', false, '{"web"}', '{"Comprehensive Comparisons","User-Friendly Interface","Regular Updates","Expert Analysis","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('CoupleWork', 'couplework', 'Talk through conflicts and get relationship coaching.', 'Talk through conflicts and get relationship coaching.', 'https://cdn.futurepedia.io/2026-03-16T18-42-13.472Z-5n7MCI1exshOS9kCLqNJ0vnLx5EM1x7-R.png', 'https://couplework.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Monthly Individual", "price": "$24.95 per month", "features": []}, {"plan": "3-Month Individual", "price": "$64.90", "features": []}, {"plan": "Annual Individual", "price": "$249.00 per year", "features": []}]', 'beginner', false, '{"web"}', '{"Personalized AI Coaching","Structured Sessions","Relationship Assessment","Voice And Text Interaction","Clear Focus","Useful Structure"}', '{}', true, '{}', '{}', '', now()),
('StageHQ AI', 'stagehq-ai', 'Instantly furnish rooms with photorealistic virtual staging.', 'Instantly furnish rooms with photorealistic virtual staging.', 'https://cdn.futurepedia.io/2026-02-27T11-17-16.420Z-EiqoZJ2HKTU703O-uTeQQDZAdx_HT69B4.png', 'https://stagehq.ai/', 'paid', '[{"plan": "20 AI Staged Photos", "price": "$19", "features": []}, {"plan": "100 AI Staged Photos", "price": "$39", "features": []}, {"plan": "250 AI Staged Photos", "price": "$69", "features": []}]', 'beginner', false, '{"web"}', '{"Instant Virtual Staging","Multiple Modes","Variety of Styles","User-Friendly Interface","Time Efficiency","Photorealistic Results"}', '{}', true, '{}', '{}', '', now()),
('Tobira', 'tobira', 'Turn scattered agents into a coordinated, governed network.', 'Turn scattered agents into a coordinated, governed network.', 'https://cdn.futurepedia.io/2026-03-26T19-35-17.010Z-zaK5D3PxBCBKnK_WKpqB2DEdW3hTHvVBb.png', 'https://tobira.ai/', 'free', '[]', 'beginner', false, '{"web"}', '{"Standardized Invocation Interface","Multi Agent Orchestration","Identity and Reputation Signals","Monitoring and Governance","Infrastructure Offload","Reusability"}', '{}', true, '{}', '{}', '', now()),
('ThumbnailAI', 'thumbnailai', 'Maximize clicks with AI-driven thumbnail effectiveness ratings.', 'ThumbnailAI is a valuable tool tailored for content creators, particularly YouTubers and social media marketers, seeking to optimize their thumbnails to attract more clicks and engagement. In today''s competitive digital landscape, where attention spans are short and visual appeal is crucial, ThumbnailAI offers an AI-powered solution to evaluate and enhance the effectiveness of YouTube thumbnails.', 'https://cdn.futurepedia.io/545a995d2c089b8b93fcde48d016c04c516f80d2-1767x903.jpg', 'https://thumbnail-ai.ybouane.com/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Rating System","User-Friendly Interface","Visual Appeal Analysis","Performance Tracking","Increased Engagement","Data-Driven Decisions"}', '{}', true, '{}', '{}', '', now()),
('Swapp', 'swapp', 'Revolutionize architectural documentation with AI-powered automation and bespoke integration.', 'Revolutionize architectural documentation with AI-powered automation and bespoke integration.', 'https://cdn.futurepedia.io/2026-02-27T11-17-17.993Z-CLBQRQteJgc8qJRpvc1KKoxdTBK7iqb8O.png', 'https://www.swapp.ai/', 'contact', '[{"plan": "Custom Pricing", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Documentation","AI-Quality Results","Seamless Integration","Data Security","Increased Efficiency","Enhanced Profitability"}', '{}', true, '{}', '{}', '', now()),
('Creatify', 'creatify', 'Transform product links into captivating video ads effortlessly with AI.', 'Transform product links into captivating video ads effortlessly with AI.', 'https://cdn.futurepedia.io/706f0ec69cb643e5111ed84b5851e33554c0f9ff-2519x1223.png', 'https://creatify.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Creator Tier", "price": "$27", "features": []}, {"plan": "Business Tier", "price": "$135", "features": []}, {"plan": "Enterprise Tier", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-powered Script Generator","One-click Output Rendering","Diverse Voice and Avatar Selection","Comprehensive Video Editor","Efficiency in Ad Creation","Cost-Effectiveness"}', '{}', true, '{}', '{}', '', now()),
('Eve Legal', 'eve-legal', 'AI-driven legal tool streamlining case management for plaintiff firms.', 'AI-driven legal tool streamlining case management for plaintiff firms.', 'https://cdn.futurepedia.io/2025-02-14T20-07-17.883Z-8zRirnTpaNUwLPI-zSVMOduOSuWWo2rzU.png', 'https://www.eve.legal/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Case Intake and Evaluation","Document Drafting","Propounding Discovery","Responding to Discovery","Time Efficiency","Increased Case Capacity"}', '{}', true, '{}', '{}', '', now()),
('Plus AI', 'plus-ai', 'Transform Google Slides with intuitive, multilingual AI tools.', 'In the ever-evolving world of digital presentations, Plus AI emerges as a revolutionary tool, especially designed for Google Slides users. This AI-driven platform enhances the process of creating and editing presentations by integrating seamlessly with Google Slides, making it a go-to solution for anyone looking to elevate their presentation game without the steep learning curve of new software. Whether you''re generating a new presentation from a simple prompt or refining an existing deck, Plus AI simplifies these tasks with its intuitive AI features.', 'https://cdn.futurepedia.io/032da3417224641db359f045481a29291933acf3-2523x1241.png', 'https://www.plusdocs.com/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Prompt to Presentation","Document to Presentation","AI in Any Language","Edit Slides with AI","Efficiency","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Book Summaries', 'book-summaries', 'Unlock book insights quickly: summaries, quotes, critical analysis.', 'Unlock book insights quickly: summaries, quotes, critical analysis.', 'https://cdn.futurepedia.io/b2547dcd9b3c15610fdd17c9ff167862728c9664-2477x1226.png', 'https://books.audioread.com/', 'free', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Extensive Library","User-Friendly Interface","Quality Insights","Regular Updates","Time Efficiency","Variety of Topics"}', '{}', true, '{}', '{}', '', now()),
('Mexty', 'mexty', 'Create interactive, hyper-personalized e-learning content.', 'Mexty is an innovative AI-driven platform that redefines the creation of personalized learning content. Tailored for educators, trainers, and instructional designers, this tool simplifies the process of building interactive, SCORM-compliant e-learning materials. With Mexty, users can craft engaging lessons, quizzes, and assessments effortlessly, catering to diverse learning styles without the need for coding skills.', 'https://cdn.futurepedia.io/2026-02-27T11-17-19.538Z-RLBl5R1UoCLP9FkfeurVUdsIbm56q66j3.png', 'https://mexty.ai/', 'freemium', '[{"plan": "Free Plan", "price": "$0 per month", "features": []}, {"plan": "Creator Plan", "price": "$9.80 per month", "features": []}, {"plan": "Professional Plan", "price": "$31.60 per month", "features": []}, {"plan": "Enterprise Plan", "price": "Custom", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Powered Lesson Creator","Interactive & Gamified Learning","No-Code Authoring","Multilingual Support","Time Efficiency","Personalization at Scale"}', '{}', true, '{}', '{}', '', now()),
('Overchat AI', 'overchat-ai', 'Chat, write, design images, craft short videos together', 'Chat, write, design images, craft short videos together', 'https://cdn.futurepedia.io/2026-03-31T17-55-53.937Z-i6QrCmPPSDHDVl2SFyzZtnF0xKuPB7GBi.png', 'https://overchat.ai/', 'freemium', '[{"plan": "Free", "price": "$0.", "features": []}, {"plan": "Pro Access", "price": "$59.99 per year", "features": []}]', 'beginner', false, '{"web"}', '{"Multi‑model hub","Text, image, and video generation","Prebuilt chatbots","Cross‑platform access","One subscription for many frontier models","Strong creative toolkit"}', '{}', true, '{}', '{}', '', now())
ON CONFLICT (slug) DO NOTHING;

-- Category assignments
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'design-com' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'dcipher-insight-booster' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'dcipher-insight-booster' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'logoai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'tutorai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'noisee-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'jinna-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'saywhatt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'aidelly' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'aidelly' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'caffeine' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'studyx' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'layer-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'layer-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ask-layla' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ceartas-dmca' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'minion-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'minion-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'wisedocs' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ai-home-design' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'whoop' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'marketalerts-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'marketalerts-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'wegic' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'wegic' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'coris' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'unriddle' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'unriddle' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'publicai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'xpander-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'leya-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'nabla' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'falcon-llm' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = '1forall' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = '1forall' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'microsoft-designer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'gigasheet' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'adobe-photoshop' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'jasper-art' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'profile-picture-maker' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'profile-picture-maker' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'datasnipper' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'datasnipper' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'jace' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'jace' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'jace' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'pykaso-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'magicphotos' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'magicphotos' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'durable-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'zoer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'freepik-ai-voice-generator' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'freepik-ai-voice-generator' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'freepik-ai-voice-generator' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'harmonai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'air' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'systran' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'murmurcast' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'murmurcast' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'murmurcast' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'monica' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'monica' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'giftpack' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'giftpack' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'giftpack' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'seowritex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'seowritex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'parspec' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'text2sql' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'text2sql' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'postsam' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'tennr' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'liberate' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'toolspend' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'deci' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'hear' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'vmake' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'offrs' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'offrs' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'fliz' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'insightbase' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'insightbase' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'zapt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'playcode' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'casper-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'casper-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'casper-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'heidi' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'heidi' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'heymilo-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'heymilo-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'topview-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'tradeos-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'replica-studios' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'replica-studios' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'replica-studios' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'magicform-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'magicform-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'flowjin' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'flowjin' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'siteline' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'syllaby' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'syllaby' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'kwakwa' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'kwakwa' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'rodin' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'marscode' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'immersity-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'spiritt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'painnt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'painnt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'goals' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'bardeen-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ambience' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'donely' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'lambda' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'evalyze' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'originality-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'amazon-sage-maker' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'conversica' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'conversica' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'conversica' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'vidmage' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'vidmage' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'vidmage' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'wondershare-virbo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'brandwell' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'brandwell' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'chatcomparison-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'chatcomparison-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'couplework' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'couplework' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'stagehq-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'tobira' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'thumbnailai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'swapp' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'creatify' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'eve-legal' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'plus-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'plus-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'book-summaries' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'book-summaries' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'mexty' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'overchat-ai' ON CONFLICT DO NOTHING;

