-- ============================================================
-- Batch 16: 100 AI tools (auto-scraped from Futurepedia)
-- ============================================================

INSERT INTO tools (name, slug, tagline, description, logo_url, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('AICarousels', 'aicarousels', 'Create stunning social media carousels with AI-driven ease.', 'Create stunning social media carousels with AI-driven ease.', 'https://cdn.futurepedia.io/b274e0c380e97ff0f792d38b81c80811c5c445e9-2521x1237.png', 'https://www.aicarousels.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Writing Assistant","Auto-Resize Functionality","Predefined Colors & Fonts","Fully Customizable Templates","User-Friendly Interface","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('StreamAlive', 'streamalive', 'Turn live chat into polls, games, insights.', 'Turn live chat into polls, games, insights.', 'https://cdn.futurepedia.io/2026-02-27T11-17-57.641Z-0RirSdd4s5NFnPWUNfhgRKEErg0L2_yXD.png', 'https://www.streamalive.com/', 'freemium', '[{"plan": "Free", "price": "Free", "features": []}, {"plan": "Starter", "price": "$40 per month", "features": []}, {"plan": "Pro", "price": "$100 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Chat-powered visuals","AI Interaction Generator and templates","Chat intelligence and analytics","Integrations and presentation builder","Low-friction for participants","Visually rich sessions"}', '{}', true, '{}', '{}', '', now()),
('Flakes', 'flakes', 'Browse by keyboard on Mac with tab-aware AI.', 'Browse by keyboard on Mac with tab-aware AI.', 'https://cdn.futurepedia.io/2026-02-27T11-17-21.059Z-0BMdxcmXN3e5w6L3q4wkcvsROFPKSKotr.png', 'https://flakes.ai/', 'free', '[{"plan": "Free download for macOS", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Keyboard-first navigation","Command palette (⌘K)","Focus mode and smart history","Productivity focused design","High efficiency for keyboard users"}', '{}', true, '{}', '{}', '', now()),
('Reshot AI', 'reshot-ai', 'AI-enhanced photo editor for professional headshots and thumbnails.', 'AI-enhanced photo editor for professional headshots and thumbnails.', 'https://cdn.futurepedia.io/dCMqHQg7g4MDxvRSTAjT76.png', 'https://www.reshot.ai/', 'paid', '[{"plan": "Monthly Plan", "price": "$19 per month", "features": []}, {"plan": "Yearly Plan", "price": "$9 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Edits","Expression Tweaks","Pose and Lighting Adjustments","Background Editing","Time Efficiency","Professional Quality"}', '{}', true, '{}', '{}', '', now()),
('Moderne', 'moderne', 'Transform codebases swiftly with AI-driven refactoring and security.', 'Transform codebases swiftly with AI-driven refactoring and security.', 'https://cdn.futurepedia.io/eee201b26365a00b01468402fc40fe293ff8a90d-2515x1231.png', 'https://www.moderne.io/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Custom Enterprise Solutions", "price": "Custom", "features": []}]', 'intermediate', false, '{"web"}', '{"Multi-repo Code Refactoring","Automated Vulnerability Remediation","AI-Driven Code Analysis","OpenRewrite Community Support","Enhanced Security","Increased Developer Productivity"}', '{}', true, '{}', '{}', '', now()),
('Leni', 'leni', 'Transforms complex real estate data into actionable, AI-driven insights.', 'Transforms complex real estate data into actionable, AI-driven insights.', 'https://cdn.futurepedia.io/c19bf29e87c58eeaaf4da22b7f80870b20d5a8a0-1920x1080.png', 'https://leni.co/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Asset Management Analytics","Leasing Convert","Revenue Management Price","Marketing & Engagement Engage","Data-Driven Decision Making","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Powtoon', 'powtoon', 'Create engaging videos from ideas instantly.', 'Create engaging videos from ideas instantly.', 'https://cdn.futurepedia.io/2026-02-27T11-17-23.721Z-AZdaWeq779NC9CO6L02rHYin3pvJBL6Ir.png', 'https://www.powtoon.com/ai/', 'paid', '[{"plan": "Lite", "price": "$49 per month", "features": []}, {"plan": "Professional", "price": "$99 per month", "features": []}, {"plan": "Business", "price": "$125 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Video Generator","AI Scriptwriter","AI Text-to-Speech","AI Avatars","User-Friendly Interface","Time-Saving Automation"}', '{}', true, '{}', '{}', '', now()),
('PowerMode AI', 'powermode-ai', 'Optimize business operations with AI-driven insights and automation.', 'PowerMode AI is an innovative tool designed to harness the capabilities of artificial intelligence to transform the way businesses operate. Its core purpose revolves around optimizing operations, enhancing decision-making, and driving efficiency through smart, data-driven insights. As someone who has explored numerous AI tools, I can attest that PowerMode AI stands out for its focus on empowering organizations to unlock their full potential by leveraging advanced AI technologies.', 'https://cdn.futurepedia.io/d7d69165c1dc264bd79dae26d40c3a8971c03b72-1856x932.jpg', 'https://powermodeai.com/', 'free', '[{"plan": "Custom Pricing", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Insights","Automation Capabilities","Customization Options","Scalability","Increased Productivity","Data-Driven Strategy"}', '{}', true, '{}', '{}', '', now()),
('Amira Learning', 'amira-learning', 'Revolutionizing reading with AI-driven, personalized tutoring.', 'Revolutionizing reading with AI-driven, personalized tutoring.', 'https://cdn.futurepedia.io/b07cd38f432636ebad872cde5fdb48bf71d64294-1920x1080.jpg', 'https://www.amiralearning.com/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Reading Assistance","Personalized Learning","Research-Driven","Comprehensive Reporting","Enhanced Reading Outcomes","Time-Efficient"}', '{}', true, '{}', '{}', '', now()),
('GobbleCube', 'gobblecube', 'Transform data into insights with AI-powered analysis and visualization.', 'Transform data into insights with AI-powered analysis and visualization.', 'https://cdn.futurepedia.io/7879ff265c67b5bf05e87dd3889407f9a977025f-1920x1080.png', 'https://gobblecube.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$49.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Analytics","Interactive Dashboards","Automated Reporting","Scalable Infrastructure","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Applaime', 'applaime', 'Revolutionize job applications with AI: ATS optimization, personalized materials, interview prep.', 'In the ever-evolving job market, standing out from the crowd has become more crucial than ever. Applaime emerges as a beacon of hope for job seekers, revolutionizing the way we approach job applications. This', 'https://cdn.futurepedia.io/2026-02-27T11-17-25.720Z-RxbyYw76rwCGbPw5YKPXaxZxi4ltzoCAP.png', 'https://www.applaime.com/', 'free', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"ATS-Friendly Strategies","Personalized Cover Letter Generator","Customized CV Profile Summary","Job Interview Preparation Wizard","Increased Job Application Success","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Finden', 'finden', 'Organize and analyze data across all of your platforms.', 'Organize and analyze data across all of your platforms.', 'https://cdn.futurepedia.io/2026-02-04T16-40-48.307Z-IQIbd_jKPaTdRcq72TMuLb4KvO-sEs3e3.webp', 'https://www.finden.me/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Unified Data Access","AI-Powered Insights","Smart File Organization","Instant Data Answers","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('SEOZilla', 'seozilla', 'Auto-generate and publish long-form SEO blog content.', 'Auto-generate and publish long-form SEO blog content.', 'https://cdn.futurepedia.io/2026-04-02T16-18-32.918Z-oSJ_BMXtjk65bxakBPMHq1Ffu2ndBDX-6.png', 'https://www.seozilla.ai/', 'paid', '[{"plan": "Basic", "price": "$19.99 per month", "features": []}, {"plan": "Starter", "price": "$49.99 per month", "features": []}, {"plan": "Pro", "price": "$99.99 per month", "features": []}, {"plan": "Ultimate", "price": "$189.99 per month", "features": []}, {"plan": "Ultimate+", "price": "$299.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI SEO + GEO content engine","Site and brand analysis","Human style long form output","Built in internal linking","Serious time savings","Human sounding focus"}', '{}', true, '{}', '{}', '', now()),
('DomoAI', 'domoai', 'Create lifelike videos from text and images.', 'Create lifelike videos from text and images.', 'https://cdn.futurepedia.io/2025-08-13T15-57-08.919Z-7Reg19FkeLD9x_lhJAdwdqPzmZgk3C-WJ.png', 'https://www.domoai.app/home', 'freemium', '[{"plan": "Basic", "price": "$9.99 per month", "features": []}, {"plan": "Standard", "price": "$27.99 per month", "features": []}, {"plan": "Pro", "price": "$69.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Video Generation","Image to Video Animation","Talking Avatars","Smart Editing Tools","Time Efficiency","Versatility"}', '{}', true, '{}', '{}', '', now()),
('Procurement Sciences AI', 'procurement-sciences-ai', 'Optimizes procurement, automates processes, enhances decision-making.', 'Optimizes procurement, automates processes, enhances decision-making.', 'https://cdn.futurepedia.io/c53265b629d844bb1520026c658b62c6cfc684a2-1920x1080.png', 'https://procurementsciences.com/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Standard Plan", "price": "$200 per month", "features": []}, {"plan": "Enterprise Solutions", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Data-Driven Insights","Automated Procurement Processes","Risk Management Tools","Customizable Dashboards","Increased Efficiency","Enhanced Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Creatify AI Product Video Generator', 'creatify-ai-product-video-generator', 'Transforms product images into dynamic marketing videos.', 'Transforms product images into dynamic marketing videos.', 'https://cdn.futurepedia.io/2025-05-07T23-11-40.270Z-wV3isk956SPIQrl6Ks90dW_ychUP8E2el.png', 'https://creatify.ai/features/product-video?amp%3Butm_medium=marketplace&amp%3Butm_campaign=futurepedia', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$39 per month", "features": []}, {"plan": "Pro", "price": "$99 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Image-to-Video Conversion","Multiple Style Options","Instant Variations","Rapid Delivery","Cost Efficiency","Speed"}', '{}', true, '{}', '{}', '', now()),
('Viyou AI', 'viyou-ai', 'Turn prompts and selfies into scroll-stopping social videos.', 'Turn prompts and selfies into scroll-stopping social videos.', 'https://cdn.futurepedia.io/2026-03-16T18-29-03.880Z-zbaCp4LXuF4IQdffzqIpR-wWnOzS4gPv0.png', 'https://viyou.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Lite", "price": "$39.99 per year", "features": []}, {"plan": "Pro", "price": "$69.99 per year", "features": []}, {"plan": "Max", "price": "$199.99 per year", "features": []}]', 'beginner', false, '{"web"}', '{"Multi-model video generation","Full AI image suite","Template driven effects","Custom AI video and image pipelines","Large model catalog","Strong social focus"}', '{}', true, '{}', '{}', '', now()),
('Glambase', 'glambase', 'An AI Influencer Creation Platform, empowering users to create ultra-realistic AI models and earn autonomously as their virtual personas engage with and generate exclusive content for audiences.', 'Glambase is an AI Influencer Creation Platform that allows users to create ultra-realistic AI models and earn autonomously. With Glambase, users can develop virtual personas that interact with audiences and generate exclusive content, including posts and images, offering a unique way to monetize digital interactions without the need for physical presence. Ideal for entrepreneurs, influencers, and creatives, Glambase simplifies managing a digital influencer and opens new earning opportunities through AI-driven content.', 'https://cdn.futurepedia.io/649f0eec65ac2dc3e1e01cc4a57e168558fa1f85-2522x1237.png', 'https://glambase.app/', 'freemium', '[{"plan": "Early Access Price", "price": "$223,", "features": []}]', 'beginner', false, '{"web"}', '{"Character Customization","Content Generation","Autonomous Influencer","Real-Time Analytics"}', '{}', true, '{}', '{}', '', now()),
('Wuri', 'wuri', 'Effortlessly create engaging videos with AI avatars.', 'Effortlessly create engaging videos with AI avatars.', 'https://cdn.futurepedia.io/2026-02-04T16-49-57.521Z-gfrHnu8gwpLLQWnhFpgd8EUR219qnHt42.webp', 'https://www.wuri.ai/', 'freemium', '[{"plan": "Basic Plan", "price": "$0 per month", "features": []}, {"plan": "Starter Plan", "price": "$10 per month", "features": []}, {"plan": "Pro Plan", "price": "$20 per month", "features": []}, {"plan": "Ultimate Plan", "price": "$60 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Video Editing","Faceless AI Avatars","Content Generation Tools","Customization and Flexibility","Efficiency in Video Production","Innovative Avatars"}', '{}', true, '{}', '{}', '', now()),
('Sloyd', 'sloyd', 'Revolutionize 3D model creation with AI, no experience needed.', 'Revolutionize 3D model creation with AI, no experience needed.', 'https://cdn.futurepedia.io/2026-02-27T11-17-44.893Z-TOpyjQrvx7hP448zwYaXNcGpV1z_rINSr.png', 'https://www.sloyd.ai/', 'contact', '[{"plan": "Free Access", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Extensive 3D Model Library","AI-Powered Customization","Ready-to-Use Models","Versatile Model Generation","Speed and Efficiency","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Autosana', 'autosana', 'Automate mobile app testing with AI-driven precision.', 'Automate mobile app testing with AI-driven precision.', 'https://cdn.futurepedia.io/2026-02-27T11-17-46.441Z-RqXM02UMH-LAwNjl7QMw75axP9dQFiOXd.png', 'https://autosana.ai/', 'paid', '[{"plan": "Paid", "price": "$500 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Powered Testing","Real-Time Feedback","User-Friendly Interface","Scalable Solutions","Time Efficiency","Accuracy"}', '{}', true, '{}', '{}', '', now()),
('SheetAI.app', 'sheetai-app', 'Unleash AI in Google Sheets: automate, analyze, and create effortlessly.', 'SheetAI App is a transformative tool that infuses the capabilities of artificial intelligence directly into Google Sheets. It''s designed to empower users to automate complex tasks, generate insightful data analysis, and even create content within their spreadsheets. By integrating AI functions such as SHEETAI_BRAIN, SHEETAI_LIST, and SHEETAI_FILL, SheetAI App simplifies spreadsheet management and', 'https://cdn.futurepedia.io/e1267955992d7579abcf3ceb21dc79df3349e613-1870x957.jpg', 'https://sheetai.app/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Efficient Copywriting with SHEETAI_BRAIN","Generate Multiple Answers with SHEETAI_LIST","Populate Data with SHEETAI_FILL","AI-Powered Insights","Enhanced Productivity","Intuitive AI Integration"}', '{}', true, '{}', '{}', '', now()),
('LOVO', 'lovo', 'Harness AI to create lifelike, multilingual voiceovers with emotional depth.', 'LOVO is an AI-powered voice generator that converts text into speech with remarkable human-like quality. Tailored for content creators, marketers, educators, and professionals, LOVO simplifies the creation of dynamic and authentic voiceovers for multimedia projects. With its advanced text-to-speech engine, LOVO offers a wide selection of voices in various languages and styles, making it a versatile solution for enhancing audio content.', 'https://cdn.futurepedia.io/77af1626b15e54ce84d5034dc10d54eea76cc586-1920x909.png', 'https://lovo.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Text to Speech","Voice Cloning","Emotion Expression","Multilingual Support","Realistic Voices","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Apriora', 'apriora', 'Streamline decision-making with AI-powered predictive analytics.', 'Streamline decision-making with AI-powered predictive analytics.', 'https://cdn.futurepedia.io/8c8dd465b473cef614d9803dd4004e921c6d8d3c-1920x1080.png', 'https://www.apriora.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Starter Plan", "price": "$30 per month", "features": []}, {"plan": "Enterprise Solution", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Scheduling","Live Interviewing","Instant Feedback","Customizable Interviewers","Efficient Scheduling","Interactive Interviews"}', '{}', true, '{}', '{}', '', now()),
('Lakera', 'lakera', 'AI''s ultimate shield: real-time threat detection, privacy, compliance.', 'AI''s ultimate shield: real-time threat detection, privacy, compliance.', 'https://cdn.futurepedia.io/2eeb56f14a4900ef705e8d89df028ee28adbc848-1920x1080.png', 'https://www.lakera.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Real-time Threat Detection","Comprehensive AI Security Suite","Advanced Red Teaming Tools","Privacy and Compliance Tools","Cutting-edge Security Features","Ease of Integration"}', '{}', true, '{}', '{}', '', now()),
('TalkPal', 'talkpal', 'Master languages with AI: immersive learning, instant feedback, multi-platform.', 'TalkPal is an innovative AI-powered language tutor designed to provide an immersive learning experience for those who wish to master new languages. With the use of GPT-powered technology, it offers users the opportunity to engage in unlimited conversations on a plethora of topics, enhancing their language skills across listening, speaking, reading, and writing. It is not just a learning tool but a comprehensive language partner that adapts to your individual pace and learning style.', 'https://cdn.futurepedia.io/8501516ae416fcd7ac254a1664ed2e56aff87d36-1918x892.png', 'http://talkpal.ai/', 'free', '[{"plan": "Basic Plan", "price": "Free", "features": []}, {"plan": "Premium 1 Month", "price": "$9.99 per month", "features": []}, {"plan": "Premium 12 Months", "price": "$4.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"GPT-Powered Conversations","Real-Time Feedback","Diverse Learning Modes","Multi-Language Support","Personalized Learning","Immersive Scenarios"}', '{}', true, '{}', '{}', '', now()),
('Veesual', 'veesual', 'Revolutionize online shopping with AI-driven virtual try-ons.', 'Revolutionize online shopping with AI-driven virtual try-ons.', 'https://cdn.futurepedia.io/98aaf9d7116d2976adc93be78660131a1ccfac13-1920x1080.png', 'https://www.veesual.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Standard Plan", "price": "$50 per month", "features": []}, {"plan": "Enterprise Solutions", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Dynamic Image Generation","Mix & Match Styling","Look Inspiration","Seamless Integration","Enhanced Customer Engagement","Reduction in Return Rates"}', '{}', true, '{}', '{}', '', now()),
('Trace', 'trace', 'Automate workflows, enhance productivity, reduce manual tasks.', 'Automate workflows, enhance productivity, reduce manual tasks.', 'https://cdn.futurepedia.io/2026-02-04T16-48-37.982Z-2ylXCHeOXk7xxdELcqBNqaB2vAuJ4YxC8.webp', 'https://www.trace.so/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$60 per month", "features": []}, {"plan": "Team", "price": "$200 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Workflow Mapping and Automation","Community-Curated Templates","AI and Human Agent Routing","Prebuilt AI Components","Time Efficiency","User Control"}', '{}', true, '{}', '{}', '', now()),
('quso.ai', 'quso-ai', 'Effortlessly create, manage, and analyze engaging social media content.', 'Effortlessly create, manage, and analyze engaging social media content.', 'https://cdn.futurepedia.io/2026-02-27T11-18-04.619Z-LBgrgjXzzuGYkGrb63fxOoE5FeG5OvddM.png', 'https://quso.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Lite", "price": "$29 per month", "features": []}, {"plan": "Essential", "price": "$39 per month", "features": []}, {"plan": "Growth", "price": "$49 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Content Creator","AI Clips Generator","AI Social Media Manager","AI Video Editor","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('iFoto', 'ifoto', 'Transform e-commerce imagery with AI: lifelike models, advanced editing, and dynamic backgrounds.', 'Transform e-commerce imagery with AI: lifelike models, advanced editing, and dynamic backgrounds.', 'https://cdn.futurepedia.io/99cd65325158d39edff158383e1f77cf3d7a7db1-2521x1287.png', 'https://www.ifoto.ai/?amp%3Butm_medium=marketplace&amp%3Butm_campaign=futurepedia', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Fashion Models","Background Changer","Cleanup Pictures","Clothing Recolor","Efficiency in Editing","Cost-Effective Solutions"}', '{}', true, '{}', '{}', '', now()),
('Patlytics', 'patlytics', 'AI-driven platform optimizing patent creation, protection, and litigation.', 'AI-driven platform optimizing patent creation, protection, and litigation.', 'https://cdn.futurepedia.io/4330eb5b7c5aa741a5dada40d4e2e292abb61e83-1920x1080.jpg', 'https://www.patlytics.ai/', 'contact', '[{"plan": "Subscription Plans", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Patent Drafting CoPilot","Litigation Intelligence","Office Action Response","Whitespace Detection","Efficiency in Management","Advanced Security"}', '{}', true, '{}', '{}', '', now()),
('Paxton AI', 'paxton-ai', 'Paxton AI is a cutting-edge legal assistant powered by Generative AI, designed to keep businesses ahead of regulatory changes', 'Paxton AI is a transformative tool designed to optimize the legal profession by integrating artificial intelligence into the workflow of attorneys. This AI legal assistant excels at making lawyering less tedious, allowing for more billable hours and delivering enhanced value to clients. Its capabilities range from learning new areas of law to rapidly drafting and comparing documents, deepening discovery, and providing accurate citations, all aimed at streamlining the legal research and document creation processes.', 'https://cdn.futurepedia.io/2026-02-27T11-17-48.282Z--9Ymi5dSTdM3dr_0lNDpWnemzAPddhTve.png', 'https://paxton.ai/', 'freemium', '[{"plan": "Free Access", "price": "Free", "features": []}, {"plan": "Custom Plans", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Extensive Legal Database Access","Custom Document Drafting","Natural Language Search","Collaborative Tools","Efficiency in Drafting Documents","Accuracy of Citations"}', '{}', true, '{}', '{}', '', now()),
('Bible Chat', 'bible-chat', 'Explore scripture, deepen faith, interactive AI-driven guidance.', 'Explore scripture, deepen faith, interactive AI-driven guidance.', 'https://cdn.futurepedia.io/c7731fd40352a0cbf044f764db8c4fa56b358916-1920x1080.png', 'https://thebiblechat.com/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Subscription Options", "price": "$4.99", "features": []}]', 'beginner', false, '{"web"}', '{"Interactive Bible AI Assistant","Verse Finder","Bible Trivia Games","Personalized Prayers","Deep Learning Integration","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Creative Reality Studio (D-ID)', 'creative-reality-studio-d-id', 'Animate and personalize digital content with AI-driven avatars and multilingual capabilities.', 'Creative Reality Studio (D-ID) is a cutting-edge platform that leverages the power of artificial intelligence to revolutionize the creation of digital media. As a seasoned reviewer, I''ve had the pleasure of exploring numerous AI tools, but D-ID stands out with its focus on personalizing and animating digital content. This tool is designed to empower content creators, marketers, and educators to transform static images and text into engaging videos with lifelike avatars, all with remarkable ease.', 'https://cdn.futurepedia.io/c970c91999e4cce358e5b86b585782a9a3db3e29-1861x940.jpg', 'https://studio.d-id.com/', 'freemium', '[{"plan": "Custom Plans", "price": "Custom", "features": []}, {"plan": "Free Demo", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Personalized Video Creation","Multilingual Text-to-Speech","Scalability","API Integration","Enhanced Engagement","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Autodesk Forma', 'autodesk-forma', 'AI-powered platform streamlining AEC design and collaboration.', 'AI-powered platform streamlining AEC design and collaboration.', 'https://cdn.futurepedia.io/d77628cf930f4adb02a75bfa4f343e299c8ff220-2532x1253.png', 'https://www.autodesk.com/products/forma/', 'paid', '[]', 'beginner', false, '{"web"}', '{"Generative Design","Data-Driven Insights","Collaborative Environment","Sustainability Analysis","Time Efficiency","Enhanced Collaboration"}', '{}', true, '{}', '{}', '', now()),
('Nanonets Resume Builder', 'nanonets-resume-builder', 'Create tailored, professional resumes with AI assistance.', 'Create tailored, professional resumes with AI assistance.', 'https://cdn.futurepedia.io/2025-05-28T20-23-23.096Z-PL8XauRXfupcSDI0a5KswRv2sIxReBBHa.png', 'https://resume.nanonets.com/', 'free', '[{"plan": "Free", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Editing","Customizable Templates","Ease of Use","Unlimited Versions","Time-Saving","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Momen', 'momen', 'Build AI-powered apps effortlessly with Momen''s integrated development platform.', 'Build AI-powered apps effortlessly with Momen''s integrated development platform.', 'https://cdn.futurepedia.io/2be8249e437aabf2b2e9e2d6bdfab8661a2b15b4-2547x1306.png', 'https://editor.momen.app/', 'freemium', '[{"plan": "Basic Plan", "price": "Free", "features": []}, {"plan": "Pro Plan", "price": "$39", "features": []}]', 'intermediate', false, '{"web"}', '{"No-Code App Building","AI Knowledge Base Integration","Custom UI Design","Rapid Development and Iteration","User-Friendly Platform","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Verdent', 'verdent', 'Plan, code, and review software in parallel.', 'Plan, code, and review software in parallel.', 'https://cdn.futurepedia.io/2026-01-29T21-17-06.171Z-khmY64epB2j7xyHBYOIaWG8XopYDdi-00.blob', 'https://www.verdent.ai/', 'freemium', '[{"plan": "Free Trial", "price": "$0", "features": []}, {"plan": "Starter", "price": "$19 per month", "features": []}, {"plan": "Pro", "price": "$59 per month", "features": []}, {"plan": "Max", "price": "$179 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Parallel AI Agents","Workspace Isolation","Plan Mode","Code Review and Verification","Fast On Larger Projects","Clearer Oversight"}', '{}', true, '{}', '{}', '', now()),
('Intrascope', 'intrascope', 'Centralize team AI chats, models, and spending.', 'Centralize team AI chats, models, and spending.', 'https://cdn.futurepedia.io/2026-02-27T11-17-50.020Z-qDwfWfCAw79jfYebvg1G6W0TltUJGqDgF.png', 'https://intrascope.app/', 'freemium', '[{"plan": "Usage-Based (Basic)", "price": "$10 per month", "features": []}, {"plan": "Usage-Based (Pro)", "price": "$24 per month", "features": []}, {"plan": "Self API", "price": "$299", "features": []}]', 'beginner', false, '{"web"}', '{"Shared Team Workspace","Multi LLM Access in One UI","Strong Governance","Cost Control Focus"}', '{}', true, '{}', '{}', '', now()),
('FakeYou', 'fakeyou', 'Revolutionize content with AI-driven, accurate voice cloning technology.', 'Revolutionize content with AI-driven, accurate voice cloning technology.', 'https://cdn.futurepedia.io/bb322c7b925bcedaf6796d50d7ab846b29c9c32e-1920x977.png', 'https://fakeyou.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Wide Range of Voices","Custom Voice Generation","Real-Time Voice Cloning","API Access","Creativity Unleashed","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('CometAPI', 'cometapi', 'Access 500+ AI models through one API.', 'Access 500+ AI models through one API.', 'https://cdn.futurepedia.io/2026-02-27T11-18-09.821Z-7t83SbAE4jDPmarw9qRoaG6c3VjT1HglY.png', 'https://www.cometapi.com/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Unified API Access","Cost Efficiency","High Performance","Vendor Independence","Time Efficiency","Scalability"}', '{}', true, '{}', '{}', '', now()),
('Mindverse', 'mindverse', 'AI-powered platform for enhanced decision-making and productivity optimization.', 'AI-powered platform for enhanced decision-making and productivity optimization.', 'https://cdn.futurepedia.io/3167f6d3a40364da6e68d1b6fd5fd2019a8bdca5-1920x1080.png', 'https://www.mindos.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$30.00 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced AI Capabilities","MindOS Studio","Mebot","High Security Standards","Customization","User Empowerment"}', '{}', true, '{}', '{}', '', now()),
('Prophet Security', 'prophet-security', 'Revolutionizing cybersecurity with AI-driven alert synthesis and adaptive learning.', 'Revolutionizing cybersecurity with AI-driven alert synthesis and adaptive learning.', 'https://cdn.futurepedia.io/3dac863f8e17bab45b38a70ce3a1548464bac2cb-1920x1080.png', 'https://www.prophet.security/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Alert Synthesis","Investigative AI","Responsive Actions","Adaptive Learning","Speed and Efficiency","Focus on High Priority Alerts"}', '{}', true, '{}', '{}', '', now()),
('Skoot', 'skoot', 'Revolutionize family travel with AI-planned itineraries and tailored activity suggestions.', 'As a seasoned traveler and a parent, I''m always on the lookout for tools that make planning family adventures less of a chore and more of a joy. This is where Skoot comes into play. Skoot is an AI-powered travel and activity planning tool designed specifically with families in mind. It aims to take the hassle out of organizing trips and activities, whether you''re planning a day out locally or a week-long holiday abroad. With its user-friendly interface and innovative features, Skoot promises to be a game-changer for parents eager to balance fun and relaxation for both kids and adults, all while keeping an eye on budget and practical considerations.', 'https://cdn.futurepedia.io/bab9104c76750df5b59168602297ff4dcad34d7d-2367x1234.jpg', 'https://skoothere.com/', 'free', '[{"plan": "Customization and Flexibility", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Itinerary Planning","Activity Suggestions","Family-Friendly Focus","Budget and Preference Customization","Ease of Use","Personalized Itineraries"}', '{}', true, '{}', '{}', '', now()),
('Zenity', 'zenity', 'Streamline GRC with automated SaaS security, compliance, and monitoring.', 'Streamline GRC with automated SaaS security, compliance, and monitoring.', 'https://cdn.futurepedia.io/6e83552f9d3a0bbb4796456b923f084aaaeb8473-1920x1080.png', 'https://www.zenity.io/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Enterprise Tier", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"SaaS Security Posture Management (SSPM)","Compliance Tracking","Real-Time Monitoring","User Behavior Analytics","Enhanced Security","Automated Compliance"}', '{}', true, '{}', '{}', '', now()),
('Transcriptik', 'transcriptik', 'Turn TikToks into searchable transcripts and stats.', 'Turn TikToks into searchable transcripts and stats.', 'https://cdn.futurepedia.io/2026-02-27T11-18-06.280Z-BWYX9ZMS9s4GBUZ87oguuz3IDI25UxFw5.png', 'https://transcriptik.com/', 'freemium', '[{"plan": "Free Plan", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$5.99 per month", "features": []}, {"plan": "Pro", "price": "$9.99 per month", "features": []}, {"plan": "Studio", "price": "$19.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI TikTok transcription","Multilingual support","Video metadata preview","Bulk and queueing","Fast to start","TikTok focused"}', '{}', true, '{}', '{}', '', now()),
('Typli.ai', 'typli-ai', 'Draft blogs, campaigns, lessons, and visuals in minutes.', 'Draft blogs, campaigns, lessons, and visuals in minutes.', 'https://cdn.futurepedia.io/2026-02-27T11-17-51.521Z-80ZK2UyOwpErFkmyVCTT2FbI96QJJ_ZoC.png', 'https://typli.ai/', 'freemium', '[{"plan": "Basic", "price": "$12.99 per month", "features": []}, {"plan": "Plus", "price": "$19.99 per month", "features": []}, {"plan": "Pro", "price": "$49.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"186 specialized writing tools","Education and academic helpers","All‑in‑one toolkit","Speed and convenience"}', '{}', true, '{}', '{}', '', now()),
('AirMusic', 'airmusic', 'Turn prompts into complete songs and music videos', 'Turn prompts into complete songs and music videos', 'https://cdn.futurepedia.io/2026-04-04T04-25-24.851Z-ZfiAyzjnpOmV62bJ5GgnXTm2eNMxeho3c.png', 'https://airmusic.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter Plan", "price": "$19.90 per month", "features": []}, {"plan": "Pro Plan", "price": "$59.90 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Text & Lyrics to Music","AI Vocals, Voice Cloning & Singing Photo","AI Music Video Tools","End to end workflow","Beginner friendly"}', '{}', true, '{}', '{}', '', now()),
('super.AI', 'super-ai', 'Automate complex document tasks with precision and efficiency.', 'Automate complex document tasks with precision and efficiency.', 'https://cdn.futurepedia.io/8db2f5f49bb14005b1a4bb5e3ef712bda43532da-1920x1080.png', 'https://www.super.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Advanced Document Processing","Human-in-the-Loop (HITL)","Document Classification","Table Recognition","Time Efficiency","High Accuracy"}', '{}', true, '{}', '{}', '', now()),
('Postly', 'postly', 'AI-driven social media planning, scheduling, and analytics across platforms.', 'AI-driven social media planning, scheduling, and analytics across platforms.', 'https://cdn.futurepedia.io/106538eef2991694c2b62a4701d973fe74889aea-1540x858.jpg', 'https://postly.ai/?fpr=4bhq6', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Scheduling","Multi-Platform Support","Analytics and Insights","Bulk Posting","Time-Saving","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('Splutter AI', 'splutter-ai', 'Streamline business operations with AI-driven chatbots and automation.', 'Splutter AI is an innovative AI chatbot solution designed to enhance business operations across various sectors. With a focus on support, marketing, and sales automation, Splutter AI streamlines customer interactions, generates leads, and provides valuable insights. Whether you''re a small business owner or part of a larger enterprise, this tool offers a comprehensive platform to simplify complex processes, making it an indispensable asset for modern businesses.', 'https://cdn.futurepedia.io/5cVoT9HZQgUXCOJFf2HiMp.png', 'https://www.splutter.ai/', 'contact', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Generative AI Large Language Model Chatbot","Scalable Messaging","Customizable and Flexible","Multiple Data Sources Integration","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('AI Studios', 'ai-studios', 'Effortlessly create professional videos with AI avatars and tools.', 'AI Studios revolutionizes video content creation by offering a comprehensive suite of AI-driven tools that enable users to create high-quality videos effortlessly. Designed for content creators, marketers, and businesses, it simplifies the video production process by integrating realistic AI avatars, natural text-to-speech capabilities, and advanced video editing features, all within a single platform.', 'https://cdn.futurepedia.io/2025-01-13T20-15-58.268Z-RrYrGcsU0MqkoLNvaXOQ92wkHbWSRsriX.PNG', 'https://www.deepbrain.io/aistudios', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$29 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Avatars","Multilingual Support","Video Templates","Text to Video Conversion","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Brief My Meeting', 'brief-my-meeting', 'Arrive prepared with automatic pre-meeting email briefings.', 'Arrive prepared with automatic pre-meeting email briefings.', 'https://cdn.futurepedia.io/2025-12-31T15-34-48.655Z-PRfmlwViAHgg4cg3FWQBBS7594hUKvu-N.png', 'https://www.briefmymeeting.com/', 'freemium', '[{"plan": "All in One", "price": "$9 per user", "features": []}]', 'beginner', false, '{"web"}', '{"Attendee and company research","Contextual history view","Relevant document surfacing","Calendar and inbox integration","Significant time savings","Stronger relationships and follow-through"}', '{}', true, '{}', '{}', '', now()),
('PopTask', 'poptask', 'Convert messy text into timed Mac menu‑bar tasks.', 'Convert messy text into timed Mac menu‑bar tasks.', 'https://cdn.futurepedia.io/2026-04-01T17-35-43.909Z-QRmuNF52YDiQ_r9l2Pw86FbIjlc0TmhPD.png', 'https://poptask.bar/', 'free', '[]', 'beginner', false, '{"web"}', '{"AI smart task entry","Hybrid on-device and cloud AI","AI task breakdown","Live countdown and alerts","Fast capture with minimal context switching","Excellent handling of messy input"}', '{}', true, '{}', '{}', '', now()),
('Pine AI', 'pine-ai', 'Offload bill hassles, win refunds and savings.', 'Offload bill hassles, win refunds and savings.', 'https://cdn.futurepedia.io/2026-03-31T15-00-21.521Z-wlrGe4TEl-7h4Ud3VIfsH18WmWEGJSGIv.png', 'https://www.19pine.ai/', 'freemium', '[{"plan": "Starter Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$30 per month", "features": []}, {"plan": "Enterprise", "price": "$200 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Autonomous calling and emailing","Bill and fee negotiation","Travel and service coverage","Security focused architecture","Huge time savings","Strong results on bills"}', '{}', true, '{}', '{}', '', now()),
('2-b.ai', '2-b-ai', 'Turn web text into clear, actionable tasks.', 'Turn web text into clear, actionable tasks.', 'https://cdn.futurepedia.io/2026-02-27T11-18-11.325Z-91Zdh-qCFcxoI0yzovHQvrBcPTuW34ggD.png', 'https://2-b.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$5.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Drag-to-task capture","AI-powered task breakdown","AI task chat assistant","Calendar integration","Frictionless capture from real work","Strong free tier for testing"}', '{}', true, '{}', '{}', '', now()),
('Mixus', 'mixus', 'Turns plain English tasks into instant, automated workflows.', 'Turns plain English tasks into instant, automated workflows.', 'https://cdn.futurepedia.io/2026-02-27T11-17-56.080Z-cba7m7KIgsZ60E29oRDwAKhPug-cddokh.png', 'https://www.mixus.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Instant Agent Generation","Human-in-the-Loop Oversight","Team Collaboration","Contextual Awareness","No Technical Barrier","Drastic Time Savings"}', '{}', true, '{}', '{}', '', now()),
('EvenUp Law', 'evenup-law', 'AI-powered tool for efficient demand packages and medical chronologies.', 'AI-powered tool for efficient demand packages and medical chronologies.', 'https://cdn.futurepedia.io/2025-02-14T20-08-56.763Z-NQsg5fUq5k2IZyfD0CRpEWvhC08IZLheM.png', 'https://www.evenuplaw.com/', 'contact', '[{"plan": "Custom Pricing", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Demands","Interactive Medical Chronologies","Data-Driven Analysis","SOC2 Certification","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('getimg.ai', 'getimgai', 'AI-driven image generation, editing, and infinite outpainting, with real-time processing.', 'getimg.ai is an', 'https://cdn.futurepedia.io/e2c0bbf217a7c3eeb16b73a67afb995a797a6449-1904x899.png', 'https://getimg.ai/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Image Generation","Intuitive Image Editor","AI Canvas for Outpainting","Real-Time Generation","Creativity Unleashed","Speed and Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Resleeve', 'resleeve', 'Revolutionize fashion design: AI sketches, virtual shoots, instant edits.', 'Revolutionize fashion design: AI sketches, virtual shoots, instant edits.', 'https://cdn.futurepedia.io/29ec75d8dde066020ffdb52a090049f0fd13e9e2-2526x1301.png', 'https://resleeve.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Design from Scratch","AI-Powered Editing","Virtual Photoshoots","Color Palette Blending","Time-Saving","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Picsart', 'picsart', 'Unleash creativity: edit photos, videos, and designs with AI-enhanced tools.', 'Unleash creativity: edit photos, videos, and designs with AI-enhanced tools.', 'https://cdn.futurepedia.io/3400894bbe11e54723735573d88b23d45dc4fb05-2510x1226.png', 'https://picsart.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Gold Subscription", "price": "$4.66 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Photo Effects","Video Editor","Layer-Based Editing","Huge Library of Templates","Versatility","Cross-Platform Availability"}', '{}', true, '{}', '{}', '', now()),
('PromptDrive.ai', 'promptdrive-ai', 'Your All-in-one Prompt Management Tool', 'PromptDrive.ai is an innovative tool designed to facilitate team collaboration and streamline AI adoption by integrating all your prompts, chats, and teammates into a single workspace. This tool is particularly useful for teams that frequently use AI tools like ChatGPT and Bard, offering a centralized platform for managing and executing prompts. With its user-friendly interface and robust features, PromptDrive.ai aims to enhance productivity and efficiency in AI-driven tasks.', 'https://cdn.futurepedia.io/2026-02-27T11-18-12.880Z-N05SgCEy-sihBZ0TxzB8qSJGBwbiFgmDY.png', 'https://promptdrive.ai/', 'free', '[{"plan": "Personal", "price": "Free", "features": []}, {"plan": "Team", "price": "$5 per user", "features": []}, {"plan": "Pro", "price": "$10 per user", "features": []}]', 'beginner', false, '{"web"}', '{"Collaboration on Prompts","Chat Collaboration","Prompt Management","Prompt Sharing","Efficient Collaboration","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('WeryAI', 'weryai', 'Generate and polish 4K-ready videos, images, music.', 'Generate and polish 4K-ready videos, images, music.', 'https://cdn.futurepedia.io/2026-02-03T15-27-25.273Z-BLl0GJgUFW7DF1HioDQfYCNIAXLmbLprA.png', 'https://www.weryai.com/', 'freemium', '[{"plan": "Basic", "price": "$14.99 per month", "features": []}, {"plan": "Standard", "price": "$24.99 per month", "features": []}, {"plan": "Pro", "price": "$69.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Model aggregator for visual AI","Text, image, and video workflows","AI video utilities","Creative extras","All in one workflow","High quality outputs"}', '{}', true, '{}', '{}', '', now()),
('PostSyncer', 'postsyncer', 'Turn ideas into scheduled posts, videos, and replies.', 'Turn ideas into scheduled posts, videos, and replies.', 'https://cdn.futurepedia.io/2026-02-04T13-20-50.000Z-mT2WVqgg5jqPbpKKJt0ptPGDjnLtghs70.webp', 'https://postsyncer.com/', 'freemium', '[{"plan": "Starter Plan", "price": "$19 per month", "features": []}, {"plan": "Pro Plan", "price": "$49 per month", "features": []}, {"plan": "Pro Plus Plan", "price": "$49 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Content Agent and Studio","AI Video Creator","Unified Visual Scheduler","Unified Comment Inbox and AI Auto-Replies","Serious Time Savings","AI-First Workflow"}', '{}', true, '{}', '{}', '', now()),
('boost.space', 'boost-space', 'Unify business data, run live AI automations.', 'Unify business data, run live AI automations.', 'https://cdn.futurepedia.io/2026-02-19T16-34-31.065Z-FdTw16RW-SGVAMXsrNBHlAgnQ9e42dsUk.png', 'https://boost.space/', 'free', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$25 per month", "features": []}, {"plan": "Business", "price": "$135 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Agentic Database & Context Layer","Data Layer & Two-way Sync","AI & Data Enrichment","MCP-based AI Agents","AI-first architecture","Integration breadth"}', '{}', true, '{}', '{}', '', now()),
('Wonder Studio', 'wonder-studio', 'Revolutionize VFX: automate animation, lighting, composition in your browser.', 'Revolutionize VFX: automate animation, lighting, composition in your browser.', 'https://cdn.futurepedia.io/2026-02-04T16-49-46.305Z-PRdLbPzkqU8JMo9UTeAxCw-Fudg0fGUi7.webp', 'https://wonderdynamics.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Animation and Lighting","Advanced Retargeting","Seamless Composition","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Airbrush', 'airbrush', 'AI-driven tool for seamless, professional headshot enhancement.', 'AirBrush AI Headshots is a revolutionary tool designed to elevate portrait editing through advanced AI technology. It offers a suite of features aimed at enhancing, retouching, and transforming headshots to achieve professional-quality results effortlessly. Perfect for photographers, social media influencers, and creative professionals, AirBrush AI Headshots simplifies the process of creating flawless images with just a few clicks.', 'https://cdn.futurepedia.io/c781f0280773630298d4b95e3b78d96b62c5fd7d-1680x876.png', 'https://appsumo.8odi.net/Pyk19q', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Retouch","Photo Eraser","Image Background Remover","Face Swap","User-Friendly Interface","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Superintelligent', 'superintelligent', 'Master AI swiftly: interactive lessons, daily updates, extensive library.', 'Master AI swiftly: interactive lessons, daily updates, extensive library.', 'https://cdn.futurepedia.io/be8fd402a5ec9e8d1a19cb754719d5b52ad4f46f-2502x1206.png', 'https://besuper.ai/', 'contact', '[{"plan": "Full Access Membership", "price": "$20 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Interactive Video Lessons","Hands-on Learning","Daily Updates","Extensive Tutorial Library","Accelerated Learning","Affordable Pricing"}', '{}', true, '{}', '{}', '', now()),
('StarWriter AI', 'starwriter-ai', 'Turns AI drafts into undetectable, high-grade essays.', 'Turns AI drafts into undetectable, high-grade essays.', 'https://cdn.futurepedia.io/2026-02-27T11-18-15.912Z-mSGQzccL2ENynlrezXwxus72AWSzResf0.png', 'https://starwriter.ai/', 'freemium', '[{"plan": "Free Plan", "price": "$0 per month", "features": []}, {"plan": "Standard Plan", "price": "$4.99 per month", "features": []}, {"plan": "Pro Plan", "price": "$9.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Humanizer","Natural Wording Variation","Lightning-Fast Processing","Model Agnostic","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Ivo', 'ivo', 'Transform legal contract review with AI-driven precision, efficiency, and customization.', 'Transform legal contract review with AI-driven precision, efficiency, and customization.', 'https://cdn.futurepedia.io/f6058cb7812db0a4a18b403d8468160ba7126db6-1887x915.png', 'https://www.ivo.ai/', 'contact', '[]', 'beginner', false, '{"web"}', '{"Efficient Review","Customized to Your Needs","Support for Multiple Formats","Issue Identification","Time Efficiency","Customization"}', '{}', true, '{}', '{}', '', now()),
('Mem0', 'mem0', 'Enhances AI with adaptive memory, reducing costs significantly.', 'Enhances AI with adaptive memory, reducing costs significantly.', 'https://cdn.futurepedia.io/2026-02-27T11-18-17.580Z-6ngX3MZWYQJ-h0PiRrAOvDNF7_oT74Moe.png', 'https://mem0.ai/', 'contact', '[{"plan": "Open-Source Version", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Self-Improving Memory Layer","Cost Reduction","Seamless Integration","Contextual Understanding","Enhanced Personalization","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Rows AI', 'rows-ai', 'Transform spreadsheets into AI-powered data analysis tools, simplifying complex insights.', 'Transform spreadsheets into AI-powered data analysis tools, simplifying complex insights.', 'https://cdn.futurepedia.io/8a06aef9b1637749ce0cf3fa4cfaedf315a20e7c-2532x1266.jpg', 'https://rows.com/ai', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Quick Insights","Deep Dives","ChatGPT Integration","Dynamic AI Interactions","Enhanced Productivity","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now()),
('GPTinf', 'gptinf', 'Detects AI writing, then rewrites it to pass.', 'Detects AI writing, then rewrites it to pass.', 'https://cdn.futurepedia.io/2026-02-27T11-18-19.798Z-GILDGXHeoY8pdukiL9VZDzZwIqvs7SHc9.png', 'https://www.gptinf.com/', 'freemium', '[{"plan": "Lite", "price": "$9.99 per month", "features": []}, {"plan": "Pro", "price": "$24.99 per month", "features": []}, {"plan": "Unlimited", "price": "$59.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI Text Humanizer","Multi-Detector Testing","Freeze Keywords Control","Multiple Rewrite Modes","Strong for Basic and Mid-Tier Detectors","Fast Rewriting with One Click"}', '{}', true, '{}', '{}', '', now()),
('CXScore', 'cxscore', 'Harness AI to analyze, predict, and enhance customer experiences.', 'Harness AI to analyze, predict, and enhance customer experiences.', 'https://cdn.futurepedia.io/33bcce52993fdd28f57a90873347b32bea0dbe9b-1920x1080.png', 'https://cxscore.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Standard Plan", "price": "$200 per month", "features": []}, {"plan": "Enterprise Solutions", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Real-Time Customer Feedback Analysis","Multi-Channel Integration","Customizable Dashboards","Predictive Analytics","Enhanced Customer Insights","Increased Responsiveness"}', '{}', true, '{}', '{}', '', now()),
('Coursebox', 'coursebox', 'Creates interactive courses with AI-driven automation.', 'Coursebox is an innovative AI-powered training platform designed to revolutionize the way educational content is created and delivered. This tool is specifically crafted for training providers, instructional design consultants, and educational institutions, aiming to simplify the development of engaging and interactive courses. By utilizing advanced AI technologies, Coursebox makes it possible to generate comprehensive training materials, including videos, quizzes, and assessments, in mere minutes.', 'https://cdn.futurepedia.io/2025-06-02T15-08-49.223Z-4IUQ0hfaycOsA02kgUit-ZTBEXSlMUdms.png', 'https://www.coursebox.ai/', 'freemium', '[{"plan": "Creator", "price": "$29.99 per month", "features": []}, {"plan": "Creator Plus", "price": "$99.99 per month", "features": []}, {"plan": "Branded Training Platform", "price": "$499.99 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Course Creator","AI LMS (White Label)","AI Training Video Generator","AI Quiz Generator","Efficiency in Course Creation","Engagement Enhancement"}', '{}', true, '{}', '{}', '', now()),
('Aragon AI', 'aragon-ai', 'Generate professional AI headshots rapidly and affordably.', 'Aragon AI is revolutionizing the process of obtaining professional headshots with its state-of-the-art AI headshot generator. This tool is specifically designed for individuals and businesses seeking to create high-quality, realistic headshots quickly and affordably. By leveraging cutting-edge AI technology developed by researchers from leading tech companies, Aragon AI simplifies the task of getting a professional headshot without the need for expensive photo shoots.', 'https://cdn.futurepedia.io/9556329c7691d7125478f539eb8547f409f93ddc-2509x1218.png', 'https://www.aragon.ai/', 'paid', '[{"plan": "Starter Plan", "price": "$35", "features": []}, {"plan": "Basic Plan", "price": "$45", "features": []}, {"plan": "Premium Plan", "price": "$75", "features": []}]', 'beginner', false, '{"web"}', '{"High-Resolution Output","Rapid Processing Time","Diverse Customization Options","Advanced AI Technology","Cost-Effective","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('AltIndex', 'altindex', 'Harness AI-driven insights from unconventional data for smarter investing.', 'Harness AI-driven insights from unconventional data for smarter investing.', 'https://cdn.futurepedia.io/2760080d58c515e22395a89cfe295f2418181e4c-2499x1222.png', '', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$29.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Alternative Data Insights","AI Stock Picks","Real-Time Alerts","User-Friendly Dashboard","Enhanced Decision Making","High Win-Rate on Predictions"}', '{}', true, '{}', '{}', '', now()),
('Relativity', 'relativity', 'Revolutionize data discovery and case strategy with AI-driven, secure technology.', 'Revolutionize data discovery and case strategy with AI-driven, secure technology.', 'https://cdn.futurepedia.io/2026-02-27T11-18-31.300Z-Sq9WPrapV-ShABx8LgSPWWTANWUj2Dupy.png', 'https://www.relativity.com/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Subscription-Based Model", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Discovery","Proactive Security","User-Friendly Interface","Open Platform","Efficiency in Data Management","Advanced AI Capabilities"}', '{}', true, '{}', '{}', '', now()),
('GPTConsole', 'gptconsole', 'Revolutionize app development with AI agents for seamless automation.', 'GPTConsole is a cutting-edge AI tool designed to revolutionize the way developers interact with artificial intelligence. This platform is dedicated to creating, sharing, and monetizing AI agents, offering specialized AI workers that not only provide information but also perform tasks for extended periods. With its focus on simplifying complex AI agent development processes—such as event chaining, lifecycle management, and memory handling—GPTConsole empowers developers to concentrate on setting agent objectives. This tool is particularly tailored for developers seeking to generate production-ready applications, build features for existing apps, and even create animated doodles.', 'https://cdn.futurepedia.io/2026-02-27T11-18-21.499Z-gP-Wf-D-zJLvNTiw9m1i83lO7pWvhJzt9.png', 'https://www.gptconsole.ai/', 'freemium', '[{"plan": "Free Credits on Sign-Up", "price": "Free", "features": []}, {"plan": "Flexi-Plan", "price": "$1", "features": []}]', 'intermediate', false, '{"web"}', '{"Developer-Focused Platform","Flexible Data Infrastructure","Customizable AI Solutions","Seamless Integration"}', '{}', true, '{}', '{}', '', now()),
('MYPEAS.ai', 'mypeas-ai', 'AI roadmaps tailored to any job description.', 'MYPEAS.AI is a cutting-edge platform that generates personalized AI roadmaps from any job description, empowering businesses to unlock the full potential of AI within their teams. Whether you’re a small business or a large enterprise, MYPEAS.AI offers a simple and effective way to integrate AI into your workflows, ensuring seamless automation and enhanced productivity.', 'https://cdn.futurepedia.io/2024-10-24T22-31-51.186Z-sLiXxJu6M0O8VClu7XGDaLEF-5Gv8IzNV.png', 'https://mypeas.ai/', 'freemium', '[]', 'beginner', false, '{"web"}', '{"Actionable AI Roadmaps","Intelligent Analysis and Insights","Comprehensive AI Consultation","Efficiency Enhancement","Tailored AI Solutions"}', '{}', true, '{}', '{}', '', now()),
('SoBrief', 'sobrief', '73,530 free book summaries in 40 languages (with paid audio).', 'SoBrief is an innovative AI-powered tool designed to transform the way we consume literature by offering comprehensive book summaries. With an impressive library of over 73,530 summaries available in audio, PDF, and EPUB formats, SoBrief aims to cater to the needs of busy readers who want to grasp the essence of a book in just 10 minutes. Perfect for professionals, students, and avid readers, it simplifies the task of keeping up with the latest books and timeless classics across various genres.', 'https://cdn.futurepedia.io/2025-01-16T16-29-45.638Z-w6wg1L7BqAgHKGZ5qEyCQNvayhWSj7s2O.png', 'https://sobrief.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$9.99 per month", "features": []}, {"plan": "Lifetime Access", "price": "$79.99", "features": []}]', 'beginner', false, '{"web"}', '{"Extensive Library","Multilingual Support","Audio Summaries","User-Friendly Interface","Time-Saving","Wide Range of Genres"}', '{}', true, '{}', '{}', '', now()),
('AirOps', 'airops', 'Task-specific AI Apps that go beyond ChatGPT—run NLP, generate-data-informed content, draft/fix/optimize SQL queries, and more', 'Task-specific AI Apps that go beyond ChatGPT—run NLP, generate-data-informed content, draft/fix/optimize SQL queries, and more', 'https://cdn.futurepedia.io/2026-02-27T11-18-22.990Z-OJaaVbeN37LiIg63DfwZHowpAB7A6hPEw.png', 'https://www.airops.com/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Workflows","Custom App Builder","Batch Operations","Memory Stores","Efficiency","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Flickify', 'flickify', 'Transform text and URLs into engaging videos effortlessly.', 'Flickify is an innovative AI tool designed to transform articles and text-based content into engaging videos with ease. Whether you''re a business owner, content creator, or digital marketer, Flickify simplifies the video creation process, enabling you to tap into new audiences and revenue streams. By automating the transformation of text and ideas into visually captivating videos, Flickify offers a seamless way to diversify your content strategy and improve your online presence.', 'https://cdn.futurepedia.io/2024-12-20T14-30-37.880Z-79e66vRIzsZMGPT_0RWc8TNESHpaigIjj.PNG', 'https://www.flickify.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$18 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Text to Video","URL to Video","Diverse Narrators and Voice Cloning","Video Avatars and Customization","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('ChefGPT', 'chefgpt', 'AI-driven tool simplifies meal planning with personalized recipes.', 'AI-driven tool simplifies meal planning with personalized recipes.', 'https://cdn.futurepedia.io/2026-02-27T11-18-33.380Z-vb_kbZdt8K0cursXNgwUpv9eQz_v6yg_2.png', 'https://www.chefgpt.xyz/', 'freemium', '[{"plan": "Free Tier", "price": "$0 per month", "features": []}, {"plan": "Pro Tier", "price": "$2.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"PantryChef","MasterChef","MacrosChef","MealPlanChef","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Lumen5', 'lumen5', 'Transform text into dynamic videos using AI, effortlessly.', 'Transform text into dynamic videos using AI, effortlessly.', 'https://cdn.futurepedia.io/e134c384d20422e866b6c1949df2a32be87837ee-1801x933.jpg', 'https://lumen5.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$79 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Automation","Extensive Media Library","Custom Branding Options","Voice-Over Capabilities","Speed and Efficiency","Ease of Use"}', '{}', true, '{}', '{}', '', now()),
('Shuffll', 'shuffll', 'AI-powered tool simplifies branded video creation and scaling.', 'Shuffl revolutionizes AI-powered video creation, offering an all-in-one solution for businesses looking to produce fully branded thought leadership videos, expert interviews, and testimonials. Designed specifically for business professionals and marketers, it simplifies the process of video production from concept to execution in just three easy steps: Plan, Record, and Scale. Whether you''re an entrepreneur seeking to enhance your brand presence or a marketing team aiming to boost engagement, Shuffl provides a streamlined and cost-effective solution to master B2B video content.', 'https://cdn.futurepedia.io/6e2137617dd50673e3955c0050f103cb27ef4db6-1897x1080.jpg', 'https://shuffll.com/', 'paid', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Video Concept Generation","Integrated Teleprompter","High-Quality Recording","Scalable Video Production","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('HeadshotGenerator.io', 'headshotgenerator-io', 'A Professional AI headshot generator starter kit powered by Next.js, Leap AI, and Vercel.', 'A Professional AI headshot generator starter kit powered by Next.js, Leap AI, and Vercel.', 'https://cdn.futurepedia.io/2026-02-04T16-41-42.548Z-f6oSrXJXxun_I521Dhq5HEtSisjRtL7p2.webp', 'https://vercel.com/templates/next.js/headshot-ai', 'freemium', '[{"plan": "Classic Tier", "price": "$19", "features": []}, {"plan": "Classic & Fun Tier", "price": "$29", "features": []}, {"plan": "Bulk Tier", "price": "$290", "features": []}]', 'beginner', false, '{"web"}', '{"Image Transformation","Advanced AI Technology","Customization Options","User-Friendly Interface","Cost-Effective","Time-Efficient"}', '{}', true, '{}', '{}', '', now()),
('Photomyne', 'photomyne', 'Digitize, enhance, and animate old photos effortlessly with AI-powered precision.', 'Digitize, enhance, and animate old photos effortlessly with AI-powered precision.', 'https://cdn.futurepedia.io/2026-02-27T11-18-38.741Z-By9LqoUgXmF0U6YPH0TqrmN4lzqYm767Z.png', 'https://photomyne.com/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}, {"plan": "Yearly Subscription", "price": "$59.99", "features": []}]', 'beginner', false, '{"web"}', '{"Easy and Speedy Scanning","Dedicated Scanning Apps","Enhancement Tools","Animation Feature","User-Friendly Interface","High-Quality Outputs"}', '{}', true, '{}', '{}', '', now()),
('VideoGen', 'videogen', 'Transform video creation: AI-powered, multi-language, one-click efficiency.', 'Transform video creation: AI-powered, multi-language, one-click efficiency.', 'https://cdn.futurepedia.io/b0a9cfa669207f86551973a3d8dd87f9edffd32d-1920x1080.png', 'https://videogen.io/?fpr=futurepedia', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"One-Click Video Creation","Extensive Stock Library","Advanced Text-to-Speech Engine","Browser-Based Editing","Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Solid', 'solid', 'Build real web apps quickly without coding skills.', 'Build real web apps quickly without coding skills.', 'https://cdn.futurepedia.io/2026-02-27T11-18-40.281Z-SC04F7iQNBVEtJI2wgvxELJzKWv1isKxS.png', 'https://trysolid.com/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Standard", "price": "$20 per month", "features": []}, {"plan": "Pro", "price": "$150 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"Full-Stack Development","No Coding Required","Integration Capabilities","Security by Design","Rapid Development","High-Quality Code"}', '{}', true, '{}', '{}', '', now()),
('MindOS', 'mindos', 'Automate customer interactions and data management with customizable AI.', 'MindOS is an innovative AI tool designed to revolutionize the way businesses interact with their customers and manage data. By offering a customizable AI agent, MindOS empowers users to automate responses to customer queries, streamline scheduling, and enhance lead generation. Tailored for businesses looking to optimize their operations and customer service, MindOS simplifies complex tasks by integrating AI-driven solutions into everyday business processes.', 'https://cdn.futurepedia.io/2026-02-27T11-18-41.862Z-zfpa-4u1z41kn5IUJ1lzfDN3bpvRdNosc.png', 'https://mindos.com/', 'freemium', '[{"plan": "Starter Plan", "price": "$29.99 per month", "features": []}, {"plan": "Growth Plan", "price": "$79.99 per month", "features": []}, {"plan": "Enterprise Plan", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Customizable AI Agents","Multilingual Support","Voice Input Capability","Integration Flexibility","User-Friendly Interface","Enhanced Customer Interaction"}', '{}', true, '{}', '{}', '', now()),
('iPlan.ai', 'iplan-ai', 'AI-driven, personalized travel itineraries at your fingertips.', 'AI-driven, personalized travel itineraries at your fingertips.', 'https://cdn.futurepedia.io/7f0e5761c1f6b6915f1c99269102094948c8f567-2495x1218.png', 'https://iplan.ai/', 'freemium', '[{"plan": "Free Version", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Itinerary Creation","User-Friendly Interface","Real-Time Itinerary Customization","Global Destination Coverage","Time-Saving","Customizable Itineraries"}', '{}', true, '{}', '{}', '', now()),
('fileAI', 'fileai', 'Automate data workflows with rapid, accurate processing.', 'Automate data workflows with rapid, accurate processing.', 'https://cdn.futurepedia.io/2026-02-04T16-40-40.967Z-mKrxAmHHXzUTbMQ0B5Yc4x97Xczc8JFg4.webp', 'https://www.file.ai/', 'freemium', '[{"plan": "Self-Serve", "price": "$0 per month", "features": []}, {"plan": "Enterprise", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"AI Schema Enrichment","Automated Data Validation","Workflow Orchestration","High Accuracy","Time and Cost Savings"}', '{}', true, '{}', '{}', '', now()),
('Finch 3D', 'finch-3d', 'AI-driven platform enhances architectural design creativity and efficiency.', 'AI-driven platform enhances architectural design creativity and efficiency.', 'https://cdn.futurepedia.io/2026-02-27T11-18-43.300Z-OUDpkCnkt474-lxIs-Jzmqvz1lLXXT-Ib.png', 'https://www.finch3d.com/', 'contact', '[]', 'beginner', false, '{"web"}', '{"Generative Design Technology","Instant Data Feedback","Seamless Integration","Error Prevention and Compliance","Enhanced Creativity","Time Efficiency"}', '{}', true, '{}', '{}', '', now()),
('Bluedot', 'bluedot', 'AI-driven tool for seamless meeting transcription and note-taking.', 'Bluedot is an innovative AI-powered notetaking tool specifically designed to enhance productivity during meetings on platforms like Google Meet and Microsoft Teams. By offering a seamless, bot-free experience, Bluedot provides automated transcription, note generation, and meeting summarization, all while integrating smoothly with various CRMs and productivity tools. Whether you''re an entrepreneur, manager, or recruiter, Bluedot simplifies the process of capturing and sharing meeting insights, allowing users to focus more on meaningful interactions.', 'https://cdn.futurepedia.io/2025-01-27T22-08-34.586Z-yfqDGW0wKOBruBEtorQZ1faBM9ThPh_Ar.PNG', 'https://www.bluedothq.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$18 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Transcription","Bot-Free Recording","Automated Note Generation","CRM Integration","Time Efficiency","Non-Intrusive Design"}', '{}', true, '{}', '{}', '', now()),
('Beatwave', 'beatwave', 'Transform audio tracks into captivating music videos effortlessly.', 'Transform audio tracks into captivating music videos effortlessly.', 'https://cdn.futurepedia.io/36414eb46bf8e13eb1b5e8ab1b4f215f1f53c6cc-2520x1340.png', 'https://beatwaveapp.com/', 'freemium', '[{"plan": "Free Access", "price": "Free", "features": []}, {"plan": "Monthly", "price": "$17 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Automatic Beatwave Engine","Professional Templates","Customization Options","Web and Mobile Optimization","Rapid Video Creation","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('BridgeWise', 'bridgewise', 'AI-driven platform for precise bridge design and analysis.', 'AI-driven platform for precise bridge design and analysis.', 'https://cdn.futurepedia.io/9cd091d2fc3d959964df01e1f798804f5fc3055a-1920x1080.png', 'https://www.bridgewise.com/', 'contact', '[{"plan": "Subscription Plans", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Global Security Analysis","Multilingual Support","Machine Learning Insights","Custom AI Tools","Expansive Coverage","Enhanced Decision Making"}', '{}', true, '{}', '{}', '', now()),
('PromptCompose', 'promptcompose', 'Manage AI prompts with version control and A/B testing.', 'Manage AI prompts with version control and A/B testing.', 'https://cdn.futurepedia.io/2026-02-04T16-45-27.478Z-70meZSiP35Ic-hu7U6cAz1trlnOaZVUx9.webp', 'https://promptcompose.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Version Control for Prompts","A/B Testing Made Simple","Developer-Ready SDKs","Prompt Blueprints","Enhanced Reliability","Data-Driven Decisions"}', '{}', true, '{}', '{}', '', now()),
('AIJobs.ai', 'aijobs-ai', 'Revolutionize your AI career or hiring with our global, specialized job platform.', 'Revolutionize your AI career or hiring with our global, specialized job platform.', 'https://cdn.futurepedia.io/2026-02-27T11-18-44.916Z-peGvqprGbABkbVlVxLF7d8OP2NgzSKOop.png', 'https://www.aijobs.ai/', 'free', '[{"plan": "Free Job Posting", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Curated Job Listings","Wide Geographic Reach","Diverse Departmental Opportunities","User-Friendly Interface","Specialized Focus","Global Opportunities"}', '{}', true, '{}', '{}', '', now()),
('KindredMind', 'kindredmind', 'Handle dementia calls in your reassuring voice.', 'Handle dementia calls in your reassuring voice.', 'https://cdn.futurepedia.io/2026-04-09T17-40-14.935Z-jjL4kgVo61yTRjTX6BLPY7x-7M1LItfVW.png', 'https://kindredmind.care/', 'paid', '[{"plan": "Essential", "price": "$129 per month", "features": []}, {"plan": "Standard", "price": "$179 per month", "features": []}, {"plan": "Complete", "price": "$239 per month", "features": []}, {"plan": "Care Circle Family Plan", "price": "$319 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Living Voice cloning","Clinical conversation engine","Personal knowledge base and training calls","Call handling tools","Clinically aligned approach","Caregiver relief"}', '{}', true, '{}', '{}', '', now())
ON CONFLICT (slug) DO NOTHING;

-- Category assignments
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'aicarousels' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'streamalive' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'flakes' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'reshot-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'moderne' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'leni' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'powtoon' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'powermode-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'amira-learning' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'gobblecube' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'gobblecube' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'applaime' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'finden' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'seozilla' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'domoai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'procurement-sciences-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'procurement-sciences-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'creatify-ai-product-video-generator' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'viyou-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'viyou-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'glambase' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'wuri' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'sloyd' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'sloyd' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'autosana' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'sheetai-app' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'lovo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'lovo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'lovo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'apriora' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'lakera' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'talkpal' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'talkpal' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'veesual' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'trace' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'quso-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'quso-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'ifoto' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'ifoto' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'ifoto' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'patlytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'paxton-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'bible-chat' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'bible-chat' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'creative-reality-studio-d-id' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'autodesk-forma' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'nanonets-resume-builder' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'momen' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'verdent' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'intrascope' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'fakeyou' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'fakeyou' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'fakeyou' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'cometapi' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'mindverse' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'prophet-security' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'skoot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'skoot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'zenity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'transcriptik' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'transcriptik' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'typli-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'airmusic' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'super-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'postly' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'postly' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'splutter-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'splutter-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ai-studios' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'brief-my-meeting' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'poptask' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'pine-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'pine-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = '2-b-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'mixus' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'evenup-law' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'evenup-law' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'getimgai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'resleeve' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'picsart' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'picsart' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'promptdrive-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'weryai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'postsyncer' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'boost-space' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'wonder-studio' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'wonder-studio' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'airbrush' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'superintelligent' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'starwriter-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'ivo' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'mem0' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'rows-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'rows-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'rows-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'gptinf' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'cxscore' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'coursebox' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'coursebox' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'aragon-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'altindex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'altindex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'relativity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'gptconsole' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'mypeas-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'mypeas-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'sobrief' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'sobrief' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'sobrief' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'airops' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'flickify' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'chefgpt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'lumen5' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'lumen5' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'shuffll' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'headshotgenerator-io' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'e9046cc6-d16b-4b54-bf0a-8fcf90ced455' FROM tools t WHERE t.slug = 'photomyne' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'photomyne' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'videogen' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'videogen' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'solid' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'mindos' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'mindos' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'iplan-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'fileai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'finch-3d' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'bluedot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'bluedot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'bluedot' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'beatwave' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'beatwave' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'bridgewise' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'bridgewise' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'promptcompose' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'aijobs-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'kindredmind' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '166567bd-3ee4-4bd6-999d-378258eec228' FROM tools t WHERE t.slug = 'kindredmind' ON CONFLICT DO NOTHING;

