-- ============================================================
-- Batch 18: 14 AI tools (auto-scraped from Futurepedia)
-- ============================================================

INSERT INTO tools (name, slug, tagline, description, logo_url, website_url, pricing_type, pricing_details, skill_level, has_api, platforms, features, integrations, is_published, best_for, not_for, editorial_verdict, last_verified_at) VALUES
('Alphastream', 'alphastream', 'Transform capital markets with AI-driven, real-time data extraction.', 'Transform capital markets with AI-driven, real-time data extraction.', 'https://cdn.futurepedia.io/566bbf137560515f31c0f1b9d7dadef75fe431b1-1920x1080.jpg', 'https://www.alphastream.ai/', 'contact', '[{"plan": "Custom Pricing", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Highly Accurate Data Extraction","Customizable Data Templates","Real-Time Data Processing","Secure and Private Data Handling","Enhanced Decision Making","Deep Market Insights"}', '{}', true, '{}', '{}', '', now()),
('Freebeat', 'freebeat', 'Transform music into engaging viral videos.', 'Transform music into engaging viral videos.', 'https://cdn.futurepedia.io/2026-02-27T11-20-10.501Z-Wfa1BfI1w4sHXwDlQRdjv_snunxyOqeAF.png', 'https://freebeat.ai/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Basic", "price": "$4.99", "features": []}, {"plan": "Standard", "price": "$9.99 per month", "features": []}, {"plan": "Pro", "price": "$24.99 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Music Video Agent","Magic Effects","Customizable Videos","Vast Toolset","User-Friendly","Versatile Platform Support"}', '{}', true, '{}', '{}', '', now()),
('Ninjachat AI', 'ninjachat-ai', 'All-in-one AI platform for writing, image, music, and analysis.', 'Ninjachat AI revolutionizes the way we interact with artificial intelligence by providing a comprehensive, all-in-one platform that integrates multiple AI models, such as ChatGPT, Claude, and Stable Diffusion. Designed for individuals and professionals seeking efficiency and cost-saving solutions, Ninjachat AI simplifies complex tasks ranging from writing and image generation to document analysis and music composition.', 'https://cdn.futurepedia.io/2024-09-13T08-37-09.821Z-6f94b99efff4f1428eaa3ff30dad60b398a31587-1920x1080.png', 'https://ninjachat.ai/', 'paid', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$11 per month", "features": []}]', 'beginner', false, '{"web"}', '{"Multiple AI Models","AI Writing Tools","Interactive Story Plotter","AI Music Generator","Time Efficiency","Cost-Effective"}', '{}', true, '{}', '{}', '', now()),
('Autodraft', 'autodraft', 'AI tool transforming ideas into engaging, high-quality content.', 'AI tool transforming ideas into engaging, high-quality content.', 'https://cdn.futurepedia.io/2025-01-31T23-23-38.447Z-twLr-fA9G0VVXWllahaojuw4kw1_EiKOd.PNG', 'https://autodraft.in/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$10 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Driven Content Creation","User-Friendly Interface","Customizable Templates","Real-Time Collaboration","Time Efficiency","Versatile Application"}', '{}', true, '{}', '{}', '', now()),
('10Web', '10web', 'AI-driven website creation, hosting, optimization, and ecommerce in one platform.', 'AI-driven website creation, hosting, optimization, and ecommerce in one platform.', 'https://cdn.futurepedia.io/cd41660fae734e17c510c30b7fa148305ca022ab-2505x1234.png', 'http://10web.sjv.io/futurepedia', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'intermediate', false, '{"web"}', '{"AI Ecommerce Website Builder","Automated Hosting","PageSpeed Booster","Security and Real-time Backups","Efficiency in Website Creation","Comprehensive Solution"}', '{}', true, '{}', '{}', '', now()),
('Gumloop', 'gumloop', 'Automate workflows effortlessly with AI-driven, drag-and-drop simplicity.', 'Automate workflows effortlessly with AI-driven, drag-and-drop simplicity.', 'https://cdn.futurepedia.io/2025-02-14T20-17-17.959Z-DO3HB5KfTVBI653YZjQFG-mF4xL259Lnh.png', 'https://www.gumloop.com/', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}, {"plan": "Pro Tier", "price": "$97 per month", "features": []}]', 'intermediate', false, '{"web"}', '{"AI-Driven Automation","User-Friendly Interface","Extensive Integration","Security and Scalability","Ease of Use","Comprehensive Security"}', '{}', true, '{}', '{}', '', now()),
('Align AI', 'align-ai', 'Streamlines AI strategy alignment with business objectives.', 'Streamlines AI strategy alignment with business objectives.', 'https://cdn.futurepedia.io/0f9c728fc0751a9308056780f6190ceb04eebbd2-1920x1080.png', 'https://tryalign.ai/', 'contact', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Real-Time Data Ingestion","Intuitive Dashboard","Conversation Breakdown","Custom Insight Reports","Efficient Data Analysis","User Experience Enhancement"}', '{}', true, '{}', '{}', '', now()),
('CatDoes', 'catdoes', 'Use AI agents to create apps from your ideas.', 'Use AI agents to create apps from your ideas.', 'https://cdn.futurepedia.io/2026-02-27T11-20-12.542Z-Ey5clRgnCX-lf5iQnxgCeW2DkloNUmBub.png', 'https://catdoes.com/', 'freemium', '[{"plan": "Free", "price": "$0 per month", "features": []}, {"plan": "Starter", "price": "$20 per month", "features": []}, {"plan": "Pro", "price": "$89.99 per month", "features": []}, {"plan": "Enterprise (DogDoes)", "price": "Custom", "features": []}]', 'beginner', false, '{"web"}', '{"Agentic App Development","Live Preview","Multi-Agent Approach","Supabase Integration","No Coding Required","Time-Saving"}', '{}', true, '{}', '{}', '', now()),
('Renamer.ai', 'renamer-ai', 'Auto-renames messy files using content into clear labels.', 'Auto-renames messy files using content into clear labels.', 'https://cdn.futurepedia.io/2026-03-02T09-15-34.540Z-YT6PypGskSrPdUdDHSsWtFwfsSnvnLqfB.png', 'https://renamer.ai/', 'freemium', '[{"plan": "Starter", "price": "$0 per month", "features": []}, {"plan": "Pro", "price": "$9.95 per month", "features": []}, {"plan": "Power User", "price": "$29.95 per month", "features": []}, {"plan": "Ultimate", "price": "$99.95 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI content-aware renaming","Magic Folders automation","Custom naming templates","Bulk renaming with safety controls","Huge time saver","Strong for ongoing workflows"}', '{}', true, '{}', '{}', '', now()),
('Booke AI', 'booke-ai', 'Revolutionizes bookkeeping with AI-driven automation and accuracy.', 'In the ever-evolving landscape of financial technology, Booke AI emerges as a revolutionary tool designed to automate and streamline the cumbersome process of bookkeeping. Leveraging advanced artificial intelligence, Booke AI enhances accuracy, speed, and efficiency in managing financial transactions and bookkeeping tasks. This tool is particularly tailored for accountants, small to medium-sized enterprises, and financial professionals aiming to minimize manual intervention and maximize productivity in their financial management.', 'https://cdn.futurepedia.io/aed1185d312cbf2c556a9af5a30b9b836977c921-1818x786.png', 'https://booke.ai/', 'freemium', '[{"plan": "Free Trial", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Automated Transaction Categorization","Real-Time Document Data Extraction","Intelligent Reconciliation Assistance","Client Communication Portal","Time Efficiency","Enhanced Accuracy"}', '{}', true, '{}', '{}', '', now()),
('PDF Flex', 'pdf-flex', 'Revolutionizes PDF interaction with AI chat and versatile conversion options.', 'Revolutionizes PDF interaction with AI chat and versatile conversion options.', 'https://cdn.futurepedia.io/be66b4b24dcd2fa79b9468060dd2be9385b257a9-2488x1203.png', '', 'free', '[{"plan": "Completely Free", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"AI Chat with PDF","Broad Conversion Spectrum","High-Quality Outcomes","Cross-Platform Accessibility","Rapid File Transformation","No Login Requirement"}', '{}', true, '{}', '{}', '', now()),
('Maps GPT', 'maps-gpt', 'AI-driven, swiftly creates customized, editable maps with intuitive search options.', 'AI-driven, swiftly creates customized, editable maps with intuitive search options.', 'https://cdn.futurepedia.io/0a6652819ee8b78e384fd308a80c1a2e8f59374e-1680x876.png', 'https://www.mapsgpt.com/', 'free', '[{"plan": "Free Use", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Custom Map Creation","Versatile Search Options","Editable Maps","Diverse Use Cases","Time-Saving","User-Friendly"}', '{}', true, '{}', '{}', '', now()),
('Deamoy', 'deamoy', 'Create professional websites with AI design.', 'Create professional websites with AI design.', 'https://cdn.futurepedia.io/2026-02-04T16-39-54.122Z-phpaaKpaX8r5XsnUPEpd7L_gn2MmX_6-2.webp', 'https://deamoy.ai/', 'freemium', '[{"plan": "Free Tier", "price": "$0 per month", "features": []}, {"plan": "Pro Tier", "price": "$12.50 per month", "features": []}, {"plan": "Team Tier", "price": "$25 per month", "features": []}, {"plan": "Enterprise Tier", "price": "$50 per month", "features": []}]', 'beginner', false, '{"web"}', '{"AI-Powered Page Building","Customizable Templates","Visual and AI Editing","Collaboration Tools","User-Friendly Experience","Cost-Effective Plans"}', '{}', true, '{}', '{}', '', now()),
('DeepL Translator', 'deepl-translator', 'Transform text across 32 languages with unmatched accuracy.', 'Transform text across 32 languages with unmatched accuracy.', 'https://cdn.futurepedia.io/b164fb9cdee1ce72f11d57087385ccc528fa5bf5-2471x1225.png', 'https://www.deepl.com/translator', 'freemium', '[{"plan": "Free Tier", "price": "Free", "features": []}]', 'beginner', false, '{"web"}', '{"Accurate Translations","Multiple Language Support","Document Translation","DeepL Write","High Translation Quality","User-Friendly Interface"}', '{}', true, '{}', '{}', '', now())
ON CONFLICT (slug) DO NOTHING;

-- Category assignments
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'alphastream' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'freebeat' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'ninjachat-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '03118187-c9c3-41cc-8112-60c5b0404fd3' FROM tools t WHERE t.slug = 'ninjachat-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '49cbbfa2-ae4d-4490-9143-8ac2fd10e390' FROM tools t WHERE t.slug = 'autodraft' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'autodraft' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = '10web' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = '10web' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'gumloop' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'align-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'align-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'catdoes' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'renamer-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'booke-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '28319852-f741-4dc6-a7fd-0dc7bd3014aa' FROM tools t WHERE t.slug = 'booke-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '0a4d2800-e4c0-458b-b449-20402acfedb7' FROM tools t WHERE t.slug = 'booke-ai' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '4cfb8b96-270a-43cd-8ea1-0630169e065f' FROM tools t WHERE t.slug = 'pdf-flex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '6afe9cfb-be3a-4000-a9a2-7bc0cb4c1c85' FROM tools t WHERE t.slug = 'pdf-flex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'pdf-flex' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, 'ec3e37ef-45f2-4d8c-9704-5f72f87a3670' FROM tools t WHERE t.slug = 'maps-gpt' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '99ea1197-e320-4535-b83d-aa8d7456f238' FROM tools t WHERE t.slug = 'deamoy' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, '553d6927-d9f8-4dbf-8e1b-5e16cbdcc616' FROM tools t WHERE t.slug = 'deepl-translator' ON CONFLICT DO NOTHING;

