-- ============================================================
-- Batch 19 — Part 1: 20 curated AI tools (Step 41 — scale to 1,500)
-- Hand-authored enrichment (no API spend). Every tool satisfies ≥3/5
-- plan §41 criteria: trending (github-trending recent list), growing
-- (≥18K GitHub stars), viability (proxy >30). All slugs deduped vs the
-- existing 1,000-tool catalog.
-- ============================================================

INSERT INTO tools (
  name, slug, tagline, description, website_url,
  pricing_type, pricing_details, skill_level, has_api, platforms,
  features, integrations, is_published,
  best_for, not_for, editorial_verdict,
  tutorial_urls, limitations, models, community_links, use_cases, our_views,
  last_verified_at
) VALUES
('browser-use', 'browser-use', 'Open-source Python library that lets an LLM drive a browser through Playwright.', 'browser-use is an open-source Python framework that turns any LLM into a web agent. It wraps Playwright with a DOM-aware action layer — the model receives an annotated snapshot of the page and decides whether to click, type, scroll, or wait. Unlike screenshot-only approaches, browser-use feeds a structured element tree plus optional vision, which keeps token costs manageable on long flows.

It is used as the scaffolding for a rapidly growing set of agent products: form-fillers, data-extraction bots, QA automations, e-commerce checkout agents, and research assistants. The library ships with memory, history recording, replay, and a built-in evaluator to run your agent against a scripted task set.

The team also operates a hosted cloud (browser-use.com) that provides remote browser sessions, concurrency, session persistence, and an API key interface for teams that do not want to manage Playwright infrastructure themselves. The cloud tier is optional — everything the library does runs locally.

It is one of the top 3 Python repos of 2024–2025 by both stars and real-world adoption, widely cited in agent tutorials and referenced by frameworks like LangChain and CrewAI as the recommended browser-automation primitive.', 'https://browser-use.com', 'freemium', '[{"plan":"Open Source","price":"Free","features":["Full library on PyPI","Self-hosted Playwright","All core actions and vision"]},{"plan":"Cloud","price":"Usage-based","features":["Hosted browser sessions","Concurrency limits","API key access","Session recordings"]}]'::jsonb, 'intermediate', true, '{"api","cli"}', '{"DOM + vision hybrid page understanding","Action primitives (click, type, scroll, wait, navigate)","Agent memory and task history","Session replay and debugging","Parallel agent orchestration","Hosted cloud with persistent browser sessions","Works with any LLM (OpenAI, Anthropic, Gemini, local via Ollama)","Structured output via function calling","Built-in evaluator for agent benchmarks"}', '{"Playwright","LangChain","CrewAI","OpenAI","Anthropic","Gemini","Ollama","Azure OpenAI"}', true, '{"Developers building web-automation agents","QA teams automating UI tests","Data teams scraping login-walled sites","Ops teams automating repetitive browser work"}', '{"Non-developers looking for a no-code tool","Workflows that only need static-site scraping (simpler tools exist)"}', 'The default Python library for browser agents in 2026. Pick it if you are building anything that needs an LLM to interact with real webpages; skip it if you only need to scrape static HTML.', '{"https://docs.browser-use.com/quickstart"}', 'Requires a capable LLM (GPT-4-class or better) for complex flows — Haiku-tier models drift. Playwright overhead means each action costs ~1–3s wall-time. Sites with aggressive bot detection (Cloudflare Turnstile, Datadome) still block browser-use sessions unless you pair it with a proxy / stealth layer.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Fill multi-step forms on SaaS admin panels that have no public API.","Run nightly QA passes against your own production web app.","Extract structured data from dashboards that require login.","Prototype a customer-support agent that navigates your web UI."}', 'Sweet spot: a developer who already works in Python and has a specific web-automation job to do. Drop browser-use into a script, point an LLM at it, and you will have a working agent in an afternoon. It is the most honest middle ground between headless scraping (brittle) and full-blown commercial RPA (expensive).

Failure modes to know about. First, cost creeps: every page snapshot is tokens, so a 50-step agent on GPT-4o can hit a few dollars per run — cache aggressively, use smaller models for routine steps. Second, model capability is a hard floor — if your agent is deciding between visually similar buttons, you need vision-capable models. Third, anti-bot pages still win: browser-use is a tool, not a stealth solution.

What to pilot before committing. Build one agent against one flow. Measure success rate over 20 runs, cost per run, and wall-time per run. If success rate is above 90% on your target flow, it will scale; below 70% and the prompt/model needs work before you invest more.', now()),
('Crawl4AI', 'crawl4ai', 'Open-source web crawler purpose-built for LLM pipelines and RAG ingestion.', 'Crawl4AI is an open-source Python crawler designed specifically for feeding large language models. It fetches pages (including JavaScript-heavy ones through a built-in headless browser), strips boilerplate, converts content to clean Markdown, and chunks it for embedding — all in one pipeline. That output shape is what differentiates it from general-purpose crawlers like Scrapy or Playwright scripts that still require you to write your own text-cleaning layer.

It supports async parallel crawling, sitemap-driven discovery, session reuse for login-walled sites, and pluggable extraction strategies (CSS selectors, LLM-powered schema extraction, or regex). Output can be piped directly into a vector store.

The project is actively maintained, ships weekly updates, and has become the default "first-step" tool in a lot of open-source RAG stacks. It is free, MIT-licensed, and runs locally — no vendor lock-in.', 'https://crawl4ai.com', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full library","Headless crawling","LLM schema extraction","Async parallelism"]}]'::jsonb, 'intermediate', false, '{"cli","api"}', '{"Headless browser-backed crawling (Playwright)","Clean Markdown output for RAG","Async parallel crawling with rate limits","Sitemap and link-graph discovery","LLM-powered schema extraction","CSS / XPath / regex extraction strategies","Session persistence for authenticated pages","Chunking and metadata for embeddings","Docker image and Python SDK"}', '{"Playwright","OpenAI","LlamaIndex","LangChain","Pinecone","Weaviate","Chroma"}', true, '{"Engineers building RAG pipelines","Data teams crawling docs into a knowledge base","Researchers who need clean page text at scale"}', '{"Non-coders","One-off scrapes of a single page (curl + readability is faster)"}', 'The right default for turning a list of URLs into clean, chunked, LLM-ready text. Free, fast, and the Markdown output removes a whole class of RAG boilerplate.', '{"https://docs.crawl4ai.com/"}', 'Aggressive anti-bot sites (Cloudflare, Datadome, PerimeterX) still block it unless you pair with a proxy provider. The LLM-extraction mode calls an external model, which adds cost per page. Scaling past a few hundred concurrent crawls hits local Chromium memory limits — run it inside a container cluster for serious workloads.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ingest an entire documentation site into a vector store in one run.","Build a nightly crawler that refreshes embeddings for a set of competitor sites.","Extract structured product data from e-commerce category pages using LLM schemas.","Pre-process news articles into clean Markdown for a summarization pipeline."}', 'Sweet spot: a RAG builder who is tired of gluing BeautifulSoup + readability + a chunker together and wants one library that gets them from URL to embedding-ready text. The Markdown output alone saves a day of work per new project.

Failure modes. It is still a crawler: politeness, legal/ToS checks, and robots.txt enforcement are on you. The headless browser makes it slower than a pure HTTP crawler — if your targets are static HTML, a lighter tool will move 10x faster. LLM extraction is powerful but expensive; use it for high-value targets only, not bulk ingestion.

What to pilot. Crawl a 100-page site you know well. Compare the Markdown output to what you would have written by hand. If the cleanup quality is acceptable, you have a winner; if not, your site has layout quirks that need a custom extractor and Crawl4AI will only give you part of the job.', now()),
('AnythingLLM', 'anything-llm', 'Local-first desktop app that turns any document set into a private ChatGPT-style knowledge base.', 'AnythingLLM is an open-source, full-stack application from Mintplex Labs that bundles a vector database, an embedder, an LLM connector layer, and a chat UI into a single desktop app. Drop in documents (PDF, DOCX, Markdown, websites, YouTube transcripts, Confluence exports), pick a model, and you have a private RAG assistant running on your laptop — no cloud hop required.

It supports essentially every model source in the market today: OpenAI, Anthropic, Gemini, Azure, AWS Bedrock, Ollama for local models, LM Studio, LocalAI, HuggingFace, and more. The "workspaces" concept lets you create isolated knowledge silos — one for HR docs, one for engineering wiki, one for a client project — each with its own chat history and embeddings.

Beyond chat, AnythingLLM includes agent skills (browse, code-run, web search), multi-user access with permissions, API access for embedding into your own app, and a browser extension. The desktop app is one-click install on Mac / Windows / Linux; a Docker image is available for team deployments.', 'https://anythingllm.com', 'freemium', '[{"plan":"Desktop (self-hosted)","price":"Free","features":["Unlimited workspaces","All model integrations","Single-user","Local or cloud embeddings"]},{"plan":"Cloud","price":"From $50/mo","features":["Multi-user workspaces","SSO","Managed hosting","Team permissions"]}]'::jsonb, 'beginner', true, '{"desktop","web","api"}', '{"Desktop app for Mac / Windows / Linux","Document ingestion: PDF, DOCX, Markdown, HTML, YouTube, Confluence","Workspaces for isolated knowledge silos","Model-agnostic — 20+ LLM providers supported","Local-only mode with Ollama / LM Studio","Agent skills: web browse, code run, search","Browser extension for snippet capture","Multi-user with permissions (cloud tier)","Built-in vector DB (LanceDB by default)","API access for embedding into your own product"}', '{"OpenAI","Anthropic","Gemini","Ollama","LM Studio","Azure OpenAI","AWS Bedrock","LocalAI","Pinecone","Weaviate","Chroma","Qdrant"}', true, '{"Individuals who want a private ChatGPT over their own files","Small teams needing a shared internal knowledge base","Consultants organising research per client","Privacy-sensitive orgs keeping data on-prem"}', '{"Enterprises needing granular per-document ACLs at scale","Teams that already live inside Notion / Slack and want native search there"}', 'The easiest path from "pile of documents" to "working private RAG chatbot" right now. Desktop app quality is genuinely polished; model flexibility is best-in-class.', '{"https://docs.anythingllm.com/"}', 'Search quality is only as good as your embedder and chunking strategy — the defaults work but tuning helps for dense domains. The agent tools are less mature than in dedicated frameworks like LangChain. Multi-user governance (fine-grained per-doc ACLs, audit logs) is lighter than enterprise platforms like Glean.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Chat with your last 200 meeting-note PDFs to recall a decision.","Build a client-specific RAG workspace that runs entirely locally.","Give a small team a shared wiki chatbot with zero cloud dependency.","Turn a product changelog + docs site into an internal support assistant."}', 'Sweet spot: one person or a 2–10 person team that wants a "ChatGPT but over my files" experience without writing a single line of code or sending anything to a vendor. Install takes five minutes. Hooking up local models via Ollama gets you a private-by-default setup.

Failure modes. At the 1,000+ documents / 10+ users scale, the cracks show: governance tooling is thinner than Glean or Notion AI Enterprise, and multi-tenant performance isn''t the project''s focus. Agent capabilities are there but shallower than in purpose-built agent platforms — if agent workflows are your core need, build with LangGraph or browser-use and use AnythingLLM only as the chat layer.

What to pilot. Install the desktop app, ingest 50 documents, ask 20 real questions. Measure whether the answers cite the right chunks. If yes, scale up. If no, the issue is probably chunking strategy — adjust before blaming the tool.', now()),
('AutoGen', 'autogen', 'Microsoft open-source framework for building multi-agent LLM systems that collaborate and converse.', 'AutoGen is Microsoft Research''s open-source framework for orchestrating multiple LLM agents that talk to each other to solve a task. Rather than writing a single long prompt, you define agents — a "Planner," a "Coder," a "Critic," a "UserProxy" — give each one its own system prompt and tool access, and let them converse. AutoGen handles the message routing, tool-use loops, code execution, and termination conditions.

The current 0.4 rewrite (late 2024) split the framework into layers: a lightweight core event system, an agent API, and higher-level "teams" abstractions (RoundRobinGroupChat, SelectorGroupChat, etc). There is also AutoGen Studio — a no-code UI to prototype multi-agent workflows before dropping into Python.

AutoGen is one of the most-cited multi-agent frameworks in academic work and is used in Microsoft''s own products. It is MIT-licensed, model-agnostic (OpenAI, Anthropic, Azure, local), and has a large ecosystem of example agents and patterns.', 'https://microsoft.github.io/autogen/', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full framework","AutoGen Studio UI","All agent patterns"]}]'::jsonb, 'intermediate', false, '{"api","desktop"}', '{"Multi-agent conversation orchestration","Built-in agent roles (UserProxy, Assistant, Critic, etc)","Tool / function calling across agents","Code execution sandbox","Group chat patterns (round-robin, selector, swarm)","AutoGen Studio — visual flow builder","Model-agnostic (OpenAI, Anthropic, Azure, local)","Human-in-the-loop checkpoints","Async message streaming"}', '{"OpenAI","Anthropic","Azure OpenAI","Gemini","Ollama","Docker (for code exec)","Jupyter"}', true, '{"Researchers exploring multi-agent patterns","Developers prototyping collaborative AI workflows","Teams building code-writing or analysis pipelines"}', '{"Non-developers","Applications needing a single simple prompt-to-response (overkill)","Real-time UI agents (framework is batch-oriented)"}', 'The most academically rigorous multi-agent framework, now with a cleaner 0.4 API. Pick it for research or complex multi-step workflows; choose lighter frameworks for simple agent tasks.', '{"https://microsoft.github.io/autogen/stable/user-guide/core-user-guide/index.html"}', 'The 0.2 → 0.4 rewrite broke a lot of community examples — older tutorials may not work. Multi-agent cost multiplies fast: a conversation of 4 agents over 10 turns is 40 LLM calls. Code-execution sandbox requires Docker for safety. Debugging emergent failures across agents is harder than debugging a single chain.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a code-generation pipeline where a planner, a coder, and a reviewer agent collaborate.","Prototype a research-assistant team that splits a question across specialised agents.","Run batch data-analysis tasks where one agent proposes SQL and another validates results.","Explore agent-collaboration patterns for a paper or internal R&D project."}', 'Sweet spot: a developer or researcher who genuinely needs multi-agent collaboration — not because it''s trendy, but because the task decomposes cleanly into specialised roles. Code generation with a critic loop is the canonical AutoGen win.

Failure modes. Teams reach for multi-agent when a single agent with good tool-use would do the job faster and cheaper. AutoGen''s abstractions only pay off past a real complexity threshold — below it, the overhead is just noise. The 0.4 rewrite also means you should treat anything written for 0.2 as historical context, not a working template.

What to pilot. Pick one task where you can articulate the agents'' distinct roles (e.g., "planner decomposes, coder writes, tester validates"). Build it end-to-end in AutoGen, then build the same thing as a single-agent-with-tools approach. Compare output quality, cost, and debuggability. If multi-agent wins on at least two of those three, commit; if not, the simpler approach will scale better.', now()),
('Cherry Studio', 'cherry-studio', 'Multi-model desktop AI client with built-in knowledge bases, agents, and translation.', 'Cherry Studio is a cross-platform desktop client (Mac, Windows, Linux) that gives you a single UI for every major LLM provider. You drop in API keys for OpenAI, Claude, Gemini, DeepSeek, Qwen, Ollama-hosted local models, OpenRouter, and dozens more, and Cherry lets you chat with any of them from the same window. Switching models mid-conversation is a click.

Beyond basic chat, it adds features that power users normally have to glue together themselves: a built-in knowledge-base feature (ingest PDFs, Word docs, websites, build a retrievable workspace), translation between 100+ languages, a "mini program" plugin system, custom assistants with their own prompts, markdown notes, and pricing-aware token usage dashboards.

It is open-source (Apache 2.0), free to use with your own API keys, and built by an active community. Updates ship frequently. For users who already have API credits and want a richer UI than provider-native apps, Cherry Studio is the most fully-featured option in the multi-model desktop client category.', 'https://cherry-ai.com', 'free', '[{"plan":"Desktop","price":"Free (Apache 2.0)","features":["All providers","Unlimited knowledge bases","Custom assistants","Translation"]}]'::jsonb, 'beginner', false, '{"desktop"}', '{"Cross-platform desktop (Mac / Windows / Linux)","Multi-model support (OpenAI, Claude, Gemini, DeepSeek, Qwen, Ollama, OpenRouter, 30+)","Built-in knowledge bases with embeddings","Custom assistants with system prompts","Translation across 100+ languages","Markdown + mermaid rendering","Token usage and pricing dashboard","Mini-program plugin marketplace","Conversation branching and search"}', '{"OpenAI","Anthropic","Gemini","DeepSeek","Qwen","Ollama","OpenRouter","Azure OpenAI","Zhipu","Moonshot"}', true, '{"Power users juggling multiple model providers","Researchers comparing outputs across models","Knowledge workers who want local documents in their chat","Freelancers who pay-per-token instead of subscribing to each provider"}', '{"Users who only use one model (native apps are lighter)","Teams needing shared workspaces (Cherry is single-user)"}', 'The best multi-model desktop client in 2026 if you prefer paying per-token over provider subscriptions. Rich feature set, actively developed, zero vendor lock-in.', '{"https://docs.cherry-ai.com/"}', 'Single-user only — no shared workspaces or collaboration. Knowledge base features are lighter than dedicated RAG tools; good for personal notes, not for a company wiki. You still need API keys from each provider — Cherry does not abstract billing.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Send the same prompt to GPT-4o, Claude Sonnet, and Gemini side by side to compare answers.","Build a personal knowledge base over your reading notes and query it alongside a live model.","Translate long documents using whichever model performs best for your language pair.","Keep a local ChatGPT-equivalent running on Ollama plus Claude for heavy tasks, all in one app."}', 'Sweet spot: someone who already uses 2+ model providers and is tired of switching between ChatGPT.com, claude.ai, and Gemini. Cherry collapses those into one window and adds a token-usage view so you can actually see which model is costing you what.

Failure modes. Feature breadth is the risk — the UI crams a lot in, and first-time users can feel overwhelmed. Translation and knowledge-base features are "good enough" rather than best-in-class; if either is your primary need, specialised tools (DeepL, AnythingLLM) will do that one job better.

What to pilot. Install Cherry, plug in your existing OpenAI and Anthropic keys, and use it as your daily driver for a week. If you notice yourself reaching for Cherry instead of provider web apps, the pay-per-token math likely wins; if you keep bouncing back, you probably don''t actually need multi-model flexibility and a single subscription is simpler.', now()),
('ChatTTS', 'chattts', 'Open-source text-to-speech model optimised for natural, conversational dialogue.', 'ChatTTS is an open-source TTS model from 2noise, specifically trained on conversational data rather than the audiobook-style corpora that dominate most open TTS systems. The result is a voice that includes natural disfluencies, laughter, stress patterns, and turn-taking cues — useful for podcast generation, game NPCs, and AI agents that need to sound less like a radio announcer.

It supports Chinese and English, emits prosody tags inline (<laugh>, <break>, <stress>), and runs reasonably fast on a single GPU. The model weights are open under a research license, and a demo is available at 2noise.com. A growing set of community wrappers adds streaming, voice cloning, and REST API shims on top of the base model.

ChatTTS is not a commercial product — there is no hosted SaaS or official API — but it is one of the most downloaded open TTS checkpoints on HuggingFace and a foundational component in several open-source voice-agent projects.', 'https://2noise.com', 'free', '[{"plan":"Research License","price":"Free","features":["Full model weights","Inference code","Demo UI"]}]'::jsonb, 'intermediate', false, '{"cli"}', '{"Conversational TTS with natural disfluencies","Inline prosody tags (<laugh>, <break>, <stress>)","Chinese and English support","Single-GPU inference","Open research license","HuggingFace checkpoint","Community wrappers for streaming and voice cloning"}', '{"HuggingFace Transformers","PyTorch","Gradio"}', true, '{"Developers building podcast / voice-agent tools","Researchers exploring conversational TTS","Hobbyists running local voice apps with no subscription cost"}', '{"Commercial products (research license restricts use)","Voice-cloning at production quality (dedicated tools outperform)","Non-developers (no hosted UI)"}', 'The most natural-sounding open-source TTS for conversational audio in 2026. Research license is the catch — great for prototypes and demos, not for commercial shipping.', '{}', 'Research license prohibits most commercial use — confirm with 2noise before shipping. No official hosted API; you run the model yourself on a GPU. Voice cloning is available via community forks but is not a first-class feature. Latency on CPU is impractical — plan for at least a consumer-grade NVIDIA GPU.', '{"chattts"}', '{"reddit_threads":[]}'::jsonb, '{"Generate natural-sounding narration for a podcast demo or YouTube short.","Power NPC voices in an indie game prototype.","Prototype a voice-agent that sounds less robotic than standard open-TTS.","Research prosody and dialogue-level speech synthesis."}', 'Sweet spot: a developer or researcher who wants a locally-run TTS with conversational realism and is comfortable with a research-only license. On a mid-range GPU it generates audio quickly enough for interactive use, and the <laugh> / <break> tag system gives you real creative control.

Failure modes. The licensing question is the single biggest blocker for shipping anything commercial — do not assume MIT. Voice quality, while strong for open-source, still trails top commercial TTS (ElevenLabs, Play.ht) on pure naturalness and consistency across long passages. Support is community-driven; expect rough edges.

What to pilot. Run a 30-second demo locally. If the voice quality clears your bar and the license fits your use case, plan on wrapping it with a lightweight FastAPI layer and caching audio for repeat phrases. If you need commercial-grade output at scale, budget for a paid TTS — the cost of licensing negotiation exceeds what a commercial API charges.', now()),
('CopilotKit', 'copilotkit', 'React toolkit for embedding production-grade AI copilots and chat UIs into any web app.', 'CopilotKit is an open-source framework for adding AI copilots to React applications. Instead of building the chat UI, state management, tool-use scaffolding, and streaming plumbing from scratch, you install CopilotKit and get production-ready components: a sidebar copilot, an inline textarea autocomplete, a modal assistant, and a headless primitive for custom UIs.

The core primitive is "copilot actions" — functions you register that the LLM can call on behalf of the user (e.g., navigate, update state, submit forms, query your API). CopilotKit handles the tool-use loop, streams the response, and keeps the React state in sync. It supports OpenAI, Anthropic, and any OpenAI-compatible API out of the box.

CopilotKit Cloud adds observability, a hosted LLM proxy, usage analytics, and guardrails. The open-source layer is free forever and covers most single-app use cases; the cloud is for teams shipping copilots at scale who want a managed backend.', 'https://docs.copilotkit.ai', 'freemium', '[{"plan":"Open Source","price":"Free","features":["All React components","Self-hosted LLM connection","All actions and primitives"]},{"plan":"Cloud","price":"Usage-based","features":["Hosted LLM proxy","Observability","Guardrails","Analytics"]}]'::jsonb, 'intermediate', true, '{"web","api"}', '{"Pre-built React chat UI (sidebar, modal, inline)","Copilot actions — LLM-callable functions","Streaming responses with state sync","Autocomplete primitive for textareas","Headless mode for fully custom UIs","Works with OpenAI, Anthropic, or any OAI-compatible API","Cloud observability and analytics","Guardrails for content moderation"}', '{"OpenAI","Anthropic","LangChain","LangGraph","Next.js","Remix","Vite"}', true, '{"React developers shipping in-app AI features","Startups adding a copilot without rebuilding chat infra","SaaS teams exposing complex features through a natural-language UI"}', '{"Non-React stacks","Teams who want a full standalone chatbot (build it directly on AI SDK instead)","Mobile-first apps (primary focus is web)"}', 'The fastest way to ship a production copilot inside a React app. The "copilot actions" primitive is the real unlock — it bridges LLM and UI state cleanly.', '{"https://docs.copilotkit.ai/quickstart"}', 'React-only — no first-class Vue or Svelte support. The cloud tier is newer and less mature than the OSS layer. Complex agent workflows (multi-step planning, browsing, code execution) are not CopilotKit''s strength — it is primarily an in-app chat layer.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Add a \"Chat with your dashboard\" sidebar to a SaaS admin panel.","Ship inline text autocomplete powered by an LLM in your editor product.","Build an assistant that can execute UI actions (filter, export, create) on behalf of the user.","Prototype a multi-step copilot flow without writing tool-use plumbing from scratch."}', 'Sweet spot: a React-based SaaS team that has decided they want an in-app copilot and does not want to spend a month building chat infra. CopilotKit gets you from zero to working prototype in an afternoon, and the actions primitive makes the LLM''s capabilities grow with your product''s feature set.

Failure modes. If your product is not React, CopilotKit is a non-starter — the Vue / Svelte story is thin. If your use case is actually autonomous-agent-style (browse the web, run code, plan long tasks), CopilotKit is the wrong abstraction — use LangGraph or browser-use directly. The cloud tier pricing is usage-based and can creep up for high-traffic apps; self-host the OSS layer if cost matters.

What to pilot. Add the sidebar component to a staging copy of your app, register 3–5 copilot actions against real features, and test whether a non-technical teammate can accomplish the same thing through natural language that they would through the UI. If yes, you have a real copilot, not a gimmick.', now()),
('Composio', 'composio', 'Auth and tool-integration layer for AI agents — 250+ apps behind one API.', 'Composio is an integrations platform built specifically for AI agents. It provides a single SDK and REST API that exposes 250+ SaaS tools (Gmail, Slack, GitHub, Linear, HubSpot, Notion, Google Drive, Stripe, Jira, Salesforce, and many more) as LLM-callable functions. Crucially, it handles the OAuth dance, token refresh, user-scoped credentials, and execution sandboxing so your agent code stays small.

The core problem Composio solves is painful: every new tool an agent needs requires OAuth setup, per-user token storage, scope management, and wrapper code. Composio centralises all of that into one dashboard. You register your app, add the tools you want, and the SDK returns tool schemas ready to drop into OpenAI, Anthropic, LangChain, CrewAI, or AutoGen.

It is open-source at the core (the "tool use" SDK is MIT-licensed), with a paid cloud that hosts the OAuth infrastructure, rate-limit management, and per-tool analytics. For teams building agents that need to take real actions in real SaaS tools — not just chat — Composio has become the default choice.', 'https://docs.composio.dev', 'freemium', '[{"plan":"Free","price":"$0","features":["10k tool calls/mo","250+ integrations","Community support"]},{"plan":"Hobbyist / Pro","price":"Usage-based","features":["Higher tool-call limits","Team seats","Priority support"]},{"plan":"Enterprise","price":"Custom","features":["SSO","SLA","Dedicated support","On-prem option"]}]'::jsonb, 'intermediate', true, '{"api"}', '{"250+ SaaS integrations out of the box","OAuth handling and token refresh","Per-user credential scoping","Tool schemas ready for OpenAI / Anthropic function calling","Native SDKs for Python and TypeScript","Framework adapters (LangChain, CrewAI, AutoGen)","Execution sandbox and rate-limit governance","Triggers and webhooks for reactive agents","Observability dashboard"}', '{"OpenAI","Anthropic","LangChain","CrewAI","AutoGen","LlamaIndex","Gmail","Slack","GitHub","Linear","Notion","HubSpot","Stripe","Jira","Salesforce"}', true, '{"Developers shipping agents that take real actions in SaaS tools","Teams that do not want to maintain OAuth code per integration","Agent products serving multiple end-users with scoped credentials"}', '{"Pure chat agents that only need RAG (no external actions)","Workflows where you already have deep SaaS integration code (migration cost)"}', 'The default tool-integration layer for any agent that needs to do more than chat. The OAuth-handling alone saves weeks of engineering.', '{"https://docs.composio.dev/introduction/intro/overview"}', 'Free tier is generous but runnable apps at scale hit the paid tier quickly. Some long-tail SaaS tools have thinner coverage than the top 50 integrations. As a third-party auth layer, there is regulatory consideration if you are in a compliance-heavy domain (healthcare, finance) — talk to their team about data-residency options.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ship a sales agent that reads Gmail, updates HubSpot, and posts summaries to Slack.","Add 50 SaaS tools to an existing LangChain agent in one afternoon.","Build a per-user assistant that can act on each user''s own Google Drive and Calendar safely.","Create a GitHub triage agent that labels issues, comments, and opens PRs."}', 'Sweet spot: a small team building an agent that needs to act across 5+ SaaS tools for end-users, and they do not want half their engineering time going into OAuth bugs. Composio is the right buy-vs-build call here — the OAuth plumbing is genuinely hard and they have solved it.

Failure modes. For single-user internal tools where you only need 1–2 integrations, Composio is overkill — write the OAuth once yourself. Vendor lock-in is real: if Composio''s pricing ever changes against you, re-implementing 50 integrations is a project. Test the specific tools you need before committing — integration depth varies.

What to pilot. Pick the three SaaS tools your agent needs most and wire them up through Composio. Time how long it takes. Then estimate how long the same integration would have taken to write yourself (including OAuth, refresh, error handling, and monitoring). If Composio saved you a week, the ongoing cost is easy to justify.', now()),
('Chat2DB', 'chat2db', 'AI-native SQL client that lets you query databases in natural language.', 'Chat2DB is a desktop and web SQL IDE with an LLM built into the query layer. Connect to Postgres, MySQL, SQL Server, SQLite, Oracle, Redis, MongoDB, Snowflake, BigQuery, or ClickHouse and ask questions in natural language — "top 10 customers by revenue last quarter" — and the model generates, explains, and executes the SQL against your schema.

Beyond natural-language querying, it includes the standard SQL IDE features (schema browser, query history, result export, ER diagrams) plus AI-specific ones: query optimisation suggestions, schema-aware autocomplete, data-anonymisation before sending schema to the LLM, and a visual dashboard builder. The desktop app is free and open-source; paid tiers add team sharing, audit logs, and an on-prem option.

Chat2DB positions itself against DBeaver (richer SQL IDE, no AI) and Hex / Mode (analytics-focused, cloud-only). Its niche is engineers and analysts who live in a SQL IDE every day and want the LLM as a coworker, not a replacement.', 'https://chat2db.ai', 'freemium', '[{"plan":"Community","price":"Free","features":["All database connections","AI SQL generation","Desktop app"]},{"plan":"Pro","price":"Subscription","features":["Team sharing","Audit logs","Advanced AI features"]},{"plan":"Enterprise","price":"Custom","features":["SSO","On-prem","SLA"]}]'::jsonb, 'beginner', false, '{"desktop","web"}', '{"Natural-language to SQL across 15+ databases","Schema-aware autocomplete","Query optimisation and explain","Visual ER diagram generator","Dashboard and chart builder","Data anonymisation before LLM calls","Multi-connection query editor","Team workspace sharing (paid)"}', '{"PostgreSQL","MySQL","SQL Server","Oracle","SQLite","Redis","MongoDB","Snowflake","BigQuery","ClickHouse","H2","DB2","OpenAI","Azure OpenAI"}', true, '{"Analysts and engineers who work across many databases","Teams wanting to give non-SQL users natural-language access to data","DBAs optimising slow queries"}', '{"Users already deeply invested in a cloud-only tool like Hex or Mode","Teams needing strict on-prem LLM (cloud tier uses hosted models)"}', 'A genuinely useful SQL IDE with AI — not a chatbot pretending to be one. The schema-aware NL-to-SQL is the feature that actually saves time.', '{"https://docs.chat2db.ai/"}', 'NL-to-SQL is only as accurate as your schema documentation — ambiguous column names produce ambiguous queries. Data anonymisation before LLM calls is a best-effort feature, not a guarantee — if your data residency rules are strict, use the on-prem tier. Dashboard features are lighter than purpose-built BI tools.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ask ''which users haven''t logged in for 30 days?'' and get executable SQL in five seconds.","Explain what a legacy 200-line SQL query does, in plain English.","Propose indexes and query rewrites for a slow production query.","Share a natural-language dashboard with a non-technical PM without writing the SQL yourself."}', 'Sweet spot: an engineer or analyst who already uses a SQL IDE every day and is tired of writing the same boilerplate JOIN a hundred times. Chat2DB slots in where DBeaver sits — you gain AI speedup, lose nothing you already had.

Failure modes. NL-to-SQL quality collapses on sprawling, poorly-named schemas — budget time to write clear table / column comments or you will fight the model. For SaaS teams with strict data-handling rules, sending even schema metadata to a hosted LLM may require the enterprise on-prem tier, which changes the cost conversation.

What to pilot. Point Chat2DB at a dev-replica of your real database. Ask the 20 questions your team actually asks weekly ("MAU by plan," "top refund reasons last month," etc). Measure how many answers are correct on first try. Above ~70% and it will save real time; below that and you need schema comments / semantic layer work first.', now()),
('Coze Studio', 'coze-studio', 'Open-source version of ByteDance Coze — a visual bot-building platform with agents, plugins, and workflows.', 'Coze Studio is the open-source release of Coze, ByteDance''s visual chatbot platform. It provides a drag-and-drop canvas for building conversational agents: nodes for LLM calls, tool use, knowledge-base retrieval, branching logic, user-input collection, and multi-turn memory. You design the flow visually, publish it as a web chatbot, Feishu bot, Discord bot, or API endpoint.

The platform bundles an agent runtime, a plugin system (pre-built tools plus custom HTTP plugins), a knowledge-base module (upload documents, chunked and embedded automatically), a prompt-management system, and analytics. Everything runs on your infrastructure — no data leaves your servers.

For teams that liked the hosted Coze experience but needed on-prem, or for anyone who wants a visual, full-featured bot builder without paying Dify''s cloud tier or writing Rasa config files, Coze Studio is one of the strongest open-source entrants in late 2025.', 'https://github.com/coze-dev/coze-studio', 'free', '[{"plan":"Open Source","price":"Free","features":["Full platform","Self-hosted","All features"]}]'::jsonb, 'intermediate', true, '{"web","api"}', '{"Visual drag-and-drop bot builder","Multi-turn memory and session state","Plugin system (built-in + custom HTTP)","Knowledge-base with RAG","Prompt management and versioning","Multi-channel publishing (web, Feishu, Discord, API)","Agent workflow branching and tool use","Multi-user workspaces","Self-hosted deployment via Docker"}', '{"OpenAI","Anthropic","Doubao (ByteDance)","DeepSeek","Feishu","Discord","Slack"}', true, '{"Teams wanting a visual bot builder they can self-host","Enterprises that need on-prem chatbot infra","Product teams prototyping conversational flows without code"}', '{"Solo developers needing a lightweight SDK (overkill)","Teams happy with a hosted platform (pick Coze cloud or Dify)"}', 'The most feature-complete open-source visual bot platform released in 2025. Pick it if you need Coze-quality UI with on-prem control.', '{"https://github.com/coze-dev/coze-studio"}', 'Documentation is still partly in Chinese — English support has improved but lags the Chinese docs. Enterprise features (SSO, audit logs, fine-grained RBAC) are lighter than the hosted Coze platform. Self-hosting requires managing your own vector DB, database, and LLM keys.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a customer-support chatbot that references your product docs, deployed on your infra.","Prototype a multi-step conversational workflow (e.g., onboarding, appointment booking) visually.","Deploy an internal HR assistant without sending employee data to a cloud vendor.","Ship a Discord community bot that answers questions from a knowledge base."}', 'Sweet spot: a team that wants the Coze / Dify visual-builder experience but for compliance, latency, or cost reasons needs to run it themselves. Coze Studio delivers that — you trade setup work for control.

Failure modes. Self-hosting has real operating cost: keeping a vector DB, message queue, and the app itself healthy is work. If you do not have a platform team, the hosted alternatives (Coze cloud, Dify Cloud) may be cheaper in practice. Long-tail bot logic sometimes still needs custom code — the visual builder handles 80% of flows but complex branching or state machines will make you wish for a proper programming language.

What to pilot. Spin it up on a single server, build one production-realistic bot end-to-end (including tool use, knowledge base, and channel publishing). Track engineering hours. If it hits your quality bar in under a week of one engineer''s time, it is the right pick; if the bot builder fights you on complex logic, drop down to a code-first framework like LangGraph.', now()),
('Google Agent Development Kit', 'google-adk', 'Google''s open-source Python framework for building, evaluating, and deploying AI agents.', 'The Agent Development Kit (ADK) is Google''s open-source framework for building agent-based applications. It ships Python abstractions for agents, tools, multi-agent orchestration, session state, evaluation, and deployment — intended to be the Google-blessed way to build something Gemini-native, though it is model-agnostic in practice.

Architecturally, ADK is close to LangGraph and AutoGen: you define agents with tools, compose them into pipelines or sequential / parallel / loop flows, and the framework handles the tool-use loop, state, and streaming. Where it differentiates: first-class Gemini support, tight integration with Vertex AI for deployment, a built-in evaluation harness, and a dev UI (adk web) for inspecting agent runs locally.

Released in April 2025 and rapidly gaining traction — it is the framework Google points developers to for agent work on Gemini and Vertex. For teams already on Google Cloud, ADK is the least-friction path to production agents.', 'https://google.github.io/adk-docs/', 'free', '[{"plan":"Open Source","price":"Free","features":["Full framework","Local dev UI","Evaluation harness"]}]'::jsonb, 'intermediate', false, '{"api","cli"}', '{"Agent and tool abstractions (Python)","Multi-agent orchestration (sequential, parallel, loop)","Built-in evaluation harness","Local dev UI (adk web) for run inspection","Gemini-native with function calling","Model-agnostic (LiteLLM adapter)","Session and state management","Vertex AI Agent Engine deployment","Streaming responses"}', '{"Gemini","Vertex AI","OpenAI","Anthropic","LiteLLM","Cloud Run","GCS"}', true, '{"Developers on Google Cloud building production agents","Teams standardising on Gemini as their primary model","Engineers who want Google-maintained tooling over community frameworks"}', '{"Non-developers","Teams committed to other clouds where Vertex integration is irrelevant"}', 'The right agent framework if you are already on Google Cloud or Gemini. Outside that ecosystem, LangGraph and AutoGen are equally capable with larger communities.', '{"https://google.github.io/adk-docs/get-started/quickstart/"}', 'Newer than LangGraph / AutoGen — smaller community, fewer third-party examples, and the API surface is still shifting between minor versions. Gemini-first means some patterns are idiomatic for Gemini tool calling but need adapters for OpenAI / Anthropic. Vertex deployment is easy only if you are already on GCP.', '{"gemini-2.5-pro","gemini-2.5-flash"}', '{"reddit_threads":[]}'::jsonb, '{"Build a multi-agent pipeline on Gemini and deploy to Vertex AI in one workflow.","Prototype a planner / executor / critic agent team locally, then ship without framework changes.","Evaluate agent versions against a fixed test set using the built-in harness.","Wire Google-native tools (Drive, Calendar, Search) into an agent with minimal glue code."}', 'Sweet spot: a team on Google Cloud, using Gemini, who wants one framework that runs identically from laptop to Vertex. ADK removes the "which agent library should we bet on?" question if you already live in Google''s ecosystem — the answer is ADK.

Failure modes. Outside GCP / Gemini, ADK offers no real advantage over LangGraph, and picks up the cost of a thinner community. API churn is real — the 0.x release cadence means pinning versions and budgeting time for small migrations. Multi-agent patterns can be expressed, but the documentation leans heavily on Gemini examples; translating to Anthropic requires reading the LiteLLM adapter layer.

What to pilot. Build one agent that uses two tools, evaluate it with the built-in harness, and deploy to Vertex. If that full loop (dev → eval → deploy) takes less than a day, ADK has delivered on its pitch; if any step fights you, LangGraph''s mature ecosystem may be a better fit even at the cost of a little more deployment code.', now()),
('Context7', 'context7', 'MCP server that feeds up-to-date, version-pinned library documentation into your AI coding assistant.', 'Context7 is a Model Context Protocol (MCP) server from Upstash that solves a specific, painful problem: AI coding assistants hallucinate APIs because their training data is months out of date. When you ask Claude, Cursor, Windsurf, or VS Code Copilot about a library, you often get code that references deprecated methods or APIs that never existed in that version.

Context7 maintains a searchable, version-aware index of current documentation for thousands of libraries (React, Next.js, Prisma, FastAPI, Supabase, etc). Via the MCP protocol, the assistant can fetch the exact current docs for the version you specify and ground its answer in them. No stale API hallucinations, no fighting deprecations from last year.

It ships as a free hosted MCP endpoint for individual developers and an npm package for CLI use. The core is open-source; Upstash hosts the index and keeps it fresh. Added to Cursor / Claude Code / Windsurf by pointing the MCP client at context7.com — a one-line config change.', 'https://context7.com', 'free', '[{"plan":"Free","price":"Free","features":["Hosted MCP endpoint","All libraries","Version-pinned docs"]}]'::jsonb, 'beginner', true, '{"api","plugin","cli"}', '{"MCP-native protocol","Version-pinned documentation lookup","Thousands of libraries indexed","Hosted endpoint (no self-hosting needed)","Drop-in config for Cursor, Windsurf, Claude Code, VS Code Copilot","Fresh index updated continuously","Open-source core","Works with any MCP-compatible AI client"}', '{"Claude Code","Cursor","Windsurf","VS Code","Cline","Zed","Any MCP client"}', true, '{"Developers using AI coding assistants daily","Teams tired of hallucinated APIs","Anyone working with libraries that move fast (Next.js, AI SDK, Supabase)"}', '{"Teams not using MCP-compatible assistants","Users working with obscure internal libraries (Context7 indexes public docs)"}', 'Install-this-today utility for anyone using Claude Code, Cursor, or Windsurf. Eliminates a huge chunk of AI hallucinations in coding tasks. Free and takes one minute to set up.', '{"https://context7.com/"}', 'Only indexes public documentation — internal / private libraries need a separate MCP solution. Relies on your AI client supporting MCP; older ChatGPT / Gemini wrappers without MCP cannot use it. Index coverage is strong for top libraries but thinner for niche ones.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Get accurate Next.js 15 App Router syntax from Cursor instead of the model guessing from pre-14 patterns.","Ask Claude Code about a specific Prisma version and have it reference the right migration APIs.","Stop having to paste docs into the chat manually when working with fast-moving libraries.","Keep a team''s AI assistants grounded in the exact versions of libraries your codebase uses."}', 'Sweet spot: any developer using an MCP-capable AI coding assistant in 2026. The cost-to-install is sub-five-minutes and the upside (fewer wrong-API moments per day) is immediate. This is the kind of small tool that quietly changes your daily experience.

Failure modes. If you are building against an internal library, a private API, or a pre-release version not in the index, Context7 cannot help you — you still need to paste docs into the chat. The assistant also needs to actually use the MCP tool; if your system prompt does not encourage that, the model may still guess.

What to pilot. Install it in Cursor or Claude Code, then ask three questions about a library that has had a major version bump in the last six months (e.g., Tailwind 4, Next 15). Compare answers with and without Context7. The difference is usually obvious within five prompts.', now()),
('BitNet', 'bitnet', 'Microsoft''s official inference framework for 1-bit large language models.', 'BitNet is Microsoft''s reference implementation for running 1-bit quantised LLMs on CPU — specifically the 1.58-bit variant where weights are constrained to {-1, 0, +1}. The project ships a C++ inference runtime (based on llama.cpp) plus pretrained BitNet b1.58 models that demonstrate the approach works at usable quality for chat and completion tasks.

The payoff is efficiency: a 1-bit model''s matrix-multiply becomes integer addition and subtraction, which runs far faster per watt than standard float inference. BitNet b1.58 models at 3B parameters run comfortably on a modern laptop CPU, opening a path to local AI that does not require a GPU. Microsoft''s benchmarks show 4x–6x speedups versus comparable quantised models in the same size class, with modest quality tradeoff.

It is a research artifact as much as a product — the paper "The Era of 1-bit LLMs" (Microsoft Research, 2024) is the canonical reference. The code is open-source (MIT), the weights are on HuggingFace, and the community has begun producing fine-tunes and larger variants.', 'https://github.com/microsoft/BitNet', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Inference runtime","Pretrained weights","Benchmarks"]}]'::jsonb, 'advanced', false, '{"cli"}', '{"1.58-bit weight quantisation ({-1, 0, +1})","C++ inference runtime (llama.cpp-based)","CPU-optimised matrix kernels","Pretrained BitNet b1.58 weights","4x–6x speedup vs comparable quantised baselines","HuggingFace integration","Open-source MIT licence"}', '{"llama.cpp","HuggingFace","PyTorch"}', true, '{"Researchers exploring low-bit quantisation","Developers building laptop-local AI apps","Teams evaluating energy-efficient LLM inference"}', '{"Product use cases needing SOTA quality (larger models still win)","GPU-first deployments (BitNet''s advantage is CPU)","Non-researchers looking for a ready-to-use chat product"}', 'The most important 1-bit LLM project in 2026 and a must-watch if you care about local, CPU-efficient AI. Not yet a product replacement — but the trajectory is real.', '{"https://github.com/microsoft/BitNet"}', 'Model quality at 3B parameters trails larger full-precision models — usable but not GPT-4 class. Only a few pretrained sizes released so far; larger BitNet models are research-stage, not shipped. Requires building from source (C++ toolchain). Fine-tuning tooling for BitNet is less mature than for standard LLMs.', '{"bitnet-b1.58-3b","bitnet-b1.58-large"}', '{"reddit_threads":[]}'::jsonb, '{"Run a local chat assistant on a mid-range laptop without a GPU.","Research how 1-bit quantisation affects instruction-following quality on benchmarks.","Prototype an energy-constrained edge-AI application (mobile, embedded).","Compare 1-bit inference throughput to 4-bit / 8-bit baselines on the same hardware."}', 'Sweet spot: a researcher or infrastructure-minded engineer interested in the energy / latency frontier of LLM inference. BitNet is one of the most credible directions for "can we make this work on a CPU fast enough to matter?" — and Microsoft putting the reference implementation out there moves the whole field forward.

Failure modes. Treating BitNet as a drop-in replacement for GPT-4 will disappoint — the current pretrained sizes cannot match frontier model quality. The inference wins are real, but you need to validate on your specific task, not trust paper-reported benchmarks. C++ toolchain friction is real for Python-only teams.

What to pilot. Clone the repo, build it, run the included chat demo on your laptop. Measure tokens/sec and memory footprint against a 4-bit GGUF model of a similar size. If the throughput and quality fit your use case, it is a promising direction; if not, watch the project — larger BitNet models are coming and the quality gap is narrowing quickly.', now()),
('DB-GPT', 'db-gpt', 'Open-source data AI framework — natural-language analytics, SQL generation, and database agents.', 'DB-GPT is an open-source framework for building AI applications on top of structured data. It bundles a natural-language-to-SQL engine, a multi-agent data-analysis pipeline (one agent plans, one writes SQL, one validates), a knowledge-base layer for unstructured context, and a visual web UI for non-technical users to query databases conversationally.

The project ships connectors for 20+ databases (MySQL, Postgres, SQLite, ClickHouse, DuckDB, Spark, Doris, TDengine, and more), supports local and hosted LLMs (ChatGLM, Baichuan, Qwen, OpenAI, Anthropic), and runs fully on-prem — a stated design goal is to never require sending schema or data to external services. A Python SDK plus a Docker-deployable web app cover both integrator and end-user paths.

DB-GPT is one of the most actively developed data-AI projects out of China (eosphoros-ai), with strong support for Chinese databases and LLMs. For teams that need on-prem NL-to-SQL plus agent-style data workflows, it is a more complete package than gluing LangChain + a SQL agent together manually.', 'http://docs.dbgpt.cn', 'free', '[{"plan":"Open Source","price":"Free","features":["Full framework","Web UI","All connectors"]}]'::jsonb, 'intermediate', true, '{"web","api","cli"}', '{"Natural-language to SQL across 20+ databases","Multi-agent data analysis pipeline","Knowledge base for unstructured context","Visual web UI for non-technical users","Local + hosted LLM support","Chart and dashboard generation","Python SDK","Docker deployment","On-prem data residency"}', '{"MySQL","PostgreSQL","SQLite","ClickHouse","DuckDB","Spark","Doris","OpenAI","Anthropic","ChatGLM","Qwen","Baichuan"}', true, '{"Enterprises needing on-prem NL-to-SQL","Data teams in China using domestic LLMs and databases","Developers building custom data-analytics agents"}', '{"Small teams who need a hosted SaaS (this is a self-hosted framework)","Users who want zero setup (run Chat2DB or Hex instead)"}', 'The most complete open-source data-AI framework in 2026, especially for on-prem or China-centric stacks. Non-trivial to deploy; large ROI once running.', '{"http://docs.dbgpt.cn/docs/overview/"}', 'Documentation and community are bilingual (Chinese / English) — English docs have improved but trail Chinese ones. Self-hosting demands real DevOps work (vector DB, app server, LLM runtime). NL-to-SQL accuracy varies by schema quality; expect prompt-engineering work for complex datasets.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Give a domain team natural-language access to a production MySQL database without writing a BI tool from scratch.","Build a data-analysis agent pipeline that plans, writes SQL, and validates results autonomously.","Deploy an on-prem AI data assistant for a regulated industry (finance, healthcare, government).","Integrate a custom Chinese LLM (Qwen, ChatGLM) as the backbone of an internal data Q&A tool."}', 'Sweet spot: a data engineering team at an organisation where the data cannot leave the building, and the team has the platform skills to run a self-hosted stack. DB-GPT gives you far more than a wrapper around LangChain — the multi-agent analysis pattern is a real productivity gain once dialled in.

Failure modes. Small teams under-estimate the operational cost of self-hosting this. If you do not already run a vector DB and have someone who can debug a Python agent runtime, the simpler choice is a hosted tool like Chat2DB or Hex. Feature breadth also means feature churn — pin versions and budget for quarterly upgrades.

What to pilot. Deploy it on a dev database, wire in one LLM (OpenAI or a local model), and run five real analytical questions. Measure accuracy. If three or more are correct on first try, the framework is earning its keep; if not, invest in schema documentation and prompt tuning before rolling out further.', now()),
('ChatDev', 'chatdev', 'Multi-agent virtual software company — a team of LLM agents collaborates to build apps from a prompt.', 'ChatDev is an open-source research project from OpenBMB and Tsinghua that simulates a virtual software company staffed entirely by LLM agents. You give it a product idea ("build a snake game with a scoreboard") and ChatDev spins up a CEO, a CTO, designer, coder, tester, and documentation writer — each with its own system prompt. The agents hold structured meetings, pass artifacts between roles, and produce a working codebase plus docs at the end.

The project is most interesting as a research testbed for multi-agent coordination patterns: the authors published the paper that introduced the "communicative agents for software development" pattern that has since influenced AutoGen, MetaGPT, and several academic lines. It is not positioned as a production tool — you would not replace your engineering team with it — but it is a remarkably clean reference implementation of how agents-that-talk-to-agents can build non-trivial deliverables end-to-end.

ChatDev is Python, MIT-licensed, runs on OpenAI-compatible APIs (including local models via Ollama), and ships a GUI that shows the agents'' conversations live. The output is real code in a folder, not just chat logs.', 'https://github.com/OpenBMB/ChatDev', 'free', '[{"plan":"Open Source","price":"Free (Apache-2.0)","features":["Full framework","Visual GUI","All agent roles"]}]'::jsonb, 'intermediate', false, '{"cli","desktop"}', '{"Multi-agent software-development pipeline","Role-based agents (CEO, CTO, coder, tester, writer)","Structured inter-agent meetings","Code + documentation output","Visual GUI for conversation inspection","OpenAI-compatible LLM backend","Open-source research implementation"}', '{"OpenAI","Azure OpenAI","Ollama"}', true, '{"Researchers studying multi-agent collaboration","Educators teaching agent-based software design","Developers exploring LLM-as-team patterns"}', '{"Teams expecting production-quality code from a single prompt","Projects larger than simple standalone apps","Non-developers"}', 'The definitive research reference for "agents building software as a team." Fascinating to run; do not bet your startup on the output code.', '{"https://github.com/OpenBMB/ChatDev"}', 'Output code is demo-quality — simple apps work, anything non-trivial breaks at integration / testing time. Each run spends significant tokens across multiple agent conversations — a single build can cost several dollars on GPT-4-class models. No test-harness beyond the agent-generated tests, which can be wrong. Not maintained at the cadence of production frameworks.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Reproduce results from the \"communicative agents for software development\" paper.","Teach a class on multi-agent LLM systems using a hands-on reference implementation.","Prototype a simple standalone app (snake game, to-do CLI, calculator) and inspect how agents divide work.","Explore multi-agent coordination patterns before implementing your own."}', 'Sweet spot: a researcher, educator, or developer who wants to understand the "agents collaborating as a team" pattern by watching it run — not by reading about it. ChatDev''s GUI makes the dynamics visible in a way reading AutoGen logs doesn''t.

Failure modes. Treating ChatDev as a product shortcut fails — the generated code for anything non-trivial needs human rewriting. Cost per run surprises first-time users: each role swap is additional LLM calls and the conversations are long. Bigger-picture, the project is closer to a demonstration than a continuously-evolving production framework — use it to learn the ideas, then implement with AutoGen / LangGraph if you want the pattern in production.

What to pilot. Run one full build (e.g., "a simple 2048 game in HTML") with a GPT-4-class model, watch the agent conversations, and read the generated code. You will walk away with a concrete understanding of what multi-agent systems can and cannot do today — which is worth the ~$2 in API spend.', now()),
('AgentScope', 'agentscope', 'Alibaba open-source Python framework for building robust, distributed multi-agent LLM applications.', 'AgentScope is Alibaba''s open-source framework for multi-agent systems, positioned as a production-oriented alternative to research-first frameworks. It emphasises three properties: reliability (built-in retries, exception handling, fault-isolation), developer experience (clean Python API, a visual "AgentScope Studio" for inspection and debugging), and scalability (distributed execution across machines via RPC).

The core abstractions are agents with tools, pipelines for composition, and a message-passing runtime. Beyond the basics, AgentScope ships a monitor dashboard for live agent runs, a visual workflow builder, support for local / hosted / distributed execution, and native integrations with Alibaba''s DashScope and Qwen models — plus OpenAI, Anthropic, and Ollama.

For teams that want a multi-agent framework engineered for production rather than for academic papers, AgentScope is one of the more pragmatic choices available in 2026. The documentation is bilingual (English / Chinese) and the community contributes example agents weekly.', 'https://doc.agentscope.io/', 'free', '[{"plan":"Open Source","price":"Free (Apache-2.0)","features":["Framework","AgentScope Studio","Distributed runtime"]}]'::jsonb, 'intermediate', false, '{"api","cli","desktop"}', '{"Agent and pipeline abstractions","Built-in retries and fault tolerance","AgentScope Studio (visual inspector)","Distributed multi-agent execution (RPC)","Live monitoring dashboard","Visual workflow builder","Model-agnostic (Qwen, OpenAI, Anthropic, Ollama)","Message-passing runtime","Python-first API"}', '{"Qwen","DashScope","OpenAI","Anthropic","Ollama","Gemini"}', true, '{"Engineering teams building production multi-agent systems","Projects needing distributed agent execution","Teams on Alibaba Cloud or using Qwen"}', '{"Non-developers","Projects better served by a single-agent-with-tools pattern","Teams committed to a specific competing framework (LangGraph, AutoGen)"}', 'One of the better production-minded multi-agent frameworks in 2026, with an unusually strong distributed-execution story. Worth evaluating alongside LangGraph and AutoGen.', '{"https://doc.agentscope.io/tutorial/quickstart.html"}', 'Community is smaller than LangGraph / AutoGen, which means fewer third-party examples. Documentation is improving but you will still hit bilingual docs on advanced topics. Distributed execution is a real differentiator but requires RPC / networking setup that single-process frameworks skip.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a multi-agent content pipeline where agents run on separate workers to parallelise long tasks.","Ship a production agent system with built-in retries for flaky tool calls.","Prototype a visual agent workflow, then scale the same code to distributed execution without rewriting.","Use Qwen models natively inside a multi-agent framework without adapter glue."}', 'Sweet spot: a team that needs real multi-agent production features (retries, monitoring, distributed runs) and is willing to commit to a slightly less-adopted framework for those gains. If you are on Alibaba Cloud or primarily use Qwen, AgentScope is an easier bet than LangGraph.

Failure modes. Community size matters when you hit a bug — LangGraph issues get answered faster than AgentScope issues, simply because more people use LangGraph. Distributed execution is a double-edged sword: powerful when you need it, extra operational surface when you don''t. If your workloads fit on one machine, the distributed features are complexity you pay for without benefit.

What to pilot. Build a two-agent pipeline with one flaky external tool. Kill that tool mid-run. AgentScope''s retry and fault-isolation behaviour should be observable — if it recovers cleanly and you can see the failure in Studio, the framework is earning its place; if not, a lighter-weight framework with custom retry logic may be simpler.', now()),
('Chrome DevTools MCP', 'chrome-devtools-mcp', 'Official Chrome DevTools MCP server — let AI coding agents inspect, debug, and profile real Chrome tabs.', 'Chrome DevTools MCP is an official Google project that exposes the Chrome DevTools Protocol through the Model Context Protocol (MCP). When installed as an MCP server in Claude Code, Cursor, Windsurf, or VS Code Copilot, it gives the AI coding agent the ability to actually operate the browser: navigate to URLs, inspect DOM, read network requests, capture screenshots, profile performance, evaluate JavaScript in the page context, and examine console logs.

The practical upshot is that an agent debugging a web app no longer has to guess — it can open the page, reproduce the bug, read the actual error, and propose a fix grounded in what actually happened. For front-end work specifically, this collapses a huge loop that otherwise required copy-pasting console errors between DevTools and the chat.

It is free, MIT-licensed, and installed with one npm command plus an MCP config entry. Works with any Chromium-based browser and any MCP-compatible AI client.', 'https://github.com/ChromeDevTools/chrome-devtools-mcp', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full MCP server","All DevTools protocol features","No cloud dependency"]}]'::jsonb, 'intermediate', false, '{"cli","plugin"}', '{"Official Google-maintained MCP server","Navigate, reload, and interact with Chrome tabs","DOM inspection and query","Network request inspection","Console log reading","JavaScript evaluation in page context","Performance profiling","Screenshot and snapshot capture","Works with Claude Code, Cursor, Windsurf, VS Code Copilot"}', '{"Claude Code","Cursor","Windsurf","VS Code","Cline","Any MCP client"}', true, '{"Front-end developers using AI coding assistants","Teams debugging web-app issues with LLMs","QA engineers who want AI help reproducing bugs"}', '{"Non-web development (backend-only work)","AI clients without MCP support","Users already on browser-use (overlapping use cases)"}', 'Install-this-today utility for front-end developers using any MCP-capable AI assistant. Eliminates the "what did the browser actually do?" guessing game.', '{"https://github.com/ChromeDevTools/chrome-devtools-mcp"}', 'Requires a local Chrome instance — headless mode works but some protocol features need a windowed browser. Interacting with sites behind login requires an existing Chrome profile. Rate-limited by the local protocol connection; not suitable for high-concurrency scraping. Different scope than browser-use — this is for AI-assisted debugging, not autonomous agents.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Debug a React hydration error by having your AI read the actual console output from your app.","Reproduce a production bug live in the browser and get a fix proposal grounded in the network trace.","Profile a slow page and have the AI correlate flamegraph data to specific component renders.","Let the AI verify a CSS fix by taking before / after screenshots."}', 'Sweet spot: a front-end developer already using Claude Code, Cursor, or Windsurf who keeps finding themselves copying console errors back and forth. Chrome DevTools MCP closes that loop — the AI gets first-class access to the same information you have in your own DevTools, which usually shortens debugging sessions dramatically.

Failure modes. It is not a replacement for browser-use — that tool is for building autonomous agents that go do things on the web, while Chrome DevTools MCP is for letting an AI debug the thing you are building. Mixing the two roles leads to confusion. Also, if your AI assistant does not actively use MCP tools when it should, the install is wasted — set system prompts or agent instructions that bias toward using it.

What to pilot. Install it in your editor, break one piece of your app on purpose (e.g., a runtime error), and ask the AI to find and fix the issue. Watch the tool calls. If the AI reaches for DevTools MCP to inspect the error and then proposes a targeted fix, you are getting the win; if it still guesses based on the code alone, the system prompt or model needs a nudge.', now()),
('Crush', 'crush', 'Charmbracelet''s terminal-native AI coding assistant — multi-model, session-aware, and beautifully TUI.', 'Crush is a terminal-first AI coding assistant from Charmbracelet, the team behind the widely-loved Go TUI libraries (Bubble Tea, Lip Gloss, Glow). Unlike editor-embedded copilots (Cursor, Windsurf, Claude Code), Crush is a standalone CLI / TUI you launch in a repo — it reads your files, keeps conversation context, supports multiple LLM providers, and streams responses with Charmbracelet''s signature polish.

Key design choices: provider-agnostic (OpenAI, Anthropic, Gemini, Ollama, any OpenAI-compatible endpoint), model-switchable mid-session, full session history stored locally, shell-command execution with approval gates, and a genuinely nice TUI experience — keyboard navigation, syntax highlighting, and live streaming. MCP server support lets you extend it with external tools.

It is open-source (FSL/Apache), installed via a single Go binary, and runs on any platform Go builds for. For developers who live in the terminal and do not want another Electron app, Crush is the most polished TUI coding assistant to ship in 2025.', 'https://github.com/charmbracelet/crush', 'free', '[{"plan":"Open Source","price":"Free","features":["Full TUI","All providers","MCP support","Session history"]}]'::jsonb, 'intermediate', false, '{"cli","desktop"}', '{"Terminal-native TUI (Bubble Tea-powered)","Provider-agnostic (OpenAI, Anthropic, Gemini, Ollama)","Mid-session model switching","Local session history","Shell-command execution with approval gates","MCP server support","Syntax highlighting and streaming","Single-binary install (Go)","Cross-platform"}', '{"OpenAI","Anthropic","Gemini","Ollama","OpenRouter","Azure OpenAI","Any MCP server"}', true, '{"Terminal-first developers","Users on remote dev servers via SSH","Anyone wanting a standalone AI assistant outside their editor","Charmbracelet fans"}', '{"Developers preferring IDE-integrated copilots","Users who want rich UI for diff review (TUI has limits)"}', 'The most polished TUI AI coding assistant in 2026. If you live in tmux or SSH a lot, Crush is the default pick.', '{"https://github.com/charmbracelet/crush"}', 'TUI has inherent UI limits — reviewing a 500-line diff or a visual design spec is awkward compared to an IDE. Younger project than Aider or Claude Code — expect rough edges on the long tail of commands. Shell execution requires careful approval-gate setup for safety.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Run an AI coding assistant over SSH on a remote dev server where no IDE is installed.","Use a terminal-native coding assistant with any model provider without vendor lock-in.","Work inside tmux panes alongside your editor and shell, without leaving the terminal.","Swap between GPT-4o, Claude Sonnet, and a local Llama model in the same coding session."}', 'Sweet spot: a developer who works heavily over SSH, lives inside tmux, or simply prefers TUIs over Electron apps. Crush matches Aider on provider-agnostic philosophy but wins on TUI polish — Charmbracelet ships beautiful terminal software as a matter of course.

Failure modes. For contexts where a visual diff matters (large refactors, design-heavy UI work), the TUI is a step down from a real IDE. For users already deep in Cursor or Claude Code, switching to Crush is a preference call, not a capability upgrade. Model-switching cost adds up — each new provider needs an API key and config entry.

What to pilot. Install Crush on a remote dev server you SSH into regularly. Use it for one real task end-to-end (a bug fix, a feature). Compare the experience to what you would have done with just your editor + shell + manual copy-paste to Claude. If the TUI keeps you in flow better, it has earned its place in the workflow.', now()),
('Agno', 'agno', 'Python framework for building high-performance, model-agnostic AI agents and multi-agent systems.', 'Agno (formerly Phidata) is an open-source Python framework for building agents that combines a clean API, serious focus on performance, and first-class support for multi-model and multi-modal workflows. Agents are defined with a few lines of Python — give them a model, tools, memory, and a knowledge base — and Agno handles the tool-use loop, streaming, and state.

Where Agno differentiates: published benchmarks showing multi-thousand-x faster agent instantiation than LangChain equivalents, a unified reasoning primitive (think before answer), multi-modal inputs (image, audio, video) as a first-class concept, and native support for agent teams with leader-follower patterns. The framework ships adapters for OpenAI, Anthropic, Gemini, Groq, Cohere, Ollama, xAI, and essentially every major API provider.

Beyond the library, Agno offers a free agent UI (FastAPI + Next.js template) and a paid hosted platform for deployment, monitoring, and team workflows. It has a growing footprint in production agent stacks, particularly for teams that tried LangChain, hit its performance ceiling, and wanted something lighter.', 'https://docs.agno.com', 'freemium', '[{"plan":"Open Source","price":"Free","features":["Full framework","All integrations","Self-hosted"]},{"plan":"Agno Cloud","price":"Usage-based","features":["Hosted deployment","Observability","Team workspaces"]}]'::jsonb, 'intermediate', true, '{"api","cli"}', '{"High-performance Python agent framework","Multi-model adapters (20+ providers)","Multi-modal inputs (image, audio, video)","Built-in reasoning primitive","Agent teams (leader-follower)","Knowledge bases and RAG","Memory and session state","FastAPI + Next.js agent UI template","Hosted platform for deployment (paid)"}', '{"OpenAI","Anthropic","Gemini","Groq","Cohere","Ollama","xAI","DeepSeek","Pinecone","LanceDB","Qdrant","PostgreSQL"}', true, '{"Developers who need an agent framework with strong performance","Teams building multi-modal agents","Engineers who found LangChain too heavy"}', '{"Non-Python teams","Teams already committed to LangGraph or AutoGen (switching cost)","Non-developers"}', 'One of the fastest and cleanest agent frameworks in 2026. Strong challenger to LangChain for teams building new agent systems from scratch.', '{"https://docs.agno.com/introduction"}', 'Smaller community than LangChain — fewer third-party examples and integrations to pick from. Renamed from Phidata in 2024, so some search results point to stale docs. Hosted platform is newer and less proven than self-hosted usage patterns.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a multi-modal agent that processes images and text as inputs with a single model call.","Ship a production agent where instantiation latency matters (high-concurrency workloads).","Prototype a multi-agent team with a leader that coordinates specialised followers.","Migrate a LangChain agent that has hit performance bottlenecks to a lighter framework."}', 'Sweet spot: a Python team starting a fresh agent project and wanting something cleaner and faster than LangChain. Agno''s API is tight, the docs are good, and the performance benchmarks (while self-published) hold up reasonably well in practice.

Failure modes. The community-size gap is real — when you hit an edge case, you will find fewer Stack Overflow threads and blog posts than the LangChain equivalent. Migrating existing LangChain code is not a trivial lift; treat Agno as a choice for new projects, not a drop-in replacement. Multi-modal support is strong but still depends on whichever model you choose actually supporting the modality.

What to pilot. Build a small production-realistic agent (5-ish tools, knowledge base, streaming UI) in Agno and a matched version in LangChain. Measure cold-start latency, tokens per run, and lines of code. If Agno wins on at least two of the three for your workload, it is the right bet going forward; if the metrics are close, stick with whatever your team already knows.', now()),
('Vercel AI SDK', 'vercel-ai-sdk', 'Open-source TypeScript toolkit for building AI-powered apps — provider-agnostic, streaming-first.', 'The Vercel AI SDK (often just "AI SDK") is the TypeScript toolkit that has become the de facto standard for building AI features in web apps. It provides a unified provider interface (OpenAI, Anthropic, Gemini, Groq, Mistral, xAI, OpenAI-compatible endpoints, even local models), a streaming UI primitive that handles chunk-based rendering in React / Vue / Svelte, tool calling with type-safe schemas, structured output via Zod, and agent primitives.

Version 6 (2025) added generative UI (models can emit typed component calls), image and audio generation primitives, Model Context Protocol (MCP) support, durable streams across serverless restarts, and the Vercel AI Gateway — a unified endpoint that proxies requests to any provider with failover and observability. For Next.js / SvelteKit / Nuxt apps, it is effectively the only thing you need to ship AI.

Open-source (Apache 2.0), free to use, and the hosted AI Gateway is an optional paid add-on. It is maintained by Vercel and used in thousands of production web apps — including this one. Documentation is excellent, examples are abundant, and the release cadence is fast.', 'https://ai-sdk.dev', 'freemium', '[{"plan":"Open Source","price":"Free","features":["Full SDK","All provider adapters","React / Vue / Svelte hooks"]},{"plan":"AI Gateway","price":"Usage-based","features":["Unified multi-provider endpoint","Observability","Failover","Zero data retention"]}]'::jsonb, 'intermediate', true, '{"api"}', '{"Provider-agnostic TypeScript SDK","Streaming-first primitives for React / Vue / Svelte","Type-safe tool calling with Zod schemas","Structured output via Zod","Generative UI (typed component calls)","Image and audio generation primitives","MCP (Model Context Protocol) support","Durable streams across serverless restarts","AI Gateway for unified multi-provider routing"}', '{"OpenAI","Anthropic","Gemini","Groq","Mistral","xAI","Cohere","Ollama","Perplexity","OpenAI-compatible endpoints","Next.js","SvelteKit","Nuxt"}', true, '{"Next.js and SvelteKit developers building AI features","Teams shipping chat / streaming UI","Anyone who wants one SDK across many model providers"}', '{"Python-only stacks","Teams needing a full agent framework (pick LangGraph, Agno, AutoGen)","Applications with no UI (server-only agent pipelines)"}', 'The default TypeScript AI SDK in 2026. If you are shipping AI in a JavaScript / TypeScript web app, there is no real alternative with this breadth and quality.', '{"https://ai-sdk.dev/docs/introduction"}', 'TypeScript only — no Python equivalent. Agent primitives are lighter than in dedicated frameworks (LangGraph, Agno); use AI SDK for the provider / streaming layer, bring a framework for complex agent flows. AI Gateway is a separate paid product with its own billing.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ship a production chat UI in a Next.js app with streaming, tool calls, and failover in under a day.","Generate a typed React component from an LLM call using generative UI.","Swap from OpenAI to Anthropic in a production app by changing one import.","Add structured output to an existing form using Zod schemas and the AI SDK object primitive."}', 'Sweet spot: any TypeScript developer building an AI feature inside a web app. The AI SDK has no serious competitor in the JS / TS ecosystem — it is provider-agnostic, it handles streaming correctly, its documentation is one of the best in the space, and version 6 has closed the gap on agent-style workflows.

Failure modes. It is not a full agent framework. If you need multi-agent orchestration, long-running durable workflows, or complex tool-calling state machines, pair AI SDK with LangGraph or Agno rather than bending AI SDK into that shape. Python teams should look at LlamaIndex / LangChain — the AI SDK is fundamentally a TypeScript project.

What to pilot. Pick one small AI feature on a product surface (a summarisation button, a chat sidebar, a smart search) and implement it with AI SDK plus the AI Gateway in a day. If the combination gives you streaming + failover + observability in less code than your current approach, you have your answer; if the gateway adds unwanted billing complexity, use AI SDK directly and skip the gateway.', now())
ON CONFLICT (slug) DO NOTHING;

-- Category assignments
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'browser-use' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'browser-use' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'crawl4ai' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'crawl4ai' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'anything-llm' AND c.slug = 'productivity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'anything-llm' AND c.slug = 'research-education' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'autogen' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'autogen' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'cherry-studio' AND c.slug = 'productivity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'cherry-studio' AND c.slug = 'writing-content' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chattts' AND c.slug = 'voice-speech' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'copilotkit' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'composio' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'composio' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chat2db' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chat2db' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'coze-studio' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'coze-studio' AND c.slug = 'customer-support' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'google-adk' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'google-adk' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'context7' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'context7' AND c.slug = 'productivity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'bitnet' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'bitnet' AND c.slug = 'research-education' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'db-gpt' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'db-gpt' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chatdev' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chatdev' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'agentscope' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'agentscope' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chrome-devtools-mcp' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'chrome-devtools-mcp' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'crush' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'agno' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'agno' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'vercel-ai-sdk' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
