-- ============================================================
-- Batch 19 — Part 2: 20 curated AI tools (Step 41 — scale to 1,500)
-- Hand-authored enrichment (no API spend). Every tool satisfies ≥3/5
-- plan §41 criteria: trending (github-trending recent list), growing
-- (≥18K GitHub stars), viability (proxy >30). All slugs deduped vs the
-- existing 1,000-tool catalog (Part 1 now live at 1,020).
-- ============================================================

INSERT INTO tools (
  name, slug, tagline, description, website_url,
  pricing_type, pricing_details, skill_level, has_api, platforms,
  features, integrations, is_published,
  best_for, not_for, editorial_verdict,
  tutorial_urls, limitations, models, community_links, use_cases, our_views,
  last_verified_at
) VALUES
('Langflow', 'langflow', 'Open-source visual builder for LangChain-style agent and RAG flows.', 'Langflow is a browser-based drag-and-drop IDE for building LLM workflows. Each node is a Python component — an LLM, a retriever, a prompt template, a tool — and connections define how data flows between them. When you are happy with the flow, export it as a Python script or deploy it behind a REST endpoint.

It is one of the fastest ways for a team to go from "idea for an AI feature" to "working API endpoint" without writing orchestration code by hand. The ecosystem of pre-built components is large: every major LLM provider, every common vector store, dozens of loaders, and a solid set of agent primitives.

Langflow is open source (MIT) and developed by Datastax. It ships with a desktop installer, a Docker image, and a hosted cloud version. The 1.0 release (2024) rebuilt the UI on React Flow and added multi-flow composition, chat streaming, and an observability layer.

Adoption is broad across solo developers prototyping, internal tool teams at mid-market companies, and the occasional production deployment where the visual representation is valued over raw code.', 'https://www.langflow.org', 'freemium', '[{"plan":"Open Source","price":"Free","features":["Self-hosted","All components","Unlimited flows"]},{"plan":"Langflow Cloud","price":"Usage-based","features":["Managed hosting","Team workspaces","Observability","Deployments"]}]'::jsonb, 'intermediate', true, '{"web","desktop","api"}', '{"Drag-and-drop flow builder","200+ pre-built components","Custom Python components","Chat streaming UI","Multi-flow composition","Export to Python or REST API","Observability and run history","Marketplace of community flows","Docker and desktop installers"}', '{"OpenAI","Anthropic","Gemini","Ollama","Pinecone","Weaviate","Chroma","Astra DB","LangChain","LangSmith","HuggingFace"}', true, '{"Teams prototyping AI features fast","Non-Python developers who want agent workflows","Educators teaching RAG / agent concepts","Solution engineers demoing to stakeholders"}', '{"Production systems needing fine-grained flow control","Pure-code teams that prefer writing Python directly"}', 'The default visual IDE for LangChain-style flows. Pick it for rapid prototyping and stakeholder demos; export to code when you graduate to production.', '{"https://docs.langflow.org/get-started-quickstart"}', 'Flows exported to Python tend to be verbose and sometimes need manual cleanup before production. Version upgrades occasionally break older flows — pin versions for production. The visual metaphor stops helping once a flow has 50+ nodes; at that scale, plain code is easier to reason about.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Prototype a customer-support RAG flow and demo it to stakeholders in an afternoon.","Build a multi-tool research agent visually and export it as a FastAPI endpoint.","Teach a team RAG concepts by having them assemble retrievers and prompts in the UI.","Iterate on a chain by swapping components without rewriting code between experiments."}', 'Sweet spot: a team that needs to ship a working AI prototype quickly and has mixed Python / non-Python skillsets. Langflow removes the first 80% of orchestration boilerplate and gives you a live chat UI out of the box. For a solution engineer who lives in demos, it is probably the single highest-leverage tool in the space.

Failure modes. The visual metaphor has real limits — complex production flows with retry logic, conditional branching, and parallelism are easier to reason about as code. Exported Python is functional but not idiomatic; expect to rewrite it if you end up maintaining the flow long-term. And the component catalog, while large, lags LangChain upstream by a week or two.

What to pilot. Rebuild one real agent or RAG pipeline you already have, from scratch, in Langflow. Time how long it takes compared to your existing code. If it is dramatically faster for iteration, it has earned a slot in your prototyping toolkit; if it is a wash or slower, stick with code.', now()),
('LangGraph', 'langgraph', 'Graph-based orchestration framework for stateful, multi-step LLM agents from the LangChain team.', 'LangGraph is LangChain''s framework for building agents as graphs. Unlike the older LangChain Agent API (which used linear chains and got unwieldy for anything complex), LangGraph lets you define nodes (functions / LLM calls / tools) and edges (transitions, potentially conditional), with explicit state that persists across steps. It is conceptually similar to a small state machine for LLM calls.

The key value: durable, inspectable execution. LangGraph persists state across agent steps, supports time-travel debugging, human-in-the-loop checkpoints, and parallel branches that reconverge. Those primitives turn out to matter a lot when you are actually running agents in production and something goes wrong on step 47.

It has become the de-facto framework for serious agent development in Python, and the companion LangGraph Studio (local visual debugger) and LangGraph Platform (hosted durable runtime) make it a complete story from prototype to production. It is open source (MIT) and model-agnostic.

LangGraph is used by Replit''s agent, Klarna''s customer service agent, and dozens of other production AI systems. It pairs well with LangSmith for observability.', 'https://www.langchain.com/langgraph', 'freemium', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full framework","Self-hosted","LangGraph Studio"]},{"plan":"LangGraph Platform","price":"From $39/mo (Plus)","features":["Durable hosted runtime","Scheduled runs","Human-in-the-loop API","Cron agents"]}]'::jsonb, 'advanced', true, '{"api","desktop"}', '{"Graph-based agent state machines","Durable state persistence","Time-travel debugging and replay","Human-in-the-loop checkpoints","Parallel branches with join","Streaming of every intermediate step","LangGraph Studio visual debugger","Long-term memory primitives","Hosted platform with schedules and cron"}', '{"OpenAI","Anthropic","Gemini","LangChain","LangSmith","Ollama","Azure OpenAI","AWS Bedrock"}', true, '{"Engineers building production agents","Teams needing human-in-the-loop approval flows","Applications with long-running multi-step workflows"}', '{"Simple single-turn chatbots (overkill)","Teams allergic to the LangChain ecosystem","Projects where lightweight frameworks like Agno fit better"}', 'The most production-credible agent framework in 2026. If you are building stateful agents that need to recover, branch, or wait for human input, this is the right default.', '{"https://langchain-ai.github.io/langgraph/tutorials/introduction/"}', 'Steeper learning curve than simpler frameworks — the graph mental model takes a week to internalise. Tightly coupled to LangChain ecosystem; if you already dislike LangChain abstractions, LangGraph inherits some of them. The hosted platform is still newer than the open-source library and pricing jumps quickly at higher tiers.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a customer-service agent that can pause, escalate to a human, and resume without losing context.","Orchestrate a multi-tool research agent with branching paths and a join step for synthesis.","Add durable replay to an agent so failed runs can be debugged from any step.","Ship scheduled agent runs via the hosted platform instead of running your own queue."}', 'Sweet spot: a team that has outgrown a simple prompt-and-response chatbot, has production scale, and needs the full matrix of features — durable state, branching, checkpointing, human-in-the-loop, observability. LangGraph is the most opinionated, most capable option here and it has earned its reputation.

Failure modes. The graph metaphor is powerful but not free — it takes real time to learn and you will write more boilerplate than in a lighter framework like Agno or the Vercel AI SDK. If your use case is a simple chatbot with two tools, LangGraph is overkill and the complexity tax will slow you down. The LangChain ecosystem still has a reputation for churn; lock versions aggressively.

What to pilot. Take one production agent flow that has given you trouble (a failed run you could not debug, a workflow that needs human approval) and rebuild just that flow in LangGraph. If the durability and inspection features solve the real problem you had, commit to the migration; if they feel like solutions to problems you do not have, keep your current stack.', now()),
('SmolAgents', 'smolagents', 'HuggingFace minimalist agent library — code-first agents in under 1,000 lines of Python.', 'SmolAgents is HuggingFace''s intentionally tiny agent framework. The full source code is under 1,000 lines of Python, and the philosophy is explicitly anti-bloat: the primary loop is a CodeAgent that writes Python code to solve a task, executes it in a sandbox, and iterates. A ToolCallingAgent variant uses JSON function calls instead.

The core insight: code-writing agents are more capable than tool-calling agents on complex reasoning tasks because code is a more expressive action space (variables, loops, conditionals) than a sequence of JSON function calls. SmolAgents bakes this philosophy in and keeps the scaffolding to the absolute minimum.

It ships with integrations to HuggingFace Inference Endpoints, OpenAI, Anthropic, LiteLLM, and any OpenAI-compatible API. Tools can be pulled from the Hub or written as plain Python functions with type hints. Sandbox options include E2B, Docker, and a local Python executor (unsafe without sandboxing).

Released by HuggingFace in late 2024 and quickly adopted as the "learn how agents work" framework — the entire codebase is readable in one sitting, which is rare in a space dominated by heavy abstractions.', 'https://github.com/huggingface/smolagents', 'free', '[{"plan":"Open Source","price":"Free (Apache 2.0)","features":["Full library on PyPI","All agent types","Sandbox adapters"]}]'::jsonb, 'intermediate', false, '{"api","cli"}', '{"CodeAgent writes Python to solve tasks","ToolCallingAgent for JSON-function style","Under 1,000 lines of readable source","Sandbox options: E2B, Docker, local","Tools as plain Python functions with type hints","HuggingFace Hub tool integration","Streaming of agent thoughts","Multi-step reasoning with memory"}', '{"HuggingFace","OpenAI","Anthropic","LiteLLM","E2B","Docker"}', true, '{"Developers learning how agents work under the hood","Teams prototyping without framework lock-in","Researchers comparing code vs tool-calling agent patterns"}', '{"Production systems needing complex state management","Non-Python teams","Use cases better served by LangGraph / AutoGen"}', 'The best framework for learning agents from first principles. Small, readable, and honest about what an agent actually is.', '{"https://huggingface.co/docs/smolagents/index"}', 'No built-in durable state or checkpointing — if a run fails, you restart. Code execution demands a real sandbox; local execution is a foot-gun in production. Ecosystem of pre-built tools is smaller than LangChain''s. Not designed for multi-agent orchestration.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a quick research agent that writes Python to fetch and analyse data.","Teach a team how LLM agents work by reading the SmolAgents source together.","Prototype a code-writing agent without committing to a heavy framework.","Compare CodeAgent vs ToolCallingAgent performance on your own task set."}', 'Sweet spot: a developer or researcher who wants to build an agent and actually understand what is happening on every step. SmolAgents strips agents down to their essentials — an LLM, an action, a result, a new prompt — and that clarity is refreshing. It is also genuinely capable for a lot of real tasks: data analysis, research, web browsing with a code interpreter.

Failure modes. For production multi-step agents with human-in-the-loop, durable state, and recovery semantics, SmolAgents does not compete with LangGraph — it was never designed to. Sandbox discipline is on you; running the CodeAgent with LocalPythonExecutor on untrusted input is a serious security risk. And the tool ecosystem, while growing, is thinner than the big frameworks.

What to pilot. Pick a task that can be solved by writing and running code (a data-analysis question, a file-processing job, a research question that needs web fetches). Build a SmolAgents CodeAgent for it and compare to your current approach. If the code-writing action space makes the task easier, SmolAgents is the right tool; if the task is pure tool-calling with no computation, any framework will do.', now()),
('Semantic Kernel', 'semantic-kernel', 'Microsoft''s open-source AI orchestration SDK for .NET, Python, and Java — enterprise-ready agent framework.', 'Semantic Kernel is Microsoft''s open-source SDK for integrating LLMs into conventional software. It provides a unified abstraction for models, a plugin model for tools, an agent framework with group chat patterns, memory and RAG primitives, filters (think middleware for LLM calls), and planners that turn a goal into a sequence of plugin invocations.

The differentiator versus LangChain / LangGraph is language breadth. Semantic Kernel has full-quality SDKs for C#, Python, and Java — a rare trio — which makes it the default choice for enterprise shops already on .NET or the JVM. It also integrates tightly with the broader Microsoft ecosystem: Azure OpenAI, Azure AI Search, Azure AI Foundry, Microsoft 365 Copilot extensibility, Entra ID auth.

The Agent Framework (integrated in 2024) brings LangGraph-style multi-agent workflows: orchestrator agents, group chat, handoff patterns, and a process framework for durable long-running flows. A new Process Framework added in 2025 handles saga-style durable workflows across systems.

Used heavily inside Microsoft (for Copilot extensibility) and in enterprise .NET / Java shops. Open source (MIT), model-agnostic, and actively released every few weeks.', 'https://learn.microsoft.com/en-us/semantic-kernel/', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":[".NET / Python / Java SDKs","Agent Framework","Process Framework","All integrations"]}]'::jsonb, 'intermediate', true, '{"api"}', '{".NET / Python / Java SDKs","Plugin model for tools","Agent Framework with group chat and handoffs","Process Framework for durable workflows","Planners (goal-to-plan synthesis)","Filters (middleware for LLM calls)","Memory primitives and RAG","Azure AI Search integration","Microsoft 365 Copilot extensibility","Model-agnostic with OpenAI / Anthropic / Azure / local"}', '{"Azure OpenAI","OpenAI","Anthropic","Gemini","Ollama","Azure AI Search","Microsoft 365","Entra ID","Pinecone","Qdrant"}', true, '{"Enterprise .NET teams","Java shops integrating LLMs","Microsoft 365 / Azure-native environments","Teams needing governance-ready AI orchestration"}', '{"Python-only startups (LangGraph / Agno are lighter)","Non-enterprise side projects","Teams without .NET or Java footprint"}', 'The default AI orchestration SDK for enterprise Microsoft / Java shops. Lacks Python-first community energy of LangGraph but wins decisively on language breadth and governance.', '{"https://learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide"}', 'Python SDK lags the .NET SDK on feature parity by a few releases. Documentation is split across multiple Microsoft sites and can be hard to navigate. The Process Framework is newer and less proven than LangGraph''s durable-runtime offering. Heavy enterprise flavour means more ceremony than leaner frameworks.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a customer-service agent in C# that integrates with Entra ID-protected internal APIs.","Ship a Java-based RAG agent over an enterprise Azure AI Search index.","Orchestrate a long-running approval workflow using the Process Framework.","Extend Microsoft 365 Copilot with a custom agent connected to internal data."}', 'Sweet spot: a Microsoft-house enterprise where .NET or Java is the primary language and Azure is the cloud. For that profile, Semantic Kernel removes every friction point — SSO, governance, existing tooling, data residency — that Python-first frameworks would force you to retrofit. Microsoft ships it because Microsoft customers demanded a serious orchestration framework in their stack.

Failure modes. If you are a Python-native team with no Microsoft ecosystem investment, Semantic Kernel''s Python SDK will feel like a second-class citizen to LangChain / LangGraph. Documentation quality varies sharply: the C# .NET content is excellent; the Java and Python content is uneven. And the Agent Framework, while capable, trails LangGraph in community adoption, meaning fewer third-party tutorials.

What to pilot. Build one agent that touches your existing Microsoft identity and data estate — an Entra-authenticated tool over a SharePoint doc set, for example. If the framework handles auth, observability, and governance gracefully, it is the right match; if you end up fighting it, a Python-first framework will serve you better even with the ecosystem-mismatch tax.', now()),
('MetaGPT', 'metagpt', 'Multi-agent framework that simulates a software company — product manager, architect, engineer, QA.', 'MetaGPT is an experimental multi-agent framework that organises LLM agents into the roles of a small software company: product manager, architect, project manager, engineer, and QA. Give it a one-line requirement ("build me a CLI for X") and the agents collaborate through a structured process — PRD generation, architecture design, task breakdown, implementation, review — to produce a working codebase.

The key idea, argued in the accompanying paper, is that encoding real-world software-engineering process into the agent graph dramatically improves output quality versus free-form multi-agent chat. Each agent has a role-specific prompt, standard operating procedures, and produces artefacts (PRDs, architecture docs, code) in the shape humans would.

MetaGPT is more research project than production framework — outputs are best on greenfield small-to-medium tasks (a simple web app, a Python CLI, a small game). It does not replace a real engineering team for complex codebases. But it is one of the most illuminating demonstrations of structured multi-agent collaboration in open source.

It is MIT-licensed, supports OpenAI / Azure / Anthropic / local models, and has an active research community building agent-society variants on top.', 'https://docs.deepwisdom.ai', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full framework","All agent roles","Model-agnostic"]}]'::jsonb, 'intermediate', false, '{"cli","api"}', '{"Multi-agent software-company simulation","Role-specific agents: PM, architect, engineer, QA","Structured SOP for each role","PRD / architecture / code artefact outputs","Git integration for commit history","Human-in-the-loop review points","Incremental development mode","Research-paper-backed design","Model-agnostic"}', '{"OpenAI","Azure OpenAI","Anthropic","Gemini","Ollama","Git"}', true, '{"Researchers studying multi-agent collaboration","Developers exploring automated code generation","Educators teaching software engineering process"}', '{"Production software teams","Complex brownfield codebases","Non-technical users"}', 'The most academically interesting multi-agent framework. Great for learning what structured agent collaboration can do; not a replacement for real engineering.', '{"https://docs.deepwisdom.ai/main/en/guide/get_started/quickstart.html"}', 'Output quality degrades sharply as task complexity grows — excellent for toy apps, poor for anything real. Cost escalates fast because each step has multiple LLM calls. Does not maintain codebase context across sessions well. The paper is inspiring; production use is niche.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Generate a first-pass CLI or small web app from a one-sentence requirement.","Study how structured agent roles affect collaboration quality versus free-form chat.","Teach multi-agent concepts by having students modify the agent SOPs.","Prototype automated PRD-to-code pipelines for very simple greenfield projects."}', 'Sweet spot: a researcher, educator, or builder who wants to learn what structured multi-agent systems can do. MetaGPT is one of the best "let me see it work" demos in the agent space — watching a PM, architect, and engineer agent argue their way to a working code repo is genuinely interesting, and the structured SOPs are a template worth borrowing for your own agents.

Failure modes. As a production code-generation tool, MetaGPT is not a replacement for Cursor / Claude Code / Copilot. Outputs on non-trivial requirements are rough and need heavy human cleanup. Multi-agent cost balloons fast — a single project spin can rack up a few dollars in API spend. Context handling over long sessions is weak.

What to pilot. Run MetaGPT on one greenfield task you would normally prototype yourself (a simple scraper, a small dashboard, a CLI tool). Compare the result to what you would have written in the same time. If the output is a useful starting point that saved you 30 minutes, keep it as a prototyping tool; if it needed more cleanup than writing from scratch, shelve it.', now()),
('OpenHands', 'openhands', 'Open-source autonomous software-engineering agent (formerly OpenDevin) — a rival to Devin.', 'OpenHands is an open-source autonomous coding agent that can plan, write, run, debug, and iterate on code across a full development environment. It runs inside a sandboxed Docker container with file-system access, a web browser, and a terminal — giving it the same surface area a human developer uses.

Originally launched as OpenDevin in response to Cognition''s Devin demo, it was renamed to OpenHands in 2024 and evolved into one of the most active open-source agent projects. The agent architecture separates Planning from Execution, supports multiple agent implementations (CodeActAgent, BrowsingAgent, VisualBrowsingAgent), and integrates with every major LLM via LiteLLM.

Interfaces include a web UI (the default), a CLI, a headless mode, and a GitHub App that responds to issues and comments. OpenHands Cloud offers a hosted version with included credits for teams that do not want to manage Docker containers.

It is MIT-licensed, benchmarks near the top on SWE-Bench among open agents, and has a rapidly growing contributor base. A primary use case is as a starting point for custom autonomous engineering agents rather than a polished end-user product.', 'https://www.all-hands.dev', 'freemium', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full agent framework","Docker sandbox","Web UI","GitHub App"]},{"plan":"OpenHands Cloud","price":"From $20/mo","features":["Hosted runtime","Included credits","Team workspaces","Managed upgrades"]}]'::jsonb, 'advanced', true, '{"web","cli","api"}', '{"Autonomous code-writing agent","Docker sandbox with file-system, browser, terminal","Multiple agent implementations","GitHub App integration","Hosted cloud with credits","LiteLLM integration for 100+ models","Planning / execution separation","SWE-Bench benchmark leadership among open agents","Headless mode for CI / automation"}', '{"OpenAI","Anthropic","Gemini","LiteLLM","GitHub","Docker","VS Code"}', true, '{"Developers experimenting with autonomous coding agents","Teams building internal coding automations","Researchers benchmarking agent performance on SWE-Bench"}', '{"Non-developers","Teams needing polished IDE-integrated copilots (Cursor fits better)","Workloads that cannot tolerate Docker overhead"}', 'The leading open-source autonomous engineering agent. Strong research momentum; more DIY than Cursor or Claude Code but far more hackable.', '{"https://docs.all-hands.dev/usage/getting-started"}', 'Docker sandbox has real overhead — each session consumes GB of memory and multiple CPUs. Complex tasks still fail more often than they succeed even on GPT-4o-class models. Setup is heavier than IDE-integrated copilots. Cost compounds with long autonomous runs; set step and time budgets.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Run an autonomous agent on a well-scoped bug from your issue tracker via the GitHub App.","Benchmark a new LLM on SWE-Bench using OpenHands as the harness.","Build a nightly automation that refactors a module and opens a PR for review.","Compare open-source agent performance against Cursor on your own codebase."}', 'Sweet spot: a developer or small team that wants to experiment with fully autonomous coding agents and is comfortable with Docker and a bit of setup. OpenHands is the most hackable credible option — you can swap models, modify agent logic, and plug it into your existing workflow through the GitHub App. As a research platform, it is arguably the most interesting agent codebase in open source.

Failure modes. Autonomy is still brittle. Even with GPT-4o or Claude Sonnet 4, complex multi-file refactors fail often enough that human review is non-negotiable. Cost per run is higher than interactive IDE use because autonomous agents loop more. And for day-to-day developer productivity, a supervised copilot (Cursor, Claude Code) will get you more done per dollar.

What to pilot. Pick three well-scoped bugs from your backlog — each should have a clear test and a bounded blast radius. Run OpenHands on all three via the GitHub App. Measure success rate, time spent reviewing, and total cost. If at least one passed cleanly and the other two needed only minor fixes, OpenHands has earned a slot in your automation stack; if none made it past review, the economics do not work yet for your codebase.', now()),
('LlamaIndex', 'llama-index', 'Data framework for LLMs — ingestion, indexing, retrieval, and agents over your private data.', 'LlamaIndex is the Python (and TypeScript) data framework for LLM applications. Where LangChain started as an orchestration framework, LlamaIndex started as a retrieval framework — the pipeline that gets your data into an LLM, as opposed to the logic around the LLM call. That focus has given it the most thorough toolbox in open source for the first half of any RAG stack.

It ships 300+ data loaders (LlamaHub), multiple indexing strategies (vector, keyword, knowledge graph, tree, summary), a query engine abstraction that handles routing and hybrid retrieval, and a workflows system for multi-step agent orchestration. LlamaIndex 0.10+ reorganised the codebase into smaller focused packages, making it easier to install only what you need.

LlamaCloud is the commercial managed version — specifically strong on LlamaParse, a PDF-parsing endpoint that handles tables, figures, and complex layouts far better than generic parsers. LlamaExtract turns unstructured documents into structured data given a Pydantic schema.

Open source (MIT), maintained by LlamaIndex Inc, and powering production RAG at many companies. Pairs with any vector store and any LLM.', 'https://www.llamaindex.ai', 'freemium', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full framework (Python + TS)","300+ loaders","All retrieval strategies","Workflows"]},{"plan":"LlamaCloud","price":"Usage-based","features":["LlamaParse (advanced PDF parsing)","LlamaExtract (schema-based extraction)","Managed indexes","Enterprise SSO"]}]'::jsonb, 'intermediate', true, '{"api"}', '{"300+ data loaders (LlamaHub)","Multiple index types: vector, keyword, KG, tree","Query engines with routing and hybrid retrieval","Workflows for multi-step orchestration","LlamaParse: advanced PDF / document parsing","LlamaExtract: schema-based extraction","Managed LlamaCloud indexes","TypeScript SDK mirror","Evaluation framework","Deep integrations with all major vector stores"}', '{"OpenAI","Anthropic","Gemini","Ollama","Pinecone","Weaviate","Chroma","Qdrant","Milvus","Elasticsearch","MongoDB","Snowflake"}', true, '{"Engineers building RAG pipelines","Teams processing complex PDFs (legal, medical, finance)","Developers needing structured extraction from unstructured data"}', '{"Applications with no retrieval need (pure chat)","Teams fully committed to LangGraph for agents (LlamaIndex agent story is lighter)"}', 'The strongest data/retrieval framework for LLMs. If your project is "LLM over our documents," start here.', '{"https://docs.llamaindex.ai/en/stable/getting_started/starter_example/"}', 'The agent / workflow side is good but not as deep as LangGraph — most teams pair LlamaIndex retrieval with another agent framework. LlamaParse and LlamaExtract are paid services that add cost per document. Package reorganisation (0.10+) broke older tutorial code; prefer current docs over blog posts.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a RAG chatbot over a folder of PDFs using LlamaParse for complex document parsing.","Extract structured records from invoices or contracts using LlamaExtract with a Pydantic schema.","Implement hybrid retrieval (vector + BM25) over a large knowledge base.","Route a query across multiple indexes using a Router Query Engine."}', 'Sweet spot: any team whose main LLM problem is "get high-quality context into the model." LlamaIndex has the best loaders, the best complex-document parser in open tools, and the cleanest mental model for retrieval. If your RAG quality is poor today, LlamaIndex (and particularly LlamaParse on hard documents) is the highest-leverage intervention.

Failure modes. For agent-heavy workloads, LlamaIndex''s workflows are functional but trail LangGraph in production polish — pair them or pick one framework per job. LlamaParse and LlamaExtract, while excellent, are managed services that you are paying per document; for very high volume, an in-house parser may be cheaper. The framework has gone through several large refactors; treat any tutorial older than six months as stale.

What to pilot. Pick your single worst document type — the one where your current RAG pipeline produces the worst answers. Run it through LlamaParse and rebuild your index. Measure answer quality on ten real questions before and after. If LlamaParse moves the needle, commit; if the bottleneck was elsewhere (chunking, reranking, prompt), at least you have localised the real problem.', now()),
('LiteLLM', 'litellm', 'Unified Python SDK and proxy for 100+ LLM providers — one API for OpenAI, Anthropic, Bedrock, local models.', 'LiteLLM is the glue layer that lets you call 100+ different LLM providers (OpenAI, Anthropic, Azure, Bedrock, Vertex AI, Together, Groq, Fireworks, Ollama, and many more) through a single OpenAI-compatible API. You write OpenAI-style code once, LiteLLM routes the actual call to whichever provider you named in the model string.

It ships in two forms. The Python SDK is a drop-in for openai-python that handles the routing. The LiteLLM Proxy is a standalone server (FastAPI + Postgres) that sits in front of all your model traffic — adding authentication, virtual keys, per-team budgets and rate limits, model-level fallbacks, logging to Langfuse or Helicone, and cost tracking. For any organisation that has more than one team using more than one provider, the Proxy quickly becomes indispensable.

LiteLLM is open source (MIT) and there is an Enterprise tier for SSO, audit logs, and priority support. It is used in production by many mid-size-and-up organisations as the spine of their AI platform.', 'https://www.litellm.ai', 'freemium', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full SDK","Self-hosted proxy","All provider adapters"]},{"plan":"Enterprise","price":"From $5K/year","features":["SSO","Audit logs","Priority support","SLA"]}]'::jsonb, 'intermediate', true, '{"api","cli"}', '{"OpenAI-compatible API across 100+ providers","Python SDK drop-in for openai-python","Standalone proxy server with virtual keys","Per-team budgets and rate limits","Model-level fallbacks and retries","Cost tracking per user / team","Logging to Langfuse / Helicone / OpenTelemetry","Prompt caching","Guardrails integration"}', '{"OpenAI","Anthropic","Azure OpenAI","AWS Bedrock","Vertex AI","Gemini","Cohere","Groq","Together","Fireworks","Ollama","Mistral","Langfuse","Helicone"}', true, '{"Platform teams managing LLM access across multiple teams","Engineers needing failover across providers","Organisations tracking cost per team / user","Prototypers who switch models frequently"}', '{"Solo developers hitting one provider only (direct SDK is fine)","Use cases needing provider-specific features not in the abstraction"}', 'The default LLM router and gateway. If you have more than one team or more than one provider, you want the proxy — full stop.', '{"https://docs.litellm.ai/docs/"}', 'Abstractions sometimes lag provider-specific features (new response formats, beta endpoints). Proxy adds one more network hop, which matters for latency-sensitive workloads. Configuration file for routing rules can grow complex for large orgs. Enterprise tier pricing is not public and involves sales.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Stand up a central LLM gateway with virtual API keys for every team in the org.","Add automatic fallback from OpenAI to Azure OpenAI during outages with zero code changes.","Track per-team LLM cost and enforce monthly budgets without writing billing code.","Run a local Ollama model behind an OpenAI-compatible endpoint for a quick prototype."}', 'Sweet spot: a platform or infra team at a company where many product teams are calling many models. The LiteLLM Proxy solves a genuinely hard set of problems — key management, budgets, failover, observability — with one lightweight service. The alternative is building that same stack yourself; teams that try inevitably end up with a worse version of LiteLLM.

Failure modes. For a solo developer or single-team project hitting only OpenAI, LiteLLM is overhead you do not need. Some provider-specific features (OpenAI''s new structured outputs at launch, Anthropic''s streaming tool deltas) lag the abstraction by a few weeks. If your workload is latency-critical (sub-second response targets), the extra network hop is worth measuring.

What to pilot. Deploy the LiteLLM Proxy in a staging environment, point two teams'' workloads at it, and turn on cost tracking. After two weeks, check: is the cost dashboard telling you something you did not already know? Did failover save an outage? If the answer to either is yes, productionise it. If neither, stay with direct provider SDKs.', now()),
('Haystack', 'haystack', 'Open-source LLM framework from deepset for production-grade RAG, search, and agent pipelines.', 'Haystack (v2, released 2024) is deepset''s open-source framework for building LLM applications. It is unapologetically production-oriented: a component-based pipeline model (each component has typed inputs and outputs, connections are validated at build time), serialisation to YAML for deployable pipelines, and a strong emphasis on evaluation and observability.

Where other frameworks lean on informal chaining, Haystack enforces explicit composition. That trade-off pays off when you move from prototype to production and need to reason about pipeline correctness, run evals on each component, or hand a YAML to your platform team for deployment.

It ships integrations for every major LLM, every major vector store, and a growing catalog of agents and tool patterns. The companion deepset Cloud is a commercial managed platform that adds a visual pipeline builder, hosted deployments, and enterprise features on top.

Haystack is Apache-2-licensed, has a large research-adjacent user base (the deepset team is known for search and question-answering research), and is used in production across companies with regulated workloads where explicit pipeline structure matters.', 'https://haystack.deepset.ai', 'freemium', '[{"plan":"Open Source","price":"Free (Apache 2.0)","features":["Full framework","All integrations","YAML pipeline serialisation"]},{"plan":"deepset Cloud","price":"Custom","features":["Managed hosting","Visual pipeline builder","SSO","Enterprise support"]}]'::jsonb, 'intermediate', true, '{"api"}', '{"Typed component-based pipelines","YAML serialisation for deployment","Evaluation framework (SAS, answer correctness, RAGAS)","Agents and tool calling","Multi-modal pipelines","Large retriever / reader catalog","Integrations with 15+ vector stores","Streaming and async support","Hayhooks for REST deployment","deepset Cloud managed option"}', '{"OpenAI","Anthropic","Gemini","Cohere","HuggingFace","Ollama","Elasticsearch","OpenSearch","Pinecone","Weaviate","Qdrant","Chroma","Milvus"}', true, '{"Teams deploying production RAG in regulated environments","Search / IR specialists migrating to LLM-powered answers","Platform teams needing declarative pipeline configs"}', '{"Quick prototypes (Langflow / LlamaIndex are faster)","Solo developers (lighter frameworks work)","Heavily agentic workloads (LangGraph is more focused)"}', 'The most deployment-credible open-source RAG framework. Production-ready out of the box; slightly heavier on ceremony than lighter competitors.', '{"https://docs.haystack.deepset.ai/docs/get_started"}', 'Typed composition is a double-edged sword — it catches errors early but slows experimentation. Agent story is newer than retrieval and trails LangGraph. Documentation is thorough but skews toward the search/IR mindset, which can feel foreign to pure chatbot builders. Ecosystem of community components is smaller than LangChain.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Deploy a production RAG service from a YAML pipeline spec with no Python glue code.","Evaluate RAG answer quality using RAGAS metrics wired into a Haystack evaluation pipeline.","Migrate a classic search application to LLM-powered answers while keeping the existing ES index.","Build a multi-modal pipeline that answers questions over PDFs and their figures."}', 'Sweet spot: a team that has already graduated from prototype to production and needs a RAG framework that behaves like a proper software component. Haystack''s typed-composition model catches a class of errors — mismatched shapes, missing inputs — that lighter frameworks surface at runtime. For regulated industries or platform teams who need declarative configs, it is the best-fit option.

Failure modes. The ceremony of typed components slows rapid iteration. For a prototype where you are still figuring out what the pipeline should do, LlamaIndex or Langflow will move faster. Agent workloads are supported but not the strong suit — LangGraph pairs better if agents are central. And the search-heritage mental model (retrievers, readers, rankers) is powerful but takes getting used to.

What to pilot. Take one RAG flow you have already prototyped in another framework and rewrite it as a Haystack pipeline with a YAML export. Deploy the YAML to a container via Hayhooks. Compare deployment friction and eval-loop quality. If Haystack wins on reliability and eval speed, it is the right graduation target; if the translation felt like forcing ceremony on a simple chain, stay lighter.', now()),
('Mastra', 'mastra', 'Open-source TypeScript AI framework — agents, workflows, RAG, evals, observability in one stack.', 'Mastra is an open-source TypeScript AI framework aimed at full-stack developers who live in the JS/TS ecosystem. It provides primitives across the full agent lifecycle: model-agnostic agent abstraction, graph-based workflows with durable state, RAG utilities, memory, evals, and an observability UI — all in idiomatic TypeScript.

The pitch to the JS community: you do not need to drop into Python to get LangGraph-class agent workflows. Mastra bundles a full stack roughly equivalent to LangChain + LangGraph + LangSmith into one TypeScript framework with a tight developer experience. The mastra dev CLI runs a local playground where you can inspect agent conversations, step through workflows, and see traces in real time.

Mastra is built by the Gatsby team (the team behind the eponymous static-site framework who pivoted to AI tooling). It is open source (Elastic License 2.0 with a generous OSS carve-out) and the commercial Mastra Cloud offers hosted deployment, shared memory stores, and team features.

Adoption is growing fast in the JS agent space, where the Vercel AI SDK fills the streaming / provider-switching layer but leaves orchestration and evals thin. Mastra slots into that gap.', 'https://mastra.ai', 'freemium', '[{"plan":"Open Source","price":"Free (Elastic 2.0)","features":["Full framework","Local playground","All integrations"]},{"plan":"Mastra Cloud","price":"Usage-based","features":["Hosted deployment","Team workspaces","Shared memory","Observability"]}]'::jsonb, 'intermediate', true, '{"api","cli"}', '{"TypeScript-native agent framework","Graph-based workflows with durable state","Model-agnostic via AI SDK under the hood","Built-in RAG utilities","Memory and thread state","Evals with LLM-as-judge","Local dev playground with traces","Observability UI","Hosted cloud option"}', '{"OpenAI","Anthropic","Gemini","Groq","Mistral","Ollama","Vercel AI SDK","Next.js","Pinecone","Chroma","PostgreSQL"}', true, '{"TypeScript developers building agent-heavy features","Next.js teams needing workflows richer than AI SDK provides","Full-stack JS engineers wanting evals and observability included"}', '{"Python teams (LangGraph is the canonical choice)","Simple chat UIs that only need AI SDK","Workloads needing the broadest possible model catalog"}', 'Effectively LangGraph for the JavaScript world. If your team is TS-native and agent-heavy, Mastra deserves a serious look.', '{"https://mastra.ai/docs/getting-started/installation"}', 'Newer project than the Python incumbents — smaller community, fewer examples, shorter track record. Evals and observability are good but not as battle-tested as LangSmith. License is Elastic 2.0 (not pure MIT) — review it for your use case. Cloud tier is newer and feature-scoped.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a customer-support agent with a durable workflow that can pause and resume in a Next.js app.","Add LLM-as-judge evals to an existing TypeScript agent without adding a Python service.","Instrument a production TS agent with traces and replay in the local playground.","Migrate a hacky chain of OpenAI calls into a structured Mastra workflow."}', 'Sweet spot: a TypeScript team that has hit the ceiling of the Vercel AI SDK — they need workflow orchestration, durable state, evals, and observability, but do not want to run a separate Python service for it. Mastra fills that gap convincingly, and the local playground experience is one of the best in the ecosystem.

Failure modes. As a newer framework, Mastra has less community momentum than LangGraph or LangChain. That matters on edge cases — fewer blog posts, fewer Stack Overflow answers, fewer third-party integrations. The Elastic License is permissive for most real use cases but adds a legal review step if your company has strict OSS policies. And the feature surface, while broad, is shallower in places than the Python equivalents.

What to pilot. Build a real feature that needs orchestration (not just a chat endpoint) in Mastra from scratch. Compare developer experience to what you would have built with AI SDK alone plus custom glue. If Mastra saves a meaningful amount of orchestration code while staying in TS, commit; if the gains are marginal and you already have AI SDK patterns that work, stay with the simpler stack.', now()),
('Letta', 'letta', 'Framework for building LLM agents with long-term memory — evolved from the MemGPT research project.', 'Letta (formerly MemGPT) is an open-source framework for building agents that have persistent memory across sessions. The core idea, from the MemGPT paper: treat LLM context as an operating-system memory hierarchy — a fast "main context" the model sees directly and a larger "external context" the agent can page in and out via tool calls. Combined with an agent loop that proactively writes summaries and retrieves on demand, this gives agents something much closer to durable memory than a typical conversation buffer.

Letta exposes this as a server (Docker or cloud) with a REST / Python SDK. Agents are first-class entities: they persist, they can be shared across users, and they accumulate memory over time. The server handles memory consolidation, archival, and retrieval; you just call the agent and it remembers.

The company also offers Letta Cloud — a hosted version with persistent storage, API-key access, and team features — and an Agents Development Environment (ADE) web UI for inspecting agent memory and tracing steps.

Apache-2-licensed, based on peer-reviewed research, and actively maintained by the original MemGPT authors. It is the cleanest answer in open source to "how do I build an agent that remembers things a month later."', 'https://www.letta.com', 'freemium', '[{"plan":"Open Source","price":"Free (Apache 2.0)","features":["Full server (Docker)","Python SDK","ADE visual UI"]},{"plan":"Letta Cloud","price":"From $20/mo","features":["Hosted server","Persistent storage","Team workspaces","API keys"]}]'::jsonb, 'intermediate', true, '{"api","cli","web"}', '{"Memory-aware agent framework","Main + external context (MemGPT paradigm)","Agent persistence across sessions","Memory consolidation and summarisation","REST and Python SDK","Agents Development Environment (ADE) UI","Tool calling","Model-agnostic","Hosted cloud option"}', '{"OpenAI","Anthropic","Gemini","Ollama","LiteLLM","PostgreSQL","Docker"}', true, '{"Developers building long-lived agents (coaching, companion, assistant)","Researchers studying memory architectures","Products where cross-session continuity is a key value prop"}', '{"Short single-turn workflows","Teams who already handle memory via RAG (Letta is overhead)","Production workloads needing strongest-possible observability (other frameworks are deeper)"}', 'The clearest open-source framework for agents with real long-term memory. If cross-session continuity matters to your product, Letta is the first tool to evaluate.', '{"https://docs.letta.com/quickstart"}', 'Memory quality still depends heavily on model choice — smaller models hallucinate their own memory. Server architecture is heavier than stateless agent libraries; deployment and ops cost is real. MemGPT paradigm is one opinion about how to do memory — alternative approaches (pure RAG, episodic memory, graph memory) may be better for some products.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a coaching agent that remembers user goals, progress, and preferences across months.","Ship a customer-service agent that recognises a repeat customer and their previous conversations.","Research how main-plus-external context compares to pure RAG on a long-conversation benchmark.","Prototype a companion app with an agent that accumulates a real relationship history."}', 'Sweet spot: a product where the value proposition is "it remembers you." Coaching apps, companion agents, long-lived customer-service identities, research assistants. Letta solves the hardest part — memory that actually holds up — and does it as an opinionated, well-documented framework rather than asking you to invent it.

Failure modes. If your agent is short-lived or your memory needs are really just "retrieve from a document store on each query," Letta is overhead you do not need — a RAG pipeline will be simpler and cheaper. The MemGPT approach is powerful but opinionated; if your memory shape is graph-natural or episodic, you may fight the abstraction. And memory quality is not just the framework''s job — weak models produce unreliable memories regardless of scaffolding.

What to pilot. Build one agent with a memory-centric value prop. Run it for two weeks on your own usage. Week 2, test it on things you mentioned in Week 1 — preferences, goals, specific facts. If recall is accurate and feels useful, Letta has earned its place; if the memory is noisy or irrelevant, investigate whether the issue is framework, model, or your prompts before committing.', now()),
('Guidance', 'guidance', 'Microsoft library for constrained LLM generation — force structured outputs and enforce syntax.', 'Guidance is a Microsoft-developed Python library for constrained LLM generation. Instead of asking a model to "please return JSON" and hoping, you write a template with explicit structure — fixed text, typed slots, branches, loops — and Guidance constrains the model''s token generation so the output is guaranteed to match the template.

It works best with local and open-source models served via llama.cpp, Transformers, or vLLM, where Guidance can manipulate logits directly to prevent invalid tokens. It also supports OpenAI and Azure via best-effort constraint reflection (no logit access means weaker guarantees, but templates still help).

Use cases include JSON/XML extraction where schema adherence matters, code generation where syntax must be valid, and multi-step reasoning where you want to force a specific format (chain-of-thought, then answer). Guidance is also notably faster than unconstrained sampling in many cases because it can skip generation for fixed template parts.

Apache-2-licensed, originally released by Microsoft Research, now maintained by a mix of Microsoft and community contributors. It is the reference implementation of the "structured generation" approach that frameworks like Outlines and LMQL also explore.', 'https://github.com/guidance-ai/guidance', 'free', '[{"plan":"Open Source","price":"Free (Apache 2.0)","features":["Full library","Local model constraints","API-model templates"]}]'::jsonb, 'advanced', false, '{"api"}', '{"Constrained generation via logit masking","Template language for LLM outputs","Guaranteed schema adherence on local models","Chat templates that enforce role structure","Regex, JSON schema, context-free grammar constraints","Batched / parallel generation","Integrations with llama.cpp, Transformers, vLLM","Also works with OpenAI / Azure (best-effort)","Faster than unconstrained sampling for structured output"}', '{"llama.cpp","Transformers","vLLM","OpenAI","Azure OpenAI","HuggingFace"}', true, '{"Engineers extracting structured data from open-source LLMs","Teams running local models that need guaranteed JSON","Researchers working on constrained decoding"}', '{"Teams exclusively on OpenAI with simple JSON needs (structured outputs are simpler)","Non-Python teams","Straightforward chat workflows"}', 'The canonical open-source structured-generation library. Essential for serious work with local / open models; OpenAI structured outputs make it less critical on hosted APIs.', '{"https://guidance.readthedocs.io/en/latest/"}', 'Real power comes with logit access — on OpenAI / Anthropic endpoints, constraints are best-effort. Template syntax has a learning curve distinct from prompts. Some features require llama-cpp-python or Transformers with specific versions. Not an orchestration framework — combine with an agent library for full applications.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Force a local Llama model to produce strictly-valid JSON matching a schema.","Generate syntactically-correct SQL from an open-source model without post-parsing.","Build a multi-role chat template that enforces system / user / assistant structure.","Speed up structured generation by skipping fixed template text."}', 'Sweet spot: a team running local or open-source LLMs (llama.cpp, vLLM-served open models) that needs guaranteed structured output. OpenAI and Anthropic now ship first-class structured outputs, which took pressure off Guidance for hosted APIs — but for self-hosted models, Guidance and its siblings (Outlines, LMQL) remain the correct answer.

Failure modes. If your stack is entirely hosted OpenAI / Anthropic, the providers'' own structured-output features are simpler and just as reliable for most schemas. Template language requires investment — teams that expect a one-line decorator will find it heavier than that. And as a library, Guidance is a piece of a stack, not a full solution; you still need orchestration around it.

What to pilot. Take one structured-extraction task on a local model where you currently post-process or retry. Rewrite it in Guidance. Measure: failure rate, wall-time per call, total tokens. If the guaranteed-schema property eliminates retries and speeds up generation, Guidance pays for its learning curve; if post-processing was already fast and rare, skip it.', now()),
('OpenAI Agents SDK', 'openai-agents-python', 'Official Python SDK for building multi-agent workflows with OpenAI models — handoffs, guardrails, tracing.', 'The OpenAI Agents SDK is the official Python framework for building agent applications, released by OpenAI as the successor to the earlier (and now-deprecated) Swarm experiment. It provides a small, focused set of primitives — Agents, Handoffs, Guardrails, and Sessions — that combine into arbitrarily complex workflows without imposing a heavy abstraction layer.

Agents are lightweight objects with a model, instructions, and tools. Handoffs let one agent transfer a conversation to another (typed and structured, not free-form). Guardrails are input/output validation that short-circuit on policy violations. Sessions provide memory. Tracing is first-class — every agent run emits a structured trace that you can view in the OpenAI traces UI or export via OpenTelemetry.

Unlike heavier frameworks, the Agents SDK is explicitly minimal: it does not try to be a universal orchestration layer. It is designed to work best with OpenAI and OpenAI-compatible models, and it plays cleanly with other OpenAI surfaces (Responses API, Realtime API, Assistants).

MIT-licensed, officially supported, and rapidly gaining adoption as the canonical "official" Python agent framework for teams already on OpenAI.', 'https://github.com/openai/openai-agents-python', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full SDK","Tracing integration","Guardrails","Handoffs"]}]'::jsonb, 'intermediate', true, '{"api"}', '{"Minimal Agent / Handoff / Guardrail primitives","Typed handoffs between agents","Input / output guardrails","First-class tracing with OpenAI traces UI","Sessions for memory","Works with Responses API and Realtime API","OpenTelemetry export","Python-first, lightweight","Works with OpenAI-compatible endpoints"}', '{"OpenAI","Azure OpenAI","OpenAI-compatible endpoints","OpenTelemetry"}', true, '{"Teams already committed to OpenAI as primary provider","Developers preferring minimal, official tooling","Production workloads needing built-in tracing and guardrails"}', '{"Teams needing strong cross-provider support (LiteLLM / LangGraph are broader)","Workloads requiring durable workflows (LangGraph is deeper)","Non-Python environments (TypeScript SDK is a separate, lighter project)"}', 'OpenAI''s official agent framework. The right default if you are OpenAI-first and want the smallest framework that does the job.', '{"https://openai.github.io/openai-agents-python/quickstart/"}', 'Designed around OpenAI; works with other providers but without some features (tracing quality, Realtime integration). No durable-runtime story — agents are stateless between runs unless you wire persistence yourself. Smaller than LangGraph in scope — you will bring your own memory, evals, and deployment tooling.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Build a multi-agent customer-service system with typed handoffs between triage, billing, and tech support agents.","Add input/output guardrails to an existing agent to reject out-of-policy requests.","Instrument an agent run with tracing visible in the OpenAI dashboard for debugging.","Prototype a voice agent by combining the Agents SDK with the Realtime API."}', 'Sweet spot: a team standardised on OpenAI, building agents, and wanting an official SDK with the least possible framework tax. The Agents SDK gives you exactly what you need — lightweight primitives, solid tracing, typed handoffs — and nothing you don''t. Pair it with the Responses API and Realtime API and you have a tight OpenAI-native stack.

Failure modes. If you rely on non-OpenAI providers as first-class citizens, the Agents SDK works but without the same feature polish — tracing is less rich, some features assume OpenAI semantics. For durable long-running workflows with branches, resumes, and scheduled runs, LangGraph is still deeper. And it is genuinely minimal — which means you will build your own evals, your own memory, your own observability around it as you scale.

What to pilot. Rebuild one agent you currently run on LangChain or a custom framework using the OpenAI Agents SDK. Compare lines of code, trace quality, and readability. If the simpler framework is enough for your needs, commit — the operational savings of running fewer dependencies add up. If you find yourself re-adding LangGraph-shaped features, stay with LangGraph.', now()),
('DeepAgents', 'deepagents', 'LangChain open-source library for building deep research agents that plan, execute, and synthesise.', 'DeepAgents is a LangChain-maintained library for building "deep" research agents — agents that decompose a complex question into sub-tasks, research each sub-task in parallel, and synthesise the results into a long-form, citation-backed answer. It is the open-source answer to commercial deep-research products (OpenAI Deep Research, Perplexity Pro).

The architecture, built on top of LangGraph, pairs a planner agent that produces a research plan with a research sub-agent spawned per sub-task, each with its own context and tool access. Results are merged and handed to a synthesis agent that writes the final report. Tools are pluggable — web search (Tavily, Exa, Brave), file search, code execution, custom APIs.

DeepAgents is under rapid development and ships opinionated defaults: a Tavily-first search stack, GPT-4o-class recommended models, and preset prompts that produce reports in the 1,500-3,000-word range with inline citations. Teams have used it to reproduce a "Perplexity Pro / Deep Research"-style feature in their own products for a fraction of the API cost.

MIT-licensed, maintained by the LangChain team, and designed to be extended rather than used as-is. It is a strong starting point for any team building research-assistant features.', 'https://github.com/langchain-ai/deepagents', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full library","Planner + researcher + synthesiser","Default search stack"]}]'::jsonb, 'advanced', false, '{"api"}', '{"Plan → research → synthesise agent pattern","Parallel sub-task research","Pluggable tools (Tavily, Exa, Brave, custom)","Long-form answer synthesis with citations","Built on LangGraph","Model-agnostic (tested on GPT-4o / Claude Sonnet)","Extendable prompts and agent roles","MIT licence"}', '{"LangGraph","LangChain","Tavily","Exa","Brave Search","OpenAI","Anthropic"}', true, '{"Teams building research-assistant features","Product builders reproducing Deep Research / Perplexity Pro","Researchers exploring agent-planning patterns"}', '{"Simple Q&A use cases (overkill)","Non-Python teams","Workloads where real-time response latency matters (reports take minutes)"}', 'The best open-source starting point for Deep Research-style features. Opinionated defaults get you 80% of the way; the rest is domain customisation.', '{"https://github.com/langchain-ai/deepagents#readme"}', 'Cost per report is non-trivial — GPT-4o-class models on multi-step research plans regularly hit $0.50–$2 per run. Quality depends heavily on search tool quality; cheap search yields thin reports. Wall-time for a report is minutes, not seconds. Newer library with fewer production case studies than LangGraph itself.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ship a Deep Research-style feature in your own product with citations and multi-step planning.","Research competitive landscapes by spawning sub-agents per competitor.","Generate long-form market analyses from a short prompt and a set of internal documents.","Prototype a legal or medical research assistant over your curated sources."}', 'Sweet spot: a product team that wants a "Deep Research"-style feature without building the planner / researcher / synthesiser scaffolding from scratch. DeepAgents packages the pattern competently and lets you focus on tools and prompts — which is where product differentiation actually happens. Reproducing Perplexity Pro''s UX in your own app is a one-weekend project with this library plus Tavily.

Failure modes. The cost profile is surprising at first — a multi-step research plan with 5 sub-agents and a synthesiser is easily 20+ LLM calls. Without caching and smart model selection (cheap planner, expensive synthesiser), your per-report spend is punitive. Quality also depends on your search tool — Tavily is good, but your real moat is a better (domain-specific) retrieval layer.

What to pilot. Generate 10 real research reports on topics where you have expertise. Read them critically. Count citation accuracy, synthesis quality, and hallucinations. If 7+ are genuinely useful, DeepAgents is a strong foundation — now invest in your tools and prompts to hit 9+. If fewer than 5 are useful, the gap is probably model or search; fix those before evaluating the framework again.', now()),
('RAGFlow', 'ragflow', 'Open-source RAG engine built around deep document parsing — tables, figures, complex layouts.', 'RAGFlow is an open-source, end-to-end RAG engine from InfiniFlow. Its differentiator is document parsing: it uses a custom deep-layout model (DeepDoc) to extract structure from complex documents — tables with merged cells, figures, multi-column layouts, forms — where naive PDF loaders produce garbage. Output is a structured representation that preserves table relationships, heading hierarchy, and figure context, which downstream retrieval can exploit.

Beyond parsing, RAGFlow ships a full RAG stack: chunking strategies per document type, keyword + vector + rerank hybrid retrieval, knowledge graph generation over a corpus, an agent builder, and a chat UI. It runs as a single Docker-compose deployment (Elasticsearch or Infinity as the backend, MinIO for files, Redis for caching, MySQL for metadata).

The project has grown rapidly among teams that found LangChain / LlamaIndex''s parsing insufficient for their document types — legal contracts, financial reports, medical charts. It is self-hostable, Apache-2-licensed, and has an active dev community.

A companion hosted version exists but the self-hosted path is where most serious adoption happens because the parsing pipeline is compute-heavy and data-sensitive.', 'https://ragflow.io', 'freemium', '[{"plan":"Open Source","price":"Free (Apache 2.0)","features":["Full engine (Docker compose)","DeepDoc parsing","All retrieval + agent features"]},{"plan":"Hosted","price":"From $99/mo","features":["Managed infrastructure","Team workspaces","Priority support"]}]'::jsonb, 'advanced', true, '{"web","api"}', '{"DeepDoc deep-layout parsing (tables, figures, forms)","Hybrid retrieval: keyword + vector + rerank","Knowledge graph generation","Chunking strategies per document type","Chat UI with citation inline","Agent builder","Multi-tenant workspaces","Docker Compose deployment","Elasticsearch / Infinity as backend"}', '{"Elasticsearch","Infinity","MinIO","Redis","MySQL","OpenAI","Anthropic","Ollama","HuggingFace"}', true, '{"Teams with complex document types (legal, finance, medical)","Enterprises self-hosting RAG","Researchers needing quality parsing for experiments"}', '{"Simple RAG over plain-text docs (overkill)","Teams without Docker / ops capacity","Applications needing millisecond query latency"}', 'The best open-source engine for RAG over messy real-world documents. If PDF quality is your bottleneck, this is the intervention to try.', '{"https://ragflow.io/docs/dev/quickstart"}', 'Infrastructure footprint is substantial (multiple services). Initial ingestion of large document sets is slow because DeepDoc is compute-heavy. Agent builder is newer than the retrieval stack and less polished. Some documentation is translated from Chinese and occasionally rough; community support is strongest in the Chinese-speaking ecosystem.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ingest a corpus of scanned contracts with tables and produce a RAG chatbot that cites the exact clause.","Build a financial-report QA system that preserves table structure in answers.","Self-host a privacy-sensitive RAG deployment for healthcare documents.","Generate a knowledge graph over a technical manual and answer questions using it."}', 'Sweet spot: a team whose RAG quality is being capped by document parsing — they are ingesting complex PDFs and the answers are thin because the tables and figures are mangled. RAGFlow''s DeepDoc is the most credible open alternative to commercial parsing services (LlamaParse, Reducto, Unstructured) and, self-hosted, keeps the data in your environment.

Failure modes. Deployment is a real project — five services, a database, storage, and non-trivial config. If your docs are clean HTML or plain-text, this is overkill and LlamaIndex with a basic loader is simpler. The agent builder is serviceable but lags dedicated agent frameworks. And the Chinese-language heritage shows in some docs; expect to read between the lines occasionally.

What to pilot. Take ten of your worst-performing PDFs — ones where current answers are thin or wrong. Ingest them into RAGFlow and ask the same ten questions you have been asking. If answer quality lifts meaningfully (especially on table / figure questions), commit to the infrastructure investment. If the parsing is only marginally better, the bottleneck is elsewhere and a lighter stack is fine.', now()),
('Dify', 'dify', 'Open-source LLMOps platform — build, deploy, and operate LLM applications from a visual workflow editor.', 'Dify is an open-source platform for building LLM applications without writing much code. Its core is a visual workflow editor (similar in spirit to Langflow) combined with a full LLMOps layer: dataset management, prompt versioning, model routing, agent builder, tool marketplace, deployment as a hosted chat UI or API, logs, and per-application analytics.

It positions itself as the platform-of-platforms — a small team can run Dify self-hosted and give many business users the ability to build their own LLM apps inside it, while engineering controls the underlying model configs, secrets, and governance. It supports role-based access control, SSO on paid tiers, and multi-workspace isolation.

Dify ships with a rich app-template library: customer support chatbots, SQL assistants, document summarisers, workflow automations. Each app is deployable as a standalone chat UI (embeddable iframe or hosted URL) or via REST API. A Model Context Protocol (MCP) bridge lets Dify apps call MCP servers as tools.

Apache-2-licensed (with a small SSO / branding carve-out), deployable via Docker Compose or Kubernetes, and widely adopted in the Chinese AI developer community with growing traction globally.', 'https://dify.ai', 'freemium', '[{"plan":"Community","price":"Free (Apache 2.0 + carve-out)","features":["Self-hosted","All core workflows","Unlimited apps","Basic logs"]},{"plan":"Sandbox","price":"Free","features":["Hosted cloud","200 runs/mo","Single workspace"]},{"plan":"Professional","price":"$59/mo","features":["5,000 runs/mo","3 workspaces","Team collaboration"]},{"plan":"Team","price":"$159/mo","features":["50,000 runs/mo","SSO","Priority support"]}]'::jsonb, 'beginner', true, '{"web","api"}', '{"Visual workflow editor","Agent builder with tools","Dataset management and RAG","Prompt versioning and A/B testing","Model-agnostic routing","App templates library","Deploy as chat UI or REST API","Role-based access control","Self-hosted (Docker / K8s) or cloud","MCP bridge for tool calling"}', '{"OpenAI","Anthropic","Gemini","Azure OpenAI","Ollama","Pinecone","Weaviate","Chroma","Qdrant","Notion","Slack"}', true, '{"Teams giving business users self-serve AI-app building","Startups shipping multiple LLM features quickly","Agencies deploying AI apps for clients"}', '{"Hardcore engineering teams (code-first is faster)","Applications needing deep programmatic customisation","Environments with strict Apache-2.0-only OSS policies (check the carve-out)"}', 'The most complete self-hosted LLMOps platform for teams that want a visual builder plus deployment in one package. Serious competitor to commercial Copilot Studio / Retool AI products.', '{"https://docs.dify.ai/getting-started/readme"}', 'Community edition has SSO and branding restrictions — read the license carefully before enterprise deployment. UI has grown complex; onboarding non-technical users still requires a training session. Workflow debugging is serviceable but less transparent than code. Community support is strongest in Chinese.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Ship a customer-facing chat assistant with RAG over company docs without writing application code.","Give business users a self-serve builder for internal AI tools, governed by engineering.","Prototype and deploy five AI features in a week as an agency using the template library.","Replace a patchwork of ChatGPT links and no-code tools with one governed platform."}', 'Sweet spot: a small-to-mid-size company or agency that wants to ship multiple LLM applications to different audiences (internal, customer-facing, client deliverables) without spinning up a custom frontend each time. Dify handles the build-deploy-operate loop competently, and the template library gets you 70% of the way on most common patterns.

Failure modes. Engineering teams who prefer code will find the visual metaphor slower for complex logic — at some point, Python + LangGraph is cleaner. The community-edition licence carves out SSO and branding, which matters at enterprise scale; read it before you build against free features that are not actually free in a commercial context. And the UI, while capable, is dense — expect a real ramp-up for non-technical users.

What to pilot. Pick three distinct AI app ideas you have been holding off on. Try to build all three in Dify in one week. If the visual builder hits the wall on any of them (custom logic, weird data source, tricky state), note where — those boundaries tell you whether Dify is your platform or just a prototyping tool.', now()),
('FastGPT', 'fastgpt', 'Open-source knowledge-base Q&A and workflow platform — self-hosted RAG with visual flow builder.', 'FastGPT is an open-source AI knowledge-base platform from the Chinese AI community that has become one of the most popular self-hosted RAG solutions globally. It combines a document-ingestion pipeline, a hybrid retrieval engine, a visual flow builder (Flow), and a chat UI into a single self-hostable application.

The workflow editor is the differentiator. Unlike simpler chat-over-docs tools, FastGPT lets you build multi-step flows with branches, LLM nodes, knowledge-base queries, HTTP requests, code execution, and tool calls. The visual editor is polished and handles fairly complex flows — you can ship a production agent entirely from the UI.

Document ingestion supports PDFs, Word docs, Markdown, CSVs, URLs, and API endpoints. Chunking is configurable and there is a decent out-of-the-box quality. Models are fully pluggable through OpenAI-compatible endpoints or a bundled adapter layer.

Apache-2-licensed, deployable via Docker Compose, and a popular pick for self-hosted RAG in 2025-2026. A hosted cloud version is offered but most serious users run it themselves.', 'https://fastgpt.io', 'freemium', '[{"plan":"Open Source","price":"Free (Apache 2.0)","features":["Full app (Docker Compose)","Unlimited knowledge bases","All workflow features"]},{"plan":"Cloud","price":"From $9/mo","features":["Hosted","Managed backups","Team workspaces"]}]'::jsonb, 'beginner', true, '{"web","api"}', '{"Visual workflow editor with branches","Knowledge-base management with hybrid retrieval","Chat UI with streaming and citations","Multi-format document ingestion","OpenAI-compatible model adapters","API keys and embed codes","Team workspaces","Audit logs","Self-hosted via Docker Compose"}', '{"OpenAI","Anthropic","Azure OpenAI","Ollama","OpenAI-compatible endpoints","MongoDB","PostgreSQL","Milvus"}', true, '{"Individuals or teams self-hosting a RAG app","Non-engineers wanting visual agent building","Agencies deploying per-client knowledge bases"}', '{"Engineering teams committed to code-first (LangGraph / LlamaIndex are stronger)","Environments with heavy non-PDF document types (RAGFlow is deeper)","Strict-governance enterprises needing deep audit / SSO"}', 'The easiest path to a self-hosted knowledge-base agent with a visual flow editor. Lightweight, polished, and production-ready for small to mid-size deployments.', '{"https://doc.fastgpt.io/docs/intro"}', 'Documentation has improved but some content is translated from Chinese and occasionally terse. Advanced retrieval tuning (reranking configs, chunk boundaries) is less exposed than in code-first frameworks. Hosted cloud tier is primarily aimed at Chinese customers; self-host is the default for most Western users.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Self-host an internal knowledge-base chatbot over a company wiki in one afternoon.","Build a multi-step lead-qualification flow where an agent queries a KB and calls an HTTP endpoint.","Deploy per-client RAG apps as an agency from a shared FastGPT instance.","Embed a product-support assistant into a marketing site via iframe."}', 'Sweet spot: a small team or solo developer who wants a polished, self-hostable alternative to commercial RAG tools and is comfortable with Docker. FastGPT''s flow builder is genuinely usable and the knowledge-base ingestion pipeline produces good defaults. For a one-afternoon internal Q&A bot, it is probably the single fastest starting point in open source.

Failure modes. For deep governance and enterprise scale (audit, SSO, per-document ACLs), it is lighter than commercial alternatives. Advanced retrieval quality ceilings are lower than dedicated engines like RAGFlow. And as an import from the Chinese ecosystem, some docs require patience — community support is primarily on Chinese-language channels.

What to pilot. Ingest one knowledge base you care about (internal wiki, product docs, personal notes). Ask twenty real questions you''d like answered. Measure: answer correctness, citation accuracy, flow editor ergonomics. If the out-of-the-box quality gets you to 16+ correct, FastGPT is the right pick for that scale. If you hit the retrieval ceiling, graduate to RAGFlow or a code-first stack.', now()),
('Langfuse', 'langfuse', 'Open-source LLM observability platform — traces, evals, prompts, datasets for production agents.', 'Langfuse is the open-source observability and experimentation platform for LLM applications. It provides structured tracing of every LLM call (inputs, outputs, tokens, cost, latency), conversation-level session views, prompt management with versioning, evaluations (LLM-as-judge, user feedback, heuristic), datasets for regression testing, and user-level analytics.

Integration is dead simple: wrap your LLM calls with a Langfuse decorator (Python / TS / Langchain / LlamaIndex / LiteLLM integrations), and traces appear in the dashboard. For agents built in LangGraph / AutoGen / the OpenAI Agents SDK, dedicated integrations capture the hierarchical step structure automatically.

Self-hosting is first-class — the entire platform runs in Docker Compose, including Postgres + ClickHouse + Redis. The managed cloud version has free (50k events/month) and paid tiers. Enterprise offers SSO, audit logs, regional data residency, and priority support.

It is MIT-licensed, has become a de facto standard for LLM observability in open-source stacks (alongside Helicone and Arize Phoenix), and is used in production by hundreds of companies.', 'https://langfuse.com', 'freemium', '[{"plan":"Self-hosted (Open Source)","price":"Free (MIT)","features":["Full platform","Unlimited events","All integrations"]},{"plan":"Hobby","price":"Free","features":["50k events/mo","1 project","Basic support"]},{"plan":"Pro","price":"$59/mo","features":["100k events/mo","Unlimited projects","Evals","Datasets"]},{"plan":"Team","price":"$499/mo","features":["Unlimited events","SSO","Priority support"]}]'::jsonb, 'intermediate', true, '{"web","api"}', '{"Structured LLM call tracing","Session and user views","Prompt management with versioning","LLM-as-judge evals","User-feedback capture","Dataset management and regression tests","Cost and token tracking per user / project","Integrations for LangChain, LlamaIndex, OpenAI SDK, LangGraph, LiteLLM","Self-hosted or cloud","OpenTelemetry compatible"}', '{"OpenAI","Anthropic","Gemini","LangChain","LlamaIndex","LangGraph","LiteLLM","OpenAI Agents SDK","OpenTelemetry","Vercel AI SDK"}', true, '{"Teams running production LLM applications","Engineers debugging agent behaviour","Product teams measuring quality across prompt changes"}', '{"Applications still in single-developer prototype phase","Teams already on Helicone / Arize / Braintrust","Environments where cloud-hosted observability is a compliance block (self-host instead)"}', 'The strongest open-source LLM observability platform in 2026. If you ship LLM features in production, this is the first instrumentation to add.', '{"https://langfuse.com/docs/get-started"}', 'Self-hosting requires real ops discipline — ClickHouse is not a set-and-forget database. Evals are good but less deep than dedicated eval platforms like Braintrust. High-volume workloads may need to sample traces to keep costs manageable. Cloud pricing jumps sharply above the Pro tier.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Debug a production agent''s unexpected behaviour by replaying the exact trace in the Langfuse UI.","Compare two prompt versions on a dataset of 100 real conversations and pick the winner.","Wire LLM-as-judge evals into CI to catch quality regressions before shipping a prompt change.","Track per-user LLM cost in a multi-tenant SaaS and bill accurately."}', 'Sweet spot: any team that has an LLM application in production and is currently debugging it with print statements. Langfuse compresses three separate needs — tracing, evals, prompt management — into one platform, and the self-host option keeps it within reach for security-sensitive environments. The Python / TS SDKs and integration adapters mean wiring it in is usually a single afternoon of work.

Failure modes. As your trace volume grows, self-hosting becomes a real ops commitment — ClickHouse tuning, backups, disaster recovery. Evals are serviceable but the depth of a dedicated eval platform (Braintrust, Promptfoo) is real if evaluation is your focus. And on very high-volume workloads (millions of traces / day), cloud pricing gets aggressive — sample or self-host.

What to pilot. Wire Langfuse into one production agent for one week. Look at traces of real user sessions. If, at the end of the week, you have found at least one real bug you would have missed otherwise, it has earned its place. If the traces surface nothing actionable, either your app is already well-tested or you need to dig into evals rather than tracing — pick your next investment accordingly.', now()),
('Promptfoo', 'promptfoo', 'Open-source CLI / library for testing and evaluating LLM prompts and agents at scale.', 'Promptfoo is a developer-first evaluation framework for LLM applications. Its primary interface is a CLI and a YAML / TS config file: you declare a set of prompts, a set of test cases (with input variables and expected assertions), and a set of providers to run them against. Promptfoo runs everything in parallel and produces a diffable report you can compare across commits.

The assertions library is comprehensive — equality, contains, regex, semantic-similarity, LLM-as-judge, classifier, factual consistency, latency budgets. You can define custom assertions as TypeScript / Python functions. Providers include every major LLM and custom HTTP endpoints.

Beyond evaluations, Promptfoo also supports red-teaming: adversarial prompt generation, jailbreak detection, and a catalog of canonical attack patterns to test an agent against. This has made it a common pick in security-conscious AI teams.

MIT-licensed, installable via npm / pip, and has a growing ecosystem. The maintainers offer a paid enterprise tier (promptfoo.dev) with team features, a cloud UI, and managed red-team runs, but the CLI and OSS features are sufficient for most teams.', 'https://www.promptfoo.dev', 'freemium', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full CLI","All assertions","Red-team basics"]},{"plan":"Enterprise","price":"Contact sales","features":["Cloud dashboard","Team runs","Managed red-teaming","SSO"]}]'::jsonb, 'intermediate', true, '{"cli","api"}', '{"YAML / TS prompt test configs","Comprehensive assertion library","LLM-as-judge and classifier evals","Red-teaming and adversarial prompts","Parallel execution across providers","Diffable reports per commit","Custom assertions in TS / Python","CI integration","Dataset imports"}', '{"OpenAI","Anthropic","Gemini","HuggingFace","OpenAI-compatible endpoints","GitHub Actions","GitLab CI"}', true, '{"Engineering teams testing prompts in CI","AI security teams red-teaming agents","Prompt engineers iterating with real test cases"}', '{"Teams needing a hosted UI-first eval platform (Braintrust is smoother)","Non-developer prompt writers","Workloads preferring observability over offline eval (Langfuse fits better)"}', 'The strongest developer-first eval framework in open source. Perfect for CI-gated prompt changes and red-teaming.', '{"https://www.promptfoo.dev/docs/getting-started/"}', 'CLI-first and YAML-heavy — not beginner-friendly. LLM-as-judge costs compound fast on large test suites; budget carefully. Red-teaming features are useful but still no substitute for professional security review. Enterprise pricing is opaque.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Block a prompt change in CI if semantic similarity on 50 test cases drops below threshold.","Red-team an agent with 30 canonical jailbreak patterns before launching a public feature.","Compare GPT-4o vs Claude Sonnet on your actual test suite and pick the winner by measurable metrics.","Prevent regressions in a prompt by tying every merge to a passing Promptfoo run."}', 'Sweet spot: an engineering team that treats prompts and agent configs as code and wants the same CI-gated discipline they use for application code. Promptfoo fits exactly there — YAML configs live in the repo, assertions are precise, reports are diffable, and a GitHub Action can block regressions automatically. For teams shipping prompt changes weekly, it pays for itself the first time it catches a regression.

Failure modes. It is not a hosted dashboard for non-developers — if the person iterating on prompts is not comfortable editing YAML in a repo, Braintrust or a hosted alternative will frustrate them less. LLM-as-judge evals are expensive at scale; keep test suites focused and sample aggressively. Red-teaming features are real but defence-in-depth — pair with human security review for high-stakes launches.

What to pilot. Pick one production prompt you have recently regressed on. Write 20 Promptfoo test cases covering the regressions and the golden paths. Wire Promptfoo into CI. Next time someone edits the prompt, check whether the CI run catches expected failures before merge. If yes, expand the test suite; if no, the assertions need work before you can trust the harness.', now()),
('GraphRAG', 'graphrag', 'Microsoft Research framework for knowledge-graph-enhanced retrieval — entities, relationships, community summaries.', 'GraphRAG is Microsoft Research''s open-source framework that augments RAG with an automatically-constructed knowledge graph. Instead of retrieving flat chunks by semantic similarity, GraphRAG extracts entities and relationships from the source corpus during ingestion, clusters them into "communities" at multiple hierarchical levels, and generates community summaries. Queries then retrieve at the appropriate level of abstraction — specific chunks for fact questions, community summaries for thematic questions.

The academic motivation: on corpora where the value is in connections across many documents (a long novel, a set of meeting transcripts, an issue tracker), flat semantic retrieval fails because no single chunk has the thematic answer. Community summaries give the model that thematic layer explicitly. The accompanying paper shows meaningful gains on summarisation-style questions over long-form corpora.

GraphRAG is released as a Python package and a self-hostable pipeline. It is ingestion-heavy: a full index build on a medium corpus is minutes to hours and costs real money (tens to hundreds of dollars in LLM calls for the extraction and summary phases). Query-time is fast. The output is persisted as a set of parquet files you can query offline.

MIT-licensed, actively maintained, and a notable reference implementation of the "graph-enhanced RAG" design pattern. A commercial hosted version exists via Azure AI Search.', 'https://microsoft.github.io/graphrag/', 'free', '[{"plan":"Open Source","price":"Free (MIT)","features":["Full pipeline","Global and local search","Multi-level community summaries"]}]'::jsonb, 'advanced', false, '{"cli","api"}', '{"Automatic entity / relationship extraction","Hierarchical community clustering","Community summaries per level","Global search (thematic) and local search (specific)","Parquet-based persistence","Configurable extraction prompts","Model-agnostic","Paper-backed design"}', '{"OpenAI","Azure OpenAI","Gemini","Anthropic"}', true, '{"Researchers building over long, thematically-rich corpora","Teams with cross-document questions (novels, transcripts)","Analysts running thematic QA over internal docs"}', '{"Simple fact-lookup RAG (overkill, expensive)","Frequently-changing corpora (re-indexing is expensive)","Teams without Python + LLM-ops capacity"}', 'The reference implementation for graph-enhanced RAG. Remarkable on thematic queries over long corpora; expensive to build and maintain.', '{"https://microsoft.github.io/graphrag/get_started/"}', 'Index-build cost and wall-time are significant (tens-to-hundreds of dollars on medium corpora, hours of runtime). Incremental updates are possible but clunky — frequent changes mean frequent reindexing. Quality depends heavily on extraction prompts and source data quality. Not production-optimised out of the box.', '{}', '{"reddit_threads":[]}'::jsonb, '{"Answer thematic questions over a long novel or transcript corpus that flat RAG cannot summarise.","Extract the entity graph from a set of meeting notes to map stakeholder relationships.","Compare GraphRAG vs standard RAG on a cross-document QA benchmark from your own data.","Build a research agent that uses community summaries for broad questions and flat chunks for specifics."}', 'Sweet spot: a team working with a corpus where the interesting questions are thematic, not factual — "what are the main themes in this novel?", "what are the unresolved issues in this ticket backlog?", "how do these concepts connect?" GraphRAG''s community-summaries layer genuinely changes what RAG can answer on this class of query. For research labs, narrative analytics, and long-document QA, the improvement is real.

Failure modes. For plain factual lookup, GraphRAG is expensive overkill — vanilla RAG will be cheaper and just as good. The cost structure surprises people: index builds are orders of magnitude more expensive than simple embeddings, and frequent corpus changes multiply that cost. Production deployment still requires significant engineering — out of the box, GraphRAG is a research pipeline, not a hosted service.

What to pilot. Pick one question that flat RAG cannot answer well on your corpus — something like "what are the three main themes in this collection?" Build the GraphRAG index and ask that question. If the answer is qualitatively better than what your existing RAG produces, the investment is justified for thematic questions. If the answer is similar or worse, the corpus may not benefit from graph structure and you should stay with flat retrieval.', now())
ON CONFLICT (slug) DO NOTHING;

-- Category assignments
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'langflow' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'langflow' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'langgraph' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'langgraph' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'smolagents' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'smolagents' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'semantic-kernel' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'semantic-kernel' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'metagpt' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'metagpt' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'openhands' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'openhands' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'llama-index' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'llama-index' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'litellm' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'haystack' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'haystack' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mastra' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'mastra' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'letta' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'letta' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'guidance' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'openai-agents-python' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'openai-agents-python' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'deepagents' AND c.slug = 'research-education' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'deepagents' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ragflow' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'ragflow' AND c.slug = 'productivity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'dify' AND c.slug = 'automation-agents' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'dify' AND c.slug = 'productivity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'fastgpt' AND c.slug = 'productivity' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'fastgpt' AND c.slug = 'customer-support' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'langfuse' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'langfuse' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'promptfoo' AND c.slug = 'code-development' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'promptfoo' AND c.slug = 'security-privacy' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'graphrag' AND c.slug = 'data-analytics' ON CONFLICT DO NOTHING;
INSERT INTO tool_categories (tool_id, category_id) SELECT t.id, c.id FROM tools t, categories c WHERE t.slug = 'graphrag' AND c.slug = 'research-education' ON CONFLICT DO NOTHING;
