-- Step 42 editorial compare: fathom-vs-grain-vs-gong
-- Three-way AI meeting / sales-call intelligence shootout. The real fork is
-- org size: solo / SMB rep = Fathom free, 5-100-rep sales team = Grain
-- (Gong-lite at $15/seat/mo), 200+ reps with RevOps = Gong. Listicles bury
-- this in feature tables; we lead with it.

INSERT INTO tool_comparisons
  (tool_ids, slug, tldr, verdict, feature_analysis, pricing_analysis,
   use_cases, benchmarks, faqs, is_editorial, published_at, last_reviewed_at, view_count)
VALUES (
  ARRAY[
    (SELECT id FROM tools WHERE slug = $body0$fathom$body0$),
    (SELECT id FROM tools WHERE slug = $body1$grain$body1$),
    (SELECT id FROM tools WHERE slug = $body2$gong$body2$)
  ],
  $body3$fathom-vs-grain-vs-gong$body3$,
  $body4$[
    {"dimension":"Best for","values":{"fathom":"Solo founders, SMB AEs, individual reps who want a free recorder + AI notes","grain":"5-100-rep sales teams who need clip-shareable knowledge libraries and light deal coaching","gong":"200+ rep orgs with RevOps, forecasting, and enterprise procurement"}},
    {"dimension":"Pricing floor (paid)","values":{"fathom":"$19/seat/mo Premium (Team Edition $29/seat/mo)","grain":"$15/seat/mo Business (billed annually)","gong":"Contact sales — public estimates $1,200-1,600/seat/year + platform fee"}},
    {"dimension":"Free tier","values":{"fathom":"Unlimited recording + AI summary on free plan (the headline draw)","grain":"Free plan: 20 meetings/mo, basic AI notes, no clip library","gong":"None — sales-led only, no self-serve free tier"}},
    {"dimension":"Conversation intelligence depth","values":{"fathom":"Recording, transcript, AI summary, action items — light by design","grain":"AI notes, smart tags, deal scorecards, coaching playlists — Gong-lite","gong":"Deep: deal scoring, forecasting, market intelligence, AI agents, win/loss"}},
    {"dimension":"Best org size","values":{"fathom":"1-5 seats (or unlimited free for solo)","grain":"5-100 seats (sweet spot 10-50)","gong":"100+ seats (procurement minimums make smaller deals impractical)"}},
    {"dimension":"CRM integration","values":{"fathom":"Salesforce + HubSpot auto-logging (Team Edition); Slack, Notion, Linear","grain":"Salesforce, HubSpot, Pipedrive, Close, Slack, Notion — bidirectional sync","gong":"Salesforce-native, HubSpot, Microsoft Dynamics, Outreach, Salesloft — deep two-way"}},
    {"dimension":"SSO + SOC 2","values":{"fathom":"SOC 2 Type II; SAML SSO on Team Edition","grain":"SOC 2 Type II; SAML SSO on Business and Enterprise","gong":"SOC 2 Type II, ISO 27001, GDPR, HIPAA-ready, SAML/SCIM, regional data residency"}},
    {"dimension":"Coaching / forecasting","values":{"fathom":"None (it is a recorder, not a CI platform)","grain":"Coaching playlists + scorecards; basic deal hygiene flags; no forecast model","gong":"Full forecast engine, deal warnings, rep scorecards, market intelligence"}}
  ]$body4$::jsonb,
  $body5$Pick by org size, not feature checklist. Solo founders and SMB reps should run Fathom — the free tier is genuinely unlimited and the AI summary is best-in-class for the price. Sales teams of 5-100 reps should run Grain at $15/seat/mo, which gives you 80% of Gong's coaching and clip-library value at roughly 1/8th the seat cost. Only at 200+ reps with a dedicated RevOps function does Gong's deal scoring, forecasting and market intelligence justify its $1,200-1,600/seat/year price tag and procurement overhead.$body5$,
  $body6$The hardest thing about choosing between Fathom, Grain, and Gong in 2026 is that listicles compare them as if they are the same product. They are not. Fathom is a free meeting recorder with AI notes. Grain is a meeting-clip-and-coaching platform priced for SMB sales teams. Gong is enterprise revenue intelligence with a forecasting model, AI agents, and a procurement cycle measured in months. Putting them in a feature grid implies they are interchangeable; they are not, and the right answer is almost entirely a function of how big your sales team is and whether you have a RevOps lead.

This page leads with that fork because it is the decision the SERP buries. If you read five "best AI meeting tool 2026" listicles, you will see the same feature checkboxes (recording, transcription, summary, CRM sync) appear under all three tools, with Gong winning on more rows by virtue of being more expensive. That comparison is not wrong, but it is misleading — Gong wins those rows because it is built for a buyer who will pay $250,000 a year, and the SMB rep reading the listicle will conclude they should buy Gong when in fact they should download [Fathom](/tools/fathom) and ship the day's first call.

**What each is optimized for**

[Fathom](/tools/fathom) is optimized for the solo or small-team rep who does not want to think about a meeting tool. The free plan is unlimited recording with AI summaries — no per-month meeting cap, no transcript paywall, no watermark. That is the headline draw and it is genuinely true as of April 2026. Fathom monetizes through Team Edition (Salesforce/HubSpot auto-logging, shared workspaces, admin controls) at $29/seat/mo and a Premium individual tier at $19/seat/mo that adds longer retention and AI Action Items. The product philosophy is "keep it boring, keep it fast" — which is why a single founder doing twenty customer interviews a month uses Fathom and never hits a wall.

[Grain](/tools/grain) sits in the middle. It is built for the 5-100-rep sales team that has outgrown a free recorder but cannot stomach Gong's price or procurement cycle. Grain Business at $15/seat/mo (billed annually) gives you AI notes, smart tags, deal scorecards, coaching playlists, and a searchable clip library — which is the killer feature for SMB sales: every rep can clip a 45-second objection-handling moment from a discovery call and drop it into Slack or a Notion playbook. Grain calls itself "Gong-lite" in conversations with prospects, and that is an accurate framing. It is consciously not trying to be a forecast engine.

[Gong](/tools/gong) is the only one of the three that is truly enterprise revenue intelligence. It is sales-led, contact-only pricing, and a multi-stakeholder procurement process. What you actually buy is the deal-scoring and forecasting engine, the market-intelligence layer (Gong correlates language across thousands of deals to flag risks before they show up in the pipeline), and increasingly the AI agents that draft follow-ups, surface coaching moments, and update CRM records autonomously. The seat price (public estimates $1,200-1,600/seat/year, frequently with a platform fee on top) means Gong is impractical below roughly 100 seats — and the procurement minimums many resellers report make it functionally unavailable below 50.

**Where Fathom wins cleanly**

If you are a solo founder, an early-stage AE on a team without a defined sales process, a customer success manager handling a small book, or a consultant doing discovery calls, Fathom is the right answer and the other two are wrong. The reasons are concrete. First, the free tier is unlimited recording — Grain caps free at 20 meetings per month and Gong does not have a free tier at all. Second, the AI summary quality is on par with Grain Business and noticeably tighter than Gong's stock summary (Gong's value is the analytics layer above the summary, not the summary itself). Third, Fathom Team Edition's CRM auto-logging into Salesforce and HubSpot covers 80% of what an SMB rep actually needs from a CRM-integrated meeting tool, at $29/seat/mo versus Grain's $15 plus seat scaling or Gong's five-figure annual minimum.

The honest weakness: Fathom does not have a clip-library or coaching workflow. If a sales manager wants to build a library of "great discovery moments" and assign them to new hires, Fathom is the wrong tool — that is what Grain and Gong are for. But if you are reading this and you do not have a sales manager, that limitation is irrelevant.

**Where Grain wins cleanly**

For a 5-100-rep sales team — the segment where most B2B SaaS lives — Grain is the right pick more often than the listicles admit. Three reasons. First, the clip-library is genuinely a knowledge-management primitive. Reps can clip the customer's exact words around an objection, a feature request, or a competitor mention, and drop it into a shared library that becomes the team's living playbook. Fathom does not do this. Gong does it but at 8x the per-seat cost. Second, Grain's deal scorecards and coaching playlists give a sales manager 80% of Gong's coaching workflow at $15/seat/mo, which for a 25-person team is the difference between a $4,500/year tool and a $40,000/year contract. Third, Grain's CRM integration (Salesforce, HubSpot, Pipedrive, Close, Slack, Notion) is bidirectional and covers the SMB stack better than Fathom's, which is biased toward Salesforce and HubSpot only.

The honest weakness: Grain has no forecast model and no market intelligence layer. If your CRO needs a deal-by-deal risk score that is statistically calibrated against historical win-loss data, Grain cannot produce it. That is the moat Gong has not surrendered.

**Where Gong wins cleanly**

For a 200+ rep org with a RevOps function and a CRO who is judged on forecast accuracy, Gong is the only credible pick of the three. The reasons are not the recording or the summary — those are commoditized in 2026, and Gong is at parity with Grain and Fathom on those primitives. The reasons are the analytics on top. Gong's forecast engine ingests every call, email, and CRM update across the team and produces a deal-by-deal risk score and a roll-up forecast that is calibrated against your own historical close data. The market-intelligence layer flags pricing pushback patterns, competitor mentions, and language shifts before they show up as lost deals. Gong's 2025 push into AI agents (Gong AI, then the agentic suite released throughout 2025-2026) layered autonomous follow-up drafting, coaching-moment surfacing, and CRM hygiene on top of the analytics base.

Compliance and procurement are the other half of Gong's moat. Gong publishes SOC 2 Type II, ISO 27001, GDPR, HIPAA readiness, regional data residency, SAML SSO with SCIM provisioning, and contractual data-handling commitments that pass enterprise InfoSec review. Grain has SOC 2 Type II and SAML SSO on Business and Enterprise, which clears most SMB and mid-market gates but is thinner on the regulated-industry checklist. Fathom has SOC 2 Type II and SAML SSO on Team Edition, which is enough for most SMB procurement but will not clear a Fortune 500 InfoSec review without an exception.

**Conversation intelligence depth — what "AI meeting tool" actually means at each tier**

The phrase "AI meeting tool" hides three different products. At the Fathom tier, AI means recording, transcription, a tight summary, and AI Action Items extraction (Fathom shipped this in 2025 and improved it through early 2026). At the Grain tier, AI means everything Fathom has plus smart tags that auto-classify call moments (objection, next steps, pricing, competitor), deal scorecards that grade calls against a rubric, and coaching playlists that surface recurring missed-opportunity patterns. At the Gong tier, AI means everything Grain has plus a forecast model, deal-risk scoring, market-intelligence pattern detection across the entire customer base, and the agentic layer that takes autonomous action on top of analysis.

You pay for depth. The depth is real. The question is whether you need it. A 25-rep team running Grain and a 25-rep team running Gong will close roughly the same number of deals; the Gong team will have better forecast accuracy and more granular coaching, but the Grain team will spend $36,000/year on the tool and the Gong team will spend $300,000+. For most SMB and lower-mid-market orgs, that delta is better spent on headcount.

**Compliance, SSO, and procurement — the enterprise gate**

This is the section that decides the choice for enterprise buyers regardless of feature preference. Gong is the only one of the three that publishes the full enterprise compliance stack (SOC 2 Type II, ISO 27001, GDPR, HIPAA-ready, EU/US/regional data residency, SCIM provisioning, contractual DPA terms that pass Fortune 500 review). Grain clears most mid-market gates with SOC 2 Type II and SAML SSO. Fathom clears SMB and lower-mid-market with SOC 2 Type II and SAML on Team Edition. If your buyer is a Global 2000 InfoSec team, the conversation starts and ends with Gong. If your buyer is a 200-person SaaS company, all three are viable.

**When to use which / when to graduate from one to the next**

The graduation path most companies follow: founders use Fathom on the free tier through the first ten hires. As soon as the sales team hits 5-7 reps and the manager wants a coaching workflow and a clip-library, they migrate to Grain Business at $15/seat/mo. Grain carries them through 100 reps comfortably; somewhere between 100 and 200 reps, the CRO starts losing patience with manual forecasting and a RevOps lead is hired. That is the moment Gong enters procurement. Skipping a step usually fails — buying Gong at 20 reps wastes most of the platform; staying on Fathom past 50 reps means the manager is rebuilding Grain's clip-library in Notion by hand.

For broader category context see the [business and finance category](/categories/business-finance) which houses all three tools, or the [compare hub](/compare) for adjacent shootouts. For an alternative SMB recorder we have profiled, see [Fireflies](/tools/fireflies) — it overlaps with Fathom on the free recorder positioning and is worth a look if Fathom does not fit. Decide on org size first, then on price.$body6$,
  $body7$All three publish (or estimate) seat-based pricing as of April 2026, but the structures are radically different and the listicle-style $/seat comparison hides the real cost.

**Fathom** is the cheapest of the three by a wide margin. The free plan is unlimited recording with AI summaries, AI Action Items, and basic CRM logging — no meeting cap, no transcript paywall, no watermark. Premium (individual) is $19/seat/mo billed annually ($24 month-to-month) and adds longer retention, AI Action Items at higher volume, and priority support. Team Edition is $29/seat/mo billed annually ($32 month-to-month) and adds Salesforce and HubSpot auto-logging, shared team workspaces, admin controls, SAML SSO, and DLP. The hidden gotcha: Fathom's free tier is genuinely unlimited but does not include CRM auto-logging, so a serious sales rep will move to Premium or Team Edition fast. Annualized real cost for a 5-rep team on Team Edition: ~$1,740/year.

**Grain** publishes Free (20 meetings/mo, basic AI notes), Starter at $19/seat/mo (unlimited meetings, basic CRM sync), Business at $15/seat/mo billed annually (the headline rate — this is the tier that most teams actually land on; it includes coaching, scorecards, smart tags, full CRM sync, clip-library), and Enterprise (custom — SSO, SCIM, advanced admin). Note that Business is cheaper per seat than Starter because Business is annual-only — Grain wants you on annual billing, which is the seat math gotcha. Annualized real cost for a 25-rep team on Business: ~$45,000/year. Add seats mid-contract and Grain pro-rates; remove seats and you typically wait for renewal.

**Gong** is contact-sales only and does not publish seat pricing. Public estimates from G2, customer disclosures on Reddit r/sales, and resellers in 2025-2026 put the seat price at roughly $1,200-$1,600/seat/year for the core platform, with a platform fee that varies by org size and frequently lands in the $5,000-$25,000/year range on top. Many resellers report a 50-seat practical minimum, though Gong has been more flexible at smaller volumes since 2024. The full procurement cycle for a Global 2000 buyer is typically 60-120 days. Annualized real cost for a 100-rep org: $130,000-$185,000/year, with a 3-year contract being typical.

**Hidden costs to flag**:
- Fathom: free tier does not include Salesforce/HubSpot auto-logging — budget Team Edition ($29/seat/mo) the moment you need that.
- Grain: Business is annual-only, so the $15/seat/mo headline rate locks you in for 12 months. Mid-contract seat reductions are usually deferred to renewal.
- Gong: the platform fee on top of seat pricing is the line item most buyers do not see in the proposal until late-stage. Add 10-20% to your seat-times-headcount estimate. Procurement overhead (legal, security review, integration testing) typically adds 60-100 hours of internal time on a first deal.

**If you are picking one to pay for**:
- *1-5 seats*: Fathom Free, then Fathom Team Edition when CRM auto-logging matters. Skip the others entirely.
- *5-50 seats*: Grain Business at $15/seat/mo. The clip-library and coaching scorecards earn out within the first quarter.
- *50-200 seats*: Grain Business unless you have a dedicated RevOps lead and a CRO judged on forecast accuracy. If you do, evaluate Gong — but expect a 90-day procurement.
- *200+ seats*: Gong is the default; Grain remains a credible alternative if forecasting is owned in spreadsheets and you do not need market intelligence.$body7$,
  $body8$[
    {"persona":"Solo founder doing customer interviews and discovery calls","recommendedSlug":"fathom","reasoning":"Fathom Free is unlimited recording with AI summaries and AI Action Items — there is no meeting cap, no watermark, and the summary quality is genuinely good. A solo founder running 20 customer interviews a month will never hit a wall on Fathom and the other two are overkill. If CRM auto-logging matters, upgrade to Team Edition at $29/seat/mo; otherwise stay on free indefinitely."},
    {"persona":"B2B AE on a 5-rep sales team","recommendedSlug":"grain","reasoning":"At 5 reps you have outgrown Fathom's solo positioning and you need a manager-friendly coaching workflow and clip-library. Grain Business at $15/seat/mo billed annually ($900/year per seat, $4,500/year for 5 reps) gives you smart tags, deal scorecards, and a searchable clip library that becomes the team's playbook. Gong is impractical below 50 seats."},
    {"persona":"RevOps lead at a 50-rep B2B SaaS org","recommendedSlug":"grain","reasoning":"At 50 reps Grain Business ($45,000/year) covers coaching, scorecards, clip-library, and bidirectional CRM sync — the full SMB CI stack at one-eighth Gong's likely price. Move to Gong only if forecast accuracy is on the CRO's scorecard and Grain's lack of a calibrated forecast model is causing real revenue surprises. Most 50-rep orgs do not need Gong yet."},
    {"persona":"Customer success manager handling a 30-account book","recommendedSlug":"fathom","reasoning":"CS calls are mostly QBRs and check-ins where the value is the recording, the action-items, and the CRM log — not deal scoring or forecasting. Fathom Team Edition at $29/seat/mo gives you Salesforce/HubSpot auto-logging and the AI summary. A CS manager rarely needs Grain's coaching workflow and never needs Gong's deal forecasting."},
    {"persona":"Product research lead running user interviews","recommendedSlug":"grain","reasoning":"Product research is the use case Grain is best at outside sales. Smart tags auto-classify mentions of features, pain points, and competitors; the clip-library lets you assemble a 90-second highlight reel of customer quotes for any sprint review. Grain Business at $15/seat/mo is the right tier. Fathom works but lacks the clip workflow; Gong is irrelevant for this persona."},
    {"persona":"Enterprise sales VP at a 300-rep org with RevOps","recommendedSlug":"gong","reasoning":"At 300 reps with a CRO judged on forecast accuracy and a dedicated RevOps function, Gong is the only credible pick of the three. The forecast engine, deal-risk scoring, market-intelligence layer, and AI agents earn out at this scale in a way they do not below 100 seats. Expect $400,000-$600,000/year all-in including platform fee and a 90-day procurement; the comparable cost in lost-deal early-warning value typically clears that bar."}
  ]$body8$::jsonb,
  $body9$[
    {"dimension":"Free recording cap","values":{"fathom":{"score":"Unlimited","unit":"meetings/mo","source":"Fathom free plan, April 2026"},"grain":{"score":"20","unit":"meetings/mo","source":"Grain Free plan"},"gong":{"score":"None","unit":"no free tier","source":"Gong sales-led only"}}},
    {"dimension":"Cheapest paid tier","values":{"fathom":{"score":"$19","unit":"USD/seat/mo (Premium, annual)","source":"fathom.video pricing"},"grain":{"score":"$15","unit":"USD/seat/mo (Business, annual)","source":"grain.com pricing"},"gong":{"score":"$1,200-1,600","unit":"USD/seat/year est.","source":"public estimates G2/Reddit/resellers 2025-2026"}}},
    {"dimension":"Conversation intelligence depth","values":{"fathom":{"score":"2","unit":"of 5 (recorder + AI summary + Action Items)","source":"editorial scoring methodology — see feature analysis"},"grain":{"score":"3.5","unit":"of 5 (CI-lite: scorecards + coaching playlists + smart tags)","source":"editorial scoring"},"gong":{"score":"5","unit":"of 5 (forecast engine + market intel + AI agents)","source":"editorial scoring"}}},
    {"dimension":"CRM integration breadth","values":{"fathom":{"score":"Salesforce, HubSpot, Slack, Notion, Linear","unit":"5+ native","source":"Fathom integrations page"},"grain":{"score":"Salesforce, HubSpot, Pipedrive, Close, Slack, Notion","unit":"6+ native, bidirectional","source":"grain.com integrations"},"gong":{"score":"Salesforce, HubSpot, Dynamics, Outreach, Salesloft, +many","unit":"deep two-way + reverse-ETL","source":"gong.io integrations"}}},
    {"dimension":"SSO availability","values":{"fathom":{"score":"SAML on Team Edition","unit":"yes (paid only)","source":"Fathom Team Edition spec"},"grain":{"score":"SAML on Business + Enterprise","unit":"yes (paid only)","source":"Grain Business spec"},"gong":{"score":"SAML + SCIM provisioning","unit":"yes (all tiers)","source":"Gong security page"}}},
    {"dimension":"SOC 2 Type II status","values":{"fathom":{"score":"Yes","unit":"audited","source":"Fathom trust page"},"grain":{"score":"Yes","unit":"audited","source":"Grain trust page"},"gong":{"score":"Yes + ISO 27001 + HIPAA-ready","unit":"audited (full enterprise stack)","source":"Gong trust center"}}},
    {"dimension":"Public review count (G2)","values":{"fathom":{"score":"~4,500","unit":"G2 reviews (4.9 avg)","source":"G2 April 2026"},"grain":{"score":"~250","unit":"G2 reviews (4.6 avg)","source":"G2 April 2026"},"gong":{"score":"~6,200","unit":"G2 reviews (4.7 avg)","source":"G2 April 2026"}}}
  ]$body9$::jsonb,
  $body10$[
    {"question":"Fathom vs Grain vs Gong — which is best in 2026?","answer":"There is no single best — the right pick is almost entirely a function of org size. Solo founders and SMB reps should run Fathom (the free tier is unlimited recording with AI summaries). Sales teams of 5-100 reps should run Grain Business at $15/seat/mo (Gong-lite at one-eighth the cost). Orgs with 200+ reps and a RevOps function should run Gong for its forecast engine, market intelligence and AI agents. Listicles compare them as if they are the same product; they are not."},
    {"question":"Is Gong worth it over Fathom?","answer":"For a solo founder or a 5-rep SMB team, no — Gong is built for a buyer who will pay $250,000+/year and the platform value is wasted below 100 seats. For a 300-rep org with a CRO judged on forecast accuracy, yes — Gong's forecast engine and market intelligence earn out in a way Fathom cannot replicate. The honest middle ground is Grain at $15/seat/mo, which delivers 80% of Gong's coaching value for 5-100-rep teams."},
    {"question":"Which is free?","answer":"Fathom has a genuinely unlimited free tier (no meeting cap, no watermark, AI summary included) — this is the headline draw. Grain has a free plan capped at 20 meetings per month with basic AI notes and no clip library. Gong has no free tier at all — it is sales-led, contact-only pricing with a typical 50-seat practical minimum."},
    {"question":"Can I export from each?","answer":"Yes, on all three, but with limits. Fathom exports transcripts, summaries and recordings to Google Drive, Slack, Notion, and CRM. Grain exports clips, transcripts, and metadata via integrations and API on Business and above. Gong supports the deepest export — full call data, transcripts, scorecard data, and CRM-side reverse-ETL — but contractual terms typically restrict re-export to third-party CI tools. Read the DPA before assuming portability."},
    {"question":"Which has the best CRM integration?","answer":"Gong, by depth — bidirectional sync with Salesforce, HubSpot, Microsoft Dynamics, Outreach and Salesloft, plus reverse-ETL into the data warehouse. Grain is second and best-in-class for SMB stacks (Salesforce, HubSpot, Pipedrive, Close — bidirectional). Fathom Team Edition covers Salesforce and HubSpot auto-logging cleanly but is shallower on niche CRMs. For a Salesforce-only SMB, all three work; for Microsoft Dynamics or a multi-CRM stack, Gong is the only deep pick."},
    {"question":"Fathom vs Grain vs Gong for solo founders?","answer":"Fathom, with no real debate. The free tier is unlimited recording with AI summaries and AI Action Items — a solo founder doing 20-40 customer interviews a month will never hit a wall and the per-meeting AI quality is on par with Grain Business. Grain's free plan caps at 20 meetings/mo. Gong does not have a free tier and the seat price is impractical for solo founders by an order of magnitude."},
    {"question":"What is the best AI meeting tool for 50-person sales teams?","answer":"Grain Business at $15/seat/mo billed annually — roughly $9,000/year for 50 seats. You get smart-tag auto-classification of call moments, deal scorecards, coaching playlists, a searchable clip-library, and bidirectional CRM sync. Gong would cost roughly $60,000-$80,000/year at the same headcount and the incremental value (forecast engine, market intelligence) typically does not earn out below 100 seats. Fathom Team Edition is too thin on coaching workflow at this size."},
    {"question":"Which AI meeting tool has SOC 2 Type II?","answer":"All three. Fathom is SOC 2 Type II audited and offers SAML SSO on Team Edition. Grain is SOC 2 Type II audited and offers SAML SSO on Business and Enterprise. Gong is SOC 2 Type II, ISO 27001, GDPR-compliant, HIPAA-ready, supports SAML and SCIM provisioning, and offers regional data residency — the only one of the three that clears Fortune 500 InfoSec review without exception."},
    {"question":"Does Gong support SSO and SAML?","answer":"Yes — SAML 2.0 single sign-on plus SCIM provisioning are available on all Gong contracts (this is a standard enterprise expectation, not a paid add-on). Gong also publishes ISO 27001, SOC 2 Type II, GDPR DPA, HIPAA readiness and regional data residency options. The full enterprise compliance stack is one of Gong's primary moats over Grain and Fathom."},
    {"question":"What is the actual Gong price per seat?","answer":"Gong does not publish pricing. Public estimates from G2, Reddit r/sales disclosures, and resellers in 2025-2026 put the seat price at roughly $1,200-$1,600/seat/year for the core platform, plus a platform fee typically in the $5,000-$25,000/year range depending on org size. A 100-rep org should expect $130,000-$185,000/year all-in. Many resellers report a practical 50-seat minimum, though Gong has been more flexible at smaller volumes since 2024. Procurement cycles for Global 2000 buyers are typically 60-120 days."}
  ]$body10$::jsonb,
  true,
  $body11$2026-04-28T00:00:00Z$body11$,
  $body12$2026-04-28T00:00:00Z$body12$,
  0
) ON CONFLICT (slug) DO NOTHING;
