-- 133 (2026-05-31) — Universal propagation: fan a tool content-change out to
-- EVERY editorial comparison that references the tool, so the cascade
-- regenerates ALL of them — not just whichever compares happen to surface in
-- the stalest-first batch before the per-run cap.
--
-- ── The gap (verified against prod 2026-05-31) ──────────────────────────────
-- propagate_freshness() (migration 103) bumps pages_freshness for every page
-- mentioning a tool — that drives the visible "Updated <date>" badges. But the
-- editorial PROSE on /compare/<slug> is regenerated by a SEPARATE pipeline
-- (lib/cron/cascade-editorials.ts) which reads v_stale_comparisons (migration
-- 088). That view flags a compare stale only when MAX(tools.last_verified_at)
-- across its pair > last_reviewed_at, and the cascade processes the queue
-- stalest-first with a per-run cap (default 30/day via the GH Actions
-- freshness-batch job). On prod this left 488 / 559 editorial compares stale
-- with a median lag of ~11.7 days and a max of ~17.7 days: a 20-day-old compare
-- whose tool changed today can sit behind a perpetually-churning queue and
-- never reach the top of a 30-row batch.
--
-- ── The fix (this migration) ────────────────────────────────────────────────
-- Extend propagate_freshness() so that, in addition to bumping pages_freshness,
-- it sets last_reviewed_at = NULL on every editorial tool_comparisons row whose
-- tool_ids contains the changed tool. NULL last_reviewed_at means:
--   • v_stale_comparisons COALESCEs it to epoch, so staleness = decades and the
--     compare jumps to the very TOP of the stalest-first queue;
--   • the cascade then ORDER BY staleness DESC processes these first.
-- Paired with raising the cascade per-run cap (lib/cron/cascade-editorials.ts +
-- scripts/refresh-compare-editorials-batch.ts), the whole referencing set drains
-- in the next run(s) instead of starving.
--
-- The page badge still renders during the gap: the compare page falls back to
-- published_at when last_reviewed_at is NULL, and the cascade repopulates
-- last_reviewed_at = NOW() the moment it regenerates the prose.
--
-- This is additive to propagate_freshness — the pages_freshness upsert (and thus
-- every "Updated <date>" badge across tool / compare / hub surfaces) is
-- unchanged. Still SECURITY DEFINER, still exception-safe: a failure here must
-- never block the underlying tools UPDATE. Idempotent: re-running the migration
-- just re-defines the function; nulling an already-null last_reviewed_at is a
-- no-op for the cascade.
--
-- Reversible: re-apply migration 103's propagate_freshness() body to revert.

CREATE OR REPLACE FUNCTION propagate_freshness(
  p_tool_slug TEXT,
  p_source    TEXT,
  p_event     TEXT DEFAULT NULL,
  p_reason    TEXT DEFAULT NULL
) RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count   INT := 0;
  v_tool_id UUID;
BEGIN
  -- (1) Bump pages_freshness for every mentioning page — this drives the
  --     visible "Updated <date>" badge on tool / compare / hub surfaces.
  --     Unchanged from migration 103.
  INSERT INTO pages_freshness AS pf (
    page_path, page_type, last_changed_at,
    change_source, change_reason, source_tool_slug, source_event, updated_at
  )
  SELECT
    ptm.page_path,
    ptm.page_type,
    NOW(),
    p_source,
    p_reason,
    p_tool_slug,
    p_event,
    NOW()
  FROM page_tool_mentions ptm
  WHERE ptm.tool_slug = p_tool_slug
  ON CONFLICT (page_path) DO UPDATE SET
    last_changed_at  = NOW(),
    change_source    = EXCLUDED.change_source,
    change_reason    = EXCLUDED.change_reason,
    source_tool_slug = EXCLUDED.source_tool_slug,
    source_event     = EXCLUDED.source_event,
    updated_at       = NOW();

  GET DIAGNOSTICS v_count = ROW_COUNT;

  -- (2) Fan out to the editorial PROSE pipeline: mark EVERY editorial
  --     comparison referencing this tool as needing regeneration by nulling
  --     last_reviewed_at. v_stale_comparisons then sorts them to the top of
  --     the stalest-first cascade queue, so all of them regenerate — not just
  --     the few that fit under the per-run cap. Wrapped in its own guard so a
  --     failure here cannot undo the pages_freshness bump above.
  BEGIN
    SELECT id INTO v_tool_id FROM tools WHERE slug = p_tool_slug;
    IF v_tool_id IS NOT NULL THEN
      UPDATE tool_comparisons
        SET last_reviewed_at = NULL
        WHERE is_editorial = true
          AND v_tool_id = ANY (tool_ids)
          AND last_reviewed_at IS NOT NULL;  -- skip already-queued rows (no-op churn)
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'propagate_freshness fan-out to comparisons failed for %: %', p_tool_slug, SQLERRM;
  END;

  RETURN v_count;

EXCEPTION WHEN OTHERS THEN
  -- Never block the underlying UPDATE.
  RAISE WARNING 'propagate_freshness(% , %) failed: %', p_tool_slug, p_source, SQLERRM;
  RETURN 0;
END;
$$;

COMMENT ON FUNCTION propagate_freshness(TEXT, TEXT, TEXT, TEXT)
  IS '1.1 freshness-cascade (rev 133) — bumps pages_freshness for every page mentioning the tool (drives "Updated <date>" badges) AND nulls last_reviewed_at on every editorial comparison referencing the tool so the editorial-prose cascade regenerates ALL of them. Exception-safe; never blocks the calling UPDATE.';
